### ISSUE TITLE
No way of knowing how to convert running volumes in quantum

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#10046]
The APIs around referral and volume discount stats don't provide decimals and quantum values to indicate how to convert the integers into the values a user would expect

The below query is for a single position. The expected volume is 15.89 (market dps 5, position dps 3). This is reflected in the running Volume but the frontend doesn't know how to convert '15895990'.  This volume could be made up of lots of different assets.

```
{
    "data": {
        "positions": {
            "edges": [
                {
                    "node": {
                        "averageEntryPrice": "69113",
                        "openVolume": "23000" // notional 15895990
                    }
                }
            ]
        },
        "volumeDiscountStats": {
            "edges": [
                {
                    "node": {
                        "runningVolume": "15895990"
                    }
                }
            ]
        }
    }
}
```

Heres a thread: 

Recent thread

https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1699642760356269

Older thread

https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1698062758483849

**Comment by gordsport** [comment]
This isue has been resolved - closing now.
