### ISSUE TITLE
Command line wallet leaves terminal input invisible upon Ctrl-C at the wrong time

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#10055]
1. Open the command line wallet: `vegawallet service run --network mainnet1` 
2. Make it ask for a password (e.g. because a website connects)
3. Press Ctrl-C
4. Type in the terminal e.g. `ls` - can you see it?

**Comment by davidsiska-vega** [comment]
```
vegawallet software version
Software version:
v0.73.3
```

and
```
davidsiska$ uname -a
Darwin D-MBP-M1.local 22.6.0 Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000 arm64
```

**Comment by ValentinTrinque** [comment]
Couldn't reproduce it so far.

<img width="1200" alt="Screenshot 2023-11-15 at 17 57 54" src="https://github.com/vegaprotocol/vega/assets/4662842/802de56f-dfd7-4c02-8f5d-0315e6797bc9">

`uname -a` yields:
```
Darwin Sentinelle.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
```
So we are basically on the same setup.

**Comment by ValentinTrinque** [comment]
Tested with Alacritty 0.12.3 (1) and Terminal 2.13 (447)
