### ISSUE TITLE
Data source filter might be too restrictive

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#10053]
Confirm that an openoracle payload, containing multiple price feeds, will match to any data sources expected in the core, even if some of the prices provided are not expected by the core.

**Comment by wwestgarth** [comment]
We have two system tests that cover open-oracle payloads:
```
test_open_data_source
test_two_markets_settled_by_one_coinbase_oracle
```
both containing prices for multiple assets:
```
 "prices": {
            "BTC": "23496.82",
            "ETH": "1866.22",
            "XTZ": "1.862",
            "DAI": "0.9998",
            "REP": "8.88",
            "ZRX": "0.349996",
            "BAT": "0.37061",
            "KNC": "1.7189999999999999",
            "LINK": "8.1295",
            "COMP": "59.295",
            "UNI": "8.105",
            "GRT": "0.12345",
            "SNX": "3.526",
        },
```

running a test locally ans watching what core does, we can see that the signed price messages in the payload are correctly unpacked into a `map[string]string` containing all asset prices:
```
map[prices.BAT.timestamp:1657734300 prices.BAT.value:370610 prices.BTC.timestamp:1660832460, ...
```
from here core matches the specs, to the data in the map where any price in the data that does not match the spec is not considered:
```
for propertyName, filter := range f.filters {
		dataValue, ok := data[propertyName] <-- here, we do not care if there is more than expected in the data
		if !ok {
			return false, nil
		}
		for _, condition := range filter.conditions {
			if matched, err := condition(dataValue); !matched || err != nil {
				return false, err
			}
		}
	}
```
we match against the only price we care about and then shoot it into the market as expected. So I think all is in order.
