### ISSUE TITLE
`GetLiquidityProvisionV2` API call is lagging up to 2 minute

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10172]
When looking on the stagnet1 charts it has been identified that the `GetLiquidityProvisionV2` call is lagging up to 2 minutes, this has been the case for a few days. 

The metric shows average request time per `requestType` for metric: `datanode_request_time_total`  over a few minutes:

![Image](https://github.com/vegaprotocol/vega/assets/83510148/f6632048-1253-4f59-9832-e54871b7e2f4)

The graph URL is here: https://monitoring.vega.community/d/c9bb95f5-ce63-42a8-a28f-49e7f704dcea/data-node-stats?orgId=1&from=now-30d&to=now&viewPanel=16

This slow running query needs to be investigated and the performance increased.

**Comment by guoguojin** [comment]
I've jumped on the database and run the query directly, it appears that there's a very large amount of liquidity provision records in the liquidity provision table which has a retention policy of only 1 day, but it has nearly 1M rows of updates in there.

Trying to find out if these are reasonable numbers for stagnet, but this slowness only affects queries that are equivalent to the API being called with the live flag set to false. When querying live liquidity provisions, performance is not great, but completes within a few seconds.

**Comment by gordsport** [comment]
@daniel1302 - are we still seeing this issue?

**Comment by guoguojin** [comment]
Confirmed with @daniel1302 that we can close this ticket for now
