### ISSUE TITLE
[Bug]: restore the position resolution event

### ISSUE THREAD

**Issue by EVODelavega** [vegaprotocol/vega#10173]
### Problem encountered

When parties are distressed, we used to emit a position resolution event containing the mark price, number of distressed parties, and the number of parties that were closed out (the difference between the two being the parties that were able to keep their position after their orders were closed)

### Observed behaviour

No position resolution event is emitted

### Expected behaviour

The event should be emitted if parties are distressed

### Steps to reproduce

```bash
Run any test that results in parties getting closed out, and capture the events. The event is not there
```

### Software version

develop

**Comment by gordsport** [comment]
implemented in another PR
