### ISSUE TITLE
[Bug]: Transfers connection doesnt support proper filtering

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10278]
### Problem encountered

List transfers API will support filtering for

`isReward:true`

And also for 

`partyId:"XXX"`

But if you try to filter for both combined it gives you an error.

### Observed behaviour

See above

### Expected behaviour

Filters should work with AND type behaviour surely?

### Steps to reproduce

```bash
Run this on mainnet


query listTransfer {
  transfersConnection(isReward:true, partyId:"978de934e67f7dfd318fdd2181442f3a944848af829cdf4c1b6d46fa1b0c87c2"){
    edges{
      node{
        transfer{
        id
        from
        fromAccountType
        to
        toAccountType
        asset{
          id
          symbol
        }
        reference
        status
        timestamp
        kind{
          ...on RecurringTransfer{
            startEpoch
            endEpoch
            dispatchStrategy{
              dispatchMetric
              dispatchMetricAssetId
              marketIdsInScope
              entityScope
              individualScope
              teamScope
              nTopPerformers
              stakingRequirement
              notionalTimeWeightedAveragePositionRequirement
              windowLength
              lockPeriod
              distributionStrategy
              rankTable{
                startRank
                shareRatio
              }
            }
          }
        }
        reason
      
      }
        fees {
          transferId
          amount
          epoch
        }
      }
    }
  }
}

```

It will fail. 

Now run it with just isReward: true or with partyId:978de934e67f7dfd318fdd2181442f3a944848af829cdf4c1b6d46fa1b0c87c2.

Both of them will work independently ... but not in combination.
```


### Software version

73.10

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

**Comment by guoguojin** [comment]
This is because when reward filter has been set to true, the API also expect the direction filter to also be provided, with direction set to From only. If you pass the direction: From in the request, it will work properly.

I will update the API so that when the reward filter has been set to true and the direction hasn't been set, then default the direction filter to the appropriate value for the rewards to be displayed properly.
