### ISSUE TITLE
[Bug]: 0.74 preview.1 protocol upgrade: Failed to initialise network history

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10304]
### Problem encountered

When trying to preform a protocol upgrade to 0.74 it failed to initialise network history meaning the automatic upgrade will fail.

### Observed behaviour

Jan 03 09:07:14 n00.stagnet1.vega.rocks visor[520438]: 2024-01-03T09:07:14.075Z        ERROR        datanode        start/node_pre.go:114        Failed to initialise network history        {"error": "failed to create network history store: failed to create ipfs node:failed to create node: failed to open ipfs repo:ipfs repo needs migration, please run migration tool.\nSee https://github.com/ipfs/fs-repo-migrations/blob/master/run.md\nSorry for the inconvenience. In the future, these will run automatically."}
Jan 03 09:07:14 n00.stagnet1.vega.rocks visor[520438]: failed to initialise network history:failed to create network history store: failed to create ipfs node:failed to create node: failed to open ipfs repo:ipfs repo needs migration, please run migration tool.

### Expected behaviour

the protocol upgrade is sucessful

### Steps to reproduce

1. protocol upgrade from 0.73.10 to 0.74 preview.1

### Software version

0.74 prview.1

### Failing test

n/a

### Jenkins run

n/a

### Configuration used

n/a

### Relevant log output

Jan 03 09:07:14 n00.stagnet1.vega.rocks visor[520438]: 2024-01-03T09:07:14.075Z        ERROR        datanode        start/node_pre.go:114        Failed to initialise network history        {"error": "failed to create network history store: failed to create ipfs node:failed to create node: failed to open ipfs repo:ipfs repo needs migration, please run migration tool.\nSee https://github.com/ipfs/fs-repo-migrations/blob/master/run.md\nSorry for the inconvenience. In the future, these will run automatically."}
Jan 03 09:07:14 n00.stagnet1.vega.rocks visor[520438]: failed to initialise network history:failed to create network history store: failed to create ipfs node:failed to create node: failed to open ipfs repo:ipfs repo needs migration, please run migration tool.

**Comment by daniel1302** [comment]
I was able to fix it pretty easy with the following steps:

1. `git clone https://github.com/ipfs/fs-repo-migrations.git`
2. `cd fs-repo-migrations`
3. `make build`
4. `ln -s /home/vega/vega_home/state/data-node/networkhistory/store/ipfs/ /home/vega/.ipfs`
5. `cd fs-repo-migrations && ./fs-repo-migrations`

**Comment by gordsport** [comment]
Closing as this is to be documented in:

- https://github.com/vegaprotocol/documentation/issues/910
