### ISSUE TITLE
Support setting metadata for keys

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#10307]
Updated requirements:

- Tx to add/edit key metadata
- Ability to associate an alias to a single key
- A check for uniqueness on that key in the Tx processing
- An API to expose metadata for a key (list the metadata for a given set of keys)

**Comment by gordsport** [comment]
- pubkey → alias (must be unique)
- pubkey → metadata list (some limit on amount of data, can be anything within the limit like market metadata)
- txn for setting
- API for getting for one or more pubkeys

spam protection:
- require current funds > net param × quantum to set or change
- limit updates per epoch
- can be same as to join a team probably, per above?

Also, for uniqueness (which means core has to track them),  to (a) manage storage used; and (b) prevent name squatting?
- core can drop the name (and data mode will mark those records as expired), meaning others can use it, after N epochs where the key has less than the funds required to update plus no open positions
