### ISSUE TITLE
After a closeout trade position status is `POSITION_STATUS_CLOSED_OUT` but if the party then places new orders, enters a trade ...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#10319]
... then the `PositionStatus` status should be reset to `POSITION_STATUS_UNSPECIFIED` so that we stop reminding losers that they lost: 
![image](https://github.com/vegaprotocol/vega/assets/62546419/2d136561-653f-464c-aaa5-e71095970ff3)

As you see in the screenshot, the key has new position. 

I suppose the realised PnL will still remind them how much they lost - but that's fair :-).

**Comment by jeremyletang** [comment]
duplicates of: https://github.com/vegaprotocol/vega/issues/10907
