### ISSUE TITLE
[Bug]: error when querying teams in GQL

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10369]
### Problem encountered

When running the folowing query it does not return results as expected:

```
query{
  teams{
    edges{
      node{
        teamId,
        referrer,
        name,
      }
    }
  }
}
```

### Observed behaviour

responce:

```
{
  "errors": [
    {
      "message": "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data",
      "stack": ""
    }
  ]
}
```

### Expected behaviour

To return the results as expected

### Steps to reproduce

1. Open GLQ playground
2. Run the query above
3. look at result

### Software version

0.74 (devnet)

### Failing test

n/a

### Jenkins run

n/a

### Configuration used

n/a

### Relevant log output

n/a

**Comment by jeremyletang** [comment]
This couldn't be reproduced.
