### ISSUE TITLE
[Bug]: Error occurs when trying to updateMarginMode to isolated mode with low margin factor

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/vega#10418]
### Problem encountered

Cannot update margin mode with low margin factor,  but higher than max(riskFactorLong, riskFactorShort).

"required position margin must be greater than initial margin"
<img width="157" alt="image" src="https://github.com/vegaprotocol/vega/assets/1754247/3b726a82-edc0-4582-a817-1872fe43d0a2">

### Observed behaviour

Market has below risk factors
![image](https://github.com/vegaprotocol/vega/assets/1754247/29eaa0a8-55c4-42f2-b451-0a12ffffbb6a)

When trying to set to low margin factor 
![image](https://github.com/vegaprotocol/vega/assets/1754247/5912da54-10fc-43cf-a564-8c1129469f5a)

error is returned
![image](https://github.com/vegaprotocol/vega/assets/1754247/417dcdf8-bfb3-4d21-a56a-7da59626eaaf)

Which is fine, margin factor should be greater than max(riskFactorLong, riskFactorShort) - in this case greather than 0.011641864953061187

When trying to set higher margin factor 0.0125

![image](https://github.com/vegaprotocol/vega/assets/1754247/b7591969-7f12-4e96-94e9-9c062ceeaa4b)

Error occurs
![image](https://github.com/vegaprotocol/vega/assets/1754247/db046eaf-7c6c-4440-8879-13b76c0df1f3)

### Expected behaviour

It should be possible to set marginFactor higher than max(riskFactorLong, riskFactorShort)

### Steps to reproduce

```bash
Send updateMarginMode transaction with "mode":2 (isolated margin) and marginFactor close to minimum value
```

### Software version

v0.74.0-preview.3 bcb3165044541ef40f0d70fccebba3964c008158

**Comment by ze97286** [comment]
The behaviour is correct. it shouldn't be possible to use a margin factor that would set the margin to less than the initial margin. See spec. https://github.com/vegaprotocol/specs/blob/nebula/protocol/0019-MCAL-margin_calculator.md#isolated-margin-mode

<img width="1054" alt="image" src="https://github.com/vegaprotocol/vega/assets/6655556/e7720396-b223-4af6-b299-82a5584eee01">

**Comment by witgaw** [comment]
The validation should be done against `max(1/max initial leverage long, 1/max initial leverage short)` (unless it can be accessed directly without taking the reciprocal).
<img width="258" alt="image" src="https://github.com/vegaprotocol/vega/assets/9922111/565ee8e7-f320-451e-abd8-b46900be05ab">

**Comment by davidsiska-vega** [comment]
> The behaviour is correct

Yep, definitely not a bug.
