### ISSUE TITLE
[Feature]: Add chain ID support to integration test framework

### ISSUE THREAD

**Issue by EVODelavega** [vegaprotocol/vega#10435]
Though the integration tests don't actually rely on the datasource package, with the L2 changes, the chain ID is now a required parameter for the oracle spec. The governance unit tests have been changed to reflect this. While in practice, it doesn't make any difference for the integration tests, it's better for the integration test framework to reflect, as accurately as possible, the data the execution engine will receive from the governance engine. That means we should be able to set the source chain ID to a specific (ideally configurable) value.

**Comment by gordsport** [comment]
closing as this is supported already
