### ISSUE TITLE
[API]: Show referee count in team and referral set stats

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#10464]
# API Overview

**In order to** Show more information on the teams and referral pages
**We update the API to** include the total number of team members or referees
**So that** We we can show a count of members without having to fetch all referees or teamReferees for every team/set in a list

## Specs

N/A

## API request details

- [ ] Add a members count field to team stats
- [ ] It should show the total number of members (referees in a team)
- [ ] It should show the total number of referees in a referral set
- [ ] Both fields should be non nullable
- [ ] Both fields should start at 0 when the team or set is created
- [ ] Should increment when a new referee is added to the set/team

### Filtering requirements (inputs)

None

### Sample API output (optional)

**Schema Changes**
```
type TeamStatistics {
  teamId
  ... 
  refereesCount: Int! //  NEW FIELD
}

type ReferralSetStats {
  partyId: ID!
  ...
  refereesCount: Int! // NEW FIELD
}
```

**Comment by JonRay15** [comment]
To be implemented on teams API rather than stats now per discussion with @ValentinTrinque
