### ISSUE TITLE
[Bug]: EstimatePosition api - rpc error `invalid account balance`

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#10470]
### Problem encountered

calling the `EstimatePosition` api report the error 
`ValueError(b"\x08\x90N\x12\x17invalid account balance\x1a\x19can't convert  to decimal")`

i _think_ its because the party does not have order margin account

### Observed behaviour

cannot retrieve response from `EstimatePosition`

### Expected behaviour

can retrieve response from `EstimatePosition`

### Steps to reproduce

```bash
1. run the test `test_perpetual_funding_payment` on develop branch
```

### Software version

dev branch

### Failing test

test_perpetual_funding_payment

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/181/testReport/junit/tests.trading/perpetual_test/Call_tests___full_t_z___test_perpetual_funding_payment/

**Comment by witgaw** [comment]
Just pass 0 if party doesn't have an account.

**Comment by witgaw** [comment]
Or is the problem that the error is not descriptive enough?

**Comment by Sohill-Patel** [comment]
@witgaw re-ran the test with your suggestion `order_margin_account_balance="0"`
```
request = trd_v2.EstimatePositionRequest(market_id=market_id, open_volume=open_volume, order_margin_account_balance="0")
response = api.grpc_stub_trd_data_v2.EstimatePosition(request)
```

The test still fails with the same error i reported

**Comment by witgaw** [comment]
Ok, I'll try to fix it in around 2h.
