### ISSUE TITLE
[API]: Provide current "vega side price for funding" on an API endpoint

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#10502]
Currently the `.../api/v2/markets/data` endpoint provides:
- mark price, 

and for perps also
```
"productData": {
                "perpetualData": {
                    "fundingPayment": "-17994",
                    "fundingRate": "-0.001210715416813",
                    "internalTwap": "14844293",
                    "externalTwap": "14862287",
                    "seqNum": "160",
                    "startTime": "1706544889000000000",
                    "indexPrice": "1494299",
                    "nextIndexPriceCalc": "1706556424211855752",
                    "indexPriceType": "COMPOSITE_PRICE_TYPE_LAST_TRADE"
                }
            },
``` 

Request (minimal): add the "vega side price for funding" next to the "indexPrice". 

Bonus (if possible): for both (perps markets) and mark price only (futures) of the composite price show the values of the 
1)~market~ ~config~ ~used~ ~somewhere~ ~(method,~weights,~staleness~settings)~ -- apparently available elsewhere so not needed here
2) values of the component prices going in
3) their age

**Comment by davidsiska-vega** [comment]
Terminology clash. Needs to be clarified what we want to call what @barnabee . 

But @ze97286 tells me that what's under "indexPrice" there is, in fact, what vega calculates using the composite price method. It's not the external data source price (which the name to me implies).

**Comment by davidsiska-vega** [comment]
Unblocked we want the names:
`underlyingIndexPrice` for the external oracle input coming from the `dataSourceSpecForSettlementData`. 
`internalCompositePrice` for the internal price synthesised from trades, order book data etc.

**Comment by ze97286** [comment]
the renaming has been done, now we have to:
1. add the underlyingIndexPrice
2. bonus: add the components of the composite price
