### ISSUE TITLE
[Bug]: EstiamtePosition with orders on rest api returns wrong values

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#10516]
### Problem encountered

comparison of grpc and rest response for the same request shows
rest response
{'margin': {'worstCase': {'maintenanceMargin': '0', 'searchLevel': '0', 'initialMargin': '0', 'collateralReleaseLevel': '0', 'partyId': '', 'marketId': '36119e7415ccd15e69b27c2e490b229da9f741f3a04d0f446e9adad8d4f5564c', 'asset': '64243f77c78492a0912937ea226dd077280f154c1dc382b855ba38e1b33281b0', 'timestamp': '0', 'orderMargin': '', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'marginFactor': ''}, 'bestCase': {'maintenanceMargin': '0', 'searchLevel': '0', 'initialMargin': '0', 'collateralReleaseLevel': '0', 'partyId': '', 'marketId': '36119e7415ccd15e69b27c2e490b229da9f741f3a04d0f446e9adad8d4f5564c', 'asset': '64243f77c78492a0912937ea226dd077280f154c1dc382b855ba38e1b33281b0', 'timestamp': '0', 'orderMargin': '', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'marginFactor': ''}}, 'collateralIncreaseEstimate': {'worstCase': '0', 'bestCase': '0'}, 'liquidation': {'worstCase': {'openVolumeOnly': '0', 'includingBuyOrders': '0', 'includingSellOrders': '0'}, 'bestCase': {'openVolumeOnly': '0', 'includingBuyOrders': '0', 'includingSellOrders': '0'}}}

grpc response
{'margin': {'worstCase': {'maintenanceMargin': '611253678061533', 'searchLevel': '672379045867686', 'initialMargin': '733504413673839', 'collateralReleaseLevel': '855755149286146', 'marketId': '36119e7415ccd15e69b27c2e490b229da9f741f3a04d0f446e9adad8d4f5564c', 'asset': '64243f77c78492a0912937ea226dd077280f154c1dc382b855ba38e1b33281b0', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'partyId': '', 'timestamp': '0', 'orderMargin': '', 'marginFactor': ''}, 'bestCase': {'maintenanceMargin': '513653678061533', 'searchLevel': '565019045867686', 'initialMargin': '616384413673839', 'collateralReleaseLevel': '719115149286146', 'marketId': '36119e7415ccd15e69b27c2e490b229da9f741f3a04d0f446e9adad8d4f5564c', 'asset': '64243f77c78492a0912937ea226dd077280f154c1dc382b855ba38e1b33281b0', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'partyId': '', 'timestamp': '0', 'orderMargin': '', 'marginFactor': ''}}, 'collateralIncreaseEstimate': {'worstCase': '733504413673839', 'bestCase': '616384413673839'}, 'liquidation': {'worstCase': {'openVolumeOnly': '0', 'includingBuyOrders': '1041209316248879224441', 'includingSellOrders': '0'}, 'bestCase': {'openVolumeOnly': '0', 'includingBuyOrders': '1030218809758247811752', 'includingSellOrders': '0'}}}

### Observed behaviour

incorrect rest api response when orders are provided

### Expected behaviour

rest response is same as grpc response

### Steps to reproduce

```bash
1. run the test from jenkin on branch `position-estimate-tests`
```

### Software version

dev branch

### Failing test

test_position_estimate_api

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/41656/

### Configuration used

```shell
request
url='http://127.0.0.1:3028/api/v2/estimate/position' params={'marketId': 'a9aa4102da1b587f2f245dd063f9b75ccde92c353736a5d228b397b8e66d655e', 'openVolume': 0, 'averageEntryPrice': '986', 'details': [side: SIDE_BUY
price: "986"
remaining: 1
is_market_order: true
], 'marginAccountBalance': '0', 'generalAccountBalance': '100000000', 'orderMarginAccountBalance': '0', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'marginFactor': None} payload={}
```

**Comment by witgaw** [comment]
It would seem that the REST API doesn't contain the orders parameters https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-estimate-position

**Comment by Sohill-Patel** [comment]
the rest request was incorrect in the above example
`2024-02-01 10:46:58.781:[INFO] [MainProcess] [MainThread] [     apiMod.py]:[    get_rest]:[ 134] REST API request url='http://127.0.0.1:3028/api/v2/estimate/position' params={'marketId': '8feb1e9a19622c804e7897bfc37c6101c7cc6574e6ea96f3991cda849ac6852e', 'openVolume': 0, 'averageEntryPrice': '986', 'orders': [{'side': 'SIDE_BUY', 'price': '986', 'remaining': '1', 'isMarketOrder': True}], 'marginAccountBalance': '0', 'generalAccountBalance': '100000000', 'orderMarginAccountBalance': '0', 'marginMode': 'MARGIN_MODE_CROSS_MARGIN', 'marginFactor': None} payload={}`

and the response is 
`2024-02-01 10:46:58.786:[INFO] [MainProcess] [MainThread] [     apiMod.py]:[    get_rest]:[ 136] REST API response status 400`

because orders is missing as per comment above
https://jenkins.vega.rocks/blue/rest/organizations/jenkins/pipelines/common/pipelines/system-tests-wrapper/runs/41789/nodes/588/log/?start=0

**Comment by Sohill-Patel** [comment]
i _think_ there is an issue with the graphql query. The grpc response in the description shows there is no party but if you provide the party in graphql query then the response is `"message": "invalid party"`

**Comment by witgaw** [comment]
How do you provide a party if there's no such field in the request?

**Comment by Sohill-Patel** [comment]
@witgaw - i did notice that but wasnt sure why it was even in the response which is why i tried it out in the graphql query

**Comment by witgaw** [comment]
How did you try it though? There just isn't such a field, GrahQL or gRPC.

It's in the reposnse because it's using the same data structure as the deprecated endpoint for estimating marign on its own, it's not populated to signify the fact that `PositionEstimate` does not relate to any party or existing position, it's just based on the position as specified with the inputs given.

**Comment by Sohill-Patel** [comment]
in graphql yo uhave the`margin` which provides the bestCase and worstCase for `MarginLevels`  which is where you can provide the party
![image](https://github.com/vegaprotocol/vega/assets/85170301/0ab54479-6cbe-489a-9b09-414c81440993)

and here is the query i used
`"query ($marketId: ID!, $openVolume: String!, $averageEntryPrice: String!, $orders: [OrderInfo!], $marginAccountBalance: String!, $generalAccountBalance: String!, $orderMarginAccountBalance: String!, $marginMode: MarginMode!, $marginFactor: String, $includeCollateralIncreaseInAvailableCollateral: Boolean, $scaleLiquidationPriceToMarketDecimals: Boolean) {estimatePosition (marketId: $marketId, openVolume: $openVolume, averageEntryPrice: $averageEntryPrice, orders: $orders, marginAccountBalance: $marginAccountBalance, generalAccountBalance: $generalAccountBalance, orderMarginAccountBalance: $orderMarginAccountBalance, marginMode: $marginMode, marginFactor: $marginFactor, includeCollateralIncreaseInAvailableCollateral: $includeCollateralIncreaseInAvailableCollateral, scaleLiquidationPriceToMarketDecimals: $scaleLiquidationPriceToMarketDecimals) {margin {worstCase {market{ id } asset{ id } party{ id } maintenanceLevel searchLevel initialLevel orderMarginLevel collateralReleaseLevel timestamp marginMode marginFactor} bestCase {market{ id } asset{ id } party{ id } maintenanceLevel searchLevel initialLevel orderMarginLevel collateralReleaseLevel timestamp marginMode marginFactor}} collateralIncreaseEstimate {bestCase worstCase} liquidation {worstCase {open_volume_only including_buy_orders including_sell_orders} bestCase{open_volume_only including_buy_orders including_sell_orders}}}}"`

**Comment by witgaw** [comment]
Ok, but how cares about that endpoint? This issue and the testing effort is about `EstimatePosition` endpoint. That's just confusing.

**Comment by witgaw** [comment]
Margin levels is one of the data structures that gets returned, how can you provide anything there?

**Comment by witgaw** [comment]
Ah I see, you mean when trying to access the field.

**Comment by witgaw** [comment]
OK, that's a problem there. A different one than this issue but still, raised it here:
https://github.com/vegaprotocol/vega/issues/10533

**Comment by ze97286** [comment]
The issue here is that this is complex structure for http get and the url gets flattened into `/api/v2/estimate/position?marketId=ea7ca6b5389f6307bc06f26b48d93a316600de1acde4525930cc3e607a075bfc&openVolume=0&averageEntryPrice=986&orders=side&orders=price&orders=remaining&orders=is_market_order&marginAccountBalance=0&generalAccountBalance=100000000&orderMarginAccountBalance=0&marginMode=MARGIN_MODE_CROSS_MARGIN
`
It probably should be done using http post.

**Comment by witgaw** [comment]
Fixed https://github.com/vegaprotocol/vega/pull/10600#event-11758164729
