### ISSUE TITLE
[Bug]: EstimatePosition - liquidation price for opposite side

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#10558]
### Problem encountered

for a short position opened at 200000 the liquidation estimates are best_case=18951965, worst_case=18774062
for a long position opened at 200000 the liquidation estimates are best_case=21111041, worst_case=21336257

@EVODelavega attempted a fix on branch `estimate-fix` which only solves the issue for a short position and not the long position. It's a starting point for who ever picks this up
jenkins run https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/42424/

### Observed behaviour

liquidation estimates for short position provided as if the position is long and vice versa

### Expected behaviour

for a short position the estimate should be > 200000 and vice versa for long position

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

dev branch

### Failing test

test_liquidation_estimate

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/42398/testReport/junit/tests.API/test_api_position_resolution/test_liquidation_estimate_Buy_/

**Comment by witgaw** [comment]
I'm not convinved yet this is necessarily a bug. I'd recommend modifying the test to use 0 for general account balance and the actual margin account balance for the margin account balance specified in the `EstimatePosition` query.
