### ISSUE TITLE
[Bug]: Snapshot testing (mainnet) - FAILED

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#10554]
### Problem encountered

Since the upgrade to 0.74.0-preview.10 the snapshot pipeline is failing:

https://jenkins.vega.rocks/job/private/job/Snapshots/job/Mainnet/15097/display/redirect

### Observed behaviour

snapshot pipeline is failing

### Expected behaviour

snapshot pipeline is passing

### Software version
0.74.0-preview.10

### Jenkins run

https://jenkins.vega.rocks/job/private/job/Snapshots/job/Mainnet/15097/display/redirect

**Comment by wwestgarth** [comment]
Mainnet and testnet pipelines are passing again -- issue was that the nodes we were syncing with were down because they tna out of disk space.
