### ISSUE TITLE
Liquidation price estimation not working as specified

### ISSUE THREAD

**Issue by guoguojin** [vegaprotocol/vega#10565]
[0012-NP-LIPE-004](https://github.com/vegaprotocol/specs/blob/palazzo/non-protocol-specs/0012-NP-LIPE-liquidation-price-estimate.md#0012-NP-LIPE-004) and [0012-NP-LIPE-005](https://github.com/vegaprotocol/specs/blob/palazzo/non-protocol-specs/0012-NP-LIPE-liquidation-price-estimate.md#0012-NP-LIPE-005) does not work as specified. The issues do not appear to be related.

For 0012-NP-LIPE-004, the estimated liquidation price with sell orders is not lower than that for the open volume. Cannot test the convergence.

For 0012-NP-LIPE-005, the specifications are satisfied when we are using cross margin, but fails when using isolated margin. The price does not change as the orders are filled.

Initial position and average price for 0012-NP-LIPE-004: 100000@985

Orders for 0012-NP-LIPE-004:

```
    orders = [
        {"side": "Sell", "price": "985", "remaining": 40000, "is_market_order": False},
        {"side": "Sell", "price": "990", "remaining": 30000, "is_market_order": False},
        {"side": "Sell", "price": "995", "remaining": 20000, "is_market_order": False},
        {"side": "Sell", "price": "995", "remaining": 9000, "is_market_order": False},
    ]
```
Initial position and average price for 0012-NP-LIPE-005: -100000@985

Orders for 0012-NP-LIPE-005:

```
    orders = [
        {"side": "Buy", "price": "985", "remaining": 40000, "is_market_order": False},
        {"side": "Buy", "price": "990", "remaining": 30000, "is_market_order": False},
        {"side": "Buy", "price": "995", "remaining": 20000, "is_market_order": False},
        {"side": "Buy", "price": "995", "remaining": 9000, "is_market_order": False},
    ]
```

The systems test PR with the test in https://github.com/vegaprotocol/system-tests/pull/3360, just in case I did something wrong in the test.

**Comment by witgaw** [comment]
I've clarified the ACs here: https://github.com/vegaprotocol/specs/pull/2161
Could you please check them against the latest [`estimate-fix`](https://github.com/vegaprotocol/vega/tree/estimate-fix) branch?
