### ISSUE TITLE
Rewards / teams / games API disagree on numbers

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10567]
## Issue Summary

We are seeing some discrepancy in testing on the APIs.

This image shows the rewards page which is based on accounts API and rewards API.  You can see iif shows that this key earned 37.19 tDAI.

![image](https://github.com/vegaprotocol/vega/assets/89918817/699012fb-a015-4944-a17e-9b09dc9bf400)

Looking at the games view, which takes its numbers from the `games` API you can see it thinks the team earned 74 .. which is 37 x 2 so adds up.

![image](https://github.com/vegaprotocol/vega/assets/89918817/6644083b-f57a-48b2-aeb0-6aa938da3052)

However, looking at the members info and at the team profile at the top, you can see this view thinks the two kkeys both earned 39 tDAI, to give a total of 78 between them at the top.  These numbers are taken from the `teamStatistics` and `teamMemberStatstics` APIs.

## Fix

Given that the actual Vega reward pot (top left of first image) is taken from an account balance it seems that 37.19 is accurate,, which suggests the `games` API is accurare and there is an issue on the `teamStatistics` and `teamMemberStatistics` APIs.

**Comment by bwallacee** [comment]
Tested using: v0.74.0-preview.10
[replay.txt](https://github.com/vegaprotocol/vega/files/14169214/replay.txt)
[genesis.json](https://github.com/vegaprotocol/vega/files/14169215/genesis.json)
