### ISSUE TITLE
[Bug]: Including new funding rate fields breaks marketsConnection query

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#10656]
### Problem encountered

The `marketsConnection` query breaks when including any of the new funding rate fields: `fundingRateScalingFactor`, `fundingRateLowerBound`, `fundingRateUpperbound`.

Including one or more of any of the fields listed above breaks the `marketsConnection` query

Note: fetching using REST works as expected

### Observed behaviour

**Query**
```
query Markets {
  marketsConnection {
    edges {
      node {
        id
        tradableInstrument {
          instrument {
            product {
              ... on Perpetual {
                __typename
                fundingRateLowerBound
              }
              ... on Future {
                __typename
              }
            }
          }
        }
      }
    }
  }
}
```

**Result**
```
{
  "errors": [
    {
      "message": "the requested element is null which the schema does not allow",
      "path": [
        "marketsConnection",
        "edges",
        6,
        "node",
        "tradableInstrument",
        "instrument",
        "product",
        "fundingRateLowerBound"
      ]
    },
    ... // All markets error
  ],
  "data": {
    "marketsConnection": null
  }
}
```

### Expected behaviour

The query should work as normal

### Steps to reproduce

```bash
1. Run the query shown above
2. Observe output
```

### Software version

0.74.1

**Comment by guoguojin** [comment]
Looks like the graphql schema definition is incorrect, according to the protobuf definition, the upper and lower bounds are optional and may not be populated:

```
  // Lower bound for the funding-rate such that the funding-rate will never be lower than this value.
  optional string funding_rate_lower_bound = 11;
  // Upper bound for the funding-rate such that the funding-rate will never be higher than this value.
  optional string funding_rate_upper_bound = 12;
```

I will update the GraphQL schema to allow null values in these fields.

**Comment by JonRay15** [comment]
This is working for upper / lower bound now.

But it is still not working for the `fundingRateScalingFactor`.
