### ISSUE TITLE
teamStats API is including individual rewards

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10691]
On the teams API the `totalQuantumRewards` is including individual rewards.

```
query teamStats{
  teamsStatistics{
    edges{
      node{
        teamId
        totalQuantumVolume
        totalQuantumRewards
        totalGamesPlayed
        gamesPlayed
        quantumRewards{
          epoch
          totalQuantumRewards
        }
      }
    }
  }
}
```

I would imagine this therefore also impacts the `teamMemberStatistics` API.

Ben has constructed a test case where games are set up one with:

```
 "entityScope": "ENTITY_SCOPE_TEAMS",
 "individualScope": "INDIVIDUAL_SCOPE_UNSPECIFIED",
```

And one with 

```
 "entityScope": "ENTITY_SCOPE_INDIVIDUAL",
 "individualScope": "INDIVIDUAL_SCOPE_IN_TEAM",
```

And he sees rewards for both appearing in the teamStats API.

We do not see the same issue on the games API so that one seems fine .. but this issue means the two dont match.

**Comment by bwallacee** [comment]
VEGA_VERSION=v0.74.1
[replay.txt](https://github.com/vegaprotocol/vega/files/14298891/replay.txt)
[genesis.txt](https://github.com/vegaprotocol/vega/files/14298892/genesis.txt)
