### ISSUE TITLE
Team Stats API volume is only including TAKER volume

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10699]
If you look at this party you will see a limit order only which was filled as MAKER. 

https://explorer.fairground.wtf/parties/a4a01c91f3b78ee94508374650ae0344adc6ba38ba677ade401174b131218d49

They are the only perons in this team 

https://vegafairground.eth.limo/#/competitions/teams/ab881ad13deeccd2a13a1a260e1769bd45c30940172cfdea96c1ab49e57f9224

Which is reporting 0 volume as below.

![image](https://github.com/vegaprotocol/vega/assets/89918817/3d4334cc-1aae-4094-a292-e844386cf9c8)

Should we be including both TAKER and MAKER in our team volume stats?  I suspect yes...

**Comment by barnabee** [comment]
Spec is pretty clear about tracking taker volume. No requirement to also track maker (or auction, or total) volume has been written anywhere that I'm aware of. Suspect this would be a post-Palazzo change if required at all.

**Comment by guoguojin** [comment]
As it's not required in the specifications, I'm going to close this issue for now.
