### ISSUE TITLE
Batch proposals are not showing LP vote properly

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10725]
On this vote in stagnet 

https://api.stagnet1.vega.rocks/api/v2/governance?proposalId=9fc3781600b7e97b42dbf00578f23811db15e89d81e4daea3a528b5e7a39947d

Daniel has voted with his LP but it is not appearing.

in here

```
"yes": [
{
"partyId": "134e5b2fdf11352a85511ec1ae5c0f876977f4bffd52ad08aa04836bf6bf8585",
"value": "VALUE_YES",
"proposalId": "9fc3781600b7e97b42dbf00578f23811db15e89d81e4daea3a528b5e7a39947d",
"timestamp": "1708513484871312000",
"totalGovernanceTokenBalance": "9876000000000000000000",
"totalGovernanceTokenWeight": "0",
"totalEquityLikeShareWeight": "0",
"perMarketEquityLikeShareWeight": {}
}
```

We should be getting an array of markets and ELS in that last part showing for each market the ELS of any LP that has voted in the proposal

**Comment by EVODelavega** [comment]
After taking a closer look at the batch proposals, I can see that there's a minimum LP participation threshold in the parameters (`"requiredParticipationLp": "0.00001",`) and an overall required participation limit (ie token holders participation) of zero (`"requiredParticipation": "0"`). The batch itself contains 2 market update proposals, and 2 market _state_ update proposals. Looking at the implementation in the core, it seems that we only allow LPs to vote on the market update proposals, not market state update proposals (ie LPs cannot vote to resume a suspended market).

Part of the issue at play here appears to be that currently it is possible to submit a batch proposal that would be impossible to pass given the right circumstances. We either should allow LPs to participate in a market state update proposal, or we should reject batch proposals that specify a required LP participation threshold, whilst containing proposals that cannot be voted on by LPs.

what seems to be happening here, as far as the LP vote not appearing goes, is the following (from core/governance/engine_batch.go:L314):

```go
func (e *Engine) addBatchVote(ctx context.Context, batchProposal *batchProposal, cmd types.VoteSubmission, party string) error {
	validationErrs := vgerrors.NewCumulatedErrors()

	perMarketELS := map[string]num.Decimal{}
	for _, proposal := range batchProposal.Proposals {
		if err := e.canVote(proposal, batchProposal.ProposalParameters, party); err != nil {
			validationErrs.Add(fmt.Errorf("proposal term %q has failed with: %w", proposal.Terms.Change.GetTermType(), err))
			continue
		}

		if proposal.IsMarketUpdate() {
			marketID := proposal.MarketUpdate().MarketID
			els, _ := e.markets.GetEquityLikeShareForMarketAndParty(marketID, party)

			perMarketELS[marketID] = els
		}
	}

	if validationErrs.HasAny() {
	        // ... omit logging
		return validationErrs
	}

	vote := types.Vote{} // construct vote, including perMarketELS

	if err := batchProposal.AddVote(vote); err != nil {
		return fmt.Errorf("couldn't cast the vote: %w", err)
	}

```

If the LP doesn't have any (or has insufficient) governance tokens, and the batch contains any proposal that cannot be voted on by the LP, their vote will have validation errors, and doesn't get added to the batch votes.
