### ISSUE TITLE
[Bug]: Old oracles that should be already deactivated are still active in the data node

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#10799]
### Problem encountered

We have the following oracles: 

- [48dcb3d9c1665600eb8b20b39c76f79fec00e4d7f7f489562ed0ec96d2acb14b](https://explorer.vega.xyz/oracles/079ffafb39a9465513bd587a0ebecbc82555272abb6c9d757a45cac1c761f705)
- [f14a9d9351ec29670111f8bdcd2e0aace759e655cd7f27dd9bc054c5a2d208c9](https://explorer.vega.xyz/oracles/079ffafb39a9465513bd587a0ebecbc82555272abb6c9d757a45cac1c761f705)
- [d77318942056e81750502a91b7111823f5cebfa9b827abaf1fc760c1e7a48beb](https://explorer.vega.xyz/oracles/079ffafb39a9465513bd587a0ebecbc82555272abb6c9d757a45cac1c761f705)
- [3c201efb4e088e6f24bce0806e09c02be586fc43bc7281a27758fc71b24059f1](https://explorer.vega.xyz/oracles/079ffafb39a9465513bd587a0ebecbc82555272abb6c9d757a45cac1c761f705)
- [dd08b862c2d9ddcb6f29e9ea6a93cfc3093f1d12a259ebcffef096344cc7448d](https://explorer.vega.xyz/oracles/079ffafb39a9465513bd587a0ebecbc82555272abb6c9d757a45cac1c761f705)

All the above oracles are old and should be deactivated, but they are still active for some reason. It confuses people who are doing some analytics/alerting. 

We arenot receiving data for the above oracles from the core anymore for about 10 days but they are still active

### Observed behaviour

OId oracles are still active but they should be inactive

### Expected behaviour

Oracles should have state `STATUS_DEACTIVATED`

### Steps to reproduce

1. Select the following query and check which oracles are still used in the markets

```
SELECT *
	FROM oracle_specs 
	WHERE (data -> 'external' -> 'ethOracle') IS NOT null
	AND id NOT IN (SELECT id FROM oracle_specs WHERE status='STATUS_DEACTIVATED')
```

### Software version

v0.74.7

![image](https://github.com/vegaprotocol/vega/assets/1239637/21d3aa09-bc02-43ec-953d-d9de24d69973)

**Comment by jeremyletang** [comment]
They all seems to be deactivated, can't see anything similar on current mainnet. closing.
