### ISSUE TITLE
[Feature]: AMM rewards should be sent to the owner's key

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#10828]
# Feature Overview

**In order for** rewards paid to AMM's to not get stuck in a vested account
**We will** distribute rewards paid to an AMM key to its owner's key instead
**So that** the owner of the AMM can access the rewards

Since the AMM's party/vega-public-key has no private key associated with it, any rewards that end up in their vested account will be stuck and cannot be transferred out.

Spec change:
https://github.com/vegaprotocol/specs/pull/2019/commits/511ae351ce5640b50ba0ca4426966f39df445c67

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by JonRay15** [comment]
Pretty sure we agreed this wouldnt be done ... rewards go to the subkey and we will be able to query for those and show them to the user
