### ISSUE TITLE
[Bug]: margin factor has been capped at 1 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#10885]
### Problem encountered

in isolated margin mode, when updating margin factor, any factors over 1 has been rejected with the following message: update_margin_mode.margin (must be between 0 (exchanged) and 1 (included))

### Observed behaviour

margin factor is capped at 1

### Expected behaviour

there should be no upper limit on margin factor

### Steps to reproduce

```bash
the margin factor should be greater than 1 on this market 

https://console.stagnet1.vega.rocks/#/markets/346d925ab76fca647e4dabb6f1e6ef9839e62a2b11a0f151368930613ce2108a
```

### Software version

v0.75.0-preview

**Comment by ze97286** [comment]
that's what the spec says. 
<img width="1023" alt="image" src="https://github.com/vegaprotocol/vega/assets/6655556/89460b37-1fcb-4ab0-86cc-3bcd3b7e8690">

**Comment by Jiajia-Cui** [comment]
> that's what the spec says. <img alt="image" width="1023" src="https://private-user-images.githubusercontent.com/6655556/312485316-89460b37-1fcb-4ab0-86cc-3bcd3b7e8690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzg3ODgsIm5iZiI6MTcxMDMzODQ4OCwicGF0aCI6Ii82NjU1NTU2LzMxMjQ4NTMxNi04OTQ2MGIzNy0xZmNiLTRhYjAtODZjYy0zYmNkM2I3ZTg2OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMTQwMTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU2N2Y2ZThkOTI3ZTFmNTUxMTRkZmIzZTg2ZjU2NDVlYTQ3NGVmNGE0YTZkMjlmMWJlMjVlOGY1OWQ5MmQwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A2aTr12kVcOCu7-zOHJs1TpytbsjCVs3QDVXid4O4bU">

that’s updated in the spec [PR](https://github.com/vegaprotocol/specs/pull/2206/files)
