### ISSUE TITLE
[Bug]: In spot market "target stake" is using wrong decimal

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#10974]
### Problem encountered

In Spot market "target stake" is using wrong decimal, it should be using asset decimal

### Observed behaviour

see the FT, line 80, target stake should be using asset decimal which is set to 2 

https://github.com/vegaprotocol/vega/pull/10967

### Expected behaviour

target stake should be using asset decimal 

### Steps to reproduce

```bash
https://github.com/vegaprotocol/vega/pull/10967
```

### Software version

v0.74.10

### Failing test

https://github.com/vegaprotocol/vega/pull/10967

**Comment by ze97286** [comment]
I don't think there's an issue. The target stake is in asset - check your position decimal places.
