### ISSUE TITLE
[Bug]: Can't show network history segments

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#10980]
### Problem encountered

When execute the following command `./vega datanode network-history show --home /home/vega/vega_home`

I am getting the following error:

```
2024-03-22T20:21:41.749Z        ERROR   root    networkhistory/networkhistory.go:128    failed to list all network history segments     {"error": "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (17041693 vs. 4194304)"}
```

### Observed behaviour

Error displayed

### Expected behaviour

Correct output displayed

### Steps to reproduce

```bash
1. Have a mainnet data node with a lot of state + archival network history
2. Execute the command as described above
```

### Software version

multiple versions (including latest)

**Comment by wwestgarth** [comment]
There is a similar issue that I think we should address while doing this. The API to list history segments has no pagniation which is a massive oversight given how much data it ends up returning:
https://docs.vega.xyz/mainnet/api/rest/data-v2/trading-data-service-list-all-network-history-segments

**Comment by EVODelavega** [comment]
The command in question uses a gRPC client that doesn't specify a max size for the messages it can receive. As per the documentation:

> MaxRecvMsgSize returns a ServerOption to set the max message size in bytes the server can receive. If this is not set, gRPC uses the default 4MB.

As seen in the error message, the response we are receiving is ~16.25MB, which is obviously > 4MB, hsence the error message reads `(17041693 vs. 4194304)` as the size of the received message versus the max acceptable size.
