### ISSUE TITLE
[Bug]: Sub proposals returned in reverse order in GraphQL

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#11005]
### Problem encountered

The subProposals are returned in the incorrect order. This makes it harder to determine market Ids in batch proposals

### Observed behaviour

The order appears to be reversed when using the `subProposals` field. The `batchTerms` are the correct order

### Expected behaviour

The order should be the same order as provided in the batch proposal

### Steps to reproduce

```bash
1. Submit a batch proposal with more than one batch
2. Use the query below
3. Notice that sub proposals are in the wrong order


{
  proposalsConnection {
    edges {
      proposalNode {
        ... on BatchProposal {
          id
          subProposals {
            terms {
              change {
                __typename
                ... on NewMarket {
                  instrument {
                    name
                    code
                  }
                }
              }
            }
          }
          batchTerms {
            changes {
              change {
                __typename
                ... on NewMarket {
                  instrument {
                    name
                    code
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
```


### Software version

0.75.3

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

**Comment by ze97286** [comment]
@mattrussell36  what is wrong about the sorting? they are sorted in ascending enactment time, how do you expect them to be sorted?

**Comment by jeremyletang** [comment]
> @mattrussell36 what is wrong about the sorting? they are sorted in ascending enactment time, how do you expect them to be sorted?

I suppose that because every proposal ID inside a batch is derived from the order in which the sub proposal was in the batch, if these are being sorted by the datanode as you explain, then it's not possible to derive the ID again from the frontend point of view.

@mattrussell36 would that be the issue?

**Comment by jeremyletang** [comment]
Discussed this with @mattrussell36 offline and they seems alright with @EVODelavega answer. closing now.
