### ISSUE TITLE
[Bug]: Panic failed to release funds from holding account for trade

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#11011]
### Problem encountered

`2024-03-26T16:46:30.322Z	ERROR	tendermint	consensus/state.go:801	CONSENSUS FAILURE!!!	{"err": "failed to release funds from holding account for trade", "stack": "goroutine 174 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:801 +0x46\npanic({0x4f85580?, 0xc002da3800?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc004f31240?})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000cce820, {0xc004d6f880, 0x2, 0x2})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec\ngo.uber.org/zap.(*Logger).Panic(0xc005129a80?, {0x5ad81d7?, 0xc00501c2c0?}, {0xc004d6f880, 0x2, 0x2})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).handleTrade(0xc005096580, {0x621d648, 0xc004f59230}, 0xc004f06210)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:2831 +0x6f7\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).handleConfirmation(0xc005096580, {0x621d648, 0xc004f59230}, 0xc004f7a180)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:1582 +0x594\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).uncrossOnLeaveAuction(0xc005096580, {0x621d648, 0xc004f59230})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:448 +0x25f\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).uncrossOrderAtAuctionEnd(0xc005096580, {0x621d648, 0xc004f59230})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:468 +0x75\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).UpdateMarketState(0xc005096580, {0x621d648, 0xc004f59230}, 0xc0056f6f40)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:481 +0x5f9\ncode.vegaprotocol.io/vega/core/execution.(*Engine).UpdateMarketState(0xc000a2e2c0, {0x621d648, 0xc004f59230}, 0xc0056f6f40)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine.go:618 +0x97\ncode.vegaprotocol.io/vega/core/processor.(*App).enactMarketStateUpdate(0xc000fab880, {0x621d648, 0xc004f59230}, 0xc003167340)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:2413 +0x356\ncode.vegaprotocol.io/vega/core/processor.(*App).onTick(0xc000fab880, {0x621d648, 0xc004f59230}, {0x1?, 0xc002da3630?, 0x0?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:2260 +0xeae\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:107\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000f4c300, {0x621d648, 0xc004f59230}, {0x40?, 0x89562e0?, 0x0?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:80 +0x263\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0xc000fab880, 0xe8, {0xc005128f40, 0x40}, {0x1d2ebab?, 0x28?, 0x0?}, {0xc004f6a1e0, 0x28}, {0x89562e0, ...})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:1015 +0x956\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00099ce40, {0xc001d02530?, 0x1ce4465?}, 0xc004f52c00)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/abci.go:162 +0x449\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x5000f60?, {0x621d728?, 0x89562e0?}, 0x7ffbcd53b108?)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc001d025d0?, {0x621d728?, 0x89562e0?}, 0xc0?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/abci/client/local_client.go:185 +0xd0\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc000b5e3f0, {0x621d728, 0x89562e0}, 0x1?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/proxy/app_conn.go:104 +0x16d\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc001d8b340, 0x6}}, {0xc001d8b350, 0xb}, 0x1, 0xe7, {{0xc005002da0, ...}, ...}, ...}, ...)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/state/execution.go:213 +0x622\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc001d96380, 0xe8)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1771 +0xb7d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc001d96380, 0xe8)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1682 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1617 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc001d96380, 0xe8, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:1655 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc001d96380, 0xc004d3aea0, {0xc000b90240, 0x28})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2334 +0x1d4d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc001d96380, 0xc004d3aea0, {0xc000b90240?, 0xc001d03c08?})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:2066 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc001d96380, {{0x61f3ae0, 0xc0041ae780}, {0xc000b90240, 0x28}})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:929 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc001d96380, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:836 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 94\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/state.go:398 +0x10c\n"}`

### Observed behaviour

the scenario - 

1. spot market proposal enacted
2. uncrossing trade moves the market to continuous
3. attempt to trade moves the market to price mon auction
4. cancel the orders that triggered price mon auction
5. lp commits provisions and submits orders
6. other parties enter orders that will cross
7. propose to terminate the market <- at this point is the panic

### Expected behaviour

no panic

### Steps to reproduce

```bash
1. run the test on system-test branch `0043-MKTL-008`
```

### Software version

dev branch

### Failing test

test_spot_market_closed_in_price_auction

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/52516/testReport/junit/tests.governance/test_spot_market_gov/test_spot_market_closed_in_price_auction/

**Comment by cdummett** [comment]
Just to add in case helpful, we just hit this panic in CI fuzzing runs also.
- https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fvega-market-sim-reinforcement/detail/vega-market-sim-reinforcement/392/pipeline
- https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fvega-market-sim-reinforcement/detail/vega-market-sim-reinforcement/394/pipeline
