### ISSUE TITLE
[Bug]: Investigate 5s blocks

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#11067]
### Problem encountered

<img width="751" alt="Screenshot 2024-04-04 at 13 19 22" src="https://github.com/vegaprotocol/vega/assets/6678/c2979fad-4e60-4dc3-93f2-fafaa629c5a3">

There are periodic slow blocks on this network. These correlate with larger transaction counts - 100+ txs. Current benchmarks are not flagging up anything that *should* cause slowness in these blocks

### Observed behaviour

* It's not all that frequent, but it is common
    <img width="726" alt="Screenshot 2024-04-04 at 13 36 53" src="https://github.com/vegaprotocol/vega/assets/6678/1133fa2b-abc1-4e50-8de8-8f48975b8115">
* They do not happen on a regular schedule
* They are distributed across validators (see spreadsheet screenshot below)
    <img width="410" alt="Screenshot 2024-04-04 at 13 34 29" src="https://github.com/vegaprotocol/vega/assets/6678/742c10ca-79df-4ebc-b6b2-cbb0e65d3c21">

The makeup of the larger blocks is relatively ordinary:
* 100-ish batch transactions
  * Most contain a cancel all in market order
  * Place 3-15 orders
* The remaining TXs are generally Chain Events for oracle data

### Expected behaviour

Block time does not increase 5x when the tx count is only 3x

### Steps to reproduce

```bash
1. Observe Grafana for slow blocks
2. Hover over the graph and get a timestamp
3. Head over to explorer and find the block for that timestamp
4. Inspect block contents
```

<img width="289" alt="Screenshot 2024-04-04 at 13 25 15" src="https://github.com/vegaprotocol/vega/assets/6678/3284d60b-f2c4-43b9-8316-68cbe4b14f7c">

<img width="1323" alt="Screenshot 2024-04-04 at 13 25 46" src="https://github.com/vegaprotocol/vega/assets/6678/25f03f64-a8ab-4578-8c53-a934c6fa4719">

### Software version

0.74.10

### Example blocks
* https://explorer.vega.xyz/blocks/41984214
* https://explorer.vega.xyz/blocks/41983632

**Comment by edd** [comment]
This *could* be related to incorrect data in the DB about who proposed a block, @jeremyletang is looking in to it

**Comment by peterbarrow** [comment]
If I remember correctly this was due to a badly configured node so closing this ticket.
