### ISSUE TITLE
Enhance positions API to take an array of keys as inputs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#11084]
# API Overview

As per title

## API request details

- [ ] Position API can be fed an array of IDs (Party IDs or sub accounts) and be returned all values

### Filtering requirements (inputs)
As above

### Sample API output (optional)

```
Dont think this is needed for this 
```

## Questions 
None

## API test scenarios
Detailed scenarios that can be executed as feature tests to verify that the API has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by JonRay15** [comment]
@mattrussell36 are you ok with having a Boolean on this for "include subAccounts" rather than feeding an array?

Are there situations where we need to query for multiple keys positions at a time?

**Comment by mattrussell36** [comment]
Can we clarify if this issue relates to the subscription or the normal request? The GraphQL query and normal endpoint both already accept multiple party IDs, so an `includeSubAccounts` argument would need to account for the parties provided.

That said, this sounds like a useful addition and sounds good to me. 

We do currently have a positions view which shows positions across all keys. Its on the portfolio page (perhaps you could argue we should make this only show positions for the current key so its less confusing with what we show on the trading page).

Finally, the positions stream (and GraphQL subscription) currently only accepts a single party ID. Ideally this would be updated to accept multiple parties and handle the `includeSubAccounts` argument in the same way as the normal http/graphql request.
