### ISSUE TITLE
[Bug]: Block Explorer API does not parse newAsset in batch proposals correctly

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#11203]
### Problem encountered

A batch proposal can (in 0.76.x) now contain a `newAsset` proposal. This is new. I suspect the Block Explorer API hasn't been updated to parse these properly - the object comes through with only `enactmentTimestamp` and no `newAsset details`

### Observed behaviour

The following `batchSubmission` (https://be.stagnet1.vega.rocks/rest/transactions/212F584E6FCF60A34219E55D71B49C212C178BD3CCF16A8D59A81E0709DFE834) contains two newAssets. Note the lack of a `newAsset` property:

```json
"batchProposalSubmission": {
        "reference": "",
        "terms": {
          "closingTimestamp": "1714051215",
          "changes": [
            {
              "enactmentTimestamp": "1714051395"
            },
            {
              "enactmentTimestamp": "1714051395"
            },
            {
              "enactmentTimestamp": "1714051395",
              "updateNetworkParameter": {
                "changes": {
                  "key": "validators.epoch.length",
                  "value": "30m"
                }
              }
            },
            {
              "enactmentTimestamp": "1714051395",
              "updateNetworkParameter": {
                "changes": {
                  "key": "limits.markets.proposeSpotEnabled",
                  "value": "1"
                }
              }
            }
          ]
        },
```

### Expected behaviour

`batchProposalSubmission`s containing `newAssets` have the `newAset` details in the JSON respojse

### Steps to reproduce

```bash
1. Submit a batch proposal with a newAsset
2. Fetch the block from the block explorer API
```

### Software version

0.76.0

**Comment by jeremyletang** [comment]
This is fixed in there already: https://github.com/vegaprotocol/vega/pull/11199
