### ISSUE TITLE
[Capped Futures] Implements data node APIs

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#11228]
Add the missing type in the entites package (if required).
Add the missing types and APIs in the graphql schema.
Add filtering in the market list API to be able to filter and return: PERPS, FUTURE, SPOTS, CAPPED FUTURE or BINARY OPTIONS markets. Inclusive or exclusive,

**Comment by JonRay15** [comment]
To confirm .... I dont see whhy front end needs this filter for now ... its fine ... we can add it later if needed.

**Comment by jeremyletang** [comment]
nothing to do.
