### ISSUE TITLE
[Bug]: market gets stuck when market is leaving opening auction and the exit price is 0

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#11313]
### Problem encountered

When market is leaving opening auction and the exit price is 0, the market gets stuck

There is increased memory consumption (30GB, normal consumption is around 6GB) 

### Observed behaviour

please see details in the feature test 
https://github.com/vegaprotocol/vega/pull/11312

### Expected behaviour

market should not be stuck 

### Steps to reproduce

When there is only a long order with price 0 after the uncrossing, the market gets stuck
<img width="604" alt="image" src="https://github.com/vegaprotocol/vega/assets/92106936/45d1a174-a543-4060-ae24-17912a589468">

if there is one more long order with non-zero price, then market can get out of opening auction
<img width="605" alt="image" src="https://github.com/vegaprotocol/vega/assets/92106936/2756f9e1-9c8d-4854-a258-ca540032c268">

### Software version

v0.75.8

### Failing test

https://github.com/vegaprotocol/vega/pull/11312

**Comment by EVODelavega** [comment]
This was indeed a bug, the fix was pushed to the AC branch, which has since been merged: https://github.com/vegaprotocol/vega/pull/11289
