### ISSUE TITLE
[Bug]: Block Explorer API filtering for Proposal does not include transfer proposals

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#11365]
### Problem encountered

Governance Transfer proposals are not included when requesting all proposals from the Block Explorer API

### Observed behaviour

https://be.vega.community/rest/transactions?first=50&filters[cmd.type]=Proposal
vs
https://vega-data.nodes.guru:3008/api/v2/governances, or more specifically

```
curl -L -X GET 'https://vega-data.nodes.guru:3008/api/v2/governances?proposalType=TYPE_NEW_TRANSFER&pagination.first=1' | jq 
```

### Expected behaviour

Filtering for proposals should include all proposals. Specifically `644e02af5d6dd4dc5142b79b908fc3cea5d11e272171e6cc09d3d57cb1c1914f` should appear.

### Steps to reproduce

```bash
1. https://be.vega.community/rest/transactions?first=50&filters[cmd.type]=Proposal
2. Observe the lack of transfer proposals
```

### Software version

0.76.8

**Comment by wwestgarth** [comment]
Because `644e02af5d6dd4dc5142b79b908fc3cea5d11e272171e6cc09d3d57cb1c1914f` was submitted as a batch proposal, which is a difference cmd type you have to do:
```
https://be.vega.community/rest/transactions?first=100&filters[cmd.type]=Batch%20Proposal
```
to see it.

**Comment by edd** [comment]
I believe @wwestgarth is correct, so I'll close this and see if there's a ticket I need on the Explorer front end to make this clearer
