### ISSUE TITLE
[Bug]: User managed to get liquidated on fully collateralised capped market

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#11453]
### Problem encountered

User went short on a market that was fully collateralised, they immediately got liquidated even though the short was at 35.5, the sell orders were at 45 and the cap price was at 100.

### Observed behaviour

With only having a position open on 1 market, which is fully collateralised, they got liquidated before settlement and/or reaching cap price.

### Expected behaviour

A fully collateralised capped market should not liquidate users unless it reaches cap, and or the user has cross margin and have open positions on other markets.
[eurofinal.json](https://github.com/user-attachments/files/16232498/eurofinal.json)
![Screenshot 2024-07-13 at 10 34 35](https://github.com/user-attachments/assets/e3370337-7dd6-42ac-8a68-6ede306cb554)

### Steps to reproduce

```bash
1. Create a capped market with 100 in cap, as in the attached file
2. Create sell orders at 45 and buyorders at 35.5 and uncross at 40
3. Make a short order at 35.5 which takes up the full margin.
4. See user getting liquidated
```

### Software version

v0.77.0-preview.7

**Comment by Jiajia-Cui** [comment]
@daunatv do you remember whether the binary settlement is set to 'true'?

**Comment by daunatv** [comment]
"cap": {
              "maxPrice": "1000",
              "binarySettlement": true,
              "fullyCollateralised": true
              
              You can find it here
              https://governance.fairground.wtf/proposals/4e589ef7e72251b075081797c2e7a45a1fb8ff95d261d9a3043a18ef3fb4463a
