### ISSUE TITLE
No position returned for market in opening auction, expect a position with 0 open vol but some margin balance.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#2585]
# Problem encountered
New market (either in auction or continuous) no one has yet matched.
I have orders in the book but I do not appear to have a position.
I do have a margin account.

# System response
no row for my position. yet I do have a margin balance

Expected: As with a market in a "normal" state. The positions API returns a position with 0 open volume.

**System version:** Specify the system version (0.xx.xx)
**Protocol:** Specify the protocol
n/a

**Component:** Specify the components that might be related
- [x] [Vega](https://github.com/vegaprotocol/vega/)
- [ ] [Tendermint](https://github.com/tendermint/tendermint)
- [ ] [Console](https://github.com/vegaprotocol/console/)
- [ ] [Ethereum Bridge](https://github.com/vegaprotocol/Event_Queue)
- [ ] [Vega Wallet](https://github.com/vegaprotocol/go-wallet/)

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Create a new market
2. wait for the opening auction
3. place an order on the empty book
4. note margin balance + note positions

<img width="1423" alt="Screenshot 2020-11-17 at 15 03 04" src="https://user-images.githubusercontent.com/13255539/99406724-21d30a00-28e6-11eb-8985-7480efd0c5a8.png">

# Expected behaviour
As per normal: a margin balance should result in a position even if open volume is 0

**Comment by gordsport** [comment]
Hey @peterbarrow 
Now we have remove the Badger DB can you recheck and see if this can be closed now?

**Comment by gordsport** [comment]
@peterbarrow 

Please can you re-review this and close if required?
