### ISSUE TITLE
Add missing integration test steps for Fees Feature Tests & API endpoints

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/vega#3692]
# Feature Overview
Implementation of below missing step definitions for feature tests for [Fees]
(https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0029-fees.md)- 
[infrastructure fees]
[maker]
[taker]
[buyer_fee]
[seller_fee]
[marker_fee]

As a QA Test Engineer 
I want missing step definition to be implemented for [Fees] feature tests  
So that I am able to run the integration tests successfully

The below three component of fee factors should be available via an API such as the market data API or market framework for querying the factors directly
[Infrastructure] 
[maker]
[liquidity]  

Implementation of missing API components - 
- A "buyer_fee" and "seller_fee" are exposed in APIs for every trade, split into the three components (after the trade definitely happened)
- The three component fee rates - [infrastructure]fee_factor, [maker]fee_factor, [liquidity]fee_factor are available via market data API or market framework so that users could understand the breakdown by querying for fee payment transfers by trade ID

# Tasks
- Implementation of the missing step definition for [Fees] feature tests-
- And the accumulated infrastructure fees should be "0" for the market "ETH/DEC21"
-  Then the following trades should be executed:
buyer    | price | size | seller     | maker   | taker      |
trader3 | 1002 | 3      | trader4 | trader3 | trader 4 |
- Then the following trades should be executed:
buyer      | price | size | seller    | maker   | taker   | buyer_fee | seller_fee | maker_fee |
trader3a | 1002  | 2    | trader4 | trader3 | trader4 | 30            | 11              | 11                |

# Acceptance Criteria
- It is possible to run the feature tests scenario for [Fees] successfully.

# Test Scenarios
    Feature: Fees Calculations
    Scenario:Fees Calculations
    Given I have open orders and no trades  
    When I look for total fees for the order  
    Then the accumulated infrastructure fees should be "0" for the market "ETH/DEC21"

    Given I have open trades  
    When I look for total fees for the trade  
    Then the following trades should be executed:
     # | buyer    | price | size | seller    | maker   | taker     |
     # | trader3 | 1002  | 3    | trader4 | trader3 | trader4 |

    Given I have open trades 
    When I look for total fees for the trade  
    Then the following trades should be executed:
    # | buyer      | price | size | seller    | maker   | taker   | buyer_fee | seller_fee | maker_fee |
    # | trader3a | 1002  | 2    | trader4 | trader3 | trader4 | 30            | 11              | 11                |

# Additional Details (optional)
Relevant Branch / Line for updating the missing step definition-
Infrastructure Fee- https://github.com/vegaprotocol/vega/blob/6036d31c362378577e9a040902f99971cbc13192/integration/features/testing-fees.feature#L59
Maker and Taker functions -
https://github.com/vegaprotocol/vega/blob/c3e0579aaea753b369af0ce7abe31adee644dde9/integration/features/testing-fees.feature#L75
Buyer_fee, Seller_fee and Maker_fee functions -
https://github.com/vegaprotocol/vega/blob/8c889381f5a65482f844e3412e1cfbb21fae17cf/integration/features/testing-fees.feature#L270

**Comment by vega-paul** [comment]
Can be closed -covered by ST
