### ISSUE TITLE
Automate release to GitHub

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#3825]
I want to ask/propose a few improvements that can be done after Sweetwater is out.

In Jenkins, we use `GitHub CLI`, and we use it to create a release in GitHub. Our current usecase:
```bash
# check if tag contains `-pre`, if yes then add `--prerelease` flag to `gh` call
[[ $TAG_NAME =~ '-pre' ]] && prerelease='--prerelease' || prerelease=''
# create a release in GitHub and upload artefacts
gh release create $TAG_NAME $prerelease ./cmd/data-node/data-node-*
```
By default `gh release create` by default uses the title and release description from Git Tag. Example result:

<img width="784" alt="Screenshot 2021-07-31 at 10 36 46" src="https://user-images.githubusercontent.com/20031574/127734244-eecce43f-ff23-45b0-b822-5a36e0a0317d.png">

Improvements to consider:
1. Using Git Tag for description has certain limitations. To work around those, we could specify the `.md` file for `gh release create --notes-file changelog.md ...`.
2. I believe that the release process can be fully automated if needed, for example:
  * Create a `release/vX.Y.Z` branch from `develop`
  * Some automated scripts will detect a new branch and:
    - Create a PR from that branch,
    - Use some scripts to generate changelog etc., and commit to the PR,
  * Manually improve changelog etc. in the PR,
  * Once happy: merge the PR,
  * Rest is automated:
    - Tag creation with comments,
    - GitHub release creation with artefacts.

@ashleyvega @edd @gordsport @jeremyletang - what do you think?

Useful links:
1. Our release process: https://github.com/vegaprotocol/devops-infra/blob/master/doc/trading-core/release_process.md
2. GitHub CLI: https://cli.github.com/manual/gh_release_create

**Comment by jeremyletang** [comment]
Discussed this with @fkondej, consensus is: we have done release for a while, and it appears that the way we operate for now is good enough for our needs. We will revisit releasing in the future if: we have the time for this, and a new need emerging in more automation around releases.
