### ISSUE TITLE
Consider versioning across nodes

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#4059]
Just an analysis ticket, raising it as we've been discussing having mainnet validators run some of the  testnet nodes too, so we might want to make it more difficult for them to mess things up by using a wrong software version for a given network.

**Comment by jeremyletang** [comment]
@witgaw anything you want to do about this ticket? It's been open for almost a year, without any action since then. Maybe move it in another more appropriate place?

**Comment by witgaw** [comment]
Can be closed now I'm pretty sure.
