### ISSUE TITLE
Add config set/get in CLI

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vega#4076]
It would be useful for scripts to be able to:
```
$ vega node config get Blockchain.Tendermint.ClientAddr
tcp://tendermint.example.com:26657

$ vega node config set Blockchain.Tendermint.ClientAddr tcp://somenewhost.example.com:26657
```
(and likewise for `faucet` and `wallet` config vars.)

The current way of doing things is:
-  either: `sed --in-place 's/ClientAddr = "xx"/ClientAddr = "yy"/' /path/to/config.toml`
- or (even worse): `python3 -c 'import toml; x=toml.load(configfile); y=toml.load(overridesfile); x+=y; toml.save(x, configfile)'`

**Comment by jeremyletang** [comment]
Closing this as there's not much appepite for it as of now, most of our infrastructure is dealing fine without, and lots of scripting has move to vegacapsule which generate and edit configuration from go code using the structs from the repository.
