### ISSUE TITLE
Run `nancy` on the CI

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#4376]
`nancy` (https://github.com/sonatype-nexus-community/nancy) is a tool that checks the dependencies of a Go project against a database of known CVEs and will flag any possible vulnerabilities. 

We should run this on the CI alongside the linters so that any security issues can be resolved quickly.

**Acceptance Criteria**
- Nancy is run on the CI
- All reported vulnerabilities have been resolved by updating dependency versions

**Comment by gordsport** [comment]
Already have GH security checks enabled - is there any benefit to having this running as well @wwestgarth
