### ISSUE TITLE
Implement an healthcheck endpoint

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#4525]
Before tendermint .35, tendermint would be able to start, and wait for the application to start up indefinitely and would just connect to it when available.
Since tendermint .35 this behaviour is not true anymore, and if the application is not available, tendermint would just stop with an error.

This is slightly annoying and require then a couple more of synchronisation than before, in order to ease devops jobs (not have random sleep N in the scripts which might fail if the node takes more than N seconds to be ready). We should implement some kind of healthcheck which would return OK once the node is ready to accept connection from tendermint.

We could also make this healthcheck more complex, and return the status of different internal service. e.g:
- OK to get tendermint connection
- OK to serve API
- OK to send tendermint transaction
- etc if needed.

**Comment by gordsport** [comment]
Close as wont fix
