### ISSUE TITLE
Coded features review: pegged orders

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/vega#4813]
Comments from @witgaw- 
Parking for now, will resume and wrap it up in August.
With engineering now: vegaprotocol/vega#3534

Related Core tickets
[[#4385](https://github.com/vegaprotocol/vega/issues/4385)]
[[#142](https://github.com/vegaprotocol/protos/issues/142)]
[[#144](https://github.com/vegaprotocol/protos/issues/144)]

**Comment by davidsiska-vega** [comment]
We have feature tests.
