### ISSUE TITLE
Coded features review: Floating point consensus (Happy Path)

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/vega#4816]
Specs for [Floating point consensus](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0065-FTCO-floating_point_consensus.md)

This ticket covers creating feature tests for happy path scenario. Dealing with negative scenarios to be done and tackled separately.

**Comment by davidsiska-vega** [comment]
We have feature tests for this.
