### ISSUE TITLE
Proposal voting with insufficient tokens in epoch returns 500 from wallet

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#4819]
Walllet request

b'{"voteSubmission": {"proposalId": "b404e72441d713dacb6e86a822ef08ebf40c48f590dc0b6349767bf7b46c8c27", "value": "VALUE_YES"}, "propagate": true, "pubKey": "32789e83398d7803ed50f04fefd78076416ff744c22a729c0c89f3f1f9fd170d"}'

Wallet response

Invalid argument error from /api/v1/command

500
'{"error":"rpc error: code = InvalidArgument desc = InvalidArgument error","details":["party has insufficient tokens to submit votes in this epoch"]}'

Im expecting a 4xx error returned here rather than 500

**Comment by wwestgarth** [comment]
handled in [5439](https://github.com/vegaprotocol/vega/issues/5439)
