### ISSUE TITLE
MarketDataByID and MarketByID response discrepancy - MarketDataByIDRequest sometimes never updates

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#4908]
Both these APIs return tradingMode.

We have system tests which create market and wait for trading mode continuous before running the workflows.

We use grpc MarketDataByIDRequest to check the tradingMode content after submitting necessary orders and lq commitment/shape to supply enough stake and conditions to enable trading.

This sometimes **never** returns back a continuous mode.
During this time I can see vegatools MARKET_DATA stream aligned with the grpc response, i..e still in auction.

But the data-node 'markets' endpoint returns a response containing "tradingMode": "TRADING_MODE_CONTINUOUS" within a few seconds.

I believe the grpc MarketDataByIDRequest and MarketByIDRequest are out of step.

vegatools

`{"id":"27614-7","block":"5BDC25A2482B985049E13BBD8760C3290281C6DB3C2738603ADCCC4C51A0E8DD","type":"BUS_EVENT_TYPE_MARKET_DATA","marketData":{"markPrice":"0","bestBidPrice":"0","bestOfferPrice":"0","bestStaticBidPrice":"0","bestStaticOfferPrice":"0","midPrice":"0","staticMidPrice":"0","market":"153cdfcd03eaac074157ae28185c12618db613892636280681ce50acaba16fbd","timestamp":"1646394998892773400","auctionEnd":"1646394473214300200","auctionStart":"1646394464214300200","indicativePrice":"0","marketTradingMode":"TRADING_MODE_OPENING_AUCTION","trigger":"AUCTION_TRIGGER_OPENING","targetStake":"0","suppliedStake":"3905000","marketValueProxy":"3905000","liquidityProviderFeeShare":[{"party":"c83bfe5e1d49e11a286e2da2238132db7c916e593223d4f6d27d46807ff9679f","equityLikeShare":"0","averageEntryValuation":"3905000"}]},"version":1,"chainId":"chain-GpJUrq"}
`

Markets API at cmd line
[markets.txt](https://github.com/vegaprotocol/vega/files/8185672/markets.txt)
"tradingMode": "TRADING_MODE_CONTINUOUS"
"id": "153cdfcd03eaac074157ae28185c12618db613892636280681ce50acaba16fbd"

MarketDataByIDRequest grpc
`{'markPrice': '0', 'bestBidPrice': '0', 'bestOfferPrice': '0', 'bestStaticBidPrice': '0', 'bestStaticOfferPrice': '0', 'midPrice': '0', 'staticMidPrice': '0', 'market': '153cdfcd03eaac074157ae28185c12618db613892636280681ce50acaba16fbd', 'timestamp': '1646395270503975700', 'auctionEnd': '1646394473214300200', 'auctionStart': '1646394464214300200', 'indicativePrice': '0', 'marketTradingMode': 'TRADING_MODE_OPENING_AUCTION', 'trigger': 'AUCTION_TRIGGER_OPENING', 'targetStake': '0', 'suppliedStake': '3905000', 'marketValueProxy': '3905000', 'liquidityProviderFeeShare': [{'party': 'c83bfe5e1d49e11a286e2da2238132db7c916e593223d4f6d27d46807ff9679f', 'equityLikeShare': '0', 'averageEntryValuation': '3905000'}], 'bestBidVolume': '0', 'bestOfferVolume': '0', 'bestStaticBidVolume': '0', 'bestStaticOfferVolume': '0', 'openInterest': '0', 'indicativeVolume': '0', 'extensionTrigger': 'AUCTION_TRIGGER_UNSPECIFIED', 'priceMonitoringBounds': []}`

**Comment by gordsport** [comment]
@vega-paul - this is believed to have been fixed - please can you re-test this?

**Comment by gordsport** [comment]
@vega-paul - do we have a test that covers this as persisting or can be closed

**Comment by ze97286** [comment]
this hasn't occurred since. Closing.
