### ISSUE TITLE
Epoch zero exists and lasts for only one block

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#4911]
# Problem encountered
While looking at a partially related snapshot bug I noticed that the first epoch has sequence number `0` and only lasts for the first block. 

This is because in `OnGenesis()` we call the `OnGenesisTimeLoaded` callbacks before we call `onGenesisAppStateLoaded`, and has the consequence that the `epochService` recieves its first `onTick()` notification before it has been given its network parameters for the epoch length. So for  the first epoch we end up with `s.epoch.StartTime == s.epoch.ExpireTime`:

```
s.epoch.StartTime = t
s.epoch.ExpireTime = t.Add(s.length) // current time + epoch length
```

and the epoch will end immediately. Given that the block time of the first block equals the time of genesis, this means that block-height `1` exists in `epochSeq=0` and then in block `2` we tick on over to a new epoch with sequence number `1`.

Ultimately this a really minor bug because not much of note will ever happen in this spurious epoch 0, but it is an AC in the spec that epochs start from 1, and block 1 should be in epoch 1.
https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0050-EPOC-epochs.md#0050-EPOC-001

# Observed behaviour
An epoch with sequence number `0` exists for a just the first block.

# Expected behaviour
An epoch with sequence number `1` starts at genesis and last for an epoch lengths worth of blocks.

# Evidence

## Logs
Below are logs of epoch 0 existing, with an expiry time equal to the start time.

```
2022-03-04T10:36:16.342Z	DEBUG	rewards.rewards	rewards/engine.go:190	OnEpochEvent
2022-03-04T10:36:16.342Z	INFO	spam	spam/engine.go:154	Spam protection OnEpochEvent called	{"epoch": 0}
2022-03-04T10:36:16.342Z	DEBUG	spam	spam/engine.go:158	Spam protection new epoch started	{"epochSeq": 0}
2022-03-04T10:36:16.342Z	DEBUG	epochtime/snapshot.go:15	serialising epoch length	{"": "0s"}
2022-03-04T10:36:16.342Z	DEBUG	epochtime/snapshot.go:16	serialising epoch	{"": "Seq 0 StartTime 2022-03-04 10:35:10.433264353 +0000 UTC ExpireTime 2022-03-04 10:35:10.433264353 +0000 UTC EndTime 0001-01-01 00:00:00 +0000 UTC Action EPOCH_ACTION_START"}
2022-03-04T10:36:16.346Z	DEBUG	execution	execution/engine.go:730	updating engine on new time update
2022-03-04T10:36:16.347Z	DEBUG	genesis	genesis/handler.go:49	vega initial state at genesis
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
We now load from checkpoint at genesis so we think this has now been resolved - please can you check again and close if OK

**Comment by wwestgarth** [comment]
Correct, when loading from a checkpoint this doesn't happen.
