### ISSUE TITLE
Cumulated LP fees not distributed on settlement or not updated on data node

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#5164]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/62546419/161313204-01d29fa9-69f0-4870-8107-da8bd2f715fe.png">

**Comment by davidsiska-vega** [comment]
@EVODelavega I've just checked via the vega-market-sim, see https://github.com/vegaprotocol/vega-market-sim/blob/undistributed_liquidity_fee_after_settle/examples/notebooks/LiquidityFeesCheck.ipynb . At the very least data node thinks the liquidity fees haven't been distributed.

**Comment by ze97286** [comment]
closed by #6201
