### ISSUE TITLE
Margin level API returns no values

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#5196]
Setup a market
Created two parties with balances
Entered two orders, trade produced

Using marginlevels API to return levels for market and both pubkeys - empty array returned

Request MarginLevelsRequest / grpc Response MarginLevels

**Comment by gordsport** [comment]
Closing 

Work that @ettec is doing should resolve the issue for the sync problem, therefore this will become redundant after he finishes work on his ticket.

@ettec - please can you repoen if this does not become the case
