### ISSUE TITLE
Improve integration test steps

### ISSUE THREAD

**Issue by EVODelavega** [vegaprotocol/vega#5202]
We have a lot of different integration test steps. Some of which only differ from each other by a single character, but perform distinct tasks/checks. This decreases readability/maintainability of the integration tests, and more than likely has already lead to duplication (implementing a step that was assumed not to be provided).

We should build a list here of steps that are overly ambiguous, document what their behaviours are, and how we can rephrase them so people working on scenario's have an easier time at it.

* `the orders should have the following states` vs ` the orders should have the following status`

**Comment by jeremyletang** [comment]
Remove the bug label, replaced to improvement as this is not a bug really.
