### ISSUE TITLE
Refactor market snapshot restore to reduce the introduction of bugs

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5215]
# Task Overview

When restoring a market from a snapshot we do so via a set of functions called `NewXXXFromSnapshot()` which are usually similar to the usual `NewXXX()` functions, but with no overlap in code paths.

This creates a whole class of bugs where new code being added to a `NewXXX()` is sometimes not added to the `NewXXXFromSnapshot()` functions.

It might be worthwhile trying to find a way to combine code paths and refactor these functions in a way that either means new values are picked up automatically, or will cause a compiler error if not included in the snapshot code path.

**In order to** elimante a class of snapshot bugs
**We will** try to refactor some code
**So that** the compiler can catch them for us

NOTE: it very well might be like it is for a reason, and so this is not possible. Prepare for this outcome.

# Examples (optional)
- `NewMarket()` and `NewMarketFromSnapshot()`
- `NewMonitor()` and `NewMonitorFromSnapshot()`
- `NewAuctionState()` and `NewAuctionStateFromSnapshot()`

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@wwestgarth - is this something that we should still do given the improvemnts in the snapshot pipelines we have made recently?

**Comment by wwestgarth** [comment]
With all layers of snapshot testing we now have this is less of a problem because we find bugs much quicker than we used to.
