### ISSUE TITLE
Trigger state variable calculation first time indicative uncrossing price is available

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#5237]
We're currently only triggering the calculation once the opening auction time elapses.

**Comment by gordsport** [comment]
Hey @witgaw, Is this issue still present?

**Comment by gordsport** [comment]
@witgaw @davidsiska-vega - please can you retest this on the latest version 0.55 and let us know what needs to be done before trading enabled?

**Comment by witgaw** [comment]
#5237 should've closed this, but will give it a quick look and close if it's indeed working like this now.

**Comment by ze97286** [comment]
https://github.com/vegaprotocol/vega/pull/5246 has closed it.
