### ISSUE TITLE
Update the implementation on Equity-like-share (spec 0042) given the change of the spec 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#5358]
change of the spec can be found here:
- https://github.com/vegaprotocol/specs-internal/pull/1088

link with the original issue [https://github.com/vegaprotocol/vega/issues/4931](url)

**Comment by gordsport** [comment]
Hey @Jiajia-Cui 
fyi Ive assigned to you and moved to in progress on the core board for the work to be done on the integration tests.
