### ISSUE TITLE
Core spam rejection message 'InvalidArgument'

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#5451]
Core rejects trx through the wallet when spam is detected.

For instance, when a stakeholder with insufficient balance for voting submits a vote core returns

'InvalidArgument - party has insufficient tokens to submit proposal request in this epoch'

When able, the wallet always returns a message prefixed with 'InvalidArgument'

**Comment by gordsport** [comment]
@vega-paul 
Please can you add more info ahead of us triaging this issue?

**Comment by ze97286** [comment]
or close it...? @vega-paul

**Comment by vega-paul** [comment]
Looking for a reason why core includes the words "Invalid Argument" in the returned message.

**Comment by wwestgarth** [comment]
Its because what we do in `api/core.go` is a mess. I'm looking at this right now in https://github.com/vegaprotocol/vega/issues/5439 so I think we can close this ticket as a dupe.

**Comment by wwestgarth** [comment]
handled in https://github.com/vegaprotocol/vega/issues/5439
