### ISSUE TITLE
Spam - missing transaction evidence when submitting large numbers of transactions concurrently

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#5462]
Problem found when submitting a large number of trx concurrently (market proposals) to attempt to test that more than the maximum trx can be stored in a block.

Test submits 20 market proposals.
During the run, after the wallet has hashed the trx and returned it, we check for proposal event or tx_error event.
If neither are found we raise an error and suspend the test. 
We scan for logs containing the hash returned by the wallet.

At a rate of 20 trx, we can see no events containing the trx and no logging by the core containing the hash.

**Comment by ze97286** [comment]
@vega-paul can we close this please?
