### ISSUE TITLE
Snapshots TM 0.35: understand backfilling

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5471]
# Spike Overview

When testing the new snapshot-pipelines against devnet with Tendermint v0.35 we noticed additional logs during a snapshot restore that did not happen when restoring in v0.34. The logs seem to suggest that tendermint now "backfills" historic blocks after a restore, for example if you snapshot restore to block-height 1000 tendermint will restore to that height, but now also send over the tendermint block-data for heights 1-999? This seems to increase the time it takes for a restore to happen, almost negating the reason for snapshot restore it in the first place.

This ticket is to look at the new tendermint release notes, and config options to see if this action is configurable so that we can fully understand how the new tendermint version works. 
The spec of it is here: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-068-reverse-sync.md
The RFC is here: https://github.com/tendermint/spec/blob/master/rfc/005-reverse-sync.md

Our snapshot system-tests currently relying on not having block-data for block_height 1 as a check that a restore did happen, so this ticket may have implications in general for updating core to 0.35.

## Specs
- [Link](xyz) to spec or milestone document info for the feature

# Acceptance Criteria
How do we know when this spike is ready to either drop or move into technical tasks:
- [ ] We understand how tendermint handles snapshots in v0.35

# Additional Details (optional)
Any additional information including known dependencies, impacted components.

# Examples (optional)
Code snippets, links to prototypes.

**Comment by gordsport** [comment]
Closing as we need to move back to 0.34 as advised by Tendermint
