### ISSUE TITLE
Cant reconcile party balance after trade - mismatch by 0.1 token (rounding?)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#5488]
Two parties
Starting balances [1000000000, 1000000000]
Propose Asset with dec=1
Propose Market with dec=0, pos=0
Add Liquidity to move to continuous state
Parties buy/sell at 970 size 4
Market terminates and settles at 1

Calcs/Fees
scaled_tradeval 38800
Trade Fees
'buyerFee' = {dict: 3} {'makerFee': '0', 'infrastructureFee': '0', 'liquidityFee': '0'}
'sellerFee' = {dict: 3} {'makerFee': '156', 'infrastructureFee': '39', 'liquidityFee': '11640'}

calc'd buyer_diff = scaled_tradeval - seller_makerFee_fee - seller_infrastructure_fee
38605 = 38800 - 156 - 39
calc'd seller_diff = scaled_tradeval - seller_liquidityFee_fee - seller_makerFee_fee - seller_infrastructure_fee
25965 = 38800 - 11640 - 156 - 39

Actual new balances 
[999961396, 1000026925]
diffs -38604, +26925

We lose 0.1 tokens when market settles (-38604 <> 38605)

**Comment by vega-paul** [comment]
I still cannot get anywhere near the core values

<google-sheets-html-origin><style type="text/css"></style>

before balances |   | trde |  
-- | -- | -- | --
999884188 | 1000080775 | maker fee | 156
999845584 | 1000107700 | infra fee | 39
-38604 | 26925 | liq fee | 11640
  |   | price | 970
  |   | size | 4
  |   | trade value | 3880
  |   | settlement | 1

**Comment by vega-paul** [comment]
I still cannot get anywhere near the core balances...

<google-sheets-html-origin><style type="text/css"></style>

  | Buyer | Seller | Trade |  
-- | -- | -- | -- | --
before balances | 999884188 | 1000080775 | maker fee | 156
after settlement | 999845584 | 1000107700 | infra fee | 39
diffs | -38604 | 26925 | liq fee | 11640
  |   |   | price | 970
  |   |   | size | 4
  |   |   | trade value | 3880
  |   |   | settlement | 1

**Comment by vega-paul** [comment]
First it looks like the trade value taken is not using the correct settlement price of 1 (trade value 4) but still uses trade value 3880 (970 * 4)

**Comment by vega-paul** [comment]
Ok so Ive had a go at verifying the differences here, I can match using the following

Buyers new bal = starting bal  - scaled trade value (38800) + maker fee (156) + scaled settlement value (40)
Sellers new bal = starting bal + scaled trade value (38800) - (infra fee 39 + liq fee  11640 + make fee 156) - scaled settlement value (40)

I can balance using above - please confirm if correct? @Jiajia-Cui

**Comment by Jiajia-Cui** [comment]
@vega-paul what are the "scaled trade value" and "scaled settlement value"? how are they scaled?

**Comment by vega-paul** [comment]
These are the original order price and value (970 and 4) with asset precision so 3880 as 38800
Settlement was price 1 size 4 so that translates to 40

**Comment by Jiajia-Cui** [comment]
ok, I can confirm your calculation looks correct

**Comment by vega-paul** [comment]
wrote a generic checking function in python system tests for checking these balances

**Comment by vega-paul** [comment]
Happy with aggressor SIDE_SELL as calcs match 
SIDE_BUY is not matching

<google-sheets-html-origin><style type="text/css"></style>

Aggressor = Buyer |   |   | Trade |  
-- | -- | -- | -- | --
starting bal | 1000000000 | 1000000000 | maker fee | 156
end bal | 1000038916 | 999949405 | infra fee | 39
  | 38916 | -50595 | liq fee | 11640
  |   |   | price | 970
  |   |   | size | 4
  |   |   | trade value | 3880
  |   |   | settlement | 1
  |   |   | settlement value | 40
