### ISSUE TITLE
Dockerfile for validators

### ISSUE THREAD

**Issue by legg** [vegaprotocol/vega#5523]
# Task Overview

**In order to** build vega as a validator I need a dockerfile in the repo
**So that** I don't need to maintain a fork for our build tools

## Specs
- The current docker/Dockerfile has a devops dependency we don't have access to

# Acceptance Criteria
When I run `docker build -t vega -f docker/Dockerfile .` it should build without errors.

**Comment by jeremyletang** [comment]
@legg the Dockerfile have been updated, from what I can see there should not be any dependency to our internal devops stuff anymore.

You can find the updated dockerfile here: https://github.com/vegaprotocol/vega/blob/develop/docker/vega.dockerfile.

Does that work for you? Can we close this issue?
