### ISSUE TITLE
Unable to perform transfer to market's Insurance account

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#5537]
# Problem encountered
Testing the below AC's for spec - [https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0013-ACCT-accounts.md](url)

AC:
Insurance pool accounts
Only transfer requests move money in or out of the insurance account. ([0013-ACCT-021](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0013-ACCT-accounts.md#0013-ACCT-021))

Unable to perform a transfer from a party's general account to the market's Insurance account , the transfer is unsuccessful and  below error event is logged.

`{"id":"9086-35","block":"C997783503B38A356A0C3DF555CE71CDF99685ED4280FB4F719927CFBD1398AA","type":"BUS_EVENT_TYPE_TX_ERROR","txErrEvent":{"partyId":"2894ee8a87d436b555a9a6516669437c78a5f1267f0e0acac3967357d27e7aa3","errMsg":"Transfer Funds - unsupported to account type","transfer":{"fromAccountType":"ACCOUNT_TYPE_GENERAL","to":"a859654ec1e9d8d2b0eea03ddc17054b0a08f73585fcb56201bfc84b26b45a62","toAccountType":"ACCOUNT_TYPE_INSURANCE","asset":"0907ebd121fcbd851d653b0b9ed04e8298572e476e82bf42eaa617c0d1f0368f","amount":"1432000000000000000000","reference":"TestTransfer","oneOff":{}}},"version":1,"chainId":"test-chain-Xuf5rs","txHash":"C8A0D47A14F12190D7C30AD116D962D14E5C3DF519C737CD5A20F8556BA92407"}`

# Observed behaviour

The transfer request is unsuccessful and the above event is received.

# Expected behaviour

The transfer should be successful.

# System response

Error event was received.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Closing as wont fix pending and additional work that may come from:
- https://github.com/vegaprotocol/specs-internal/issues/1141
