### ISSUE TITLE
Market depth update stream reports duplicated price entries 

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#5548]
# Problem encountered
While updating the order book info, some items in the stream come with only price fields (no info on volume or number of orders). 

# Expected behaviour
Any market depth update on orders state is expected to reflect information on price, volume and number of orders.

# System response
`[
   {
      "update":{
         "marketId":"168334fb6bf6802a5c53b9e716f6ad618ba63ceffb281a6d360f60a4ef31d1c6",
         "sequenceNumber":"1657183282437714032",
         "previousSequenceNumber":"1657183282437714032"
      }
   },
   {
      "update":{
         "marketId":"168334fb6bf6802a5c53b9e716f6ad618ba63ceffb281a6d360f60a4ef31d1c6",
         "buy":[
            {
               "price":"106900000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"89900000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"44400000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"106800000"
            }
         ],
         "sell":[
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            }
         ],
         "sequenceNumber":"1657183286978566043",
         "previousSequenceNumber":"1657183282437714032"
      }
   },
   {
      "update":{
         "marketId":"168334fb6bf6802a5c53b9e716f6ad618ba63ceffb281a6d360f60a4ef31d1c6",
         "buy":[
            {
               "price":"106800000"
            },
            {
               "price":"55500000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000"
            },
            {
               "price":"106800000",
               "numberOfOrders":"1",
               "volume":"154764311"
            }
         ],
         "sell":[
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"130000000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"133300000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"153300000",
               "numberOfOrders":"1",
               "volume":"300000"
            },
            {
               "price":"120100000"
            },
            {
               "price":"120100000",
               "numberOfOrders":"1",
               "volume":"135720924"
            }
         ],
         "sequenceNumber":"1657183286978566164",
         "previousSequenceNumber":"1657183286978566043"
      }
   },
   {
      "update":{
         "marketId":"168334fb6bf6802a5c53b9e716f6ad618ba63ceffb281a6d360f60a4ef31d1c6",
         "sequenceNumber":"1657183286978566164",
         "previousSequenceNumber":"1657183286978566164"
      }
   }
]`

## Automation
Code [here](https://github.com/vegaprotocol/system-tests/pull/901/files#diff-4d2279a818588f113ebc9d2df27c47813a2b0db21b9f5751985d2f35b44c4a11R305)

**Comment by ze97286** [comment]
@gordsport why is this not closed?

**Comment by ze97286** [comment]
no worries, I'm just saying there's no bug here so this should be closed. @RomanLeca please confirm and if so please close.

**Comment by gordsport** [comment]
Closing as now to be addressed in the spec:
- https://github.com/vegaprotocol/specs-internal/issues/1143
