### ISSUE TITLE
Updating network param "market.monitor.price.defaultParameters" fails

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#5591]
# Problem encountered
There are two price monitoring network params I can update, in order to pass them to market proposals which lack these values, as per [spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0032-PRIM-price_monitoring.md#0032-PRIM-010):
```
{"key": "market.monitor.price.defaultParameters", "value": "{\"triggers\": []}"}
{"key": "market.monitor.price.updateFrequency", "value": "4s"}
```
# Observed behaviour
When I try to ammend triggers via network params, I get
`PROPOSAL_ERROR_NETWORK_PARAMETER_VALIDATION_FAILED unable to validate market.monitor.price.defaultParameters: unable to unmarshal value, json: unknown field "auctionExtension" `
and this is a perfectly existing field
# Expected behaviour
Network parameter update should succeed for all keys involved

## Automation
https://github.com/vegaprotocol/system-tests/pull/937/files#diff-df0711119e012eb9e7d3e79d43980877543576fd08f46f2a39dd2347f03fe6baR290

**Comment by wwestgarth** [comment]
The field name here for the network-parameter is in snake-case so we're looking for `auction_extension` and not `auctionExtension`. You can see and example in mainnet's genesis file: https://github.com/vegaprotocol/networks/blob/master/mainnet1/genesis.json#L357
