### ISSUE TITLE
'updateFrequency' param is not updated for price monitoring

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#5592]
# Problem encountered
There are two price monitoring network params I can update, in order to pass them to market proposals which lack these values, as per [spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0032-PRIM-price_monitoring.md#0032-PRIM-010):
```
{"key": "market.monitor.price.defaultParameters", "value": "{\"triggers\": []}"}
{"key": "market.monitor.price.updateFrequency", "value": "4s"}
```
It is possible to amend **only** `market.monitor.price.updateFrequency`  although I am not sure updating only this param **without making sure the other one exists** is intended behavior.

# Observed behaviour
After updating the param value from default _**4s**_ to _**6s**_, at teardown, resetting network params will display this:
```
[INFO] MainProcess utils.py:reset_network_params:705 ----- Resetting param market.monitor.price.updateFrequency to 4s was 6s
```

but in the test, I will always get a null value (not 4, not 6)
```
>           assert pricemon_config['priceMonitoringSettings']['updateFrequency'] == '6'
E           AssertionError: assert '0' == '6'
E             - 6
E             + 0
```

## Automation
[Code](https://github.com/vegaprotocol/system-tests/pull/937/files#diff-df0711119e012eb9e7d3e79d43980877543576fd08f46f2a39dd2347f03fe6baR291)

**Comment by wwestgarth** [comment]
So it doesn't update in the market data because its not wired into anywhere so updating is doesn't actually _do_ anything. I think that network-parameter has been superseded by `network.floatingPointUpdates.delay` @ze97286 ?

**Comment by ze97286** [comment]
The network parameter market.monitor.price.updateFrequency is used when the market is created to populate the updateFrequency, but as far as I can see updateFrequency is not used for anything.

**Comment by witgaw** [comment]
I don't see it being used for anything either. I think that functionality is now handled by the state variable engine so we need to get rid of the network parameter and the (now) obsolete variable within price monitoring engine.

**Comment by ze97286** [comment]
https://github.com/vegaprotocol/vega/pull/5625 for getting rid of updateFrequency in priceMonitoring.
