### ISSUE TITLE
Snapshot: topology engine's `t.currentTime` is not restored properly

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5598]
# Problem encountered
If a snapshot is taken the block before a new-epoch where a validator is being demoted, restoring from that snapshot falls out of consensus.

The reason boils down to `t.currentTime` in the topology engine not being restored and left set to `time{}`. In the next epoch update when we try to use to create a resourceID for the notary engine we get a difference hash.

So we should  set it to the block-time of the restored block from the context in the restore code

**BUT**

There is another issue here. Since we have already started the next block, you would expect `t.currentTime` to be the time of the current block, so why is it not set in our `OnEpochEvent` call for the next block?. It is because we have another case of unsyncronised engine internal times.

The topology engine sets its internal `currentTime` from within its `t.BeginBlock()` call but this happens _after_ the epoch update trigger and so during `OnEpochEvent` its `currentTime` is of the previous block. So we should fix that as well.

# Observed behaviour
Snapshots don't work.

# Expected behaviour
Snapshots do work.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jeremyletang** [comment]
Do we even need to keep the current time in the topology engine and snapshot?

**Comment by ze97286** [comment]
I don't think we should store the block time and restore it from the snapshot. The block time should never be relevant because it's already ended and would be superseded by the call of block time. If I understand what you're saying correctly what's causing the issue is that when the next block is the beginning of a new epoch the onEpochEvent is called *before* the topology engine's onBeginBlock was called - so a couple of simple solutions would be:
1. Not to save the currentTime in topology, there's really no need, the time service will always return the actual current time
2. Or to update the currentTime also from the startTime on an epochEvent when a new epoch is started.
