### ISSUE TITLE
Update after 0038-OLIQ spec change

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5605]
The [0038](https://github.com/vegaprotocol/specs/blob/master/protocol/0038-OLIQ-liquidity_provision_order_type.md) spec has been updated:

- https://github.com/vegaprotocol/specs/pull/1163

with the following info:

> Note: if the resulting quote price of any of the entries in the buy / sell shape leads to negative product value from the [product quote-to-value function](0051-PROD-product.md#quote-to-value-function) but strictly positive volume then the entire LP order for this LP is undeployed, their stake won't count towards target stake being met and they shall not receive any LP fees regardless of their equity-like-share. This can lead to a [liquidity auction](0035-LIQM-liquidity_monitoring.md) if the supplied stake for the market is below the required level due to this LP. 

This change is covered in the feature test:l
 - https://github.com/vegaprotocol/vega/pull/5596

However the change needs to also be implemented on the core side.

**Comment by davidsiska-vega** [comment]
The spec is written be forward looking but of course for cash settled futures the "product value" is just the price that they're trading at.

**Comment by gordsport** [comment]
@EVODelavega - please can you confirm that it is not possible for the price to be negative here? 

If so we can move out / close this issue as its already as per the spec.

**Comment by EVODelavega** [comment]
Prices in core are of the type uint256, so in that sense it is impossible to have negative prices. Pegged orders and LP orders are only deployed during continuous trading, and we correct the price point to be within the bounds set by price monitoring. Unless the price monitoring component doesn't account for uint256 overflow, it shouldn't be possible to have negative (or rather int overflow) prices
