### ISSUE TITLE
Document the wallet JSON-RPC API

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#5618]
Find a way to provide a OpenAPI file for the HTTPv2 API.

To investigate https://open-rpc.org/

**Comment by edd** [comment]
This ticket erplaces https://github.com/vegaprotocol/vegawallet/issues/6

**Comment by edd** [comment]
Open RPC looks good to me:
- For https://github.com/vegaprotocol/documentation: https://github.com/open-rpc/docs-react or https://github.com/mzernetsch/jrgen or https://github.com/contributte/anabelle seem good
- For code https://github.com/open-rpc/typings and https://www.npmjs.com/package/@open-rpc/generator-client look good

Hopefuilly it isn't a pain on the creation side.
