### ISSUE TITLE
Fail to load from checkpoint when Ersatz validator exists

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5629]
# Problem encountered

After adding a new node to the network with validator state Erstaz, attempting to load from a checkpoint that contains that new node fails in tendermint with:

```
creating tendermint node: error="error during handshake: error on replay: invalid size for PubKeyEd25519. Got 0, expected 32" closerError=""
```

The problem code is here in `topology_checkpoint.go`:
```
for _, v := range nextValidators {
		// NB: if the validator set in the checkpoint doesn't match genesis, vd may be nil
		vd := t.validators[v]
		pubkey, err := base64.StdEncoding.DecodeString(tmKey[v])
		if err != nil {
			continue
		}

		if vd != nil {
			vd.validatorPower = votingPower[v]
		}

		update := tmtypes.UpdateValidator(pubkey, votingPower[v], "")
		vUpdates = append(vUpdates, update)
	}
```

And there are atleast two issues:
- we populate `tmKey[]` from the genesis validators, but loop over `nextValidators ` which are the checkpoint validators, the additional ersatz node isn't in `tmKey[]` and so we return an empty string from the map
- we populate `vUpdates` without filtering out non-tendermint nodes, so we pass erstaz/pending nodes in as TM validators but with 0 voting power. Tendermint doesn't like this: `Cannot create validator set: cannot process validators with voting power 0`

# Observed behaviour
Cannot load from a checkpoint with a validator set that isn't from genesis.

# Expected behaviour
Can load from a checkpoint with a validator set that isn't from genesis.

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

On this (in progress) branch https://github.com/vegaprotocol/system-tests/compare/0069-VCBS-047?expand=1 there is a test called `test_restart_from_checkpoint_extra_ersatz`. Run it. Enjoy it. Its there to be enjoyed.

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by daniel1302** [comment]
An example checkpoint that is failing to load for for vegacapsule is here:
[20220531122916-30-750b8bef76dd53d08f92b9983801c2c580c136037beb6f844ea336d3d9a5eb37.cp.zip](https://github.com/vegaprotocol/vega/files/9190441/20220531122916-30-750b8bef76dd53d08f92b9983801c2c580c136037beb6f844ea336d3d9a5eb37.cp.zip)
