### ISSUE TITLE
Reconsider naming of "settlement data" endpoint in APIs 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vega#5641]
# Problem encountered
The APIs reference something called 'settlement price decimals', however this won't scale to non-cash products and settlement data is not necessarily a price, even for cash settled futures. 

Suggestion: rename to settlementDataDecimals in line with the [product parameter](https://github.com/vegaprotocol/specs/blob/master/protocol/0016-PFUT-product_builtin_future.md#1-product-parameters). 

# Observed behaviour
Example: https://docs.vega.xyz/docs/testnet/grpc/vega/markets.proto#future

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by barnabee** [comment]
Hmm so there ar a few odd things here:

1. The field that exists at a data source level to set the number of implied decimals in values carried by that source actually sits in the Future product, not the data source spec, as far as I can tell
2. All the fields related to settlement data seem to be named settlement price even though it isn't necessarily a price (could be a temperature or an interest rate or, well, anything really) and the [names are different in the spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0016-PFUT-product_builtin_future.md#1-product-parameters)
3. The field doesn't seem to be available in GraphQL
