### ISSUE TITLE
Bug: trade did not happen as expected 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#5643]
line 118, trade did not happen as expected while market is in continuous mode, there is enough supplied stake on the market

[PR](https://github.com/vegaprotocol/vega/pull/5642/files)

**Comment by ze97286** [comment]
@Jiajia-Cui the trade doesn't happen because it's a wash trade. By line 118, aux3 has an outstanding order of buy 2 (with remaining 1 unit) so when they place the sell order in line 118 it is identified as wash trade and is not allowed to go through.

**Comment by Jiajia-Cui** [comment]
Closed as its a wash trade which is expected to not happen
