### ISSUE TITLE
Event not emitted by core after ethereum key rotation is applied

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#5647]
When an ethereum key rotation is applied , we expect core to produce the below event.

`BUS_EVENT_TYPE_ETHEREUM_KEY_ROTATION`

But this event is not emitted by core and we don't see this event on the event stream.

Also, because of this the data node isn't updated with the new ethereum key.

Query - after the ethereum key rotation is applied by core - should it also produce and emit the signature bundles for removing the old ethereum key and adding the new ethereum key.

If, so those events are also not emitted.

**Comment by karlem** [comment]
@ze97286 Just wanted to double check. Is this merged pls?

**Comment by ze97286** [comment]
no, it's not merged, it's in your branch in https://github.com/vegaprotocol/vega/pull/5648

**Comment by vega-paul** [comment]
Im using the fix branch for testing
I see the rotation event now - old/new key etc
datanode still not updated so node details are not updated by the rotations - is there more to do to fix this?

**Comment by ze97286** [comment]
yes, @pscott31 is working on it

**Comment by pscott31** [comment]
The date node PR [is merged](https://github.com/vegaprotocol/vega/pull/5788) now
