### ISSUE TITLE
Improve errors returned to the client on transaction submission

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/vega#5671]
Currently the errors a client receives on transaction submission can be somewhat opaque and difficult to know what needs to be changed in order to have a successful submission. Update the error handling to return specific errors for the different failure modes.

One example of this would be that an error in proto parsing will return the response:
`{"method": "/vega.api.v1.CoreService/SubmitTransaction", "error": "rpc error: code = Internal desc = Internal error"}`
even though internally to the server a full error message detailing which fields are missing/incorrect is available. It would be useful to pass this through to the client.

**Comment by gordsport** [comment]
This has been reviewed in recent API improvements
