### ISSUE TITLE
Deprecate Datanode V1 APIs

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5674]
Once we have the V2 APIs developed, documented and tested we need to deprecate the V1 APIs

- [ ] ensure V2 APIs are fully tested
- [ ] ensure that users have been given an adequate warning
- [ ] ensure that the FE team have moved over to V2
- [ ] deprecate the V1 APIs

**Comment by jeremyletang** [comment]
Work started there: https://github.com/vegaprotocol/vega/pull/6664 feel free to take over
