### ISSUE TITLE
data node shows old status for asset by AssetByID

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#5687]
# Problem encountered
An asset which has been proposed, enabled and listed still reports as STATUS_PROPOSED, but should report STATUS_ENABLED. The same asset shows the correct state when you request _all_ assets via the `Assets` api. (At least sometimes, the cache does seem to catch up later, but I've seen this be unreliable, often slow, and at least once, _never_ seemed to update).

# Observed behaviour
Asset reports STATUS_PROPOSED

# Expected behaviour
Asset reports STATUS_ENABLED

# System response
```
        "status": "Enabled",
        "id": "4e4ae6ab30f55cf82bcff2323144f46b85c31e1e743f6104174997ea793fdf72",
        "source": {
          "__typename": "ERC20"
        },
        "name": "Test Asset"
      },
```

# Steps to reproduce

## Automation
```
pytest -k test_propose_new_erc20_token
```
Make sure [this PR](https://github.com/vegaprotocol/system-tests/pull/859) has been merged, then make sure [this assert](https://github.com/vegaprotocol/system-tests/blob/0c081366bfa562b3e7114e980eeca75ef1ab44df/modules/govMod/governMod.py#L912) is enabled, which I've disabled due to this bug.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@jgsbennett 
Now the asset proposal/governance has been implemented can you re-check this and close if resolved?
