### ISSUE TITLE
GraphQL: Future type is missing settlement_price_decimals

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5694]
https://github.com/vegaprotocol/data-node/blob/81a2212bd8e4497eb7926ff6994419d564135218/gateway/graphql/schema.graphql#L1026-L1042

https://github.com/vegaprotocol/protos/blob/d91c28cf25c7b9a1265cfeda4965be5ec80f6321/sources/vega/markets.proto#L37-L38

# Tasks
- [ ] Add it

**Comment by TomMcL** [comment]
Just hit this one too whilst trying to check that an Oracle was configured correctly for a Future product, currently no way to extract that once it's set it seems
