### ISSUE TITLE
Docs strings for all GraphQL schema fields

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5696]
This is a non-blocking feature following on from vegaprotocol/data-node#550. The [docstrings](https://www.apollographql.com/docs/resources/graphql-glossary/#docstring) above each field are used to populate the:
* [GraphQL documentation](https://docs.vega.xyz/docs/mainnet/graphql/overview)
* [Documentation sidebar in Playground](https://lb.testnet.vega.xyz/playground)
* [Type documentation in frontend clients](https://github.com/vegaprotocol/frontend-monorepo/blob/master/apps/trading/lib/__generated__/AssetFields.ts)

and some fields are missing documentation, or have really basic descriptions. vegaprotocol/data-node#550 isn't at fault - most new fields have strings, but not all, and it made me realise we could do with an audit. A lot of this task could be split between @vegaprotocol/frontend & @vegaprotocol/core, but ultimately, doing it will help everyone

**Comment by jeremyletang** [comment]
Just quickly looked over that, and it seems pretty much all is documented. Is that good to close @edd?

**Comment by edd** [comment]
There are still some missing fields, but I know there's at least one more specific ticket so let's close this big unknown task in favor of specifics 👍
