### ISSUE TITLE
REST API status of the oracle spec = UNSPECIFIED

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/vega#5697]
# Problem encountered
REST API market status = UNSPECIFIED. 

GraphQL has the status as a "state" of a market. REST has a "status" field, but see below, it is set to unspecified.

**GRAPHQL:**
`{
  "data": {
    "markets": [
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction"
        }
      },
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction"
        }
      },
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction"
        }
      },
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction"
        }
      },
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "Continuous"
        }
      },
      {
        "state": "Active",
        "tradingMode": "Continuous",
        "data": {
          "marketTradingMode": "MonitoringAuction"
        }
      }
    ]
  }
}`

# System response

**REST:**
`{
      "id": "076BB86A5AA41E3E",
      "tradableInstrument": {
        "instrument": {
          "id": "unused-id",
          "code": "BTCUSD.MF21",
          "name": "BTCUSD Monthly (30 Jun 2021)",
          "metadata": {
            "tags": [
              "base:BTC",
              "quote:USD",
              "class:fx/crypto",
              "monthly",
              "sector:crypto"
            ]
          },
          "future": {
            "maturity": "2021-06-30T23:59:59Z",
            "settlementAsset": "6d9d35f657589e40ddfb448b7ad4a7463b66efb307527fedd2aa7df1bbd5ea61",
            "quoteName": "USD",
            "oracleSpec": {
              "id": "89994814666a16350285ca9c31b7c6d4bcfc171e14652923b0384949505d03d9",
              "createdAt": "0",
              "updatedAt": "0",
              "pubKeys": [
                "0x8873a1ecb80ba0ffd1e55acc0572df27381a9b65e0b6d6a9f095c92329eb29ea"
              ],
              "filters": [
                {
                  "key": {
                    "name": "prices.BTC.value",
                    "type": "TYPE_INTEGER"
                  },
                  "conditions": [
                  ]
                }
              ],
              "status": "STATUS_UNSPECIFIED"
            },
            "oracleSpecBinding": {
              "settlementPriceProperty": "prices.BTC.value"
            }
          }
        },
        "marginCalculator": {
          "scalingFactors": {
            "searchLevel": 1.025,
            "initialMargin": 1.05,
            "collateralRelease": 1.1
          }
        },`

**System version:** Specify the system version "appVersion": "v0.38.1"
**Protocol:** Specify the protocol

- [ ] REST

**Component:** Specify the components that might be related
- [ ] [Vega](https://github.com/vegaprotocol/vega/)
- [ ] [Tendermint](https://github.com/tendermint/tendermint)
- [ ] [Console](https://github.com/vegaprotocol/console/)
- [ ] [Ethereum Bridge](https://github.com/vegaprotocol/Event_Queue)
- [ ] [Vega Wallet](https://github.com/vegaprotocol/go-wallet/)

# Steps to reproduce

https://lb.testnet.vega.xyz/markets

**Comment by ze97286** [comment]
"status": "STATUS_UNSPECIFIED" in REST is not the state of the market, it's the status of the oracle spec.
