### ISSUE TITLE
error adding checkpoint reported at beginning of a test run

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#5700]
# Problem encountered
[This test run](https://jenkins.ops.vega.xyz/blue/organizations/jenkins/vegaprotocol%2Fsystem-tests/detail/PR-766/3/pipeline/154/) has a big data node error at the beginning of the network logs. Unclear if it actually had any impact on anything, I spotted it because the parent job had lots of failures, and so I went to check on the state of the network. Note that I also raised https://github.com/vegaprotocol/vega/issues/5342 to track some ominous looking vega errors that appear later on in the 
[same logs](https://github.com/vegaprotocol/data-node/files/8641438/network.zip).

# Observed behaviour
```
Job: testnet-nodeset-full-2, Task: data-node-2: 2022-05-06T08:52:14.542Z	ERROR	broker/sqlstore_broker.go:159	failed to process event id:"170-7"  block:"A859CEC690C7438381C0D71FF1032D15416FF7C03DF1225313E5805D683112B9"  type:BUS_EVENT_TYPE_CHECKPOINT  checkpoint:{hash:"4d20107b1d3ed44239878bbd2d393b1d252edbd734fc07e1f01002af7108a404"  block_hash:"A859CEC690C7438381C0D71FF1032D15416FF7C03DF1225313E5805D683112B9"  block_height:170}  version:1  chain_id:"test-chain-dVuSbp" error:ERROR: duplicate key value violates unique constraint "checkpoints_pkey" (SQLSTATE 23505)
Job: testnet-nodeset-full-2, Task: data-node-2: error adding checkpoint
Job: testnet-nodeset-full-2, Task: data-node-2: code.vegaprotocol.io/data-node/sqlsubscribers.(*Checkpoint).consume
Job: testnet-nodeset-full-2, Task: data-node-2: 	/jenkins/workspace/system-tests/system-tests-capsule/data-node/sqlsubscribers/checkpoint.go:66
Job: testnet-nodeset-full-2, Task: data-node-2: code.vegaprotocol.io/data-node/sqlsubscribers.(*Checkpoint).Push
Job: testnet-nodeset-full-2, Task: data-node-2: 	/jenkins/workspace/system-tests/system-tests-capsule/data-node/sqlsubscribers/checkpoint.go:49
```

# Expected behaviour
No data node errors in logs

# Steps to reproduce
Unclear. Only seen this once, on the aforementioned failing smoke job. Checked one other passing run, which contained no errors.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@pscott31 @guoguojin @ettec 

Please can you confirm that this bug is still present?

**Comment by pscott31** [comment]
The error 

`error:ERROR: duplicate key value violates unique constraint "checkpoints_pkey" (SQLSTATE 23505)`

Should not be possible any more since [this PR](https://github.com/vegaprotocol/data-node/pull/683), as there is no longer a PK on the checkpoints table. Closing this (feel free to reopen if there are any objections)
