### ISSUE TITLE
Correct filtering not applied for transfers queries

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#5703]
No filtering is applied on the queries for transfers.

The attached is a transfers query executed which is filtered by the pubKey , however the results returned contain all the transfers available in the system.

Expected: Only transfers pertaining to the input pubKey should be returned.  

`
query {
  transfers (pubkey:"f83a45fb2b462f4027701cf09ccf9cddc819b6b01d4de260f1cb07a83467c1e2") {
    id
    from
    to
    toAccountType
    asset {
      id
    }
    amount
    reference
    status
    kind {
      ... on OneOffTransfer {
        deliverOn
      }
      ... on RecurringTransfer {
        startEpoch
        endEpoch
        factor
      }
    }
  }
}
`

![Screenshot 2022-04-25 at 15 09 00 (2)](https://user-images.githubusercontent.com/91467655/165106973-3ed34cc3-8c49-42c4-a2f6-45261c957b5e.png)

**Comment by gordsport** [comment]
Closing as transfer tests have been refactored and this issue has not presented again

**Comment by MuthuVega** [comment]
Retested and is working fine.
