### ISSUE TITLE
Proposal subscription does not work for newly streamed in proposals

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vega#5704]
# Problem encountered
Proposal subscription does not work for newly streamed in proposals

```gql
subscription Sub {
  proposals (partyId: "PARTID") {
    id
  }
}
```

# Observed behaviour
Created a proposal from public key, no event was received, even after minutes of waiting. I do not know if this was a factor but the proposal was rejected, however I would expect he subscription to give us everything by default and we can add filters later down the line if needed.

# Expected behaviour
A subscription update with the newly created proposal should be sent to the client.

# System response
Nothing

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Start subscription (either on playground or in an app or similar)
2. Create proposal
3. Notice that no update is recieved when the proposal is created

# Evidence

Uploading Screen Recording 2022-04-19 at 11.53.29.mov…

## Additional context
Proposal was rejected maybe that was a factor?

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by pscott31** [comment]
This is fixed in datanode v2, confirmed with @dexturr
