### ISSUE TITLE
Querying by id should be consistent and functional across all top level models

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vega#5709]
# Problem encountered

* assets query errors on GQL if the asset id is not present
* proposal query errors on GQL if the asset id is not present

There are also some inconsistencies:
* asset should be queried through `id` not assetId to be consistent with markets, parties and proposals
* node id should be of type `ID` not `string`

# Observed behaviour
* assets query errors on GQL if the asset id is not present
* proposal query errors on GQL if the asset id is not present

# Expected behaviour

* assets query does not error on GQL if the asset id is not present and instead returns null
* proposals query does not error on GQL if the asset id is not present and instead returns null

```
query ($guess: ID!) {
  asset (assetId: $guess) {
    id
  }
  proposal (id: $guess) {
    id
  }
}
```

```
{
  "guess": "a42f27fff304646a096ad77236927db723f004fd4b23a2616e3cb0593ebf80a0"
}
```

```
{
  "errors": [
    {
      "message": "rpc error: code = NotFound desc = NotFound error",
      "path": [
        "asset"
      ]
    },
    {
      "message": "rpc error: code = Internal desc = Internal error",
      "path": [
        "proposal"
      ]
    }
  ],
  "data": null
}
```

**Comment by asiaznik** [comment]
Trying to get both `asset` and `proposal` given correct `proposalId` result as expected but given correct `assetId` it errors not returning any data.

### test query
```gql
query Guess($guess: ID!) {
  proposal(id: $guess) {
    id
    rationale {
      title
    }
  }
  asset(assetId: $guess) {
    id
    symbol
  }
}
```

### ✅ given proposal id it returns a proposal and errors on asset only
```json
{
  "guess": "918c3eeab8d8619cfb3e385794c184d23591473dc5a31dd635b4966df122304c"
}
```
```json
{
  "errors": [
    {
      "message": "rpc error: code = NotFound desc = NotFound error",
      "path": [
        "asset"
      ]
    }
  ],
  "data": {
    "proposal": {
      "id": "918c3eeab8d8619cfb3e385794c184d23591473dc5a31dd635b4966df122304c",
      "rationale": {
        "title": "Tesla Quarterly (September 2022)"
      }
    },
    "asset": null
  }
}
```

### 🐞 given asset id it errors not returning anything (should return proposal)
```json
{
  "guess": "449dbfb66e7a444c485b4fdc77ddc6bbf81abbf7c8e247ac299c25e9557b99cf"
}
```
```json
{
  "errors": [
    {
      "message": "rpc error: code = NotFound desc = NotFound error",
      "path": [
        "proposal"
      ]
    }
  ],
  "data": null
}
```

**Comment by gordsport** [comment]
Hey @AnExsomnis 
The FE team have just tested this on devnet and it seems if this remains broken:
![Screenshot 2022-09-01 at 12 59 11](https://user-images.githubusercontent.com/83510148/187908956-a8e2e712-c6de-4eec-a043-b10f4f03fcf4.png)

Please can you advise if this is still the case or if the query needs changing, below is what has been used to test in devnet just now:

```
query asst {
  assetsConnection {
    edges {
      node {
        id
        name
      }
    }
  }
}

query Guess($guess: ID!) {
  proposal(id: $guess) {
    id
    rationale {
      title
    }
  }
  asset(id: $guess) {
    id
    symbol
  }
}
```
with variables
```
{
  "guess": "993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede"
}
```

**Comment by pscott31** [comment]
I don't see the issue here, unless I am reading this wrong... You asked for a proposal that doesn't exist and GQL said 'not found'. What would you expect it to do?

**Comment by gordsport** [comment]
@dexturr @asiaznik 👆

**Comment by pscott31** [comment]
(though as an aside it seems like a bit of a strange query to begin with; how did you end up with an ID that is either an asset ID or a proposal id?)

**Comment by pscott31** [comment]
![image](https://user-images.githubusercontent.com/94362991/187953222-050c2a1a-c85b-46d9-a30c-de492bf8e29d.png)

**Comment by asiaznik** [comment]
It appears I haven't checked it on devnet. I've just re-checked and it's fine there. My bad (url mixup).

**Comment by AnExsomnis** [comment]
Closing

**Comment by dexturr** [comment]
I'd expect it not to error, and just to return null. When we get an error property back on the response this is sent into sentry, and querying for something that doesn't exist isn't an "error" from the backend perspective, it's just not been found.

Use case wise, on the block explorer we need a search box so that people can put in Ids and we take them to the correct place. Unlike in Eth where transactions and wallets have a different amount of characters, all Ids in vega are the same length of hex characters which means we need to query all models to try and find which one the user is actually looking for, if any exist. Which is the motivation for this ticket.
