### ISSUE TITLE
Provide filters for order query/subscription

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#5711]
# Feature Overview
I'd like to query and/or subscribe to updates for orders of specific types to prevent over fetching

As an API user (console or otherwise)

I want to get order data for a specific set/type of orders

So that its easier to manage the resulting data

# Tasks
- [ ] API Split complete
- [ ] List of filters determined

# Product Owner
I'm not sure who this should be assigned to.

# Acceptance Criteria

- It is possible to only fetch orders for a specific market (already done)
- It is possible to only fetch orders for a specific party (already done)
- It is possible to only fetch orders for a specific party _and_ market
- It is possible to fetch orders by type
- It is possible to fetch orders by status
- It is possible to fetch orders by time in force
- It is possible to fetch orders by side
- It is possible to only fetch LP orders
- It is possible to only fetch pegged orders

# Test Scenarios
```gherkin
    Feature: Party queries for orders by type
    Scenario: Party has 1 Market order
    When the Party queries for orders by type Market
    Then the API should return 1 order
      And the order should be of type Market
```     

# Impacted Systems / Engines
- API

**Comment by gordsport** [comment]
Hey @mattrussell36 @guoguojin 

I think this could be a duplicate of:
- https://github.com/vegaprotocol/vega/issues/5684

If so please can you close this?
