### ISSUE TITLE
GraphQL: `historicBalances` query is undocumented

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5719]
https://github.com/vegaprotocol/vega/blob/87821cdddfc5f78e4d9927bfdef05c829181399d/datanode/gateway/graphql/schema.graphql#L594-L597

# Tasks
- Add field documentation

**Comment by guoguojin** [comment]
Documentation for this query was added in this PR https://github.com/vegaprotocol/vega/pull/6221
