### ISSUE TITLE
When in market is in Auction: User does not have a position (with margin levels) but does have open orders on the book

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5721]
# Problem encountered
<img width="1583" alt="Screenshot 2021-06-25 at 14 03 32" src="https://user-images.githubusercontent.com/13255539/123429283-af828080-d5be-11eb-970c-0179f6d73532.png">

Here the user has two orders on the TSLA market. and no open volume. 
The API is returning a margin account for that market. 
But we'd expect to see a row in the positions query that also contains TSLA market.

For This key `d9823badc71758501524f893920e509833734532c0beadb9619a216608db60af` it does not appear to.

We suspect this is because the market is in auction.

Event when in auction Core should return a position row so that users can see margin levels.

# System response

```GraphQL
query{
  party(id:"d9823badc71758501524f893920e509833734532c0beadb9619a216608db60af"){
  	accounts{
      type
      market{name}
      balance
    }
    positions{
      market{name}
      margins{
      initialLevel
        searchLevel
        collateralReleaseLevel
        maintenanceLevel
      }
    }
  }
}
```

gets
```JSON
{
  "data": {
    "party": {
      "accounts": [
        {
          "type": "General",
          "market": null,
          "balance": "999949"
        },
        {
          "type": "General",
          "market": null,
          "balance": "29872520666"
        },
        {
          "type": "General",
          "market": null,
          "balance": "9997241095"
        },
        {
          "type": "General",
          "market": null,
          "balance": "10000000000"
        },
        {
          "type": "Margin",
          "market": {
            "name": "BTCUSD Monthly (30 Jun 2021)"
          },
          "balance": "149289057"
        },
        {
          "type": "Margin",
          "market": {
            "name": "ETHBTC Quarterly (30 Jun 2021)"
          },
          "balance": "51"
        },
        {
          "type": "Margin",
          "market": {
            "name": "UNIDAI Monthly (30 Jun 2021)"
          },
          "balance": "24500"
        },
        {
          "type": "Margin",
          "market": {
            "name": "Tesla Quarterly (30 Jun 2021)"
          },
          "balance": "2758905"
        }
      ],
      "positions": [
        {
          "market": {
            "name": "BTCUSD Monthly (30 Jun 2021)"
          },
          "margins": [
            {
              "initialLevel": "149289057",
              "searchLevel": "145734556",
              "collateralReleaseLevel": "305687117",
              "maintenanceLevel": "142180055"
            }
          ]
        },
        {
          "market": {
            "name": "ETHBTC Quarterly (30 Jun 2021)"
          },
          "margins": [
            {
              "initialLevel": "51",
              "searchLevel": "50",
              "collateralReleaseLevel": "53",
              "maintenanceLevel": "49"
            }
          ]
        },
        {
          "market": {
            "name": "UNIDAI Monthly (30 Jun 2021)"
          },
          "margins": [
            {
              "initialLevel": "24479",
              "searchLevel": "23896",
              "collateralReleaseLevel": "25645",
              "maintenanceLevel": "23314"
            }
          ]
        }
      ]
    }
  }
}
```

We'd expect to see a blob in the Positions JSON for the TSLA market. But it is not there.

**System version:** Specify the system version (0.xx.xx)
**Protocol:** Specify the protocol
- [ ] gRPC
- [ ] REST
- [x] GraphQL

**Component:** Specify the components that might be related
- [ ] [Vega](https://github.com/vegaprotocol/vega/)
- [ ] [Tendermint](https://github.com/tendermint/tendermint)
- [ ] [Console](https://github.com/vegaprotocol/console/)
- [ ] [Ethereum Bridge](https://github.com/vegaprotocol/Event_Queue)
- [ ] [Vega Wallet](https://github.com/vegaprotocol/go-wallet/)

# Steps to reproduce

## Manual
PLace orders on a market that is in auction.

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

https://github.com/vegaprotocol/system-tests/tree/master/....

`Add the necessary file(s) needed to reproduce the problem`

## Not reproducible
Explain why the problem/bug is not reproducible

# Expected behaviour

# Logs
If applicable, add logs and/or screenshots to help explain your problem.

# Additional content

**Comment by gordsport** [comment]
@campbellssource - please can you re-try this in consolev2?
