### ISSUE TITLE
Experiment: How many consoles can we have open, pointed at an API node, before it falls over

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5726]
We're about to onboard a few more people as part of ETHGlobal. It's possible, although unlikely, that 50 people could all open a console at once, looking at the same API node. Will it cope? It should. It probably will. But... will it?

We should get an idea of roughly how many consoles are supported on a node. This is obviously a vague and handwavey number, because a console can be configured as much as someone wants. But let's assume that by a console we mean:
- The console with the default layout, logged in to a unique user id

Is there any trouble with 5 open? 20? 100? 1000?

I listed this as an experiment because the answer doesn't particularly matter. It's just to know a rough number at which we might want to add more API nodes.

Aslo see duplicate: 
- https://github.com/vegaprotocol/vega/issues/6441

**Comment by edd** [comment]
This has been covered

**Comment by peterbarrow** [comment]
This was covered in initial perf testing. We developed an app to simulate console connections and used it to test scaling. The data node scaled very well across CPU cores and could easily handle 50 users.

Closing this ticket as I do no think we have issues with console scaling.
