### ISSUE TITLE
API Feature request: Historical Assets balance allocation

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5727]
This ticket will need refinement: 

How much BTC is deployed to Vega right now?
How much yesterday?
How much of it is deployed, vs available, vs staked, ready to release, held in insurance bools, held in fees 🤷 

It would be nice to draw this sort of graph.

<img width="1005" alt="Screenshot 2020-08-24 at 13 29 25" src="https://user-images.githubusercontent.com/13255539/91044831-d6260280-e60d-11ea-9843-863db4de00d5.png">

**Comment by gordsport** [comment]
@campbellssource 
I believe we have implemented APIs for historical data. Do you have what you require for this issue?
