### ISSUE TITLE
Add rolling 24 hour volume traded API

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5732]
Please can we include sum of all contracts traded in a rolling 24 hours period for a given market in the Market data API.

Users can currently get something similar by using the candle charts but it would be good to have this as part of the market data API.

Candle data is based on the top of an hour, min etc. Ideally this would be a rolling 24 hour period, if not we need to know the time of when the value is calculated.

**Comment by gordsport** [comment]
Do with:

- https://github.com/vegaprotocol/vega/issues/5688
