### ISSUE TITLE
Add GraphQL subscription for statistics

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5734]
We have a query for `statistics` in GraphQL. It would be nice to be able to have a subscription fort the same data, as right now we’re polling the query in Console.’

# Tasks
- Add GraphQL subscription for `Statistics`
- Update subscription at the end of each block

**Comment by mattrussell36** [comment]
@gordsport @jeremyletang @edd 

Any chance we can prioritize this for the next milestone? I'd be okay with not having the full set of stats data. I think we just need a subscription to give use the latest block height and vega time for the connected datanode.
