### ISSUE TITLE
Add `CoreApiService` endpoints to OpenAPI spec

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vega#5747]
`trading.swagger.json` contains 4 endpoints from `TradingService`, but zero from `CoreApiService`.

https://github.com/vegaprotocol/protos/blob/f599718bb7cb206ff61372ef18ff4e99d7bc3e04/sources/vega/grpc-rest-bindings.yml#L14-L25

https://github.com/vegaprotocol/protos/blob/f599718bb7cb206ff61372ef18ff4e99d7bc3e04/sources/vega/grpc-rest-bindings.yml#L27-L49

**Comment by jeremyletang** [comment]
This is already done.
