### ISSUE TITLE
Validation on the governance rational URL field

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5752]
# Task Overview

In the [governance spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md#types-of-proposals) it is mentioned:

>The protocol (Vega core) is not expected to verify that the hash corresponds to the contents of the linked file. It is expected that any client tool that allows voting will do this at client level.

The following [front end issue](https://github.com/vegaprotocol/frontend-monorepo/issues/797#issuecomment-1201372260) is looking into options to validate at the client side.

This has generated a few options on the core side for consideration / discussion:

1. core forcing Rationale URL to start with `ipfs://`
2. increase the size of the description field. spec says it is limited to [1024 characters](https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md#constraint).

In implementing one of the above options it will mean that the FE does not have to perform the validation.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jeremyletang** [comment]
1. we should not enforce any kind of URL.
2. we can increase ever the length of the url or the length of the description or both with something which would fit better and is not un-reasonable.

**Comment by gordsport** [comment]
@campbellssource - what increase to the description would you need in FE? its currently 1024 chars?

**Comment by campbellssource** [comment]
20k was agreed on Slack, as was adding a compulsory "title" field: see PR here: https://github.com/vegaprotocol/specs/pull/1186
