### ISSUE TITLE
Do a vegawallet release to inform users to switch to vega wallet

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5766]
When 0.54 is released to mainnet, the last wallet release in the old repo (`0.16.1`) will be incompatible with that release. Users will need to switch over to vega wallet in *this* repo instead. 

Note after reopening: The update notifications on the wallet from this repo are great! However people who try to connect to *testnet* and below with 0.16.1 will see no update notification. That’s what this ticket is for.

# Tasks
## Release one final update on [vegaprotocol/vegawallet](https://github.com/vegaprotocol/vegawallet) 
- [ ] https://github.com/vegaprotocol/vegawallet/issues/594
- [ ] vegaprotocol/vegawallet#593
- [x] #6311

**Comment by ValentinTrinque** [comment]
I had a chat with @jeremyletang about this. The unstability problem shall disappear once you are opening mainnet. So spending too much time on this is not a good move. So we are going for the best-effort.

## Plan

1. Stop telling the user to update every time we release something by removing the version check on every command
2. Add a warning on the `service run`, `tx` and `command` commands to warn the user the wallet is not compatible with the version of the network against those commands are run.
3. Improve the `version` command to show a compatibility matrix between this wallet and the registered network.

**Comment by ValentinTrinque** [comment]
This plan requires the following issues to be addressed first:
- https://github.com/vegaprotocol/vega/issues/5802

**Comment by ValentinTrinque** [comment]
<img width="1080" alt="Screenshot 2022-08-13 at 18 56 43" src="https://user-images.githubusercontent.com/4662842/184503634-571efd20-1bf4-4fce-8fa0-13c7b370e7af.png">

**Comment by edd** [comment]
Not completed

**Comment by gordsport** [comment]
Added back to the backlog `todo`

**Comment by ValentinTrinque** [comment]
Closing this issue in favor of the three sub-issues mentioned in original post.
