### ISSUE TITLE
Datanode API V2 Review

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5778]
In order to fully understand where we are in terms of the data-node and the API capabilities we need to conduct a review. 

Tasks:

- [x] Define / document what data we are storing in the data-node DB
- [x] Define / document what APIs exist (for each type gRPC/Graph/rest) and what data they are exposing
- [x] Define / document what filtering etc. capabilities each of these APIs has
- [x] Define / document what event types we are capturing and storing in the data-node DB

Info on trading related APIs: 
- https://docs.google.com/spreadsheets/d/1fwRD0RmP6ScLzM1CVj_gwe7L_j2rqFQBBUwf7Plj3tY/edit#gid=0

Once the above information has been captured we need to set up a review session with the data-node team, the ELT, Barney, David and Lewis (@gordsport can arrange this) to:

- [ ] review and discuss the above
- [ ] review and understand if there are any other event types we should be storing

**Comment by pscott31** [comment]
The review [is done](https://docs.google.com/spreadsheets/d/1Qy6poO87d-lkaqBXa4Q1tNlbW9vxEP2KVz719woZGPY/edit?usp=sharing)

**Comment by gordsport** [comment]
> The review [is done](https://docs.google.com/spreadsheets/d/1Qy6poO87d-lkaqBXa4Q1tNlbW9vxEP2KVz719woZGPY/edit?usp=sharing)
> 
> 
> 
> 

Thanks Phil - I'll set up some time to go through this

**Comment by gordsport** [comment]
Closing as review to start a-sync in [slack](https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1661156254188789) and a meeting to be scheduled if required.

New issues to be opened based on actions from the review
