### ISSUE TITLE
Performance issue with: /parties/xxx/positions

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5789]
This endpoint is taking in excess of 5-10 seconds to load:

https://lb.testnet.vega.xyz/datanode/rest/parties/6817f2b4d9464716c6756d2827d893872b1d33839e211c27a650629e428dc35c/positions

It is not happening with any other endpoint, so it looks like a server-side issue with how the data is being fetched.

**Comment by gordsport** [comment]
When testing directly hitting data-node its reported the query is faster 

Tested comparing hitting data node directly (without lb): https://n06.testnet.vega.xyz/datanode/rest/parties/6817f2b4d9464716c6756d2827d893872b1d33839e211c27a650629e428dc35c/positions

**Comment by gordsport** [comment]
@fkondej 
If this issue is found to be the load balance let me know and I will transfer this issue to the devops repo

**Comment by pscott31** [comment]
The load balancer might not be helping, but doing the query directly in SQL takes ~2sec which is pretty bad
