### ISSUE TITLE
Encode chain ID in the transaction signature

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#5802]
As of now a transaction for a network A cannot be differentiated from a transaction to a network B. While it's probably not the best practice to reuse a wallet over different network, a transaction being compatible on any network as soon as the pubkey exists, it could be reused from a network to the mainnet for example.

We want to add the chain ID as part of the message encoded to be signed for each transaction.
In order to support backward compatibility with older wallet, the network should:
- append the chain ID to every input data, and verify the signature
  - if its a valid signature, OK
  - if it's a invalid signature, remove the prefix ans validate again the signature
    - If it's a valid signature, trasnaction is OK
    - if not, transaction is rejected
- The wallet should prefix all input data with the chain ID, and sign this message.

**Comment by emilbayes** [comment]
So append or prepend the chainId? I think we should prepend and add a delimiter that cannot be part of any valid chainId, as our chainId's are not fixed length. Eg `concat('fairground\0', input_data_bytes)`

**Comment by jeremyletang** [comment]
Yes prepend indeed, with a delimiter. It’s not possible to append the chain id as proto encoding don’t have any kind of termination for the message.

**Comment by emilbayes** [comment]
Should it even be present on the wire? Isn't this only part of signature verification?

eg.

```
fun Sign (ChainId, Message, PrivateKey) -> Signature
  Digest = SHA3-256(ChainId || Message)

  Curve = Ed25519
  H = SHA-512
  Key = PrivateKey
  Data = Digest
  Nonce = H( H(PrivateKey)[32:64] || Digest ) // RFC

  Signature = EdDSA-Sign(Curve, H, Key, Data, Nonce)

fun Verify (Signature, ChainId, Message, PublicKey) -> {T, F}
  Digest = SHA3-256(ChainId || Message)

  Curve = Ed25519
  H = SHA-512
  Data = Digest

  return EdDSA-Verify(Curve, H, PublicKey, Data, Signature)
```

**Comment by jeremyletang** [comment]
You are totally right, not even sure why I thought about that.

**Comment by ValentinTrinque** [comment]
We need to add a JSON-RPC endpoint to return this info as well.
