### ISSUE TITLE
revert tendermint 0.35.x to 0.34.x

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#5804]
Tendermint have advised that they will no longer be carrying on with 0.35 and will be building again on 0.34

Therefore we need to revert back to 0.34 and ensure that all places (Vega capsule etc..) are updated as required.

**Comment by gordsport** [comment]
@mattrussell36 @dexturr 
FYI: this may have some impact on the block explorer as I think you query the tendermint APIs and these are subject to change.

**Comment by dexturr** [comment]
@gordsport, we aren't using anything 0.35 specific at this time. We haven't altered the code for tendermint things since 0.34 so we shouldn't need to do anything :+1:
