### ISSUE TITLE
Import relevant vegatools in the vega core

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#5807]
Some tools are not necessary to operate a node like lp watcher, or vegatools streams. But some overs are used actively to debug / inspect the state of the node like the checkpoints and snapshots tools.

Let's import these tools back in the vega codebase and expose them through the CLI.

**Comment by peterbarrow** [comment]
The tools which we want importing into the core are:

**Comment by jeremyletang** [comment]
Would be good as well to make the tools work with the vega home path as well as a custom path.
