### ISSUE TITLE
Snapshots: rejected markets should unregister state-vars on cleanup

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5809]
# Problem encountered
An attempted snapshot restore on testnet failed: https://vegaprotocol.slack.com/archives/CEE07A084/p1659960112784089?thread_ts=1659951886.428729&cid=CEE07A084

because the state-var engine's snapshot contains references to a market's state variables that do not exist. When we restore a _market_ from a snapshot, we re-register the state-variables and then as a `post-restore` in the state-var engine we restore all the state-var engines state for those re-registered state-vars. When they get out of sync, for example if a market is removed from the execution engine but the state-variables for it still exist in the state-variable engine, the restore panics.

_Based on pure guess work_ I think the reason for the failure on testnet if because we are not calling `UnregisterStateVariable` when market's are removed due to their proposal being rejected. Currently we only call `UnregisterStateVariable` when a market is settled.

My reasonings for this are:
1) In testnet's block explorer I can see a rejected market
2) In the system-tests I cannot find a test that rejects a market proposal, which would be why my soak-test script has not picked up this configuration

# Observed behaviour
A clear and concise description of how the system is behaving.

# Expected behaviour

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by daniel1302** [comment]
Here are snapshots that are broken, probably related to this file: https://vega-public-files-only.s3.amazonaws.com/snapshots.tar.gz
