### ISSUE TITLE
Add an API to allow Vegacapsule to query last committed block.

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#5842]
This is to allow Vegacapsule (VC) to ensure that datanode has processed all blocks that core has processed at the point of upgrade such that it can safely shut down the datanode.  This is to avoid a situation where core upgrades at block X, but datanode is shutdown having only processed block X -1 ( or X -2 etc). were this to happen, when core is restarted from snapshot at block X, datanode (after restart) would be missing blocks and would complain. There would be no easy way out of this situation other than rolling back core to a previous snapshot or getting a dump of datanode with height at X or above.  We want to avoid this.

**Comment by gordsport** [comment]
Closing as we will use a sleep to cover the time for the block to be committed before the datanode shuts down.

Should this not work we can reopen
