### ISSUE TITLE
Make automatic consent available for wallet API v2

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#5848]
The flag `--automatic-consent` hasn't been ported to the wallet API v2.

It should be.

However, we may not want every review process to be automatically accepted. Some thought has to be given:
- is automatic consent only for transaction, then connection and permissions review stay manual
- is automatic consent only for transaction and permissions, with connection manual. This opens the door to enabling abusive permissions.
- is automatic consent for every review. This opens the door to rogue software to empty a wallet.

**Comment by gordsport** [comment]
Will V1 API suffice for this?

**Comment by gordsport** [comment]
Moving to a stretch task for the enable trading governance vote. The V1 api deprecation task:
- https://github.com/vegaprotocol/vega/issues/5617
has also been made a stretch as it cannot be done until this task is done on the V2 APIs

**Comment by ValentinTrinque** [comment]
This has been implemented in:
- https://github.com/vegaprotocol/vega/issues/6203
