### ISSUE TITLE
Remove the prefix from enum fields (e.g. TYPE_LIMIT should be LIMIT)

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5877]
Remove the prefix from enum fields (e.g. TYPE_LIMIT should be LIMIT). It is inconsistent with the APIs of every other trading exchange I have used (none has these prefixes), and it leads to unnecessary handling on the client.

**Comment by jeremyletang** [comment]
This is due to protobuf. Because protobuf code generation doesn’t work the same on every language, this is required to ensure namespace and prevent symbols colision on the generated code.
