### ISSUE TITLE
Flatten the objects in the REST response

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5879]
The REST responses contain several nested objects. This is inconsistent with all other trading APIs and means that bespoke handling of JSON response is required for Vega compared to all other centralised exchanges.

**Comment by jeremyletang** [comment]
The REST apis are generated from the protobuf definitions. Because of this they matches the exact same layout as those. I’m affraid we won’t be able to do this, we would need to write by hand all REST apis.

**Comment by barnabee** [comment]
This definitely isn't a core bug. It's as designed and seems unlikely to make sense to change but discussion should be somewhere like protocol design on Slack or the specs repo in the first instance.
