### ISSUE TITLE
Send latest state to the client when opening a new subscription

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5880]
When opening a connection to a GraphQL subscription the existing orders or positions should be pushed to the client, followed by any subsequent updates.

**Comment by pscott31** [comment]
The current behaviour is that all the ObserveXXX functions only stream changes, not an 'initial image'.

For example, if you subscribed to trades you might not want to get every single trade sent to you in the first message. You can subscribe to get updates to orders on any party/market but you might not want to get every single order ever. You might well want to get live orders or something but we have got other API points for querying that stuff [actually we don't for live orders but that's next on my todo].

I think it muddles things up to mix up observing and querying. It would probably upset the frontend's existing use of these APIs too. The response could potentially be very large and we've gone to some pains in the querying API to support paging and stuff so as not to hit GRPC message size limits etc...

So I don't think this is a bug, but if we want to have a discussion about what the API should do then we can have that. I'll leave the issue open for a bit.

**Comment by MM0819** [comment]
> The current behaviour is that all the ObserveXXX functions only stream changes, not an 'initial image'.
> 
> For example, if you subscribed to trades you might not want to get every single trade sent to you in the first message. You can subscribe to get updates to orders on any party/market but you might not want to get every single order ever. You might well want to get live orders or something but we have got other API points for querying that stuff [actually we don't for live orders but that's next on my todo].
> 
> I think it muddles things up to mix up observing and querying. It would probably upset the frontend's existing use of these APIs too. The response could potentially be very large and we've gone to some pains in the querying API to support paging and stuff so as not to hit GRPC message size limits etc...
> 
> So I don't think this is a bug, but if we want to have a discussion about what the API should do then we can have that. I'll leave the issue open for a bit.

You make some good points about not implementing this uniformly across all subscriptions and fair comments about needing to consider the potential impact on the front-end (though that is not a reason not to implement it). Nevertheless, this is standard behaviour when subscribing to centralised exchanges, and we should spec out more specifically which subscriptions should support this on Vega and in what manner.

For example, upon subscribing to positions, I definitely want to receive all of my open positions, and when subscribing to orders, I definitely want to receive all of my open orders.

**Comment by jeremyletang** [comment]
It don’t think it’s a bug, close to a missing feature. Not for all subscriptions, but as lewis said. When loading the page you could call the query api, then the subscription. Although seing that the subscription will send you data only once the state update, there could be a gap of time between which state have changed and you’re a bit off sync.
I don’t think itMs necessary for all subscription, but surely things like accounts, orders, positions should provide the initial state. Trade for example should not.

**Comment by pscott31** [comment]
OK fair enough. I presume we don't want to fanny around with trying to add pagination and stuff to these, are we just going to assume we can fit it all in one GRPC message
