### ISSUE TITLE
Accounts don't appear to have a unique identifier

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5883]
Accounts don't appear to have a unique identifier. I had to construct my own from type-market-asset-party.

**Comment by jeremyletang** [comment]
Correct accounts do not havr identifier as of now. They are a mix of an optional market, asset and pubkey.

**Comment by barnabee** [comment]
That seems fine… primary key is a composite? 🤷 

Not sure what value a unique ID has here? Can't see why this would need to change, it'd just mean you need to lookup the ID for the composite anyway…
