### ISSUE TITLE
Don't return exclamation marks when the field should instead be null

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5884]
REST API missing market ID is returned as "!" which is just weird - return null, please

**Comment by jeremyletang** [comment]
This is a a leak from internals of the core and should be remove most likely yes.

**Comment by jeremyletang** [comment]
Just checked on the APIs and this is fixed (looking at https://api.n01.stagnet3.vega.xyz/api/v2/accounts for example), please open again if you find the issues anywhere else.
