### ISSUE TITLE
Get LP commitments for all markets

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5885]
There's no REST endpoint to get all LP orders for a party (across all markets)

**Comment by gordsport** [comment]
Hey @jeremyletang 
has this been resolved in: 
- https://github.com/vegaprotocol/vega/pull/5797

Or is this an API we need to add?

**Comment by pscott31** [comment]
Yes you can do this like so:

![Image](https://user-images.githubusercontent.com/94362991/186232939-a9a05e50-3b8e-4392-bcd4-3f393169cd7f.png)

I'll close this issue feel free to reopen if I've missed something

**Comment by MM0819** [comment]
@pscott31 Yes, that looks good! I was going by the v1 docs I guess...
