### ISSUE TITLE
Get LP orders for party and market should not return a list

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5886]
This endpoint shouldn't return an array (there's only ever gonna be one): https://n06.testnet.vega.xyz/datanode/rest/liquidity-provisions/party/9d666ddfd25278835b3ce1c63d5a9bb74ee4be7b60c229e7254a7f214ac91899/market/10c4b1114d2f6fda239b73d018bca55888b6018f0ac70029972a17fea0a6a56e

**Comment by jeremyletang** [comment]
Correct. Although I’m pretty sure this is dur to the fact that the underlying grpc request is actually filtered over thr market and party. And if the market wasnt specified there you would get all the party LPs

**Comment by gordsport** [comment]
Closing as wont fix at this time
