### ISSUE TITLE
Get assets via GraphQL subscription

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5887]
There is no GraphQL subscription to get assets

**Comment by jeremyletang** [comment]
There’s no plans for this so far. Asset are created very rarely, adding a subscription for something which might happen once in a while seems unnecessary.

**Comment by MM0819** [comment]
Hmm, I see. So how frequently would you advise somebody to update their local version of the assets in their client application? Is once a day enough, for example?

**Comment by barnabee** [comment]
@MM0819 what's the use case for a subscription? Only places I can think you'd actually get a list of assets would be a market creation form or for deposits, and I'd load the list once on page load for those. Anything else I'd suggest just memoising the requests for the specific asset ID(s) you see in other data.
