### ISSUE TITLE
Get LP commitments via GraphQL subscription

### ISSUE THREAD

**Issue by MM0819** [vegaprotocol/vega#5888]
There is no GraphQL subscription to get just my LP orders (I have to nest them inside an orders subscription)

**Comment by jeremyletang** [comment]
What exactly would you like here? The orders created by the network to fullfil your commitment? If yes we should be able to easily add a filter on the orders subscription for that.

**Comment by MM0819** [comment]
No, I mean a subscription to get the commitment itself (for example, so that I can keep an up-to-date version of it without the need for polling). I believe the status of the commitment can change when things happen in the core?

**Comment by jeremyletang** [comment]
Ah, correct. It can be deployed or undeployed. But also cancelled if the party was not able to fullfil the bond.

**Comment by MM0819** [comment]
Yeah, so I am getting the LP commitment with the following subscription. But this means I get the same thing back inside of every order, and so the load is unnecessarily heavy...

```       
subscription {
            orders(partyId: "PARTY_ID", marketId: "MARKET_ID") {
                id
                price
                side
                type
                size
                remaining
                status
                market {
                    id
                }
                liquidityProvision {
                    id
                    status
                    commitmentAmount
                    fee
                    sells {
                        liquidityOrder {
                            reference
                            proportion
                            offset
                        }
                    }
                    buys {
                        liquidityOrder {
                            reference
                            proportion
                            offset
                        }
                    }
                }
            }

**Comment by jeremyletang** [comment]
Indeed, that’s definitely not the way to do this. It also wouldn’t work for long as we will reduce the amount of data available in subscription to reduce graphql complexity.
