### ISSUE TITLE
[graphql] Fix documentation for udpateAsset 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5904]
https://github.com/vegaprotocol/vega/blob/277b3e9318ccc772df34fd49fe039d8283993f8b/datanode/gateway/graphql/schema.graphql#L2959

#5281 added updateAsset to graphql, but the graphql documentation is copy and pasted incorrectly

# Task
- [ ] Make documentation correct

**Comment by gordsport** [comment]
Hey @ValentinTrinque 
As you did the update asset work please can you have a look at this issue?
