### ISSUE TITLE
TestCannotSend consistently failing on macOS amd64

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#5941]
# Problem encountered
I am using GitHub Actions to compile and publish the `data-node` binary. One of the preconditions is to pass unit tests, which run ok for most of the binaries, but it keeps failing for `macOS amd64`, e.g. https://github.com/vegaprotocol/vega/runs/7897445224?check_suite_focus=true

# Observed behaviour
One unit test has failed 4 times in a row
```
=== RUN   TestCannotSend
    observer_test.go:94: 
        	Error Trace:	/Users/runner/work/vega/vega/datanode/utils/observer_test.go:94
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestCannotSend
--- FAIL: TestCannotSend (0.17s)
FAIL
FAIL	code.vegaprotocol.io/vega/datanode/utils	0.387s
```

# Expected behaviour
All Unit Tests should pass every time.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
run unit tests locally on your machine

## Automation
1. Go to vega repo https://github.com/vegaprotocol/vega
2. Select `Actions` tab at the top
3. Select `Release vega, data-node and vegawallet binaries` from the left menu
4. Click `Run workflow` drop down on the right
5. Select options
  - do NOT select `Publish ...` (i.e. leave unticked)
  - provide your branch name as `Git Tag ...`
  - select `data-node`
  - select `amd64`
6. Click `Run Workflow`

# Evidence

## Logs
```
=== RUN   TestCannotSend
    observer_test.go:94: 
        	Error Trace:	/Users/runner/work/vega/vega/datanode/utils/observer_test.go:94
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestCannotSend
--- FAIL: TestCannotSend (0.17s)
FAIL
FAIL	code.vegaprotocol.io/vega/datanode/utils	0.387s
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@fkondej 
We have not had reports of this recently from Mac users - can this be closed?
