### ISSUE TITLE
Improve the wallet connection workflow on API v2

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#5967]
To improve user experience, we want to reduce the number of time the passphrase is asked without compromising the security

**Current situation:**

- Application A wants to connect wallet 1
- Wallet app ask if connection is okay
- If yes, unlock wallet 1 using passphrase
- Application B wants to connect wallet 1
- Wallet app ask if connection is okay
- If yes, unlock wallet 1 using passphrase

**Desired situation:**
- Application A wants to connect wallet 1
- Wallet app ask if connection is okay
- If yes, unlock wallet 1 using passphrase
- Application B wants to connect wallet 1
- Wallet app ask if connection is okay
- If yes, we use the unlocked wallet.

This improvement doesn't introduce breaking changes. I could even improve the wallet modification synchronization across different sessions.

**Comment by barnabee** [comment]
I think it would be a nice improvement to not require the pasword if the wallet is unlocked but perhaps to auto-lock the wallet after some period of inactivity and if the user locks their computer. Perhaps that is more of a future enhancement though.

**Comment by barnabee** [comment]
I was also thinking particularly about, say application A connects to wallet 1 and wallet 2, and application B connects to wallet 1, and application C connects to wallet 3, how does this work if I am switching between applications and wallets? How often do I need to re-enter the passwords, and do I need to switch (lock/unlock?) wallets in the UI at all?

**Comment by ValentinTrinque** [comment]
_In the examples below, I assume we have the improved workflow described above._

Once you are connected to a wallet, you get a token. So if you want, on an application to switch wallet, the application can just change the token in the requests.

So, the app 1 connects wallet A (connection verification + passphrase input), and gets the token A1. It then connects to wallet B (connection verification + passphrase input because different wallet), and gets token B1. So switching between wallet is just switching token on the third party app.

Now you have app 2 connecting to wallet B (connection verification but no passphrase as already unlocked), and gets token B2. It's a different token once again.

So the passphrase input will be only required when unlocking the wallet the first time and during permissions update.

**Comment by ValentinTrinque** [comment]
In the end, despite achieving the primarily goal of this issue, I didn't implemented it the way it is described [this comment](https://github.com/vegaprotocol/vega/issues/5967#issuecomment-1224026510).

The locking mechanism is now completely separated from the connection layer. The connection layer uses a wallet store that hold a list of all the unlocked wallet. So if it has been unlocked by any ways, it won't require a passphrase input anymore.
