### ISSUE TITLE
Nothing appears on the event bus for ignored/filtered out oracle messages

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#5985]
# 0047-DSRF-010
_If two data sources originate from **the same data point** (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) **but have different filters** or other properties (i.e. they are not exactly the same definition) then **any data that is filtered out by both data sources results in a separate log/event** for each that references the appropriate source in each case._

# Problem encountered
Two markets have the same oracle except the settlement price filter (>100 and >90).
After termination, when the settlement message is emitted with a price of 80, it is filtered out by both markets, but nothing appears on the event bus.

## Automation
Test case [here](https://github.com/vegaprotocol/system-tests/pull/1104/files#diff-07f5da4add0e7dd80985fdf2d4304dfc042af5143621253c98d687f2d0d53001R198)

## market 1 emits
{"id":"5652-17","block":"901423D8900C71093EF402D60CB90AC25117D492B8A7AB14D72D924C084725F5","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"id":"9b279f4883eb3ebc3f33c18fcbb8d6628c70add5f16e633f50d3a63917bc50ef","createdAt":"1661350117170658000","pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"filters":[{"key":{"name":"price.BTC.value","type":"TYPE_INTEGER"},"conditions":[{"operator":"OPERATOR_GREATER_THAN","value":"**100**"}]}],"status":"STATUS_ACTIVE"},"version":1,"chainId":"test-chain-WO6BrA","txHash":"37EEE0D5B0EE41EC0DAFE1D5FA5AEE22FFAE0BF9EE9B0A4C8856F4C6C7DC2D09"}

{"id":"5652-18","block":"901423D8900C71093EF402D60CB90AC25117D492B8A7AB14D72D924C084725F5","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"id":"07818a77a4638eb75ba27a1087e07b1e680ce382605862e70e4f6fab2c2bd62f","createdAt":"1661350117170658000","pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"filters":[{"key":{"name":"trading.termination","type":"TYPE_BOOLEAN"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"True"}]}],"status":"STATUS_ACTIVE"},"version":1,"chainId":"test-chain-WO6BrA","txHash":"37EEE0D5B0EE41EC0DAFE1D5FA5AEE22FFAE0BF9EE9B0A4C8856F4C6C7DC2D09"}

## market 2 emits
{"id":"5689-19","block":"E068D2CBBD2E9F30B0D3213A161EF6F8D56B3761D01F3D6A311F47787D63DE78","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"id":"75ac29da92425754442b7e155384629264e803d53f1c21ecf43b62e7228c40b3","createdAt":"1661350145205107000","pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"filters":[{"key":{"name":"price.BTC.value","type":"TYPE_INTEGER"},"conditions":[{"operator":"OPERATOR_GREATER_THAN","value":"**90**"}]}],"status":"STATUS_ACTIVE"},"version":1,"chainId":"test-chain-WO6BrA","txHash":"2D985AEFA8DD44B22ABBF9F3F49B9E2AC068BB4E68186D0B87755DD486A3C4B9"}

{"id":"5689-20","block":"E068D2CBBD2E9F30B0D3213A161EF6F8D56B3761D01F3D6A311F47787D63DE78","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"id":"07818a77a4638eb75ba27a1087e07b1e680ce382605862e70e4f6fab2c2bd62f","createdAt":"1661350117170658000","pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"filters":[{"key":{"name":"trading.termination","type":"TYPE_BOOLEAN"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"True"}]}],"status":"STATUS_ACTIVE"},"version":1,"chainId":"test-chain-WO6BrA","txHash":"2D985AEFA8DD44B22ABBF9F3F49B9E2AC068BB4E68186D0B87755DD486A3C4B9"}

## trading termination emits
{"id":"5728-30","block":"61FDA368222AB976B0A358779E9DB74BC21B7DBCDDC3A1F1E1E2F9675A075134","type":"BUS_EVENT_TYPE_ORACLE_DATA","oracleData":{"pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"data":[{"name":"trading.termination","value":"True"}],"matchedSpecIds":["07818a77a4638eb75ba27a1087e07b1e680ce382605862e70e4f6fab2c2bd62f"],"broadcastAt":"1661350174790709000"},"version":1,"chainId":"test-chain-WO6BrA","txHash":"E252B718DEAA784EE5C22290EFC1E53BE506F29CD5254C31FC08C1C2B1E9CBB2"}

## Settlement message sent emits
{"id":"5730-18","block":"AEA2C1223FC0EEABEDD4164E00079FC1BDA5A1A57E6ACAF7D0FC00DAC0B8A2FE","type":"BUS_EVENT_TYPE_ORACLE_DATA","oracleData":{"pubKeys":["7a3803ca844ac11368cb545bbdf7ba11698071ef9c420ba3399e9d7bf51833a4"],"data":[{"name":"price.BTC.value","value":"**80**"}]},"version":1,"chainId":"test-chain-WO6BrA","txHash":"EEAF38816C5F138305C79353857D738F1749E916AEB3C329EE7CB7531BB413B1"}

## That's it
No more events with BUS_EVENT_TYPE_ORACLE_SPEC or BUS_EVENT_TYPE_ORACLE_DATA are emitted until the test completes.

**Comment by jeremyletang** [comment]
@RomanLeca what other message do you expect here exactly? This AC must be unclear, because you submit data which matches no subscribers. The events is used by no one, and sent to the bus (you can see there's no matchedSpecIds on the event). That AC is wrong, seeing that the data is expected by no one as it pass the filters of no subscribers, what would you then expect? Send an event for every single subscribers for which this data didn't match?

**Comment by RomanLeca** [comment]
@jeremyletang , I am happy to have this AC removed alongside **0047-DSRF-007** which is very similar and a bit self-conflicting:
_When data is **filtered out** and no event is emitted this is recorded either in logs or on the event bus (this may only happen on the receiving node if the event is a transaction that is rejected prior to being sequenced in a block)._

@barnabee , are we ok to remove both of these from the spec?

**Comment by barnabee** [comment]
@RomanLeca pretty sure we discussed these on the call yesterday and they perhaps need rewording rather than removal, will take a look in a bit

**Comment by gordsport** [comment]
@AnExsomnis - please can you review this issue with @RomanLeca when you get a good opportunity. Its believed that this AC can/should be tested, albeit with some tidying/clarity to the spec wording.

**Comment by RomanLeca** [comment]
This has been tested a while ago. Closing.
