### ISSUE TITLE
OOM issues and data node shuts down with stderr failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:unexpected EOF

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6020]
Every nightly system test run shows datanode shutting down during the run

We can see 
```
failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:unexpected EOF
```

data-node shut down followed by core

have to restart network to recover
[dnl.txt](https://github.com/vegaprotocol/vega/files/9455355/dnl.txt)

Found a signal 9 termination in the datanode logs
```
2022-08-28 01:29:32.530 UTC [1] LOG:  server process (PID 193) was terminated by signal 9: Killed
```

Googled it, seems to be due to OOM issues and RDS settings
https://www.postgresql.org/message-id/AEEF347B-39EC-41FC-8AC9-2AFA54F71391%40gmail.com

**Comment by gordsport** [comment]
This issue should be fixed with the merge of the following PRs:
- https://github.com/vegaprotocol/docker/pull/50
- https://github.com/vegaprotocol/jenkins-shared-library/pull/230
- https://github.com/vegaprotocol/vegacapsule/pull/249
- https://github.com/vegaprotocol/system-tests/pull/1120

**Comment by gordsport** [comment]
Hey @vega-paul 
All the issues related to fixing this have been done. Please can you retest and close this if ok now?
