### ISSUE TITLE
0026-AUCT-001 is marked as covered by an integration test, but isn't

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6022]
https://github.com/vegaprotocol/vega/blob/0f41d01fd75049b96179b12df9c4b8305e9da119/core/integration/features/verified/0026-AUCT-auction_interaction.feature#L119

https://github.com/vegaprotocol/specs/blob/master/protocol/0026-AUCT-auctions.md#0026-AUCT-001 does not cover opening auctions, but having a market proposed and enacted that is not CONTINUOUS

**Comment by Jiajia-Cui** [comment]
- opening auction comes automatically once market is enacted, and opening auction does not have a minimum duration, it ends when orders cross;

- other type of auctions (liquidity auction or price monitoring auction) have "market.auction.minimumDuration" which is to control the auction duration

So I think the test is consistent with spec AC001

**Comment by edd** [comment]
> So I think the test is consistent with spec AC001

As per our off-github slack:

> As a user, I can configure a market through the market configuration to use auction mode 
This isn't currently possible as Vega only currently support continuous trading. The linked integration test does not use non-continuous trading, so it's not matching the criteria. However I feel like it's the criteria that's bad, rather than the test. The test is good :)

**Comment by gordsport** [comment]
closing as this issue was been resolved with:
- https://github.com/vegaprotocol/specs/pull/1214
