### ISSUE TITLE
Issue after update market proposal enactment - Testnet/Fairground

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#6032]
# Problem encountered
After a market update proposal has been enacted there is an issue which is displayed in console
**Error message in info screen. Something went wrong: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil**

# Observed behaviour
A clear and concise description of how the system is behaving.

# Steps to reproduce
1: Propose and vote through an update market proposal on an existing market
https://docs.vega.xyz/docs/testnet/tutorials/proposals/update-market-proposal
https://token.fairground.wtf/governance/propose

2: Go to the updated market in the console and access the market info screen after enactment. -https://console.fairground.wtf/markets/
**Error message in info screen. Something went wrong: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil**

# Expected behaviour
Console should be able to display the market information

# System response
Instead of market info this below message is displayed.
**Error message in info screen. Something went wrong: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil**

## Logs
See screenshot
<img width="880" alt="Screenshot 2022-09-01 at 10 41 04" src="https://user-images.githubusercontent.com/100769129/187871453-d64351e8-dde8-43b1-a4b9-6180b93596a4.png">

## Additional context
Test performed on testnet/fairground v0.55.0+dev

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by dexturr** [comment]
```
  query MarketInfoQuery($marketId: ID!, $interval: Interval!, $since: String!) {
    market(id: $marketId) {
      id
      name
      decimalPlaces
      positionDecimalPlaces
      state
      accounts {
        type
        asset {
          id
        }
        balance
      }
      tradingMode
      accounts {
        type
        asset {
          id
        }
        balance
      }
      fees {
        factors {
          makerFee
          infrastructureFee
          liquidityFee
        }
      }
      priceMonitoringSettings {
        parameters {
          triggers {
            horizonSecs
            probability
            auctionExtensionSecs
          }
        }
      }
      riskFactors {
        market
        short
        long
      }
      accounts {
        type
        asset {
          id
        }
        balance
      }
      data {
        market {
          id
        }
        markPrice
        indicativeVolume
        bestBidVolume
        bestOfferVolume
        bestStaticBidVolume
        bestStaticOfferVolume
        openInterest
        bestBidPrice
        bestOfferPrice
        trigger
        priceMonitoringBounds {
          minValidPrice
          maxValidPrice
          trigger {
            horizonSecs
            probability
            auctionExtensionSecs
          }
          referencePrice
        }
      }
      liquidityMonitoringParameters {
        triggeringRatio
        targetStakeParameters {
          timeWindow
          scalingFactor
        }
      }
      candles(interval: $interval, since: $since) {
        volume
      }
      tradableInstrument {
        instrument {
          id
          name
          code
          metadata {
            tags
          }
          product {
            ... on Future {
              quoteName
              settlementAsset {
                id
                symbol
                name
              }
              oracleSpecForSettlementPrice {
                id
              }
              oracleSpecForTradingTermination {
                id
              }
              oracleSpecBinding {
                settlementPriceProperty
                tradingTerminationProperty
              }
            }
          }
        }
        riskModel {
          ... on LogNormalRiskModel {
            tau
            riskAversionParameter
            params {
              r
              sigma
              mu
            }
          }
          ... on SimpleRiskModel {
            params {
              factorLong
              factorShort
            }
          }
        }
      }
      depth {
        lastTrade {
          price
        }
      }
    }
  }
```

Market info query

**Comment by ze97286** [comment]
seems like risk factors are missing. 
<img width="1750" alt="Screenshot 2022-09-01 at 13 22 01" src="https://user-images.githubusercontent.com/6655556/187912674-21efbe11-dff2-4a81-a5b5-3f5bed1883d3.png">

**Comment by MadalinaRaicu** [comment]
NOTE: accounts and candles are deprecated.  (we need to fix that) 
in this example we were querying accounts 3 times (this has been fixed on master)
