### ISSUE TITLE
`auctionEnd` field should be blank in an auction that has no set end date

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6037]
See #6029. A liquidity auction that has exceeded minimumAuctionLength will end as soon as it possibly can. The current result in the API is that marketData.auctionEnd is constantly updated as 'now', which due to various factors more relevant to #6029 can make it appear to be in the past. Neither now nor in the past is correct, because the market is still in auction.

In this situation, it is better to return 'undefined' / null / equivalent than an invalid date

# Tasks
- [ ] Update `auctionEnd` not to update continuously in the case of auctions that will exit immediately if their trigger is hit

**Comment by EVODelavega** [comment]
@jeremyletang was working on some changes WRT auction end yesterday. Looking at it then, it appeared as though auctions, even if extended, would call `OnAucitonEnd`. This should be fixed now, but I'll go through it to ensure that the events we send do make sense
