### ISSUE TITLE
Freeform proposal description size can be > 10000 characters

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6055]
Test covers this AC
test_NewFreeFormProposal_boundary_Char_Description
Proposal with description > 10000 in size is enacted, expected Declined

https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md

A freeform governance proposal with a description field that is empty, or not between 1 and 10,000 characters, will be rejected ([0028-GOVE-019](https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md#0028-GOVE-019))

**Comment by jeremyletang** [comment]
20k chars is now the max size for all proposals.
