### ISSUE TITLE
Core/Datanode load test fails - failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:unexpected EOF

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6059]
https://vegaprotocol.slack.com/team/U02MBDKMVV1

We have a capsule load test running now, started approx 9 hrs ago. 

The full-2 allocations for datanode have vanished on this run, not sure what happened  but it started ok. Could someone please check this run below? Run scheduled for 2 days so will cut it when someone confirms we should abort due to VC issues. (4/9  - aborted the run)

Pipeline can be seen here...
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/4843/pipeline/269/

**Comment by karlem** [comment]
@vega-paul This can quite easily happen now since we added the requested feature for not restarting. So if data-node panics or something it won't be restarted. I am not sure this is related to VC I would say more to data node. @pscott31 could you help?

**Comment by vega-paul** [comment]
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/4843/artifact/testnet/logs/testnet-nodeset-full-2-full/data-node-2.stderr-2022-09-03T13%3A35%3A55Z.log

failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:unexpected EOF

**Comment by gordsport** [comment]
Hey @vega-paul 
Please can you update on the frequency of this issue?

**Comment by vega-paul** [comment]
Happened here
failed to flush subscriber:flushing ledger: failed to copy ledger entries into database:unexpected EOF
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/8991/artifact/testnet/logs/testnet-nodeset-full-2-full/

Same issue

**Comment by vega-paul** [comment]
related to https://github.com/vegaprotocol/vega/issues/6210

**Comment by gordsport** [comment]
@vega-paul 
This is expected to be a data node issue not capsule. As its related to https://github.com/vegaprotocol/vega/issues/6210 which is now closed can this be closed?

**Comment by gordsport** [comment]
closing pending further information
