### ISSUE TITLE
Data node fails to respond to REST requests/requests are not serviced

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6062]
Network is running with datanode
Network is clean/green/no errors on stderr

![image](https://user-images.githubusercontent.com/86229849/188426084-9643596f-98c9-463c-9634-54de507a6066.png)

Submitted a REST request from command line to localhost:3029
This hangs - never returns back anything part Accept

Curl trace....

```
== Info:   Trying 127.0.0.1:3029...
== Info: Connected to localhost (127.0.0.1) port 3029 (#0)
=> Send header, 95 bytes (0x5f)
0000: 47 45 54 20 2f 61 70 69 2f 76 32 2f 73 74 61 74 GET /api/v2/stat
0010: 69 73 74 69 63 73 20 48 54 54 50 2f 31 2e 31 0d istics HTTP/1.1.
0020: 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 .Host: localhost
0030: 3a 33 30 32 39 0d 0a 55 73 65 72 2d 41 67 65 6e :3029..User-Agen
0040: 74 3a 20 63 75 72 6c 2f 37 2e 37 39 2e 31 0d 0a t: curl/7.79.1..
0050: 41 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a    Accept: */*....
```

Have to restart network to recover

**Comment by vega-paul** [comment]
Will monitor

**Comment by gordsport** [comment]
Hey @paul,
Please can you update on the monitoring of this issue?

**Comment by vega-paul** [comment]
cant reproduce - also no further examples of this
