### ISSUE TITLE
A one-off transfer to an account reward type ignores the TO field

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6067]
# Problem encountered
Single transfers to a reward pool should not be used, and should not be supported (#6066). However, they are currently possible. And there's a weird wrinkle:

```bash
vegawallet command send --wallet test --pubkey a35db5fcbc46962cc8283dbbccc506e82c95a548eddc913da5e35ea173c3b279 --network stagnet3 '{
    "transfer":{
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "toAccountType": "ACCOUNT_TYPE_GLOBAL_REWARD",
        "to":"a35db5fcbc46962cc8283dbbccc506e82c95a548eddc913da5e35ea173c3b279",
        "asset":"b4f2726571fbe8e33b442dc92ed2d7f0d810e21835b7371a7915a365f07ccd9b",
        "amount":"1",
        "oneOff":{
            "deliverOn": 0
        }
    }
}'
```

The above code snippet suggests it will transfer 0.000...1 *from* my general account, to my `ACCOUNT_TYPE_GLOBAL_REWARD` account. But a party can't have an account of that type (see: [00013-ACCT](https://github.com/vegaprotocol/specs/blob/master/protocol/0013-ACCT-accounts.md#accounts-controlled-by-parties)). What happens instead is that the `TO` field is ignored and the transfer instead targets the `ACCOUNT_TYPE_GLOBAL_REWARD` for asset `b4f2726571fbe8e33b442dc92ed2d7f0d810e21835b7371a7915a365f07ccd9b`, which it then transfers. 

# Expected behaviour
The transfer should be rejected because a party that is not 00000000000 can never have a `ACCOUNT_TYPE_GLOBAL_REWARD`.

**Comment by ze97286** [comment]
@edd the description isn't accurate. you *can* setup a one off transfer to ACCOUNT_TYPE_GLOBAL_REWARD. it is correct that the to is ignored in this case. What would you suggest to make it cleaner and clearer?

**Comment by edd** [comment]
It's imperfect, but what if it was enforced that to is `0000....00` for a one off transfer **if** the target account type is `ACCOUNT_TYPE_GLOBAL_REWARD`

What this avoids is fat-fingering an account type and accidentally transfering it to a global reward pool. 

I think this should also be the case for any transfer destined for a reward pool, in case the same problem exists there. 

I guess a better solution would be different types - ones that should specify 000 would use a different tx/command. But the 0000 thing works as well.
