### ISSUE TITLE
node fails to run after restoring from checkpoint

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vega#6069]
# Problem encountered
One of the nodes (testnet-nodeset-full-2-full) fails, after restoring checkpoint in vegacapsule. Consulted with @vega-paul 

# Observed behaviour
Network fails because of the following and cannot be used using UI (e.g. Token FE). I'm using latest vegacapsule from origin/main and latest vega from origin/develop. I'm following the simplest case of restoring checkpoint (default config from vegacapsule).

# Expected behaviour
All nodes/job should be up and running correctly to be used in UI tests.

# System response
stderr:
`panic: Failed to process committed block (2:F5C011B41E27EE44B581E805AD5321F5FF4FD3EF370D92BE63E4FE7AB23CE1E6): leveldb: closed

goroutine 140 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0x14000555500, 0x0)
	/Users/rado/go/pkg/mod/github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:407 +0xf08
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/Users/rado/go/pkg/mod/github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:110 +0x80`

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually (following https://github.com/vegaprotocol/vegacapsule README):
1. Clone vegacapsule & vega repo, `go install ./...` in both of them.
2. Run `vegacapsule nomad`.
3. Run `vegacapsule network bootstrap --config-path=$HOME/vega/vegacapsule/net_confs/config.hcl --force`
4. Run some UI, e.g. Token from frontend-monorepo. Make changes. I associated 100tokens to vega wallet.
5. Go to `$HOME/.vegacapsule/testnet/vega/node0/state/node/checkpoints`, copy any of the checkpoints and paste somewhere else.
6. Run `vegacapsule network stop`
7. Run `vegacapsule nodes unsafe-reset-all`
8. Run `vegacapsule nodes restore-checkpoint --checkpoint-file PATH_TO_YOUR_CHECKPOINT_FILE --home-path $HOME/.vegacapsule/testnet`
9. Run `vegacapsule network start`
10. See the jobs in nomad UI  and open FE app.

Very similar case happen, when trying to restore checkpoint on fresh network, then all jobs are green, but no response is coming to FE. 

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Hey @radoslaw-szpiech 
Please can you re run this and add the full logs to this issue so we can investigate further?

**Comment by radoslaw-szpiech** [comment]
Apparently the issue was caused due to incorrect restoring the checkpoint.
Network must be stopped with flag: `vegacapsule network stop --nodes-only flag`, to make this scenario work. I created an issue to update vegacapsule readme file.
