### ISSUE TITLE
datanode to wait for upgrade block

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#6080]
When validators decides to schedule an upgrade, and event is sent to the data-node. The datanode should listen to these events and to keep track of scheduled upgrades.

Once the time of the upgrade is reached, the visor will then ask the data-node to shutdown. In order to ensure that the whole state of the data-node is correct regarding to the validator nodes, the data-node should ensure that it processed all blocks up to the block of the  upgrade.

Respectively the core node shouldn't shutdown as well until the data-node have consumed all blocks in the broker queue (pending to be sent).

Once all events have been saved in the database, both nodes should stop gracefully.

**Comment by gordsport** [comment]
Update on (very high level) process / scope of this work:

1. visor communicates upgrade block
2. Datanode sets a flag that its consumed/saved last blocks data
3. Visor takes over the processes (core and DN) of shutting down/upgrading etc...


Therefore datanode just need to set a flag when step 2 is done and have an API that allows visor to know thats done
