### ISSUE TITLE
Doubly counted associated tokens on mainnet - vega v0.53

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6087]
It seems to me that on mainnet the data node is double counting associated vega tokens (and when I say data node I mean, I am hoping it's only the data node and not core as well).

```
party(id:"ae5d7b6d5ed030a476e2a8acb0d7965fdbfb9535d492b1287def26005f7b5a75")
	{
    id
    stake {
      linkings {
        amount
        
      }
    }
  }
```
on http://mainnet-observer.ops.vega.xyz:3008/playground returns
```
{
  "data": {
    "party": {
      "id": "ae5d7b6d5ed030a476e2a8acb0d7965fdbfb9535d492b1287def26005f7b5a75",
      "stake": {
        "linkings": [
          {
            "amount": "7978391471600497959544"
          },
          {
            "amount": "850196376840000000000001"
          },
          {
            "amount": "7978391471600497959544"
          }
        ]
      }
    }
  }
}
```
The big number is correct; the two starting with 797... are not in the sense that there should be just one of them.

**Comment by gordsport** [comment]
The fix for this issue is in: 
- https://github.com/vegaprotocol/vega/pull/6091

**Comment by gordsport** [comment]
@davidsiska-vega, This has now been merged into develop and could be retested there, alternatively this can be retested in stagnet3 when its deployed
