### ISSUE TITLE
Market Proposer rewards paid out more than once

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6097]
Spec Ref - https://github.com/vegaprotocol/specs/blob/master/protocol/0056-REWA-rewards_overview.md

AC 0056-REWA-041 states that the market proposer reward are NOT to be paid more than once

However we noticed that if a recurring transfer with a recurrence count of 3 is set up for an asset / market with the dispatch metric as market proposer rewards - then the market proposer rewards are paid out 3 times for the same party / asset / market

Test run - https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/5777/artifact/

Rewards Payout events - https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/5777/artifact/test_logs/workspace.tests.rewards.trading_rewards_test/test_distribute_market_proposer_rewards_no_eligibility/BUS_EVENT_TYPE_REWARD_PAYOUT_EVENT.txt

**Comment by ze97286** [comment]
@MuthuVega what is the name of the test?

**Comment by MuthuVega** [comment]
@ze97286 - the name of the test is test_distribute_market_proposer_rewards_no_eligibility
However the name of the test doesn't correlate to the issue I have raised here - was troubleshooting something else and stumbled upon this issue.

**Comment by ze97286** [comment]
what I meant was `trading_rewards_bug`, I found it anyways, thanks.
