### ISSUE TITLE
Core still producing events with account type - ACCOUNT_TYPE_REWARD_TAKER_PAID_FEES

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6113]
Recently there was a change in core to rename ACCOUNT_TYPE_REWARD_TAKER_PAID_FEES to ACCOUNT_TYPE_REWARD_MAKER_PAID_FEES

However , we can still see that core is producing events with the TAKER_PAID_FEES account type.

Question : Noticed that there were no changes to protos as part of this change - do we need to update protos to reflect the change in account type name?

Transfer Request:

```
16:00:27  2022-09-08 15:00:27.042:[INFO] [MainProcess] [MainThread] [transferMod.py]:[submit_transfer]:[ 205] Wallet Transfer Req is {'transfer': {'fromAccountType': 'ACCOUNT_TYPE_GENERAL', 'to': '822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a', 'toAccountType': 'ACCOUNT_TYPE_REWARD_MAKER_PAID_FEES', 'asset': '822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a', 'amount': '18340000000000000000', 'reference': 'TestTransfer', 'recurring': {'startEpoch': '47', 'endEpoch': '50', 'factor': '1', 'dispatchStrategy': {'assetForMetric': '822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a', 'metric': 'DISPATCH_METRIC_MAKER_FEES_PAID', 'markets': []}}}}
16:00:27  2022-09-08 15:00:27.042:[INFO] [MainProcess] [MainThread] [transferMod.py]:[submit_transfer]:[ 206] Transfer From Trader is E1F8D60CE4
16:00:27  2022-09-08 15:00:27.067:[INFO] [MainProcess] [MainThread] [ walletsMod.py]:[wallet_sign_submit_txn_v2]:[ 251] TRX request b'{"transfer": {"fromAccountType": "ACCOUNT_TYPE_GENERAL", "to": "822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a", "toAccountType": "ACCOUNT_TYPE_REWARD_MAKER_PAID_FEES", "asset": "822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a", "amount": "18340000000000000000", "reference": "TestTransfer", "recurring": {"startEpoch": "47", "endEpoch": "50", "factor": "1", "dispatchStrategy": {"assetForMetric": "822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a", "metric": "DISPATCH_METRIC_MAKER_FEES_PAID", "markets": []}}}, "propagate": true, "pubKey": "244523994d8721104abbb689384792d4cde7f781ab8f378a6c21f2c9e0c20b18"}'
```

Event Produced by Core for this Transfer:

`{"id":"836-4","block":"974E16A387D92E7D701703928E465684EF2E2838296FBC8E06BF039DA1E383D6","type":"BUS_EVENT_TYPE_TRANSFER","transfer":{"id":"dfc837030c3814d6e140a12fe7e4799e30c81588482917c4c41b1011de05a328","from":"244523994d8721104abbb689384792d4cde7f781ab8f378a6c21f2c9e0c20b18","fromAccountType":"ACCOUNT_TYPE_GENERAL","to":"822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a","toAccountType":"ACCOUNT_TYPE_REWARD_TAKER_PAID_FEES","asset":"822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a","amount":"18340000000000000000","reference":"TestTransfer","status":"STATUS_PENDING","timestamp":"1662649227227726263","recurring":{"startEpoch":"47","endEpoch":"50","factor":"1","dispatchStrategy":{"assetForMetric":"822ab6b7d3eea2b9b7f16d3237d04e728307ea3ecbea45288d9cfe87200c181a","metric":"DISPATCH_METRIC_TAKER_FEES_PAID"}}},"version":1,"chainId":"test-chain-M6laLM","txHash":"FD9B10B81227AB089C6D49A8A5A84F0D8094388F4CDA525FA18CDB475B278F62"}`

Jenkins Run Link - https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/5992/

Test Marker - trading_rewards
Test Name - test_funding_reward_accounts_recurring

cc: @ze97286

**Comment by gordsport** [comment]
Hey @MuthuVega 
Please can you migrate to using the tools that are inside the core vega repo and then re-test this issue?

**Comment by MuthuVega** [comment]
This is now resolved - Thx
