### ISSUE TITLE
Wallet feature request: Persistent storage of transactions

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#6142]
# Feature Overview

**In order to** see previous transaction that a wallet has signed
**We will** build a persistent + encrypted store of transactions 
**So that** wallet users can check to see what a key has signed: for record keeping, debuting etc.

## Specs
- [User interface/wallet](https://github.com/vegaprotocol/specs/user-interface/0001-WALL-wallet.md)  (👈 this may not yet have been merged. Here is the [PR](https://github.com/vegaprotocol/specs/pull/1181))

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] 
- [ ]

# Acceptance Criteria

- **should** see a history of transactions the wallet app has signed as read from the local app (persistent storage) (<a name="0001-WALL-080" href="#0001-WALL-080">0001-WALL-080</a>)
  - persistent transaction history **must** be encrypted and require the wallet password to view (<a name="0001-WALL-081" href="#0001-WALL-081">0001-WALL-081</a>)
  - **should** be possible to delete individual transactions (<a name="0001-WALL-082" href="#0001-WALL-082">0001-WALL-082</a>)
  - **should** be possible to delete the whole transaction history (<a name="0001-WALL-083" href="#0001-WALL-083">0001-WALL-083</a>)
  - **would** like to set a maximum age / expiry time for history items after which they are deleted (<a name="0001-WALL-084" href="#0001-WALL-084">0001-WALL-084</a>)

[these were committed](https://github.com/vegaprotocol/specs/pull/1181/commits/94917202298a2d9393ec04659dfd55de8b4304c1) to FE Acceptance criteria but commented out until implementation.

See also the detail that is required on each transaction: https://github.com/vegaprotocol/specs/user-interface/0001-WALL-wallet.md#transaction-detail

This should supersede any "session" based transaction history that may exist.

----  This ticket has not been completed below this point ----

# Test Scenarios
Detailed scenarios (1-3!) that can be executed as feature tests to verify that the feature has been implemented as expected. We use the follow format:

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/integration/) for more format information and examples.

# Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature. 

# Examples (optional)
Code snippets from the spec for reference

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by barnabee** [comment]
I'm not sure yet how prioritisation will be decided as it's clear with put lots in Cosmic Elevator for now that might not all make it in (and also that these milestones mean less for front end once trading is live), but…

I want to record here that although I've said it would be acceptable from a privacy point of view to do this, I am not convinced it would be worth the effort to do this any time soon vs other features we could work on.
