### ISSUE TITLE
Bug in feature test, initial order from trader3 should be rejected but got accepted in the feature test 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#6188]
please see details in the [PR](https://github.com/vegaprotocol/vega/pull/6165)

- In the feature test in line 79, the initial order from trader3 should be rejected since they do not have enough collateral to cover the initial margin level.

- I think its a bug existing in feature test.

- I did the same test in market-sim (with the same risk parameter/net work parameter and same orders on the market), and the order from trader3 does get rejected.

**Comment by ze97286** [comment]
@Jiajia-Cui why do you think it should be rejected?

They have 90 in their general account (line 31) and the maintenance level is size * markPrice * longRiskFactor = 10*10* 0.800728208~=81 < 90

**Comment by Jiajia-Cui** [comment]
this is the case when a new trade is entered, we should check the initial margin level which is 162, since trader3 only has 90, the order should be rejected

**Comment by Jiajia-Cui** [comment]
I think its a bug in feature test runner, not in core

**Comment by ze97286** [comment]
I'm pretty sure the test in the market-sim is sufficiently different to explain it (e.g. if trader3 is also an LP on the sim). The feature test just passes the order to the market which is the actual vega core market.

**Comment by ze97286** [comment]
The behaviour is correct. See discussion in https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1663340003602599

**Comment by Jiajia-Cui** [comment]
It's the expected behaviour, the minimum collateral amount required for a new trade to be entered into is the mentainance margin instead of initial margin.
