### ISSUE TITLE
Bug in margin calc when trader reduces their order size 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#6202]
please see the feature file in this [PR](https://github.com/vegaprotocol/vega/pull/6147)

party1 has reduced their order size from 20 to 2 (line 69), but there is no change in margin account and margin level; while party4 has doubled their order size from 20 to 40 (line 70), and the margin account and margin levels had been all doubled.

So the bug in margin calc only existing when trader reduces their order size

**Comment by ze97286** [comment]
@Jiajia-Cui what is the bug here? we don't immediately update the margin if the size is _decreased_. It will be updated on the next mark-to-market.

**Comment by Jiajia-Cui** [comment]
@ze97286 I think we should update the margin when the order size changes, could you please let me know where in the spec is the instructions for NOT updating the margin?

**Comment by ze97286** [comment]
there's no *direct* evidence but there's a couple of indirect pieces of evidence. 

1. https://github.com/vegaprotocol/specs/blob/a9f2168e7e32b80ab128f9847215277330e19d1c/protocol/0011-MARA-check_order_allocate_margin.md#acceptance-criteria - the ACs speak explicitly about doing this if order is amended such that size/price is increased
2. This comment in the code is obviously not proof of anything but I think is indicative of past discussions:
```
// Perform check and allocate margin if price or order size is increased
	// ignore rollback return here, as if we amend it means the order
	// is already on the book, not rollback will be needed, the margin
	// will be updated later on for sure.
```
