### ISSUE TITLE
vegacapsule node crash

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vega#6210]
stderr: failed to flush subscriber:failed to copy market data into database:unexpected EOF

**Comment by pscott31** [comment]
Hi, this looks like postgres running out of memory and being OOM killed - what was happening at the time? There were some capsule config changes [a little while](https://github.com/vegaprotocol/system-tests/commit/1542bc391ca11e716bb63b222fbeca2595e440f2) back to give the postgres docker container a bit more memory; does this predate that?

**Comment by vega-paul** [comment]
dupe

**Comment by jeremyletang** [comment]
closing as duplicates
