### ISSUE TITLE
Datanode v2 API for get candles has redundant interval parameter

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vega#6222]
_When re-implementing example scripts for the v2 APIs I've noticed the following possible issue:_

We've now got a two step process, step 1 is to find the custom candle id for a given market via `candle intervals list` and we get back something like:

```
{
  "intervalToCandleId": [
    {
      "candleId": "trades_candle_1_hour_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "1 hour"
    },
    {
      "candleId": "trades_candle_6_hours_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "6 hours"
    },
    {
      "candleId": "trades_candle_1_day_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "1 day"
    },
    {
      "candleId": "trades_candle_1_minute_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "1 minute"
    },
    {
      "candleId": "trades_candle_5_minutes_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "5 minutes"
    },
    {
      "candleId": "trades_candle_15_minutes_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84",
      "interval": "15 minutes"
    }
  ]
}
```

Step 2 is to then call the `candles list` endpoint with a specific ID for an available interval given above:

So if I'm looking for the 1 hour candles for the market X I send in the following ID:

`trades_candle_1_hour_6e30c57de005b1bc16527c1d52ca022e45a5d4e9f020dc133ee6f834c1035c84`

Also I need to specify a required parameter called **interval** e.g. **INTERVAL_I1H** to /candle call

This **INTERVAL_I1H** seems like it is now redundant as the interval/bucket is encoded in the ID from step 1.

Maybe there's more functionality, if so please let me know :thumbsup:

**Comment by gordsport** [comment]
Hey @guoguojin 
Please can you confirm the PR number that resolved this?
Then we can close this issue / request @cdm retests on devent?
Thanks

**Comment by guoguojin** [comment]
https://github.com/vegaprotocol/vega/pull/6213 maps the INTERVAL_I?? GraphQL enum to the appropriate v2 interval and resolves the candle id automatically.
