### ISSUE TITLE
Wallet key rotation on 5 node network fails - failed to reload node wallet: failed to call NodeWallet.Reload method: failed to post data

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6247]
Running this test test_hot_key_rotation (branch feat_clef_ethereum_key_rotation)

Network-infra run so we use capsule_config_network_infra.hcl

Test fails

```
AssertionError: Error reloading wallet for the node failed to reload node wallet: failed to call NodeWallet.Reload method: failed to post data "{\"method\":\"NodeWallet.Reload\",\"params\":[{\"Chain\":\"vega\"}],\"id\":4575828879440392563}": Post "[http://unix/rpc":](http://unix/rpc) dial unix /tmp/vega-0.sock: connect: no such file or directory
  
assert 'failed to re...r directory\n' == ''
  + failed to reload node wallet: failed to call NodeWallet.Reload method: failed to post data "{\"method\":\"NodeWallet.Reload\",\"params\":[{\"Chain\":\"vega\"}],\"id\":4575828879440392563}": Post "[http://unix/rpc":](http://unix/rpc) dial unix /tmp/vega-0.sock: connect: no such file or directory
```

**Comment by wwestgarth** [comment]
could be because the network_infra config doesn't have the admin server switched on like the normal capsule config does:
```
[Admin]
    [Admin.Server]
      SocketPath = "/tmp/vega-{{.NodeNumber}}.sock"
      Enabled = true
```

I'll jump on your branch and give it a go.

**Comment by wwestgarth** [comment]
This isn't a core bug. The system tests need to map in the socket files into the docker container. It already does it for the node1 but not for node0: https://github.com/vegaprotocol/system-tests/blob/develop/scripts/Makefile#L498

So the tests either need to map in the file for node0, or used node1 to rotate keys. I can see in the diff for the branch the test used to use node1, but now uses node0 so maybe just revert that line.

**Comment by vega-paul** [comment]
tried node 1 for wallet rotation
that fails to same issue
test test_hot_key_rotation
branch feat_clef_ethereum_key_rotation

**Comment by wwestgarth** [comment]
This has been resolved now.
