### ISSUE TITLE
Querying for something that does exist in the REST api, or something totally invalid, both result in an error.

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6251]
# Problem encountered
Querying for something that does exist in the REST api, or something totally invalid, both result in an error.

### Examples of this issue:

- https://github.com/vegaprotocol/vega/issues/6230
- https://github.com/vegaprotocol/vega/issues/6232
- https://github.com/vegaprotocol/vega/issues/6234
- https://github.com/vegaprotocol/vega/issues/6236
- https://github.com/vegaprotocol/vega/issues/6238
- https://github.com/vegaprotocol/vega/issues/6294

### Other tasks:

- [ ] Check all API endpoints to ensure this issue is not seen anywhere it should not be.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by dexturr** [comment]
This is also present for getting an asset by id and getting a proposal by id

**Comment by AnExsomnis** [comment]
Closing - sub-issues job merged.
