### ISSUE TITLE
historicBalances query returns erroneous response when groups by MarketId, AssetId or PartyID

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/vega#6297]
# Problem encountered
historicBalances query returns error regarding `groupBy` parameter value. If this enum param is fulfilled by PartyId, AssetId or MarketId response is erroneous, if its AccountId or AccountType response seems to be ok.
![Screenshot 2022-09-26 at 12 41 25](https://user-images.githubusercontent.com/338931/192266113-0b470eec-ffb1-4a90-8de7-fa9c44a126b2.png)

# Definition of Done
query returns always proper data with no error

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by edd** [comment]
Related old issue: #5681
