### ISSUE TITLE
Datanode connectivity issues on Jenkins pipelines

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#6317]
# Problem encountered
Many tests fail at different stages (proposal, undelegation, asset data requests, etc) with a couple of similar errors, most frequent being GRPC connectivity

# Test run 
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-nightly/detail/system-tests-nightly/142/tests/

# Error
```
failed on setup with "grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-09-27T11:38:27.931663233+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {created_time:"2022-09-27T11:38:27.931650741+00:00", grpc_status:14}]}"
```

**Comment by gordsport** [comment]
Hi @pscott31 @RomanLeca 
We had some Jenkins OOM/OOD errors last week, do we know if this can be recreated of likely to have been caused by infra?
