### ISSUE TITLE
[datanode] REST request for accounts returns blank ID fields 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6320]
https://api.n06.testnet.vega.xyz/parties/073ceaab59e5f2dd0561dec4883e7ee5bc7165cd4de34717a3ab8f2cbe3007f9/accounts

Returns:

```json
{
  "accounts": [
    {
      "id": "",
      "owner": "073ceaab59e5f2dd0561dec4883e7ee5bc7165cd4de34717a3ab8f2cbe3007f9",
      "balance": "10000000000",
      "asset": "5cfa87844724df6069b94e4c8a6f03af21907d7bc251593d08e4251043ee9f7c",
      "marketId": "",
      "type": "ACCOUNT_TYPE_GENERAL"
    },
    {
      "id": "",
      "owner": "073ceaab59e5f2dd0561dec4883e7ee5bc7165cd4de34717a3ab8f2cbe3007f9",
      "balance": "1882987018",
      "asset": "6d9d35f657589e40ddfb448b7ad4a7463b66efb307527fedd2aa7df1bbd5ea61",
      "marketId": "",
      "type": "ACCOUNT_TYPE_GENERAL"
    },
    {
      "id": "",
      "owner": "073ceaab59e5f2dd0561dec4883e7ee5bc7165cd4de34717a3ab8f2cbe3007f9",
      "balance": "997216278",
      "asset": "993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede",
      "marketId": "",
      "type": "ACCOUNT_TYPE_GENERAL"
    },
    {
      "id": "",
      "owner": "073ceaab59e5f2dd0561dec4883e7ee5bc7165cd4de34717a3ab8f2cbe3007f9",
      "balance": "4537558200000000000",
      "asset": "fc7fd956078fb1fc9db5c19b88f0874c4299b2a7639ad05a47a28c0aef291b55",
      "marketId": "",
      "type": "ACCOUNT_TYPE_GENERAL"
    }
  ]
}
```

It's valid for `marketId` to be blank (although preferable would be nothing) but feels strange that ID is empty. In GraphQL, accounts don't have IDs. Is it just that... accounts don't have IDs?

# Choose Your Own Adventure
## Option 1: Fill the account ID, because accounts by party should have IDs
- [ ] Ensure account id is not empty in REST query for accounts by party

## Option 2: Remove the account ID, because accounts by party don't have IDs
- [ ] Remove account id  in REST query for accounts by party

**Comment by pscott31** [comment]
Accounts do have IDs but they are supposed to be an internal implementation detail that doesn't leak out of our APIs. I think I left it there because it was kind of handy when debugging, but I'll remove it.

**Comment by pscott31** [comment]
Though this is actually quite a bit more fiddly than I imagined as we re-use the protobuf type from core; so we either need to remove it from there (and I dunno if it is used), or copypasta it with that field missing and rejig the 7 places that use it in datanode protos
