### ISSUE TITLE
Support additional wallet connection preferences

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#6380]
I would be nice if we could save the users from connection reviews fatigue.

Today, when an third party application wants to connect to a wallet, we ask for the user approval.

Approving the connection every time can be tedious. We might want to let the user set the hostname as "always accept"-ed. We would be able to build a list of  allowed hostname.

We could also add an option to "always reject" a hostname, and build a list of blocked hostname.

This would shift the connection approval payload from 

`approved = true | false`

to

``` 
approvalMode = 
  always accept | 
  accept only this time |
  reject only this time |
  always reject
```

**Comment by barnabee** [comment]
What happens currently… I need to re-approve if I refresh the page? After a timeout? Both?

**Comment by ValentinTrinque** [comment]
> if I refresh the page? 

If the third party application managed to loose the token with the refresh, yes you will have to re-apprve and re-select the wallet.

> After a timeout?

We don't have timeouts for now. Will come later.

**Comment by barnabee** [comment]
Would be interested to see how Metamask et al. do it but it would seem like an approval for a site should persist, yeah.
