### ISSUE TITLE
Data node buffering when under very heavy load

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6470]
**Ticket to be refined**

Investigations are planned in order to better manage the number of events created in the core or how the datanode handles them. This is being conducted in:

- https://github.com/vegaprotocol/vega/issues/6440

We also need to investigate methods to be handle times when the constraints are reached and to have as little impact on the network and users as possible.

Current options may include rate limiting or graceful failing. @ettec may have some tools used during development that could aid in this.

@ettec here: there is a branch I wrote initially for snapshot recovery that has a file base buffering event source, I chose not to merge it when I moved snapshots to using Deltas as there is much less need for it when deltas are used.  however it is still available on this branch 5706-block-buffering  if we think we need to buffer

**Comment by ettec** [comment]
This  has been done, file buferring added already
