### ISSUE TITLE
Possible Nil pointer in core

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/vega#6471]
# Problem encountered
A possible nil-pointer dereference on this line: https://github.com/vegaprotocol/vega/blob/ee04ec87bf8c354cc14b0c66ab3005d0a63714df/core/events/ledger_movements.go#L44

**Comment by ze97286** [comment]
@zale144 is it? can e, or the FromAccount or ToAccount be nil? I don't think it can by construction. If either was nil, the construction of this LedgerMovement event would panic.

**Comment by zale144** [comment]
I think maybe through `TransferResponseEventFromStream`. I was manually sending events and it happened somehow. Better safe than sorry

**Comment by ze97286** [comment]
you're right, because it can be owner can be legitimately nil in case its system owner.

**Comment by ze97286** [comment]
why is it reopened?

**Comment by gordsport** [comment]
It's had a new PR linked to this issue. Reopens to flag work still ongoing, or, to discuss why work is still ongoing with this issue
