### ISSUE TITLE
Handle data sources properties

### ISSUE THREAD

**Issue by AnExsomnis** [vegaprotocol/vega#6483]
Different data sources will have different:
 - signer key encryption scheme
 - signer key length
 - name/type
 - be external/internal

Decide how to handle above differences when different types of sources are functioning in the system (or maybe along with ETH integration).
On low level serialization/deserialization steps we will need this information in order to interpret the signer.
Decide if a simple low level protocol of data serialization/deserialization of the signers is a good idea for handling the types.
Important: add documentation for describing it.

Discuss with @jeremyletang

**Comment by gordsport** [comment]
Closing as done / to be done with ethereum oracles
