### ISSUE TITLE
Error when querying for erc20WithdrawalApproval with invalid withdrawal ID

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6495]
Get an error when querying for erc20WithdrawalApproval with an invalid withdrawal ID

Note: Querying using a valid withdrawal ID returns correct data.

**Query with Invalid Withdrawal ID:**

```
query {
  erc20WithdrawalApproval (withdrawalId: "ABCD") {
    assetSource
    amount
    nonce
    signatures
  }
}
```

**Response:**

```
{
  "errors": [
    {
      "message": "rpc error: code = NotFound desc = NotFound error",
      "path": [
        "erc20WithdrawalApproval"
      ]
    }
  ],
  "data": {
    "erc20WithdrawalApproval": null
  }
}
```

**Query with Valid Withdrawal ID:**

```
query {
  erc20WithdrawalApproval (withdrawalId: "02e742808d36d1f71c5df376f9ec16b4da46aa513b9d536cf13ebeb01e075310") {
    assetSource
    amount
    nonce
    signatures
  }
}
```

**Response:**

```
{
  "data": {
    "erc20WithdrawalApproval": {
      "assetSource": "0x67175Da1D5e966e40D11c4B2519392B2058373de",
      "amount": "10000000000000000000",
      "nonce": "1665667110",
      "signatures": "0x2cd8ed3ccb3b978cf2c5508e692d96f65e62be049c697be1c1dd282d8aea01ae328ece401cf8cc7a5619103b03073e560d17e99ec017d64d0399b536b576cda1007b7b65090c96a31dcf0d49362628966bbc577250206cbb64ab42b285e7e692a11bfce36afaa538227b4150d8bb886badcba853ded2e5617f0446c856307371f201"
    }
  }
}
```

**Comment by guoguojin** [comment]
I believe this is expected behaviour. If you make a request for an ID that doesn't exist, then the API should return a `Not Found` error, should it not?

If you were to pass an invalid Hex ID for the Withdrawal ID, then you should get a different error along the lines of `Invalid Hex ID`.

For List APIs, we would not return an error if there is no data, only an empty list.

**Comment by MuthuVega** [comment]
Looks like this is the standard error when querying for data that doesn't exist. 
Closing ticket.
