### ISSUE TITLE
Snapshots: failure seen on stagnet1 pipeline

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#6563]
# Problem encountered
Snapshot failures are being seen on the stagnet1 snapshot-pipeline

We need to investigate and fix.

# Observed behaviour
Snapshots created after block ~40000 fall out of consensus with the following error:
```
[2022-10-21T10:34:00.773Z] 2022-10-21T10:34:00.603Z	ERROR	tendermint	v0/reactor.go:379	Error in validation	{"err": "wrong Block.Header.LastResultsHash.  Expected 2929F9ECA252194F20D5846E6DD23A4B69EEA006433A0A8993F0D0740C3C1D76, got 18E072A5DCBF652CED0043A929675258C5B243533EC043302B5001C48ED0B4BA"}
```

# Expected behaviour
All snapshots should work.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jeremyletang** [comment]
Not sure if this is relatedm, but I've had a very similar issue today, when trying to connect to a network running v0.59.0 with the v0.58.0 code, and this because we have migrated to the tendermint v0.34.22 I assumed. this might be related.
