### ISSUE TITLE
Order margin double counted in auctions

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#6569]
When calculating margin during auctions we calculate order margin via a call to:
https://github.com/vegaprotocol/vega/blob/44e1777f32b332502595ac8639f89341cb5b696b/core/risk/margins_calculation.go#L65

(should be ` e.calculateMargins(m, markPrice, rf, **false**, true)`) 

and then add the order margin calculated again (this time with a volume-weighted average price) a few lines down:
https://github.com/vegaprotocol/vega/blob/44e1777f32b332502595ac8639f89341cb5b696b/core/risk/margins_calculation.go#L75-L80

**Comment by gordsport** [comment]
Waiting for the following to be merged before scheduling:
- https://github.com/vegaprotocol/vega/issues/6496

**Comment by gordsport** [comment]
@witgaw 

Please can you check this bug still exists now the above has been merged?

**Comment by witgaw** [comment]
Yeah, it still exists (the above was just a blocker in a sense that'd there be a lot of merge issues if the two were worked on in parallel.
