### ISSUE TITLE
Staging1 Panic: duplicate key value violates unique constraint "79_64_orders_history_pkey"

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#6572]
# Problem encountered
failed to flush subscriber:failed to copy orders entries into database:ERROR: duplicate key value violates unique constraint "79_64_orders_history_pkey" (SQLSTATE 23505)

# Where
Stagnet1

# Release
v0.59.0

# Details
This happens after vega ran out of memory and is replaying the chain, which seems to happen very quickly. Full log attached. 
[n00.log.zip](https://github.com/vegaprotocol/vega/files/9843964/n00.log.zip)

**Comment by gordsport** [comment]
Along with linked PR this issue also requires the fix to be covered under issue:
- https://github.com/vegaprotocol/vega/issues/6601

**Comment by gordsport** [comment]
This is believed to be resolved in the linked issue and mentioned issue above - new ticket to be reopened if required
