### ISSUE TITLE
Fall back on indicative uncrossing price during opening auction for margin calculations

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#6576]
There's one case where we just supply mark price for margin calculation, this should provide a value that falls back on indicative uncrossing price if mark price is not available (and return zero if that's not available too):

https://github.com/vegaprotocol/vega/blob/44e1777f32b332502595ac8639f89341cb5b696b/core/execution/margin.go#L38

**Comment by gordsport** [comment]
Waiting for the following to be merged before scheduling:
- https://github.com/vegaprotocol/vega/issues/6496

**Comment by gordsport** [comment]
@witgaw 

Please can you check this bug still exists now the above has been merged?

**Comment by witgaw** [comment]
Yes, it still exists, the above was only blocking it but had nothing to do with fixing it. I remember about, but I'm still going through MTM frequency change related work at the moment.

**Comment by EVODelavega** [comment]
This is no longer the case. We now instead pass down the indicative price from `core/execution/liquidity_provision.go`, where we check:

```go
price := m.matching.GetIndicativePrice()
if price.IsZero() {
    price = m.getLastTradedPrice()
}
```

**Comment by witgaw** [comment]
This is fine now as @EVODelavega explained above, closing the issue.
