### ISSUE TITLE
Subscription to liquidity provision does not seem to work 

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/vega#6579]
# Problem encountered
Subscription to liquidity provision does not seem to work 

# Observed behaviour
Subscription to liquidity provision does not seem to work in testnet 0.58 whenever I do another LP submission or amendment. 

I am following other subscriptions as well (ex. I am also checking bond accounts via sub) and they do update. 

# Expected behaviour

I do expect to get some data for the following subscription. 
 https://api.n11.testnet.vega.xyz/graphql/

```gql
subscription LiquidityProvisionsUpdate {
  liquidityProvisions(
    partyId: "<your own pub key>"
    marketId: "b4d0a070f5cc73a7d53b23d6f63f8cb52e937ed65d2469a3af4cc1e80e155fcf"
  ) {
    commitmentAmount
    partyID
    createdAt
    updatedAt
    fee
    status
  }
}
```

# System response
Whenever I do the above sub it seems that it is hanging. 

![Screenshot 2022-10-24 at 10 54 08](https://user-images.githubusercontent.com/16125548/197506012-e05c0cbb-640e-4e7d-a333-26da3e15006e.png)

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Use sample API scripts to do an LP [subscription](https://github.com/vegaprotocol/sample-api-scripts/tree/master/submit-create-liquidity-provision) or [amendment](https://github.com/vegaprotocol/sample-api-scripts/tree/master/submit-amend-liquidity-provision)
2. For any of these markets:  https://console.fairground.wtf/markets, market ID can be found in the URL. Use your own pub key as party ID. 
3. Check if the above sub provides any updates. 

## Automation
Same as above. 

# Evidence
Screenshot above.

## Logs
No logs.

## Additional context
Add any other context about the problem here including; system version numbers and components affected.
0.58.0

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

Subscription updates. 

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jeremyletang** [comment]
Pushing to orgona trail stretch, this subscribtion might not even be needed, it is to be reviewed what subscribtion will stay.

**Comment by gordsport** [comment]
@MadalinaRaicu 
Can you confirm if this issue is still present or if this issue can be closed?

**Comment by wwestgarth** [comment]
May have been fixed by: https://github.com/vegaprotocol/vega/issues/7870
