### ISSUE TITLE
data-node: No such file or directory (SQLSTATE 58P01)

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#6591]
# Problem encountered
Data-Node stops after a couple of minutes of working.

# Observed behaviour
Data-Node startups work for a couple of minutes and then stop themselves.

# Expected behaviour
Data-Node should continue to work

# Evidence

## Logs
```bash
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]: 2022-10-24T21:04:05.493Z        ERROR        deHistory.snapshot        snapshot/service_create_snapshot.go:94        failed to snapshot data        {"error": "failed to copy table data:failed to execute copy copy (select * from stake_linking_current order by id) to '/home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/vega-devnet1-202210242046-600-currentstatesnapshot/stake_linking_current': ERROR: could not open file \"/home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/vega-devnet1-202210242046-600-currentstatesnapshot/stake_linking_current\" for writing: No such file or directory (SQLSTATE 58P01)"}
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]: panic: failed to snapshot data:failed to copy table data:failed to execute copy copy (select * from stake_linking_current order by id) to '/home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/vega-devnet1-202210242046-600-currentstatesnapshot/stake_linking_current': ERROR: could not open file "/home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/vega-devnet1-202210242046-600-currentstatesnapshot/stake_linking_current" for writing: No such file or directory (SQLSTATE 58P01)
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]: goroutine 12418 [running]:
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]: code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).createSnapshot.func5()
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/dehistory/snapshot/service_create_snapshot.go:96 +0x374
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]: created by code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).createSnapshot
Oct 24 21:04:05 n00.devnet1.vega.xyz visor[1318020]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/dehistory/snapshot/service_create_snapshot.go:90 +0xb2d
```

## Additional context
Three extra things:

1. Config: https://github.com/vegaprotocol/ansible/blob/master/roles/barenode/templates/datanode/config.toml.j2#L216-L217
2. Data-Node creates strange directory: `/home/vega/vega_home/state/data-node/dehistory/home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/` (note: `/home/...` is repeated)
3. The directory from the config exists and has good permissions (everyone can do everything):
```bash
$ sudo ls -lah /home/vega/vega_home/state/data-node/dehistory/snapshotsCopyTo/
total 8.0K
drwxrwxrwx 2 vega vega 4.0K Oct 24 21:22 .
drwxrwxrwx 6 vega vega 4.0K Oct 24 21:26 ..
```

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@fkondej 
I may have raised a duplicate issue for this:
- https://github.com/vegaprotocol/vega/issues/6593

Please can you check/confirm and I will close mine if required
