### ISSUE TITLE
Support filters in ordersConnection

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#6615]
# Feature Overview

**In order to** allow traders to better track orders
**We will** update the ordersConnection query and orders subscription
**So that** client applications can retrieved data in the correct order and with filters applied

# Acceptance Criteria

- [x] I can filter by one or more order statuses
- [ ] I can filter by one or more order types
- [ ] I can filter by one or more market ids
- [ ] I can filter by one or more order TIFs
- [ ] I can filter by liquidity order

### Additional information
Suggested query
```
ordersConnection(
  dateRange: { ... }
  pagination: { ... }
  filter: {
    status: [OrderStatus!]
    type: [OrderType!]
    marketId: [ID!]
    timeInForce: [OrderTimeInForce!]
    excludeLiquidity: Boolean
  }
) {
  edges { ... } 
}
```

**Comment by bglownia** [comment]
@mattrussell36 @guoguojin 
Regarding filter by market ids what we want to achieve is to give user possibility for filter by market name. 
It will be great if we can just pass market name keyword and then it will be changed to market Id's like `WHERE market_id IN (SELECT id FROM market WHERE name LIKE '%keyword%' ` or full text search if available. We can build this capability of changing keywords to matching market id's on FE, but it will be much easier to be done on database level

**Comment by guoguojin** [comment]
Regarding filtering by market name, it doesn't currently make sense with the existing ordersConnection APIs. ordersConnections are subqueries to market and parties, so other than ordersByReference, there is no direct query on orders. You must query for order via either a market or marketsConnection parent query, or a party or partiesConnection parent query.
