### ISSUE TITLE
Update risk parameters ranges

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#6630]
update risk parameters ranges:

risk aversion lambda: $10^{-8} \leq \lambda \leq 0.1$
tau: $10^{-8} \leq \tau \leq 1$
mu: $-10^{-6}\leq \mu \leq 10^{-6}$
r: $-1\leq r \leq 1$
sigma: $10^{-3} \leq \sigma \leq 100$

**Comment by davidsiska-vega** [comment]
Note that $r$ doesn't actually drive anything in the risk model.

**Comment by vega-paul** [comment]
@Jiajia-Cui Can someone update the spec please?
https://github.com/vegaprotocol/specs/blob/cf115fb002c34e90c929b2351cac3ec50969255e/protocol/0028-GOVE-governance.md

**Comment by ze97286** [comment]
@vega-paul I don't see why this bug needs to be open in *this* repo. There's clearly no issue here.
