### ISSUE TITLE
Datanode entities should copy values when converting to/from proto

### ISSUE THREAD

**Issue by EVODelavega** [vegaprotocol/vega#6637]
A number of entity types in the datanode/entities package are assigning raw pointers to certain fields, without cloning/copying the values. This can lead to bugs, and should be replaced with `DeepClone()` or copies of the values.

**Comment by ettec** [comment]
Datanode entities are not mutated after initial creation, whether that be when adding to the node or hydrating from the DB. Source proto objects are also never mutated in the datanode, so in the few cases where the entity holds a reference to a source proto (where it is stored as a jsonb type) holding a reference to the proto is acceptable and `DeepClone()` is not required.
