### ISSUE TITLE
data source no. of decimals to be stored in the data source definition

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6645]
The number of decimals on a data source is not currently stored in the data source definition ([as described here](https://github.com/vegaprotocol/specs/blob/master/protocol/0045-DSRC-data_sourcing.md#allowable-types)) it is stored in the  market definition.

To align with the specification we need to store the number of decimals on a data source in the data source definition.

**Comment by AnExsomnis** [comment]
Ref https://vegaprotocol.slack.com/archives/C8WS7M50E/p1667218490524629
