### ISSUE TITLE
Historic reward summary per epoch 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega#6650]
# Feature Overview

**In order to** provide an overview of the rewards earned 
**We will** provide a way to query reward types over a specified window of epochs
**So that** there is a way to accurately present aggregated reward information to the user

Example for an API that would facilitate this, not set in stone if this doesn't make sense data node side, but filtering by epoch would enable this really easily, as suggested by Phil.

```
query PartyRewards {
    party (id: 'foo') {
        rewards ( fromEpoch: 1, toEpoch: 10) {
           pagination // as normal
           edges {
                 asset
                 amount
                 rewardType
                 marketId
                 // ....ect/
              }
           }
        }
    }
}
```

# Background

Currently we cannot query reward types per epoch, only the last N rewards and therefore have no way to accurately present to the user the rewards they have earned per epoch.

<img width="1162" alt="Screenshot 2022-10-31 at 16 18 29" src="https://user-images.githubusercontent.com/46783148/199057816-8915afbf-2d76-4835-b90a-b75502548d31.png">

Implementing this solution with existing API would mean we take a risk on presenting an epoch with an incomplete data set - the totals could be wrong, and it's possible we miss out whole reward types as well as individual rewards - and we'd have no way of knowing it.

# Tasks
- [ ]
- [ ]

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.

- It is possible to

Acceptance Criteria and Feature Test Scenarios can, in some cases, be closely related. If acceptance criteria become fully covered by feature test scenarios they can be removed leaving on acceptance criteria that can't be directly or fully proven with tests.

# Test Scenarios
Detailed scenarios (1-3!) that can be executed as feature tests to verify that the feature has been implemented as expected. We use the follow format:

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/integration/) for more format information and examples.

# Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature. 

# Examples (optional)
Code snippets from the spec for reference

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by dexturr** [comment]
If we add an epoch summary and it is not a huge amount of work, adding totals for the amount the user has earnt to date would be nice. However if that would require work that would expand this scope of this ticket drastically then we can live without it :+1:

**Comment by ckpringle** [comment]
Currently blocking https://github.com/orgs/vegaprotocol/projects/110/views/45

**Comment by pscott31** [comment]
So you probably already figured you can get this information by doing e.g.

```graphql
{
  parties{
    rewards {
      asset {id}    
      amount
      rewardType
      epoch{id}
    }
  }
}
 ```

Which will give you every reward for every party on every epoch.. I'm not quite clear what extra functionality what you want on top of that? To be able to specify a particular epoch rather than get them all? if that's it then that is super easy - or do you want us to add some numbers up for you as well?

**Comment by gordsport** [comment]
Hey @ckpringle 
Its possible that this can be done already in GQL:

```
{
party(id: '1234567890'){
    id
    rewards{
        epoch{id}
        asset{name}
        amount
        }
    }
}
```
