### ISSUE TITLE
tradesConnection nested under party hangs

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#6668]
# Problem encountered
When querying for trades under a party the query hangs. Observed on https://api.n09.testnet.vega.xyz/graphql whilst other queries were working as normal

# Observed behaviour
query:
```
{
  party(id: "70d14a321e02e71992fd115563df765000ccc4775cbe71a0e2f9ff5a3b9dc680") {
    id
    tradesConnection(pagination: { first: 100 }) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

# Expected behaviour
Query returns first 100 trades

# System response
No response. Fetch request is left hanging

**Comment by vega-paul** [comment]
Can we ensure that alongside the fixing of this issue, some of our graphql system tests are adjusted to use pagination settings to provide some regular coverage.

**Comment by jeremyletang** [comment]
closed by https://github.com/vegaprotocol/vega/pull/6683
