### ISSUE TITLE
Add definition tables for numeric mappings in data-node v2 database 

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vega#6669]
Whilst exploring the database via SQL there are field values that use numeric references for Vega specific enums, it would be great to have a source of truth for these to join to either in memory, temp tables, or inserted as a table on db creation.

Currently a DB user has to go into the generated proto files and find the numeric mapping for the enum variable.

Note: This is a nice to have for those users exploring the data directly in Postgres clients.

**Comment by pscott31** [comment]
I think ideally we'd have all the enums mapped to postgres enums
