### ISSUE TITLE
Add route to Get a trade by ID in data-node v2 API

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/vega#6672]
- It is possible to list trades and list orders in the v2 datanode API (http://api.n10.testnet.vega.xyz/api/v2/trades & http://api.n10.testnet.vega.xyz/api/v2/orders). 
- It is possible to get a specific order by ID (http://api.n10.testnet.vega.xyz/api/v2/order/{order-id}).
- It is **not** possible to get a specific trade by ID.

Please can I request we add the route/request/response for a user to get a trade by ID similarly to the order by ID request route.

**Comment by jeremyletang** [comment]
@cdm  we didn't have this endpoint in v1 previously. we'll do with this for now unles we hit some absolute requirement for it.

**Comment by gordsport** [comment]
Closing as this data can be captured in other queries. Can reopen when it becomes a requirement
