### ISSUE TITLE
Margin allocation doesn't change after partial trade with limit orders

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#6675]
# Problem encountered
Margin balance updates correctly from 0 to a positive value when an order is placed.
If that order is partially filled, margin needs to be downsized, as per [MARA-005](https://github.com/vegaprotocol/specs/blob/master/protocol/0011-MARA-check_order_allocate_margin.md#0011-MARA-005), but it stays the same.

# Steps to reproduce
1. Place a limit order (GFN, GTC, GTT) after market is continuous and record the margin balance for trader
2. Partially fill the order and record the margin balance again.
3. Margin balances from steps 1 and 2 must be different.

## Automation
https://github.com/vegaprotocol/system-tests/pull/1381/files#diff-4264854593ad978a15a9a2c219a890981b7b8f83a04489c676a0e43830d73712R45

# Evidence
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/21295/tests

**Comment by RomanLeca** [comment]
second run with issues on **pegged GFN**
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/21364/tests

**Comment by gordsport** [comment]
@RomanLeca 

Can this be closed now based on:

https://github.com/vegaprotocol/specs/pull/1412#issuecomment-1316826655
