### ISSUE TITLE
Stake event lost (sandbox) when too few active validators

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vega#6694]
# Problem encountered
On a network where there aren't enough validators (2/3+1) to meet the minimum for consensus, a stake event was sent but never processed. 

Once the network had validators available, the transaction still wasn't processed. Unstaking and restaking was successful, though. 

The transaction should be processed once there are enough healthy consensus validators online.

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
We have updated the sandbox network to mitigate this happening
