### ISSUE TITLE
Announce node: Data node API should show pending validators in same epoch they're announced in

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vega#6696]
Currently, a prospective validator node is only shown by the API in the epoch following their "announcement". That means that, on the token site, a validator can't self stake right away, which can delay the whole process by a day in a 24-hour epoch network.

**Comment by candida-d** [comment]
duplicate of a ticket to come

**Comment by jeremyletang** [comment]
Correct @wwestgarth, there was confusion here.

**Comment by candida-d** [comment]
Yes, sorry @wwestgarth - reopening with the correct details!
