### ISSUE TITLE
Unable to start a new datanode using decentralised history

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6703]
Receive the below error when trying to start a new datanode by initialising the history data from decentralised history.

**Datanode Error:**

`failed to initialise datanode from decentralized history:failed to get most recent history segment from peers:failed to get most recent history segment:failed to get most recent history segment`

**Steps:**

Start a network with 2 nodes and a full node using vegacapsule
Let the network run and produce some blocks
The create another full node using vegacapsule
Set the flag - `AutoInitialiseFromDeHistory = true` for that datanode
Start the full node

**Comment by ettec** [comment]
fixed in : https://github.com/vegaprotocol/vega/pull/6714
