### ISSUE TITLE
Improve the UX on the  historic balances API 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6731]
During the use of the historic balances API  a number of [concerns](https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1667835994007459) have been raised about its UX.

This API needs to be reworked in order to be more user friendly to use.

Further details TBC

**Comment by jeremyletang** [comment]
For info, this ticket is really about hiding the internals of the accounts, e.g: the * and ! which internally refer to a system account or absence of market.
