### ISSUE TITLE
A governance proposal with `0` required participation passes with no votes in favour...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6747]
... and it shouldn't. 

If the required participation is `0` then at least one governance token must be voting in favour (and if there are more votes then the required majority rules must be met).

**Comment by jeremyletang** [comment]
Can we make the required participation minimum 1 instead of 0?

**Comment by davidsiska-vega** [comment]
The required participation is a fraction.

**Comment by jeremyletang** [comment]
> The required participation is a fraction.

ah true.
