### ISSUE TITLE
Implement CSV export for ledger movement

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#6754]
We need to implement a CSV export for ledger movement in the datanode.

Let's keep it simple at first, the datanode should provide a grpc + rest endpoint to retrieve a CSV file containing ALL ledger entry for a party.

The endpoint should take as parameters:
- 1 pubkey (required) - we will filter ledger entry with this pubkey as a from or to account
- 1 asset (required) - we will filter ledger entry for this specific asset
- start and end date (optional) - if not specified all ledger entries since all time matching the 2 previous required filters.

Let's not over optimised for now and do it on a blocking connection with large timeout? Later if we realise these takes too long to generate on the go, we can eventually do it asynchronously, but that might be unnecessary for now (may be wrong)

**Comment by AnExsomnis** [comment]
Reopening this issue because it needs to do the csv export from the core.
More context on this here: https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1678978421095099

**Comment by gordsport** [comment]
Closing and linked to the new issue:

- https://github.com/vegaprotocol/vega/issues/7859
