### ISSUE TITLE
`firstBlock` and `laskBlock` are always `0` in epoch data

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#6758]
# Problem encountered
Asking for epoch data for any epoch always has `0` for the first and last blocks in that epoch.

For example `https://api.devnet1.vega.xyz/api/v2/epoch?id=147`, where epoch 147 is in the past returns:
```
{
  "epoch": {
    "seq": "147",
    "timestamps": {
      "startTime": "1668000892108449000",
      "expiryTime": "1668000952108449000",
      "endTime": "1668000954596724000",
      "firstBlock": "0",
      "lastBlock": "0"
```

# Observed behaviour
first and last block in and epochs timestamps are always 0.

# Expected behaviour
They should be populated with the start/end block for the epoch.

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by ze97286** [comment]
is the core emitting this information in the epoch event?

**Comment by jeremyletang** [comment]
Just looked into that, we don't need the first and last block necessarily in the event, we can get the information on the data node by joining on the vega_time (start_time and end_time of the epoch) on the blocks table.
