### ISSUE TITLE
Receive errors when starting a new datanode using dehistory

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6781]
Received the below errors when starting a new datanode with dehistory.

**Error 1:**

`failed to initialise datanode from decentralized history:failed to fetch history blocks:failed to fetch history:could not get file with CID: context deadline exceeded`

**Jenkins Run:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/24906/

**Jenkins Error Log:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/24906/artifact/testnet/logs/testnet-nodeset-full-5-full/data-node-5.stderr-2022-11-11T10%3A45%3A46Z.log

**Error 2:**

`failed to initialise datanode from decentralized history:failed to find any active peer addresses`

**Jenkins Run:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/24835/

**Jenkins Error Log:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/24835/artifact/testnet/logs/testnet-nodeset-full-4-full/data-node-4.stderr-2022-11-10T22%3A46%3A42Z.log

**Comment by MuthuVega** [comment]
Another instance for **Error 2**

**Jenkins Run:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/318/testReport/junit/tests.datanode/datanode_test/Call_tests___network_infra_a_n___test_datanode_fetch_history_segments_into_datanode/

**Jenkins Error Log:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/318/artifact/system-tests-network_infra-a-n/testnet/logs/testnet-nodeset-full-6-full/data-node-6.stderr-2022-11-14T01%3A09%3A16Z.log

**Comment by ettec** [comment]
@MuthuVega did you add in the peer config as I suggested for this?
