### ISSUE TITLE
Replay in nullchain fails on trying to snapshot

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6792]
Running a replay in vega market sim. 
1. Set up vega market sim following README.md
2. Set vega version in .env to be `07e3753fe001243fa0b0c0e08dd240cb64032330` and run `make` to recompile the binary. 
3. Run `python ./vega_sim/replay/replay.py --retain_log_files  --dir` with the attached replay file here: 
[replay.zip](https://github.com/vegaprotocol/vega/files/9991130/replay.zip) (of course you'll have to unzip first). 
4. You should see the replay ending much too early with 
```
panic: failed to save snapshot to disk

goroutine 22844 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0xc0?, 0x1?, {0x1?, 0x0?, 0x0?})
        /Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.22.0/zapcore/entry.go:198 +0x7c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x1400fc29450, {0x140115619c0, 0x1, 0x1})
        /Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.22.0/zapcore/entry.go:264 +0x2ac
go.uber.org/zap.(*Logger).Panic(0x1400103c000?, {0x107002736?, 0x140021dd880?}, {0x140115619c0, 0x1, 0x1})
        /Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.22.0/logger.go:251 +0x54
code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow.func2()
        /Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/snapshot/engine.go:841 +0x10c
created by code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow
        /Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/snapshot/engine.go:851 +0xb08
```

**Comment by wwestgarth** [comment]
Note of things to do here:
- add an endpoint so the vega-sim can ask the nullchain for when its finished replaying
- cancel replay when `sigterm` is caught (it currently does not shutdown gracefully, and is why we try to save a snapshot after we've closed the snapshot-engine)
