### ISSUE TITLE
Run go-fuzzer

### ISSUE THREAD

**Issue by Vegaklaus** [vegaprotocol/vega#6793]
# Task Overview

In order to gain more confidence in the code, and avoid that bug-hunters can get easy bounties by running automated tools, run the nosy-neighbour scanner through the code that it can run in 

## Details
The fuzzer can be found at https://github.com/infosecual/nosy 
The license should be ok for use, but it would still be a good idea for legal to have a look at it.

The scanner can be pointed to the GitHub repository, and will then try to automatically perform fuzzing tests. 
- For some code, it will run pretty much automatically (there's some go-versioning conflict, which can be resolved manually)
- Other code has a naming conflict, which can be resolved comparatively easily 
- Some code does not work for yet unknown reasons.

@fkondej has done a short test run, and could resolve the first two issues.

The scanner needs significant resources (0.5% of the code took 1h on the test), so access to  an extra server will be required.
We do not know at this point how serious the issues are that the scanner will detect.  The two issues that have been found during the test are functions deliberately panicking if they get malformed input, which should not be reachable from the outside.  To evaluate the usefulness of the scanner (and to see how much work is worthwhile putting in in the future), we would need more alarms to see if any actual bugs are found. Also, the functions of most interest are the outward-facing ones (i.e., the functions parsing transactions); It needs to be verified if those are among the ones that the fuzzer can handle or the ones that it didn't manage to.

The scanner outputs detected issues while running, so the evaluation of the usefulness can be done in parallel to its execution; it is also possible to modify the order in which functions are scanned, and thus prioritise those with outside APIs.

If the fuzzer comes up with useful results, it would also make sense to run it on third party libraries.

**Comment by gordsport** [comment]
closing as this is now to be done in:
- https://github.com/vegaprotocol/system-tests/issues/2071
