### ISSUE TITLE
[cli wallet] 0.62.1 Command line validation of new market proposal failing with valid market

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6801]
# Description
With cli wallet 0.62.1 submitting to `fairground` (also 0.62.1) Submitting what **appears** to be a valid new market proposal with an internal oracle fails validation. @AnNiran recreated the JSON in a test as a go struct, and successfully passed it, which makes me think the unmarshalling might be incorrect?

# Expected output
Market proposal is submitted to a node.

# Actual output
```
✗ invalid request: proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_binding.trading_termination_property (is mismatching), 
proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_for_trading_termination.filters (is required),
proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_for_trading_termination.signers (is required)
```

# To recreate
1. Visit https://deploy-preview-384--vega-docusaurus.netlify.app/testnet/tutorials/proposals/new-market-proposal#templates-and-submitting
2. Switch to the `token dAPP (JSON)` field - that is the JSON that we will be submitting in step 5
3. Switch to the `Command line / OSX tab`
4. Switch the pubkey and wallet name for a pubkey/wallet you actually have in a wallet. It does not need any funds at this point.
5. Copy & Paste the command
6. Errors!

# Notes
- The JSON sample / annotated JSON / command line in the documentation preview linked above are generated by a script @edd wrote, which uses the Swagger files as a basis for generating the samples. It's entirely possible there's a mistake in there and not the validation. However @AnNiran checked and thinks it looks valid, and successfully run an equivalent go test that passes.

## Wallet version check
```
❯ ./vegawallet version
Software version:
v0.62.1

Git hash:
c2681f660f38e9058554b5b366acb70d33b8c6e9

Network compatibility:
- devnet:
  Unable to determine this network version:
  no healthy node available for version check
- fairground:
  This network is running the version v0.62.1
  Compatible.
- mainnet1:
  This network is running the version v0.53.0
  Incompatible.
- stagnet3:
  This network is running the version v0.63.0+dev.1410cc69.modified
  Incompatible.
```

**Comment by ze97286** [comment]
@edd I don't think it's the unmarshalling. The validation isn't quite right anymore because it's trying to verify that the data source has a filter matching the binding property which doesn't work for internal data source.
