### ISSUE TITLE
Support API token on the wallet service

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#6819]
An app can send an API token along with the request. We verify the app can use the token, and forward the request.

The configuration relies on a allowlist, instead of a block to ensure tight control, and avoid unanticipated access from an unreviewed hostname or chain-id. 

### Commands

```sh
# Generate a token
vega wallet api-token generate --passphrase-file <token-file-passphrase>

# Delete a token
vega wallet api-token delete --passphrase-file <token-file-passphrase> --force

# List all the registered tokens.
vega wallet api-token list --passphrase-file <token-file-passphrase>

# Describe the token
vega wallet api-token describe --passphrase-file <token-file-passphrase> --token <API_TOKEN>
```

### File structure

Living in an file `/wallet-service/tokens.json` encrypted with a passphrase:

```js
{
  "fileVersion": 1, // To plan for file format upgrade
  "tokensVerison": 1, // To plan for token format upgrade
  "resources": { // Set of reusable resources, that avoid duplication and ease updates.
    "wallets": {
      "mywallet1": "my_wallet_passphrase",
      "mywallet2": "my_wallet_passphrase",
    }
  },
  "tokens": { // The registered tokens
    "TOKEN_1": {
      "wallet": "mywallet2"
    },
    "TOKEN_2": {
      "wallet": "mywallet1"
    },
    "TOKEN_3": {
      "wallet": "mywallet2"
    }
  }
}
```

### Impact
- [ ] #6926
- [ ] #6927

### Verification
When loaded the file consistency should be checked.

**Comment by daniel1302** [comment]
Does it mean:

```
"approved": [
            "vega.xyz",
            "token.dapp"
          ]
```

we are going to rely on the `Host` header?

We need to pay attention that it can be prepared

**Comment by ValentinTrinque** [comment]
@daniel1302 More likely the `Origin` (or `Referer`, if the former is not enough) header.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by barnabee** [comment]
The hostnames approved only add any security when this is used from a browser, because the origin and referer are only not trivially forgeable when called from a browser. 

This will mostly used from scripts and apps that aren't browsers.

**Comment by ValentinTrinque** [comment]
Blocked by:
- #5967

Handling a long-living token is not compatible with the current internal implementation of the token management system. It needs to be updated to support it.
