### ISSUE TITLE
Snapshot: settlement engine position differ during SettleMTM

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#6831]
# Problem encountered
A snapshot failure was observed on fairground, and as always it comes with a long backstory.

We have a case where during `settlement.SettleMTM()` a party hits the following piece of code:
```
// we don't want to accidentally MTM a party who closed out completely when they open
// a new position at a later point, so remove if size == 0
if current.size == 0 && current.Buy() == 0 && current.Sell() == 0 {
	// broke this up into its own func for symmetry
	e.rmPosition(party)
}
```

and their position is removed from the settlement engine, _but still exists in the positions engine_.

We then take a snapshot, but we only snapshot the position engine. When we restore the market we naively push all restored positions into the settlement engine:
```
func (m *Market) PostRestore(ctx context.Context) error {
	m.settlement.Update(m.position.Positions())
```

which leads to a mismatch in restored state. The mismatch causes a consensus failure the next time a trade occurs and we enter `settlement.SettleMTM()` again. We make this call to `getCurrentPositions()`:
```
for _, evt := range positions {
	party := evt.Party()

	// get the current position, and all (if any) position changes because of trades
	current := e.getCurrentPosition(party, evt)
```

For the node that _hasn't restored_ and _doesn't_ have a position for the party in the settlement engine, this call creates a position with the updated post-trade position from the positions engine and we do nothing:
```
if !hasTraded && current.price.EQ(markPrice) {
	// no changes in position and markPrice hasn't changed -> nothing needs to be marked
	continue
}
```

for the node that has restored from a snapshot, `getCurrentPosition()` returns the old position we just pushed in from the positions engine, which has different price and then we go an calculate a mtm-share. Accounts then differ, consensus failure panic.

An obvious fix would be to save in the snapshot which positions weren't in the settlement engine and to not restore them, but first I want to be sure that getting in a state where we have a position in the positions engine, but not in the settlement engine is expected.

# Observed behaviour
A clear and concise description of how the system is behaving.

# Expected behaviour

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by ze97286** [comment]
can we instead use a single source of positions? (the position engine)
