### ISSUE TITLE
Incorrect AggregatedLedgerEntries type

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#6844]
Two things here: 

- `transferType` is `String` when it should be `TransferType`.
- `AggregatedLedgerEntries` should be de-pluralized to `AggregatedLedgerEntry`

**Comment by mattrussell36** [comment]
LedgerEntry `type` field is still a string when it should be `TransferType`. Additionally there appear to be missing transfer types in the schema

**Comment by jeremyletang** [comment]
It’s been merge on develop just maybe not deployed on the env you are using
