### ISSUE TITLE
V2 API GetOrder returns garbage object response when requesting order and invalid version Id

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6846]
System test to reproduce

test_amend_price_active_and_parked_orders_in_trading

Previous to the bug, when the library function runs
request=api.trd_v2.GetOrderRequest(order_id=orderId, version=ver)
api.grpc_stub_trd_data_v2.GetOrder(request)
It returns an empty object and we detect that and assume the last valid response is the latest version

Now it always returns 
```
order {
  price: "0"
  created_at: -6795364578871345152
  expires_at: -6795364578871345152
  updated_at: -6795364578871345152
}
```

And therefore we can no longer detect an empty response and assume end of searching by version.

Expecting empty response from GetOrder when no data found for order/ver

**Comment by guoguojin** [comment]
I think this has already been resolved, looking at the code, when the instrument is not found, an error and a null is returned. I added a test to my PR for the ordersConnection to make sure that is the case. I will do some additional testing and if I'm correct, I'll close this issue with my ordersConnection PR.

**Comment by vega-paul** [comment]
https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/360/testReport/tests.matching_engine/continuous_trading_test/Call_tests___full_g_n___test_amend_price_active_and_parked_orders_in_trading/
