### ISSUE TITLE
more on gas and priority

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#6853]
# Feature Overview

Apply recent changes to max gas spec:
1. Add network param for network.transactions.minBlockCapacity 
2. Update the formulas to use minBlockCapacity
3. Update the cancel order to match spec
4. Calculate tx priority as per the spec

https://github.com/vegaprotocol/specs/blob/master/protocol/0079-TGAP-transaction_gas_and_priority.md

**Comment by davidsiska-vega** [comment]
I've merged https://github.com/vegaprotocol/specs/pull/1397 .
