### ISSUE TITLE
Error when starting a datanode from dehistory

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6893]
Receive the below error when trying to start a new datanode from dehistory.

**failed to initialise datanode from decentralized history:failed to find any active peer addresses**

This error is happening pretty consistently, please see below for Jenkins build.

Its the node 5 which fails all the time and needs looking into.

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28530/

Jenkins Error:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28530/artifact/testnet/logs/testnet-nodeset-full-5-full/data-node-5.stderr-2022-11-22T01%3A16%3A55Z.log/*view*/

Additional Jenkins Runs with the same failure:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28520/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28506/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28501/

**Comment by ettec** [comment]
@Phil is mid change on this see thread https://vegaprotocol.slack.com/archives/C04B3P9KKV3/p1669110689687199
