### ISSUE TITLE
Incorrect behaviour when MID reference price is outside the price monitoring bounds

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#6904]
According to [038-OLIQ](https://github.com/vegaprotocol/specs/blob/master/protocol/0038-OLIQ-liquidity_provision_order_type.md):

> Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module (the min/max price that would not trigger the price monitoring auction per triggers configured in the market, see [price monitoring](https://github.com/vegaprotocol/specs/blob/master/protocol/0032-PRIM-price_monitoring.md#view-from-quant-library-side) spec for details) it should get shifted to the valid price that's furthest away from the mid for the given order-book side. **If the reference price itself is outside the valid price range the order should get placed at - when bid/ask is used as a reference, or one tick away from it - when mid is used as a reference.**

The price monitoring bit works fine in isolation, the reference price outside bounds bit works fine when BID/ASK is used as a references however when MID is used as a reference and:
1. MID is above the max valid price bound the sell side is deployed as expected, however the buy side gets placed at the lower valid price range bound,
1. MID is below the min valid price bound the buy side is deployed as expected, however the sell side gets placed at the upper valid price range bound.

See https://github.com/vegaprotocol/vega/pull/6902/files for details (test passes now, but associated comments point at the problems)

**Comment by jeremyletang** [comment]
Discussed with @witgaw the behavour of the core is correct. Specs may needs some changes to makes them clearer.
