### ISSUE TITLE
Tool to fuzz inputs into core to see checkTx is coping

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6922]
# Task Overview

**In order to** build confidence that an accidentally or deliberately malformed transaction doesn't knock a node over
**We will** build tools for generating fuzzed protobuf inputs 
**So that** we can incorporate those into our testing framework and environments

# Task

As a start have a look at https://github.com/trailofbits/protofuzz - we may or may not want to use this (not up to me). 

We should set it up so that we can send random inputs to every transaction that can go into core. 

# Acceptance Criteria
How do we know when this technical task is complete:
- We have a tool that can send transactions with random / fuzzed inputs into core. 
- The transactions should all be rejected (unless the randomness number generator gets extremely lucky) 

**Before Merging**

Probably not a tool that should / needs to live in core. Up to core to decide where it should go.

**Comment by davidsiska-vega** [comment]
Related by separate: https://github.com/vegaprotocol/vega/issues/6793

**Comment by gordsport** [comment]
Closing as now replaced with:

https://github.com/vegaprotocol/system-tests/issues/2071
