### ISSUE TITLE
Tool to fuzz inputs that make it past checkTx

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6923]
Similar to https://github.com/vegaprotocol/vega/issues/6922 

but we want to `pubKey` and signature to be valid so that the random transaction can make it past `checkTx` and into core. We should set it up so that we can send random inputs to every transaction that can go into core. 

Again https://github.com/trailofbits/protofuzz could be a starting point; but a search to see what other tools exist may be a good idea. @Vegaklaus can be consulted for libraries / strategies. 

As part of this, we may want to make sure that we log any errors / warnings core generates when this is used against it even if there is no outright crash.

**Comment by gordsport** [comment]
Closing as now replaced with:

https://github.com/vegaprotocol/system-tests/issues/2071
