### ISSUE TITLE
non-existent party placing orders on a non-existent market after a restart

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6930]
# Problem encountered
After stagnet 3 was reset it has been observed in block explorer that a non-existent party placing orders on a non-existent market. 

Party ID: `47836c253520d2661bf5bed6339c0de08fd02cf5d4db0efee3b4373f20c7d278`

TX in block explorer
![image (1)](https://user-images.githubusercontent.com/83510148/203797543-a9007ca8-b501-43dd-a73d-09e76d7b8d4b.png)

# Expected behaviour
It is expected that these orders should be rejected before being added to a block.

## Additional context
Reported issue [here](https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1669229219790519) with the following info:

```
curl 'https://api.stagnet3.vega.xyz/graphql' -X POST -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: application/json, multipart/mixed' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://api.stagnet3.vega.xyz/graphql/' -H 'content-type: application/json' -H 'Origin: https://api.stagnet3.vega.xyz' -H 'DNT: 1' -H 'Alt-Used: api.stagnet3.vega.xyz' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '{"query":"{\n  party(id:\"47836c253520d2661bf5bed6339c0de08fd02cf5d4db0efee3b4373f20c7d278\") {\n    id\n  }\n}"}'
```

```
{"errors":[{"message":"no resource corresponding to this id","path":["party"],"extensions":{"code":5,"type":"NotFound"}}],"data":{"party":null}}
```

```
curl 'https://be.stagnet3.vega.xyz/rest/transactions/E670C972FF65556F59731590B913872D8E21636D4CB3A876A93F86810D26A1F9' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'Origin: http://localhost:3000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site'
```

```
{
  "transaction": {
    "block": "272118",
    "index": 0,
    "hash": "E670C972FF65556F59731590B913872D8E21636D4CB3A876A93F86810D26A1F9",
    "submitter": "47836c253520d2661bf5bed6339c0de08fd02cf5d4db0efee3b4373f20c7d278",
    "type": "Submit Order",
    "code": 70,
    "cursor": "272118.0",
    "command": {
      "nonce": "14938675305933262200",
      "blockHeight": "272117",
      "orderSubmission": {
        "marketId": "ca7768f6de84bf86a21bbb6b0109d9659c81917b0e0339b2c262566c9b581a15",
        "price": "",
        "size": "1",
        "side": "SIDE_BUY",
        "timeInForce": "TIME_IN_FORCE_IOC",
        "expiresAt": "0",
        "type": "TYPE_MARKET",
        "reference": "",
        "peggedOrder": null
      }
    },
    "signature": {
      "value": "5e04e5fec010872bfc3ea13e288ea37f23ddf6a0eb47e9d9500ebd58806636bdd1c084c6669bed2d1b5e2684720f1c5058bdddf1d1b0719c73e5eff736b55d0f",
      "algo": "vega/ed25519",
      "version": 1
    }
  }
}
```

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by wwestgarth** [comment]
I don't know about the original of the bot sending these transactions in, but for this bit `It is expected that these orders should be rejected before being added to a block.` I don't think this is true.

We have [a system test for an AC](https://github.com/vegaprotocol/system-tests/blob/develop/tests/wallet/vegawallet_test.py#L1434) that flexes it, the expected (pre-cosmic-elevator) outcome is for the order to make it into the block but for a tx-error event to be emitted with a `party does not exist` string. The idea is that for now the proof-of-work is enough.

**Comment by gordsport** [comment]
Closing as this is not a bug and expected behaviour for Alpha Mainnet as per the above comment.
