### ISSUE TITLE
Received ORDER_ERROR_INSUFFICIENT_ASSET_BALANCE instead of ORDER_ERROR_MISSING_GENERAL_ACCOUNT

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vega#6951]
# Problem encountered
The system is raising this error ORDER_ERROR_INSUFFICIENT_ASSET_BALANCE instead of ORDER_ERROR_MISSING_GENERAL_ACCOUNT

# Expected behaviour
Trying to test: https://github.com/vegaprotocol/specs/blob/master/protocol/0024-OSTA-order_status.md#0024-OSTA-028
After doing these steps I was expecting to the the missing general account error.
`Create market1 with asset1
Create asset2
Create party with asset2 (deposit=1, asset_to_deposit=asset2)
Create order with party for market1`

# Steps to reproduce
`Create market1 with asset1
Create asset2
Create party with asset2 (deposit=1, asset_to_deposit=asset2)
Create order with party for market1`

## Automation
`@pytest.mark.full
@pytest.mark.orderstatus
def test_missing_general_account(context):
    """
    Order reason of "ORDER_ERROR_MISSING_GENERAL_ACCOUNT"
    user does not have a general account with the asset required for the market (0024-OSTA-028)
    """
    traders_wo_general_account = marketsTrading.traders(context, count=1, asset_to_deposit='dummy_asset', deposit_amount=1, trader_type='trader_wo_general_account')
    trader_wo_general_account = traders_wo_general_account[0]

    tr1 = context['order_status_traders'][0]

    market_id = context['order_status_market']
    ordersMod.reset_market(context, market_id, traders=tr1, state_reqd='TRADING_MODE_CONTINUOUS')

    wallet_response = ordersMod.limit_order_submit(context=context, market=market_id,
                                                   side='Buy', price=1000, trader=trader_wo_general_account,
                                                   tforce='GTC', size=10, ord_ref='not_enough_asset_balance',
                                                   confirm_order=True)
    assert 'not_enough_asset_balance' in wallet_response
    ordersMod.find_and_verify_order_event(context,
                                          market=market_id,
                                          trader=tr1,
                                          size=10,
                                          price=1000,
                                          status="Rejected",
                                          reason='ORDER_ERROR_INSUFFICIENT_ASSET_BALANCE',
                                          ordRef='not_enough_asset_balance',
                                          tforce='GTC',
                                          ordtype="Limit")`

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by davidsiska-vega** [comment]
My suggestion is to remove the AC: https://github.com/vegaprotocol/specs/pull/1487/files and then the core work is simply to get rid of the error message `ORDER_ERROR_MISSING_GENERAL_ACCOUNT` if it's indeed never triggered (which I think is the case but may be wrong).
