### ISSUE TITLE
getting wallet exception instead of an order rejection reason

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vega#6967]
# Problem encountered
getting a wallet exception instead of a order rejection reason for the following cases:
spec: https://github.com/vegaprotocol/specs/blob/master/protocol/0024-OSTA-order_status.md

# Observed behaviour
ORDER_ERROR_INVALID_TYPE vs assert 'order_submission.time_in_force' and 'is required' in wallet_response
ORDER_ERROR_INVALID_MARKET_ID vs assert 'order_submission.market_id' and 'should be a valid vega ID' in wallet_response
ORDER_ERROR_MUST_BE_LIMIT_ORDER vs assert 'is expected to be an order of type LIMIT when the order is pegged' in wallet_response
ORDER_ERROR_MUST_BE_GTT_OR_GTC vs assert 'is expected to have a time in force of type GTT, GTC or GFN when the order is pegged' in wallet_response
ORDER_ERROR_WITHOUT_REFERENCE_PRICE vs assert 'order_submission.pegged_order.reference' and 'is required' in wallet_response
ORDER_ERROR_BUY_CANNOT_REFERENCE_BEST_ASK_PRICE vs assert 'order_submission.pegged_order.reference' and 'cannot have a reference of type BEST_ASK when on BUY side' in wallet_response
ORDER_ERROR_SELL_CANNOT_REFERENCE_BEST_BID_PRICE vs assert 'order_submission.pegged_order.reference' and 'cannot have a reference of type ' + reference_type + ' when on ' + error_side + ' side' in wallet_response
ORDER_ERROR_OFFSET_MUST_BE_GREATER_THAN_ZERO vs assert 'order_submission.pegged_order.offset' and 'must be positive' in wallet_response

# Expected behaviour
maybe we should update the specs ?

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by ValentinTrinque** [comment]
This issue is unclear. Closing.
