### ISSUE TITLE
No updates coming from the liquidity provision subscription 

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/vega#6969]
# Problem encountered & Observed behaviour
No updates coming from the liquidity provision subscription. Seems stuck in iGQL

# Expected behaviour
I would expect to get updated data from the following subscription

```gql
subscription LiquidityProvisionsUpdate($marketId: ID) {
  liquidityProvisions(marketId: $marketId) {
    id
    partyID
    createdAt
    updatedAt
    marketID
    commitmentAmount
    fee
    status
  }
}
```

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Go to https://api.n11.testnet.vega.xyz/graphql/
2. Run

```gql
subscription LiquidityProvisionsUpdate {
  liquidityProvisions(
    marketId: "325dfa07e1be5192376616241d23b4d71740fe712e298130bfd35d27738f1ce4"
  ) {
    id
    partyID
    createdAt
    updatedAt
    marketID
    commitmentAmount
    fee
    status
  }
}
```

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/16125548/204357748-03f7616c-a860-4901-8ca5-8ee600f36dd4.png">

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
This endpoint will be removed
