### ISSUE TITLE
Balances and Ledger Entries don't always sum

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/vega#6973]
The sum of ledger entries in and out of a given account in a given block should always exactly equal the difference between the balance of the account at the end of that block, and the previous balance of that account. 

Here's an SQL query that takes quite a long time to run but which will return no rows if that is true:

```sql
with ledger_in as (select account_to_id as account_id, vega_time, -quantity as quantity from ledger),
     ledger_out as (select account_from_id as account_id, vega_time, quantity from ledger),
     ledger_both as (select * from ledger_in union all select * from ledger_out),
     ledger_summed as (select vega_time, account_id, sum(quantity) as ledger_sum from ledger_both group by vega_time, account_id),
     balance_deltas as (select vega_time, account_id, balance - lag(balance,1,0) over (partition by account_id order by vega_time) as balance_delta from balances),
     joined as (select coalesce(l.vega_time, b.vega_time) as vega_time,
                       coalesce(l.account_id, b.account_id) as account_id,
                       l.ledger_sum,
                       b.balance_delta
                  from ledger_summed l
                       full outer join balance_deltas b
                       on l.vega_time=b.vega_time and l.account_id=b.account_id)
     select * from joined where ledger_sum != balance_delta;
```

When run on a small network, e.g. from the system tests, it is.

However I ran this on testnet the other day across ~30million ledger entries, there were ~300 blocks where this was not true. Investigate why. Maybe

- core not sending / sending incorrect ledger entries or balances
- datanode not handling them all correctly
- maybe it's all OK and there is a problem with above SQL query
- some other sort of fun

**Comment by EVODelavega** [comment]
Deposits, the accounts with negative delta's are external system accounts for deposits, the ledger delta's are negative as a result, the amount being the sum of each asset deposited to vega accounts.
