### ISSUE TITLE
Make the wallet service network agnostic

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vega#6978]
# Feature Overview

Currently the wallet service accepts requests only for a certain network. Ideally, we want it to be able to serve different networks without having to be restarted when the user switches networks. This would render switching networks / having an active network redundant in the wallet. 

## Specs

(raw copy from @barnabee 's message on slack)
- I have wallets and keys and for each I can select what network(s) they should work on / I generate them specifically for a network
- When I connect an app it includes a network ID and creates a link or "connection" between the dapp and the wallet representing the connection from that app to a specific network ID, and any keys I have approved (which must be keys I have in the wallet set to work for / generated for that network ID)
- An single dapp app can therefore have connections to many networks, each with a set of associated keys it has access to.
- The dapp then sends a transaction for signing with any valid combination of connection (network) and pubkey
- Nobody ever has to "switch" in the wallet, the wallet just chekcs the connection (network ID) and pubkey are valid and approved by the user, asks for an unlock password if needed, and dipslays the txn for approval (with a network name and logo very prominently)

# Acceptance Criteria

- i can connect to the wallet app from different dApps on different networks, without having to restart the wallet service
- i can send requests to the wallet with specifying my dApp's network chain ID, the wallet would be able to determine if it can serve the request based on the available imported networks and their current chain ID.
- when i generate a key, i can select which network i want to generate it for

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by barnabee** [comment]
My message was a bit of a brain dump from my experience. I would like to see some decent thought and user / UX input on this before we actually embark on doing it.
