### ISSUE TITLE
Wallet doesn't increase the PoW difficulty as it should

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7000]
It has [been seen](https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1669885572659819) that parties can be banned from submitting TXs and is related to the PoW difficulty not being increased in the wallet.

`2022-12-01 08:33:52.404 ERROR 802745 --- [TaskScheduler-1] com.vega.protocol.api.VegaApiClient      : {"error":"party is banned from sending transactions"} `

We need the wallet to submit correct PoW proofs - if it doesn’t the party gets banned for a number of epochs which would significantly impact any LP that is running a bot.

**Comment by ValentinTrinque** [comment]
We need feedback from the research team before we can address this issue

**Comment by gordsport** [comment]
Waiting for this spec issue to be defined before we can start:

- https://github.com/vegaprotocol/specs/pull/1449

**Comment by ValentinTrinque** [comment]
Depends on:
- https://github.com/vegaprotocol/vega/issues/7114
