### ISSUE TITLE
markPrice doesn't update when market is settled, even after MTM time has passed

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#7001]
# Problem encountered
Mark price needs to be updated when settling the market according to PFUT-011

# Observed behaviour
According to the event stream, I have a `markPrice` field on a settled market that expects to be updated at `nextMarkToMarket`  which is later than `timestamp` of when stream says market is settled. This makes the test that covers
_Once a market is finally settled, the mark price is equal to the settlement data and this is exposed on event bus and market data APIs ([0016-PFUT-011](https://github.com/vegaprotocol/specs/blob/master/protocol/0016-PFUT-product_builtin_future.md#0016-PFUT-011))_
to fail, because I’m currently asserting the settlement value against `markPrice` which is not updated yet (`nextMarkToMarket` > `timestamp`)
**EVENT BUS:**
{"id":"9349-5",
   "block":"BB08A6A84EB082E81B166468E044F470B18EB4CAEB280A285B2F3C07EE7750E0",
   "type":"BUS_EVENT_TYPE_MARKET_DATA",
   "marketData":{
      **"markPrice":"100000000",**
      "market":"5a629fd6a4e8aad340c45b13af428119ed1d47e631addc70da1eb89197a71859",
      "**timestamp**":"1669825893732730000",
      "marketState":"STATE_SETTLED",
      "**nextMarkToMarket**":"1669825897033133000",
      "**lastTradedPrice**":"123400000"
   }
}
The correct price for settlement is visible on `lastTradedPrice` field.

The problem is this is the **last** markPrice in graphQL long after nextMarkToMarket has been reached.
        {
          "node": {
            "id": "5a629fd6a4e8aad340c45b13af428119ed1d47e631addc70da1eb89197a71859",
            "state": "STATE_SETTLED",
            "data": {
              "nextMarkToMarket": "2022-11-30T16:31:37.033133Z",
              "timestamp": "2022-11-30T16:31:33.73273Z",
              **"markPrice": "100000000"**
            }
          }
        }

**Comment by EVODelavega** [comment]
This issue should be fixed already
