### ISSUE TITLE
Error received during starting datanode - failed to initialise datanode from decentralized history

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7007]
Running against the below branches:

vega - `dehistory-failed-to-get-analysis`
vegacapsule - `add-swarm-key-support`
systemtests - `fix_datanpode_swarmkey_config`

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31721/

Error Received:

failed to initialise datanode from decentralized history:failed to fetch history blocks:failed to fetch history:could not get file with CID, connected peer addresses ,/ip4/127.0.0.1/tcp/4055,/ip4/127.0.0.1/tcp/4045,/ip4/127.0.0.1/tcp/4025,/ip4/127.0.0.1/tcp/4035,/ip4/127.0.0.1/tcp/4065,/ip4/10.100.0.79/tcp/4085,/ip4/127.0.0.1/tcp/4085: context deadline exceeded

Jenkins Error Link:

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31721/artifact/testnet/logs/testnet-nodeset-full-7-full/data-node-7.stderr-2022-12-01T13%3A42%3A14Z.log/*view*/

**Comment by ettec** [comment]
This is fixed, upping the initliase time out sorted this.

**Comment by MuthuVega** [comment]
Ran against the dev branches, the error rate has definitely gone down.
However, the tests failing now aren't writing any related logs , so not too sure if they are the same issue or different.

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/32859/
Failing Test
[https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/32859/testReport/junit[…]ode_test/test_datanode_history_segments_are_deterministic/](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/32859/testReport/junit/tests.datanode/datanode_test/test_datanode_history_segments_are_deterministic/)

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/32861/
Failing Test
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/32861/testReport/junit/tests.rewards/trading_rewards_test/test_graphql_queries/

**Comment by ettec** [comment]
as discussed  (https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1670338798758389?thread_ts=1670337150.321639&cid=C02KVKMAE82) missing logs is due to test timing out before the context timeout.  Have agreed to alter system test to reduce the timeout and handle datanode restart if it does not initialise in a reasonable time

**Comment by gordsport** [comment]
This has been resolved with the increase in the timeout for the test
