### ISSUE TITLE
Ledger entries showing reward for maker fees paid as stake reward - Fairground

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#7012]
## Description

Ledger entries on Fairground console is indicating that` reward for maker fees paid`, filled that reward pool, is `stake reward`.
Trade on https://console.fairground.wtf/#/markets/e9ec6d5c46a7e7bcabf9ba7a893fa5a5eeeec08b731f06f7a6eb7bf0e605b829

## Steps to Reproduce

1. Go to https://console.fairground.wtf/#/markets/e9ec6d5c46a7e7bcabf9ba7a893fa5a5eeeec08b731f06f7a6eb7bf0e605b829
2. Get the asset and put at least one market trade
3. Wait until the epoch is over
4. Check portfolio ledger entries - https://console.fairground.wtf/#/portfolio
 

## Expected behavior

Should be indicated as reward from maker fees paid reward pool
Run the query below on https://api.n12.testnet.vega.xyz/graphql/
`query accountbalance {
  party(id: "476fc2843ba2d64aa1c73a1e1b7215843f581cf4d6c8f46587b12b37e27cc8fa") {
    accounts {
      type
      balance
      asset {
        id
        name
      }
    }
    rewards {
      rewardType
      receivedAt
      amount
      percentageOfTotal
      asset {
        name
      }
    }
  }
}`

Should give result similar to
`      "rewards": [
        {
          "rewardType": "ACCOUNT_TYPE_REWARD_MAKER_PAID_FEES",
          "receivedAt": "2022-11-29T11:47:14.183846Z",
          "amount": "136805029218921419896",
          "percentageOfTotal": "21.61552810051279",
          "asset": {
            "name": "TAKer"
          }
        }
      ]`

## Screenshots

<img width="682" alt="Screenshot 2022-11-29 at 13 32 56" src="https://user-images.githubusercontent.com/100769129/204589948-73f93b38-aa0d-4830-9148-79c76a888891.png">
<img width="1424" alt="Screenshot 2022-11-29 at 13 19 46" src="https://user-images.githubusercontent.com/100769129/204589966-0dd8d45e-8741-4584-b899-13e1fe3b9d57.png">

- OS: macOS
- Browser Chrome
- Version v0.62.1 Fairground

**Comment by ze97286** [comment]
@cdm would you mind if instead of adding more resolution to the transfer type we actually name it for what it is which is TRANSFER_TYPE_REWARD_PAYOUT rather than TRANSFER_TYPE_STAKE_REWARD which it not necessarily is?
