### ISSUE TITLE
Dehistory: datanode snapshots become out of sync with core after netparam change

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#7026]
# Problem encountered

When the network parameter `snapshot.interval.length` is changed, the snapshots taken by core and the datanode become out of sync and occur at different block heights.

We can see this in the logs on any CI run that hits the snapshot tests:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/32434/pipeline

Core takes snapshots at heights: `988, 1040, 1092, 1128, 1148`
Datanode takes snapshots at heights: `988, 1040, 1092, 1120, 1140`

# Observed behaviour
After changing the network parameter `snapshot.interval.length` the snapshots taken by core and datanode become out of sync

# Expected behaviour
That a core node and a datanode take snapshots at the same block-heights.

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by ze97286** [comment]
would it be better if the core emits an event on a snapshot block rather than trying to infer the block from the interval?

**Comment by wwestgarth** [comment]
note: https://github.com/vegaprotocol/vega/issues/7098
