### ISSUE TITLE
Dehistory: having an RPC endpoint that dumps data to a target path on the host is not a good idea - lets remove it

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#7029]
# UPDATE:
The `FetchDeHistorySegment` endpoint is still at risk being exposed, as it is possible to make any data node download arbitrary content onto their machine.

Add similar functionality as core so `FetchDeHistorySegment` is behind an admin endpoint

# Problem encountered
We seem to have this RPC endpoint to the datanode:

```
// Copy history segment data to a target file
    rpc CopyHistorySegmentToFile(CopyHistorySegmentToFileRequest) returns (CopyHistorySegmentToFileResponse);
```

which tells the datanode to copy a segment to an arbitrary location on the host machine. This is not secure for a publically exposed endpoint.

Fetching is not as bad, but still similar in that it is a activity that should be performed _only by the node operator_ but it is exposed in a public API.
```
// Fetch a history segment from another peer in the network
    rpc FetchDeHistorySegment(FetchDeHistorySegmentRequest) returns (FetchDeHistorySegmentResponse);
```

# Observed behaviour
Why does this endpoint exist?

# Expected behaviour
An endpoint like this should not exist.

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
We should expose this on the admin endpoint (if does not exists we should create one)

**Comment by gordsport** [comment]
Add similar functionality as core so `FetchDeHistorySegment` is and admin endpoint

**Comment by ettec** [comment]
if we add the admin endpoint, could we put the dump command back?  its potentially useful if we start to see divergence of segments on some random environment
