### ISSUE TITLE
Remove deprecated `vegawallet info`

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7069]
Depends on:
- https://github.com/vegaprotocol/vega/issues/7068

- [ ] vegawallet info -> vegawallet describe

For version 0.65

**Comment by daniel1302** [comment]
There is one change required in the vegacapsule: https://github.com/vegaprotocol/vegacapsule/blob/fa41d89dc586f66d6977bc0a92ab73bedcda6bd6/generator/vega/commands.go#L84
