### ISSUE TITLE
Dehistory: fetch command hanging when trying to fetch invalid history segment

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7077]
The fetch command when used to fetch an invalid / non existant history segment hangs and doesn't return an error message.

**Example:**
```

./vega datanode dehistory fetch QmQracbu28pi44Cn5JN1eKahMyoy1AYuLiBXDwYj4W1AE8 208 --home /Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/data-node/node3
fetching history for segment id:QmQracbu28pi44Cn5JN1eKahMyoy1AYuLiBXDwYj4W1AE8




```

**Expected:** 

The timeout value in the config for the fetch command must kick in and the command should return an error message if its unable to fetch the segment within the timeout.

Command hanging in Jenkins:

![Screenshot 2022-12-07 at 16 20 12 (2)](https://user-images.githubusercontent.com/91467655/206233530-e84637d2-094a-4cb6-a27a-baa606612081.png)

**Jenkins Run:**

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/33509/

System Tests Branch - `feat_dehistory_tests_5`
System Tests Marker - `dehistory_fetch_hanging`

**Comment by ettec** [comment]
The fetch **command** doesn't have a timeout, that is intentional, user can control-c.    The fetch when doing auto initialise does timeout.
