### ISSUE TITLE
add event for snapshots so we know when its being created / finished

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7098]
### Issue reported:

In the [PR 5535](https://github.com/vegaprotocol/vega/pull/5535#issuecomment-1175961239) the following was raised:
 
I think we are going to have to be careful more careful with which snapshots are sent/accepted when state-syncing. For example if someone if running an old version of core and state-syncs against a network with a newer version it'll just get handed a snapshot and it will just try to use it. We'll want to put something in to reject any snapshots from different versions.

#### Additional information:

https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1670585146077249

## Suggested change:

Add an event on snapshot so data node does not have to work out when the snapshot is taking itself.

**Comment by jeremyletang** [comment]
Also, create an API so future node runner, could call existing nodes and get the list of existing snapshots.

**Comment by gordsport** [comment]
this has been completed
