### ISSUE TITLE
Expose spam protection per users details

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#7114]
Implement an endpoint in the core.proto server to expose per users spam information.
This needs to be implemented as forwarding the endpoint to the core node from the datanode as is done with the others endpoint in this service.

### inputs
- one required party id.

### outputs
- pow infos
- state of all spam protections for the user

**Comment by gordsport** [comment]
Additional internal context: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1670837995450059

**Comment by ValentinTrinque** [comment]
Once done, we can consume this in the wallet:
- https://github.com/vegaprotocol/vega/issues/7000

**Comment by ze97286** [comment]
@ValentinTrinque ok, I think there's some confusion here. This ticket has nothing to do with #7000 which depends on nothing but itself. 

Given the remainder of the slack discussion on this topic do we even need to do this? what for?

**Comment by gordsport** [comment]
At a minimum we need to explain in simple terms in the documentation how to avoid getting banned (in normal operation).

If that cant be done we need to implement this (some functionality to improve UX around spam/banning)

Ideal state (later work):

Users are warned that they will be banned soon via the CLI/APIs, they could bypass this using `--force`
