### ISSUE TITLE
Loading dehistory into datanode will fail if the database user does not have superuser permission

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#7121]
Loading dehistory into datanode will fail if the database user does not have superuser permission.  

The code does this:

`killAllConnectionsQuery := fmt.Sprintf(
		`SELECT
	pg_terminate_backend(pg_stat_activity.pid)
		FROM
	pg_stat_activity
		WHERE
	pg_stat_activity.datname = '%s'
	AND pid <> pg_backend_pid();`, connConfig.Database)`

pg_terminate_backend required superuser permissions.  Without this there is a risk that the load will fail due to resources being held by other connections.  However it may be a better approach to attempt this, log it and if it fails continue to try to load anyway

@jeremyletang I can't recall the exact scenario in which not doing this was an issue, I think it was because originally database was being wiped by doing a drop/create db, now its using goose to wipe the db, so maybe this could be removed.  Note the user will still need the replication role as we use `SET session_replication_role = replica;` to diabled triggers during load.

**Comment by guoguojin** [comment]
`SET session_replication_role = replica;` can only be done by a user with superuser privileges in Postgres 14. Postgres 15 allows a regular user with the appropriate set permission to set session_replication_role, however at this time TimescaleDB does not officially support Postgres 15.

For now, as we need to be able to set the replication role to disable triggers when loading data, the database user for the data-node will need to be one with superuser privileges.

Additional roles that need to be granted in the future if running as a regular user are:

`pg_write_server_files` - for using the copy command when creating snapshots
`pg_signal_backend` - for closing existing connections when loading data
