### ISSUE TITLE
triggeringRatio does not update correctly over GRPC and gQL

### ISSUE THREAD

**Issue by RomanLeca** [vegaprotocol/vega#7171]
# Problem encountered
When proposing a market with a float value (e.g. **0.3**) for triggeringRatio, the proposal passes, but the outcome value is **0.0** over GRPC and **0** over gQL

# Test run here
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/36675/tests

**Comment by jeremyletang** [comment]
Also shouldn't triggeringRatio be a string here instread of a float in the proto?
