### ISSUE TITLE
Dehistory: Error when fetching history segment

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7196]
Received the below error when trying to retrieve the history segments from a datanode.

**Error message:**

```
E1221 02:27:34.513341611  167495 backup_poller.cc:136]                 Run client channel backup poller: UNKNOWN:pollset_work {created_time:"2022-12-21T02:27:34.513211505+00:00", children:[UNKNOWN:Bad file descriptor {created_time:"2022-12-21T02:27:34.513174908+00:00", errno:9, os_error:"Bad file descriptor", syscall:"epoll_wait"}]}
```

Have seen this error twice in a span of 2 days , however this error doesn't happen all the time and is difficult to reproduce consistently.

Jenkins Logs for latest occurrence:

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/37309/consoleText

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/37309/testReport/junit/tests.datanode/datanode_test/test_datanode_restore_from_dehistory/

Jenkins Logs for previous occurrence:

https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/470/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_restore_from_dehistory/

**Comment by ettec** [comment]
This error in the IPFS layer possibly implies a closed network connection, however given the intermittency of this and the fact that if it occurs the impact is minimal, I think we should deprioritise to low at least.
