### ISSUE TITLE
Memory leak in Wallet V2

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/vega#7250]
# Problem encountered
While using the vega wallet V2 in one of the bots, after a couple of minutes the memory usage of the bot went up to 3GB.

# Observed behaviour
Since the bots started using wallet V2, the memory usage went up significantly, in particular in traderbot.

# Expected behaviour
The bots memory usage should be in the range of 25-45MB

# Evidence
With `BuildRoundRobinSelectorWithRetryingNodes`:
<img width="1218" alt="Screenshot 2023-01-05 at 12 13 34" src="https://user-images.githubusercontent.com/20242145/210777782-0a1a19d6-4a96-431d-b5e6-6cf4524f30ac.png">
With caching the node connections:
<img width="653" alt="Screenshot 2023-01-05 at 12 19 51" src="https://user-images.githubusercontent.com/20242145/210779080-391d6cd4-040b-40c1-9a85-fc998fb1991d.png">

# Steps to reproduce
Call any method that acquires a node connection, such as `SignTransaction` 

## Additional context
The bug is likely here: https://github.com/vegaprotocol/vega/blob/9feefa371528630cf8a766c555ff69bfd7f74f9a/wallet/api/node/builder.go#L12
where on each endpoint method call all of the nodes are constructed, eventually calling `grpc.Dial`, and it doesn't seem like those connections are closed at any point.

**Comment by ValentinTrinque** [comment]
The memory leak happens when the resources returned by the round-robbin selector builder are not free'd, by calling `Stop()`. The current implementation assumes the responsibility of releasing the resources belongs to the component providing the builder.

This way it's possible to handle the management of the node selector to the upper layers as follow:

```go
// We keep track 
nodeSelectors := map[string]api.NodeSelector{}

nodeSelectorBuilder := func(hosts []string, retries uint64) (node.Selector, error) {
    // This hash is used to determine if we already have a node selector for this setup.
    hostHash := hash(hosts)

    ns, alreadyBuilt := nodeSelectors[hostHash]
    if alreadyBuilt {
        return ns, nil
    }

    nodeSelector, err := node.BuildRoundRobinSelectorWithRetryingNodes(hosts, retries)
    if err != nil {
        return nil, err
   }

   // We keep track of the nodeSelector for future use.
   nodeSelectors[hostHash] = nodeSelector

   return nodeSelector, nil
}

handler := api.NewAdminSendTransaction(...., nodeSelectorBuilder)

response, err := handler.Handle(...)

// Close the node selectors when exiting the program, or whenever we see fit
for _, ns := range nodeSelectors {
    ns.Stop()
}
```

**Comment by ValentinTrinque** [comment]
Quick note: This is not an ideal implementation, but this methods exists primarily for one time / temporary sending.

If you are drifting away for that use case, consider using the service with a long-living token instead.
