### ISSUE TITLE
Rename dehistory

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7255]
To open a discussion on this before Alpha Mainnet as changing now would be much less complex than changing after the next mainnet deployment happens.

Does dehistory imply that we are removing history, for example "deprioritising" something would remove it. 

I wanted to open this up as a team discussion to make sure that this name is both clear to the project team but also to contributors in the future

**Comment by candida-d** [comment]
IMO, yes. Dehistory isn't an intuitive shorthand for decentralised history, and I don't think it would help anyone understand what the feature provides. In docs I will avoid at all costs describing it as "dehistory".

**Comment by jeremyletang** [comment]
> IMO, yes. Dehistory isn't an intuitive shorthand for decentralised history, and I don't think it would help anyone understand what the feature provides. In docs I will avoid at all costs describing it as "dehistory".

agreed, it is much confusing.

**Comment by pscott31** [comment]
What about DistHist ?

**Comment by pscott31** [comment]
Or maybe just dhistory

**Comment by wwestgarth** [comment]
Or `shared-history` then we don't need to shorten anything its already just two syllables

**Comment by ettec** [comment]
the abbreviation to 'dehistory' is not ideal (me being a lazy typist), but I think the name 'decentralised history' best captures what it is.  So I suggest just update the command and config to not use the abbreivation, the cmd line will be used very infrequently so not a big deal if the user has to type a few more chars.

**Comment by ettec** [comment]
This is how the spec describes the requirement:

 Historical data must be available to load into the datanode and must not be dependent on any centralized entity.

So decentralized history fits best IMO

**Comment by ettec** [comment]
> IMO, yes. Dehistory isn't an intuitive shorthand for decentralised history, and I don't think it would help anyone understand what the feature provides. In docs I will very much avoid describing it as "dehistory".

agree, in the Readme its also refererred to as decentralized history,  (apart from where config or cmd lines are mentioned)

**Comment by wwestgarth** [comment]
> This is how the spec describes the requirement:
> 
> Historical data must be available to load into the datanode and must not be dependent on any centralized entity.
> 
> So decentralized history fits best IMO

Its a bit of a mouthful and decentrallisation is almost a implied given the nature of everything we do. Maybe we can just call is `history`, and in the docs explaining it and its use of IPFS explain that its decentralised.

**Comment by jeremyletang** [comment]
> > This is how the spec describes the requirement:
> > Historical data must be available to load into the datanode and must not be dependent on any centralized entity.
> > So decentralized history fits best IMO
> 
> Its a bit of a mouthful and decentralization is almost a implied given the nature of everything we do. Maybe we can just call is `history`, and in the docs explaining it and its use of IPFS explain that its decentralized.

Agreed with that. history would be just fine. I mean IPFS is not called DEFS or DEIPFS, still we get what it is. I'm in favor of droping the `de` prefix and not adding event `shared` or `decentralised`, just call it history.

**Comment by ettec** [comment]
> > > This is how the spec describes the requirement:
> > > Historical data must be available to load into the datanode and must not be dependent on any centralized entity.
> > > So decentralized history fits best IMO
> > 
> > 
> > Its a bit of a mouthful and decentralization is almost a implied given the nature of everything we do. Maybe we can just call is `history`, and in the docs explaining it and its use of IPFS explain that its decentralized.
> 
> Agreed with that. history would be just fine. I mean IPFS is not called DEFS or DEIPFS, still we get what it is. I'm in favor of droping the `de` prefix and not adding event `shared` or `decentralised`, just call it history.

True, but IPFS means 'Inter-Planetary File System' - so the clues in the name already, adding decentralized would not make sense in this case.  However datanode has history in its tables and decentralised history which are different things.   I think distincition from this and clarity of definition is important when we have conversations on this and also for understanding mechanics of datanode, 'its a mouthful' doesn't really matter tbh, its akin to saying we should call or variables x,y etc, who cares if it takes a second more to pronounce or type it aids discussion and comprehension.

**Comment by wwestgarth** [comment]
> > > > This is how the spec describes the requirement:
> > > > Historical data must be available to load into the datanode and must not be dependent on any centralized entity.
> > > > So decentralized history fits best IMO
> > > 
> > > 
> > > Its a bit of a mouthful and decentralization is almost a implied given the nature of everything we do. Maybe we can just call is `history`, and in the docs explaining it and its use of IPFS explain that its decentralized.
> > 
> > 
> > Agreed with that. history would be just fine. I mean IPFS is not called DEFS or DEIPFS, still we get what it is. I'm in favor of droping the `de` prefix and not adding event `shared` or `decentralised`, just call it history.
> 
> True, but IPFS means 'Inter-Planetary File System' - so the clues in the name already, adding decentralized would not make sense in this case. However datanode has history in its tables and decentralised history which are different things. I think distincition from this and clarity of definition is important when we have conversations on this and also for understanding mechanics of datanode, 'its a mouthful' doesn't really matter tbh, its akin to saying we should call variables x,y etc, who cares if it takes a second more to pronounce or type if it aids discussion and comprehension.

I don't think "Inter-Planetary" is a synonym for "decentralised". You can have a private IPFS network and then its centralized. So whereas IPFS _allows_ for decentralization, it is not true that every IPFS network in decentralized.

And the same is true for vega. Testnet is centralized with datanodes which you can pull centralized history. Even in mainnet if the history segment you are pulling only exists on one datanode, or all the datanodes are operated by the same person, it is not decentralized content.

So I don't think we should use the word decentralized, because thats an aretfact of the network and its operators, and not inherit to the code itself.

**Comment by ettec** [comment]
Definition thing - but if production of the history segments and supply of those segments does not depend on anyone (or subset of) a set of nodes in the network (as it does not) it is IMO decentralized.  And regardless of the exact word we do need to distinguish between a datanodes decentalized history and normal history.
