### ISSUE TITLE
Update Tendermint as TendermintCore will soon be an archive repo

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7268]
## Issue:

As per https://github.com/tendermint/tendermint/issues/9972 TendermintCore is going to be an archive repo. 

Informal systems has a fork of Tendermint and looks to be getting funding to develop this when the original is archived. This issue use the Informal version of Tendermint

**Comment by 08d2** [comment]
The linked issue is clearly infeasible and should not be taken seriously.

**Comment by jeremyletang** [comment]
> The linked issue is clearly infeasible and should not be taken seriously.

?
