### ISSUE TITLE
Account History in console not showing fees (stagnet1 v0.66.0)

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#7274]
## Description

The fees "Infrastructure, Maker, Liquidity" does not appear in account history.

## Steps to Reproduce

1. Go to https://stagnet1.console.vega.xyz/#/portfolio
2. Make a few trades on a market
3. Click on Any of the fees (Infrastructure, Maker, Liquidity)

## Expected behavior

Fees history should be shown.

## Screenshots

<img width="1305" alt="Screenshot 2023-01-06 at 13 57 14" src="https://user-images.githubusercontent.com/100769129/211019320-b43a3664-b6fd-4b0a-b554-425c79aa1749.png">
<img width="1305" alt="Screenshot 2023-01-06 at 13 56 57" src="https://user-images.githubusercontent.com/100769129/211019328-ffd9604b-8363-4f3f-bac0-d3aef5672b87.png">

## Device details

- OS: macos
- Browser Chrome
- Version Vega v0.66.0

**Comment by pscott31** [comment]
OK so I don't understand what this account type is actually for, but I noticed that the only party that has accounts of this type is the `network` party and there is only one per market. 

```
data_node_db=# select party_id, market_id from accounts where type=7;
 party_id |                             market_id
----------+--------------------------------------------------------------------
 \x03     | \xeda61c9948ae97182c344b6a900e960a6c85271a4db1926eb26c82d847d9ba78
 \x03     | \x02cd091cae47c43eff726412e4945c09a04c8641ef863862d70217cc149fdd10
 \x03     | \x2bf3cab7a239f34f40145a0700f8f12bc504bd2ec3a65d5915c4e58881dfcb52
 \x03     | \x86948f946a64e14bb2e284f825cd46879d1cb581ce405cc62e4f74fcded190d3
 \x03     | \x954410d873a6d1a419b8a11e7e3a5178f65b976f3140bb78fc97d21daf08877f
 \x03     | \xab7fd1e94472b0d6b37b2b0780ffe6a8688c81846aa5798743297db179c4f760
 \x03     | \x14719259af09239e479c107c6a69dbdae05dbde619ad06632af27a2fc2c9a9c7
 \x03     | \x3fed7242cce2cbe7df8cc3a2808969fc6e108f2047838c4af323c10430dfe041
(8 rows)
```

So I think individual parties do not have accounts of this type. I had a quick look in the ledger for trades involving these accounts:
```
data_node_db=# select account_from_id, account_to_id, type from ledger where account_from_id in (select id from accounts where type=7) limit 3;
                          account_from_id                           |                           account_to_id                            |              type
--------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------
 \x453ef38515a18caa14660e1aad5ef4bb1c701b24bbe6977440e109d9945f973f | \x48d6857c6f88c6a9b17e0fe50dced80e40d9d908018350e6e8481f3a0c628f57 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x453ef38515a18caa14660e1aad5ef4bb1c701b24bbe6977440e109d9945f973f | \x48d6857c6f88c6a9b17e0fe50dced80e40d9d908018350e6e8481f3a0c628f57 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x453ef38515a18caa14660e1aad5ef4bb1c701b24bbe6977440e109d9945f973f | \x344e728ed3ae1da6a32e842caf501f6dbe90cb22ec26362ac0f01a3a383d50c8 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
(3 rows)
```

And so it looks like when fees are paid they come _from_ an account with ACCOUNT_TYPE_FEES_MAKER and into a **general** account:
```
data_node_db=# select party_id, a.type as to_account_type, l.type as transfer_type from ledger l join accounts a on a.id=l.account_to_id  where account_from_id in (select id from accounts where type=7) limit 5;
                              party_id                              | to_account_type |          transfer_type
--------------------------------------------------------------------+-----------------+---------------------------------
 \x2f19d514966e7d7a69a8f010c249a57823a15f2ed37d36c0d7b8a3ea165a07e6 |               4 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x2f19d514966e7d7a69a8f010c249a57823a15f2ed37d36c0d7b8a3ea165a07e6 |               4 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x18e4006f08d2cdbcb3b90150f77f102656720f6b8acf7303ee6ea33641bf1c27 |               4 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x18e4006f08d2cdbcb3b90150f77f102656720f6b8acf7303ee6ea33641bf1c27 |               4 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
 \x18e4006f08d2cdbcb3b90150f77f102656720f6b8acf7303ee6ea33641bf1c27 |               4 | TRANSFER_TYPE_MAKER_FEE_RECEIVE
(5 rows)
```

So I don't think the data node is doing anything wrong here. If you put 'network' as the party in your query you see answers.

**Comment by jeremyletang** [comment]
the maker_fee account is just an account where fees are callected before they get paid to the parties @pscott31

**Comment by pscott31** [comment]
Yea I figured :)

**Comment by pscott31** [comment]
OK So I'm closing this is it's NotABug(tm) - only the network party has accounts like ACCOUNT_TYPE_FEES_MAKER and they are used as the _from_ account when paying rewards (with the _to_ account being a parties' general account).

So it doesn't make any sense to look at balance changes on accounts with this type, unless you want to see what is in the network's internal accounts for some reason.

If it is required that we want to see fees of certain types being paid into users' accounts, we'd have to look at ledger entries and filter them on _from_ account type, and sum those. TFE are going to remove them from the drop-down of account types to inspect balances on.
