### ISSUE TITLE
GraphQL: dataSourceSpec spec status is incorrectly formatted

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7281]
# Problem encountered
A field in the DataSourceSpec type does not return data in the format that the schema says it will.

https://github.com/vegaprotocol/vega/blob/41eaddcbea3367c138cd1cd8a039646d40b78b3c/datanode/gateway/graphql/schema.graphql#L1365

Says it will return one of the values from

https://github.com/vegaprotocol/vega/blob/41eaddcbea3367c138cd1cd8a039646d40b78b3c/datanode/gateway/graphql/schema.graphql#L1382-L1391

Instead it returns `"1"`

# Steps to reproduce

```graphql
query OracleSpecs {
  oracleSpecsConnection {
    edges {
      node {
        dataSourceSpec {
          spec {
            status
          }
        }
      }
    }
  }
}
```
# Tasks
- [ ] Fix mapping so that an enum value is returned

# Note
- Only explorer is using this field, and it's not doing anything useful with it so this is not high priority
- `{ markets { state } }` is an example of a field that is similar but maps correctly (see https://github.com/vegaprotocol/vega/blob/41eaddcbea3367c138cd1cd8a039646d40b78b3c/datanode/gateway/graphql/schema.graphql#L1715)

**Comment by jeremyletang** [comment]
for info @guoguojin @AnExsomnis it would seem that the enum is just not mapped in the gqlgen.yml file like others (the marshaller has been implemented though).
