### ISSUE TITLE
When the market parameter triggeringRatio for an existing market is updated via governance, the next time conditions for entering auction are evaluated, the new triggering ratio is applied

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7300]
When the market parameter triggeringRatio for an existing market is updated via governance, the next time conditions for entering auction are evaluated, the new triggering ratio is applied. ([0035-LIQM-010](https://github.com/vegaprotocol/specs/blob/master/protocol/0035-LIQM-liquidity_monitoring.md#0035-LIQM-010))

A test was written to cover this and has been passing

tests.network_parameters.test_network_parameters.test_market_triggering_ratio_update_affects_auction_entry

Now failing on the full run since 
https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/533/#showFailuresLink

We have totalstake at 3905000000000000000000000
and
"updateNetworkParameter":{"changes":{"key":"market.liquidity.targetstake.triggering.ratio","value":"1"}}}

market data shows
"targetStake":"14100332250000000000000000","suppliedStake":"3905000000000000000000000"

market status expected to move to STATE_SUSPENDED but remains STATUS_ACTIVE as
The liquidity monitoring auction is triggered when total_stake < c_1 x target_stake

**Comment by jeremyletang** [comment]
Not a bug.
