### ISSUE TITLE
Unable to submit additional txns greater than param value spam.pow.numberOfTxPerBlock

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7311]
**Spec Ref:**
https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md

**AC:**
For a given block, a user is able to submit more than spam.pow.numberOfTxPerBlock transactions with only spam.pow.difficulty zeros by tying them to one or more historic blocks all of which are within spam.pow.numberOfPastBlocks blocks ([0072-SPPW-010](https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md#0072-SPPW-010))

Trying to test the above AC but unable to submit more that the specified number of transactions in network param `spam.pow.numberOfTxPerBlock` by trying the proof of work to different blocks.

**Scenario:**
spam.pow.numberOfTxPerBlock = 3
spam.pow.increaseDifficulty = 0

Try and submit 9 orders for a user in a single block , BUT use different historic blocks for the PoW for every 3 transactions.

**Expected Result:**
Expect all 9 orders to be submitted successfully

**Observed Result:**
Only 3 orders are successfully submitted and for others receive error `failed to verify proof of work`

Jenkins Runs:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/40635/testReport/junit/tests.spam/spam_protection_ban_test/test_submit_transactions_in_same_block_with_increased_difficulty_accepted_Use_Different_Historic_Block_/

Jenkins Logs:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/40635/consoleText

System Tests Branch - **feat_additinal_spam_pow_tests**
System Test Name - **test_submit_transactions_in_same_block_with_increased_difficulty_accepted**
System Tests Marker - **spam_new_tests**

**Comment by wwestgarth** [comment]
I think theres an issue in the test. You have the loop which changes the block height:
```
`elif scenario == "Use_Different_Historic_Block":`
```

but then ultimately when we get to the loop which sends in the txn they are just using a static block height:
```
for i in range(order_range):
                input_data, input_data_serialised = Wallet.prepare_transaction_to_submit(context=settings.context,
                                                                                         block_height=block_height, <--- here
                                                                                         chain_id=chain_id,
                                                                                         txn_type_to_prepare="ORDER",
                                                                                         order_ref=order_reference+str(i))
```
and so the proof-of-work will be wrong in three cases because it will verify with the wrong block-hash?

**Comment by MuthuVega** [comment]
Thx a ton @wwestgarth , will amend and test
