### ISSUE TITLE
User NOT banned when using a blockheight older than spam.pow.numberOfPastBlocks

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7322]
Spec Ref:
https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md

AC:
Using a block older than spam.pow.numberOfPastBlocks blocks prior to the current block is detected and leads to a temporary banning of the account ([0072-SPPW-011](https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md#0072-SPPW-011))

Scenario:
Submit transactions using proof of work generated by using a block height older than the network param spam.pow.numberOfPastBlocks

Expected Behaviour:
Using older block is detected and the user is banned.

Observed Scenario:
The older block is detected and a response as below is received.
`data: "unknown block height for tx:77d2e3f686a99f637bf43c9fb2c01030105fc24c9ad827c20ed176dc16d3f175, command:Submit Order, party:00d1cf1788f91ad17a89086ecae992ea3fb683ebe0bad918795abe16e2de152c"`

These transactions are NEVER added to the block and the user is NOT banned.

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/41197/

Jenkins Logs:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/41197/consoleText

System Tests Branch - feat_additinal_spam_pow_tests
System Tests Marker - spam_new_tests

**Comment by davidsiska-vega** [comment]
I think if the POW is for a block that's too old then the transaction shouldn't be included in a block but the party shouldn't get banned. 

If the mempool is full and network is busy then the submitter has no control of how many blocks will come before their transaction goes in. 

So the behaviour 
> These transactions are NEVER added to the block and the user is NOT banned. 
seems sensible to me and it's [0072-SPPW-011](https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md#0072-SPPW-011)) which I think we may want to re-work. @Vegaklaus comments?

**Comment by Vegaklaus** [comment]
Agree, banning is essentially for abusing the Tendermint API issues we have to sneak past the rejection mechanisms; in this case the transaction will be safely rejected, so banning isn't necessary

**Comment by gordsport** [comment]
Closing as `wontfix` in core and the spec to be updated in:

- https://github.com/vegaprotocol/specs/issues/1522
