### ISSUE TITLE
Add undocumented methods to wallet openrpc

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vega#7328]
The following methods are undocumented in the wallet's openrpc.json:

- `admin.delete_api_token`
- `admin.describe_api_token`
- `admin.generate_api_token`
- `admin.list_api_tokens`
- `admin.update_passphrase`
- `client.get_permissions`
- `client.request_permissions`

**Comment by ValentinTrinque** [comment]
- `client.request_permissions`
- `client.get_permissions`

these doesn't exist anymore

**Comment by ValentinTrinque** [comment]
The endpoints on `admin.*_api_token` don't exist on the API because the token is implementation specific.
