### ISSUE TITLE
Segment creation should use pre-allocated connection to prevent failure due to external process consuming all connections

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#7336]
Segment creation should use pre-allocated connection to prevent failure due to external process consuming all connections

Currently history segment creation creates a connection for the lifetime of the segment creation, this is problematic if an external process is using the postgres instance (should we even allow this? things could go wrong in very unexpected ways perhaps have dedicated instance(s) for this sort of stuff?) and consumes all available connections, at this point the segment creation will fail as it will not be able to create a connection.

**Comment by jeremyletang** [comment]
We should probably reserve some connection all the time for: writing and segment saving, and another pool just for the read?

**Comment by ettec** [comment]
> We should probably reserve some connection all the time for: writing and segment saving, and another pool just for the read?

yeah - we have seperate connection for writing, and a pool for reading already, we will have a seperate connection for these just for segment creation
