### ISSUE TITLE
Discrepancies in data retention policies applied on datanode

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7350]
The data retention values from the configs aren't applied correctly for all applicable hypertables in the config.
The config lists 18 tables BUT not all of them have got retention policy applied on the database.

Some of the data retention policies state that the retention is applied for table `_materialized_hypertable_3` , `_materialized_hypertable_7` etc. Not too sure what these tables are.

Below is the list of data retention config form the datanode config:

**Data retention configs:**

`[{'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'balances'}, {'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'checkpoints'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'conflated_balances'}, {'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'delegations'}, {'DataRetentionPeriod': '6 months', 'HypertableOrCaggName': 'ledger'}, {'DataRetentionPeriod': '1 month', 'HypertableOrCaggName': 'orders'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'trades'}, {'DataRetentionPeriod': '1 month', 'HypertableOrCaggName': 'trades_candle_1_minute'}, {'DataRetentionPeriod': '1 month', 'HypertableOrCaggName': 'trades_candle_5_minutes'}, {'DataRetentionPeriod': '1 month', 'HypertableOrCaggName': 'trades_candle_15_minutes'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'trades_candle_1_hour'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'trades_candle_6_hours'}, {'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'market_data'}, {'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'margin_levels'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'conflated_margin_levels'}, {'DataRetentionPeriod': '7 days', 'HypertableOrCaggName': 'positions'}, {'DataRetentionPeriod': '1 year', 'HypertableOrCaggName': 'conflated_positions'}, {'DataRetentionPeriod': '1 day', 'HypertableOrCaggName': 'liquidity_provisions'}]`

**Query to retrieve the data retention policies applied in the database:**

`SELECT schedule_interval, config, hypertable_name FROM timescaledb_information.jobs WHERE timescaledb_information.jobs.proc_name = 'policy_retention'
`

**Data retention policies applied in the Database:**

`[(datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 2}, 'balances'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 3}, '_materialized_hypertable_3'), (datetime.timedelta(days=1), {'drop_after': '6 mons', 'hypertable_id': 4}, 'ledger'), (datetime.timedelta(days=1), {'drop_after': '1 mon', 'hypertable_id': 5}, 'orders'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 6}, 'trades'), (datetime.timedelta(days=1), {'drop_after': '1 mon', 'hypertable_id': 7}, '_materialized_hypertable_7'), (datetime.timedelta(days=1), {'drop_after': '1 mon', 'hypertable_id': 8}, '_materialized_hypertable_8'), (datetime.timedelta(days=1), {'drop_after': '1 mon', 'hypertable_id': 9}, '_materialized_hypertable_9'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 10}, '_materialized_hypertable_10'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 11}, '_materialized_hypertable_11'), (datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 13}, 'market_data'), (datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 14}, 'delegations'), (datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 18}, 'margin_levels'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 19}, '_materialized_hypertable_19'), (datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 20}, 'checkpoints'), (datetime.timedelta(days=1), {'drop_after': '7 days', 'hypertable_id': 21}, 'positions'), (datetime.timedelta(days=1), {'drop_after': '1 year', 'hypertable_id': 22}, '_materialized_hypertable_22'), (datetime.timedelta(days=1), {'drop_after': '1 day', 'hypertable_id': 23}, 'liquidity_provisions')]`

**Comment by ettec** [comment]
hi, in this case those materialized hypertables will be related to candle materialized views, you can map them back to the underlying candle interval using this query:

SELECT * FROM _timescaledb_catalog.continuous_agg
ORDER BY mat_hypertable_id ASC

**Comment by MuthuVega** [comment]
Looks OK if I were to use the above query in conjunction with my original query.
