### ISSUE TITLE
Update API to have segment ID information

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7355]
## Issue:

When trying to use one of the advanced network-history use cases users are unable to find the required information

### Use Case:

Once data-node is started from the latest NetworkHistory segment, I wanted to fetch older segments
but when I try it, I am required to provide: expected <start-history-segment-id> <num-blocks-to-fetch> .

### Information required:

- the oldest segment available from all my peers?
- the segment id for a specific block?
- the segment id from let say 7 days ago (or 1 month ago)?

**Comment by ettec** [comment]
Hi, been through this Scenario with @fkondej, in short we agree that what the API currently provides is sufficient, we are undecided if it would be useful to be able to get more that just the latest segment id.

@candida-d fyi

To summarise the situation and how we resolved it using current nework history cmd line (which should be as per exisiting instructions, nothing new here, just an example of how it was done in practice) - note this sequence of operations is not something that it would be expected that most operators would do unless they are interested in being an archive node, or have a particular need to view data from some part of history before they first started there node.

A new (effectively) data-node joined the network at height 5000 (say) and was  processing data as expected.   Fryd wanted to load all data from height 0-5000 into the node.

Fryd first of all ran this command to show what data the node held:

`data-node network-history show`

Which, as expected, showed that the node had data from 5000-12000 (current height) and had network history available to load from height 5000 to 12000, along with the corresponding segment ids.

Using this information fryd was able to take the id of the oldest segment and load all data from height 0 to 5000, as follows:

`data-node fetch <segment-id-of-segment-at-height-5000>  5000`

this fetched all network history from height 0-5000 into the nodes network history store.

after this fryd loaded the network history into the store using the following command (not this command requires that datanode is not running)

`data-node network-history load`

datanode was restarted and worked as expected, holding all data from 0 to 12000

**Comment by ettec** [comment]
@jeremyletang @gordsport - think this is closeable based on my comment above?

**Comment by jeremyletang** [comment]
Alright, cheers for the write up.
