### ISSUE TITLE
Core stake linkings response data holds incorrect staking bridge receipt hash

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7394]
To confirm the core has acknowledged the Accepted stake from the ethereum staking bridge, we use the GetStakeRequest/GetStake API and wait for matching pubkey, amount, STATUS_ACCEPTED and hash from the staking bridge receipt.

When running staking serially this works and we quickly match the core APi response with the ethereum receipt via the stake to bridge contract function.

When staking to the bridge in parallel we noticed sometimes one of the batch of staking requests cannot be matched with the datanode API - all data matches apart from the hash and therefore we fail the thread.

**Comment by vega-paul** [comment]
need a test to reproduce

**Comment by gordsport** [comment]
Closing to be re-opened with more information pending a test to reproduce
