### ISSUE TITLE
data-node failed to restart with: context deadline exceeded

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7396]
# Problem encountered
Both `n06.devnet1.vega.xyz` and `n07.devnet1.vega.xyz` data-nodes failed to restart with the same symptoms:
- `n07` failed at around 2023-01-20 22:22:00,
- `n06` failed at around 2023-01-21 03:24:00.

The restart was triggered by a pipeline that automatically restarts a random node every 1 hour. This process is relatively quick, and the node is usually down for about ~3min.

Extra:
After that, I restarted one node on Stagnet 1 and Stagnet 3 networks (using the same script), and it succeeded without problems.

# Observed behaviour
Restart failed with the message:
```
failed to initialize datanode from network history: failed to load history into the datanodefailedto load snapshot data:failed to update current order state: failed to execute sql to update vega_time_to: timeout: context deadline exceeded
```

# Expected behaviour
The node should restart without a problem.

# Evidence

## Logs
```
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990594]: 2023-01-21T03:23:52.383Z        DEBUG        root        visor/visor.go:82        starting config file watcher
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990594]: 2023-01-21T03:23:52.383Z        INFO        root        visor/visor.go:116        Starting binaries
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990594]: 2023-01-21T03:23:52.385Z        DEBUG        root        visor/binaries_runner.go:93        Starting binary        {"binaryPath": "/home/vega/vegavisor_home/current/vega", "args>
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990594]: 2023-01-21T03:23:52.385Z        DEBUG        root        visor/binaries_runner.go:93        Starting binary        {"binaryPath": "/home/vega/vegavisor_home/current/vega", "args>
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990629]: 2023-01-21T03:23:52.867Z        INFO        root        node/node.go:91        starting vega        {"version": "v0.67.2-11411-8fbfcd0e", "commit-hash": "8fbfcd0e01eeae7a2c010c8>
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990629]: 2023-01-21T03:23:52.867Z        INFO        root        node/node.go:366        vega is starting with pprof profile, this is not a recommended setting for production
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:23:52.884Z        INFO        cfgwatcher        config/watcher.go:90        config watcher started successfully        {"config": "/home/vega/vega_home/config/data>
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:23:52.884Z        INFO        root        start/node_pre.go:57        vega is starting with pprof profile, this is not a recommended setting for production
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:23:52.885Z        INFO        root        start/node_pre.go:67        Starting Vega Datanode        {"version": "v0.67.2-11411-8fbfcd0e", "version-hash": "8fbfcd0e>
Jan 21 03:23:52 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:23:52.885Z        INFO        root        start/node_pre.go:104        Initializing Network History

....

Jan 21 03:24:59 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:24:59.082Z        INFO        networkHistory.snapshot        networkhistory/service.go:196        recreating continuous aggregate data
Jan 21 03:24:59 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:24:59.082Z        INFO        networkHistory.snapshot        snapshot/service_load_snapshot.go:133        recreating all continuous aggregate data
Jan 21 03:24:59 n06.devnet1.vega.xyz visor[1990630]: 2023-01-21T03:24:59.996Z        INFO        networkHistory.snapshot        networkhistory/service.go:196        restoring current order state
....

Jan 21 03:28:53 n06.devnet1.vega.xyz visor[1990630]: failed to initialize datanode from network history: failed to load history into the datanodefailed to load snapshot data:failed to update current order state: failed to execute ....
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by fkondej** [comment]
Happened again on `n07` at 7:22 pm on 21st Jan 2023.

**Comment by gordsport** [comment]
Info on cached markets:
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1674465936054479?thread_ts=1674315912.009099&cid=C9E6XA8GK

- https://github.com/vegaprotocol/vega/issues/7401

**Comment by gordsport** [comment]
Possibly resolved with this issue:
- https://github.com/vegaprotocol/vega/issues/7361

**Comment by ettec** [comment]
yep same as https://github.com/vegaprotocol/vega/issues/7361
