### ISSUE TITLE
panic: data-node when restarting with NetworkHistory

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7397]
# Problem encountered
I have encountered the problem on both: `n06.devnet1.vega.xyz` and `n07.devnet1.vega.xyz`, when trying to manually restart the nodes (with increased timeouts) after those went down after this issue: https://github.com/vegaprotocol/vega/issues/7396

- `n07.devnet1.vega.xyz` - I have tried to restart this multiple times, each time increasing timeouts. In the end `30min` timeout was enough to restart the node after being for `~15hours` down. But then I encountered the `panic`. Then I did `unsafe-reset-all` and `clear DataNode Store` (i.e. drop db), and restarted from remote snapshot and latest NetworkHistory segment - the restart was successful
- `n06.devnet1.vega.xyz` - Before the first manual restart, I increased timeouts to `1hour`, and restarted the node after being down for `~10hours`. After around ~40min the data-node paniced.

# Observed behaviour
The data-node panic

# Expected behaviour
The data-node should start successfully after fetching all data from NetworkHistory from other nodes.

# Evidence

## Logs
```
2023-01-21T14:32:43.292Z        INFO        root        start/node_pre.go:122        loaded history from height 54001 to 105900 into the datanode
2023-01-21T14:32:43.296Z        INFO        root        start/node_pre.go:128        Initialized from network history
2023-01-21T14:32:43.304Z        INFO        root        start/node_pre.go:156        Applying Data Retention Policies
2023-01-21T14:32:43.607Z        INFO        root        start/node_pre.go:163        Enabling SQL stores
panic: unable to add built-in network party: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)
goroutine 1 [running]:
code.vegaprotocol.io/vega/datanode/sqlstore.(*Parties).Initialise(0xc00030c858, {0x53b79b8, 0xc0010cecc0})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/sqlstore/parties.go:50 +0x138
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*SQLSubscribers).CreateAllStores(0xc001b80900, {0x53b79b8?, 0xc0010cecc0}, 0xc0019fbc38?, 0xc00697ab00, {{0x0?, 0x35?}})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/start/sqlsubscribers.go:178 +0x1a6
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).persistentPre(0xc001b80900, {0xc00007f360, 0x19, 0x21})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/start/node_pre.go:170 +0x1485
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).Run(0xc001b80900, 0xc00007f380?, {0x53d8ed0?, 0xc00046ed50}, {0xc0019a0c30, 0x0, 0x3})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/start/node.go:85 +0x2a5
code.vegaprotocol.io/vega/cmd/data-node/commands.(*StartCmd).Execute(0x7398520, {0xc0019a0c30, 0x0, 0x3})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/start.go:73 +0x608
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000ed5da0, {0xc0000740c0, 0x3, 0x3})
        /jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x809
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
code.vegaprotocol.io/vega/cmd/data-node/commands.Execute({0x53b79f0, 0xc000078060})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/root.go:56 +0x1f2
main.(*datanodeCmd).Execute(...)
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/datanode.go:27
main.Main({0x53b79f0, 0xc000078060})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/main.go:59 +0x1ea
main.main()
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/main.go:45 +0x27
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Info on cached markets:
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1674465936054479?thread_ts=1674315912.009099&cid=C9E6XA8GK

**Comment by ettec** [comment]
This issue occurred as the load of data timed out leaving the database in a partial loaded state, the timeout was a result of thsi issue: https://github.com/vegaprotocol/vega/issues/7361
