### ISSUE TITLE
Data-node migration failed on stagnet3 during the protocol upgrade

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7403]
# Problem encountered
Protocol upgrade failed on stagnet3 with the following error:

```
Jan 23 01:12:40 n00.stagnet3.vega.xyz visor[481540]: 2023-01-23T01:12:40.431Z        ERROR        root        start/node_pre.go:137        Failed to initialise database, retrying...        {"error": "failed to migrate to latest schema:error migrating sql schema: ERROR 0002_pnl.sql: failed to run SQL migration: failed to execute SQL query \"ALTER TABLE positions\\n  ADD COLUMN pending_open_volume         BIGINT NOT NULL,\\n  ADD COLUMN pending_realised_pnl        NUMERIC NOT NULL,\\n  ADD COLUMN pending_unrealised_pnl      NUMERIC NOT NULL,\\n  ADD COLUMN pending_average_entry_price NUMERIC NOT NULL,\\n  ADD COLUMN pending_average_entry_market_price NUMERIC NOT NULL;\\n\": ERROR: column \"pending_open_volume\" of relation \"_hyper_21_13_chunk\" contains null values (SQLSTATE 23502)"}

```
It is related to new migration added last week

# Observed behaviour
The network is not able to perform the protocol upgrade

# Expected behaviour
Network should start migration and be able to start

# System response
The error in the visor logs (see the attached file

# Steps to reproduce

# Evidence

## Logs
See the attached file

## Additional context
[vegavisor.log](https://github.com/vegaprotocol/vega/files/10478607/vegavisor.log)

Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by daniel1302** [comment]
[vegavisor.log](https://github.com/vegaprotocol/vega/files/10478613/vegavisor.log)

**Comment by ettec** [comment]
the 002.sql is adding a not null column, needs a default value @EVODelavega
