### ISSUE TITLE
Core Withdrawal confirmations send 0 length signature bundle when withdrawing after a pending node created

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7406]
So after a pending node joins
An erc20 withdrawal fails
Withdrawal Approval core response not reached signature expected length 782

branch test/0069-VCBS-validators_chosen_by_stake-053-to-057
test test_node_trx_workflow
will run network_infra network running (5 TMs)

**Comment by wwestgarth** [comment]
Just like to confirm its not a test issue first since the expected signature length is a bit too high. Only tendermint validators signatures will be emitted but `get_erc20_signature_length()` looks like is not filtering them out. I would expect the length to be 652.

**Comment by vega-paul** [comment]
tests use this formula to derive the expected bundle length
    erc20_signature_length = ((132 * node_count) - (node_count * 2)) + 2
    
we are seeing 0 len bundle from GetERC20WithdrawalApproval when a pending node exists in the network

**Comment by wwestgarth** [comment]
I've changed it to this:
```
def get_erc20_signature_length():
    # First get Node details
    node_details = get_node_details()
    node_count = 0
    for n in node_details:
        if n["rankingScore"]["status"] == "VALIDATOR_NODE_STATUS_TENDERMINT":
            node_count += 1
    # Each signature for a validator is 132 bytes, and we only need the leading 0x which is 2 bytes
    erc20_signature_length = ((132 * node_count) - (node_count * 2)) + 2
    return erc20_signature_length
```
and the test found all the signatures and withdrew successfully with a (5,0,1) and (5,1,0) set: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/43954/tests

The test then failed when trying to change the nodeset to (4,2,0), which is unrelated to signature generation but I can still look at.

**Comment by wwestgarth** [comment]
This seems to be ok, and the issues are just making sure the multisig contract is up to date throughout node changes. I have a branch:
https://github.com/vegaprotocol/system-tests/compare/test/0069-VCBS-validators_chosen_by_stake-053-to-057...fiddle-fiddle?expand=1

with a test that adds 3 new nodes, withdrawing with some ersatz/pending and ultimately with 3/4 of the tendermint nodes being newly added nodes and it all passes:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/44254/pipeline/366
