### ISSUE TITLE
Remove deprecated headers in datanode API

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/vega#7419]
# Problem encountered
The following datanode API HTTP headers:

```
Grpc-Metadata-X-Vega-Connection
Grpc-Metadata-X-Block-Height
Grpc-Metadata-X-Block-Timestamp
```
should be properly mapped from gRPC to HTTP gateways, meaning, they should not contain the `Grpc-Metadata-` prefix.
Therefore, they should be deprecated and replaced with:

```
X-Vega-Connection
X-Block-Height
X-Block-Timestamp
```

**Comment by gordsport** [comment]
closed by: 
- https://github.com/vegaprotocol/vega/pull/7415
