### ISSUE TITLE
Core keeps every withdrawal forever in the banking engine in-memory map + checkpoints

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/vega#7440]
Not a huge deal right now -  I mean who is going to want to take their assets _out_ of Vega when it's so awesome right?

It seems like this was on purpose:
```go
func (e *Engine) finalizeWithdraw(
	ctx context.Context, w *types.Withdrawal,
) error {
	// always send the withdrawal event, don't delete it from the map because we
	// may still receive events
```

But one day there might be a very many of these and it could bloat up the core node and its checkpoints.

It also causes a diff when comparing contents of a core checkpoint to a datanode that's been restored from a 'current state' snapshot without any history as datanode counts withdrawals as part of 'history'.

Happy to be told this is NotAnIssue but thought I'd stick it on here for discussion

**Comment by gordsport** [comment]
closing as a duplicate
