### ISSUE TITLE
Data node panics when capital letters are in the home path

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7456]
# Problem encountered
I have the following home path in Jenkins: `/jenkins/workspace/private/playgrounds/DanielH/visor-pup-testing/networkdata/testnet/data-node/node5`

When I put capital letters in any directory name I can see the following panic: 

```
panic: failed to open unix socket

goroutine 295 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0018f6040?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00053a000, {0xc0018e80c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x49ef80b?, {0x4b9ad3b?, 0xc001fa09a0?}, {0xc0018e80c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:251 +0x59
code.vegaprotocol.io/vega/datanode/admin.(*Server).Start(0xc00190c600, {0x53be3d8?, 0xc00190c440})
	/jenkins/workspace/private/playgrounds/DanielH/visor-pup-testing/vega/datanode/admin/server.go:66 +0x87d
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func3()
	/jenkins/workspace/private/playgrounds/DanielH/visor-pup-testing/vega/cmd/data-node/commands/start/node.go:125 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/jenkins/GOPATH/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/jenkins/GOPATH/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:72 +0xa5
Error: maximum number of possible restarts has been reached: failed to execute binary /jenkins/workspace/private/playgrounds/DanielH/visor-pup-testing/networkdata/testnet/visor/visor5/current/vega [datanode node --home /jenkins/workspace/private/playgrounds/DanielH/visor-pup-testing/networkdata/testnet/data-node/node5]: exit status 2
```

# Steps to reproduce

## Manual

Reply the following jenkins pipeline: https://jenkins.ops.vega.xyz/job/private/job/playgrounds/job/DanielH/job/visor-pup-testing/54/

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
After 2 hours debugging issue and investigations there are various articles why sock path is limited to 108chars(actually 107 and termination char).

See those sock paths:
/jenkins/workspace/private/playgrounds/NameA/visor-pup-testing/networkdata/testnet/data-node/datanode.sock - 108 chars (failure here: [https://jenkins.ops.vega.xyz/job/private/job/playgrounds/job/DanielH/job/visor-pup-test[…]-3-with-vega-data-node.stdout-2023-02-06T19%3A12%3A32Z.log](https://jenkins.ops.vega.xyz/job/private/job/playgrounds/job/DanielH/job/visor-pup-testing/66/artifact/testnet/logs/testnet-nodeset-full-3-full/visor-3-with-vega-data-node.stdout-2023-02-06T19%3A12%3A32Z.log))

/jenkins/workspace/common/vegavisor-pup-automatic-download-binaries/networkdata/testnet/data-node/datanode.sock - 111 chars - failure here: [https://jenkins.ops.vega.xyz/job/common/job/vegavisor-pup-automatic-download-binaries/8[…]-3-with-vega-data-node.stdout-2023-02-06T23%3A10%3A41Z.log](https://jenkins.ops.vega.xyz/job/common/job/vegavisor-pup-automatic-download-binaries/8/artifact/testnet/logs/testnet-nodeset-full-3-full/visor-3-with-vega-data-node.stdout-2023-02-06T23%3A10%3A41Z.log)


@zale144 it is believed that there is nothing we can do as sock path is limited by structure used in the Linux kernel - when this gets re-prioritised can we confirm this and if so label as `wont-fix` and close

**Comment by wwestgarth** [comment]
Closing as won't-fix as in Gordon's comment.
