### ISSUE TITLE
Block Explorer API not decoding transfers properly

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7462]
# Problem encountered
A transfer transaction exists on chain, but requesting it from the block explorer API returns very little data

# Observed behaviour
Marking as blocked:
- Can't fetch transfer by ID from graphql/rest: https://github.com/vegaprotocol/vega/issues/7461
- Inadequate details from block explorer API (Possible bug, waiting for confirmation)

The BE API only returns:

```json
{
 "nonce": "0",
 "blockHeight": "0"
}
```

despite the payload being:

```
CrUBCJ+ukPPs6OTk2QEQ2rkgoj+iAQgEEkA0MmIxNTJkZGY3OTdhMGY0YmY4NjQxNzQ1ZGI2MjlmMjlhMjk3YmQwZTEwNjJlY2FkYjQwNTM5YjQ0ZDMxOTAyGAQiQGJmNWI5NDY0ZDE1NGZmZWZmNTdmMDVmOTBiMjIzYzEwNDVmMDc1NGJlZmQwMWE5YTQyYzk5MzgyMTE1ZTc4MzMqFTEwMDAwMDAwMDAwMDAwMDAwMDAwMKoGABKTAQqAAWI2YTY3Mjc4ZWJjODk3NzA2NzE5YTZkMWQ5MzM2NjA4ZDdiZmU3NWNkNGY3MTcwOGY2ODc2M2JjNzM4MWI3ZmY3M2M1NDA2ODUxNjY2MGRlMzdhNDY0OGY2YzMxNGQ3OTk5NWYxNTY2ODcyM2ViMGUwM2I5N2ZmZWQxZDQ1MzAyEgx2ZWdhL2VkMjU1MTkYAYB9A8K7AUUKQDgwMzBmYjU2Yzk5Yjg0NDc0Y2I1NjUxNzFjYzc4NjlmMTk0ZTQ5ZmNkNzhkNjM1MGI1NTc3ZWZjN2I0NjllNzgQowfSPkA2OTQ2NGUzNWJjYjhlOGEyOTAwY2EwZjg3YWNhZjI1MmQ1MGNmMmFiMmZjNzM2OTQ4NDVhMTZiN2M4YTBkYzZm
```

The deterministic ID for this (derived from sig) is `de2c21476a567e790e17369e9d02f9fef580ad59e8721723c1cde91b5e51e906`, but due #7461 I can't fetch it by ID

# Expected behaviour
An endpoint where I can get the transfer by ID

# Steps to reproduce
1. Submit a transfer. You'll see something like:

```JSON
{
    "pubKey": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f",
    "propagate": true,
    "transfer": {
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "to": "efa7484279b75d9580613282e8592a04e7947c1b5b1195a4e06bca8e3982fcd4",
        "toAccountType": "ACCOUNT_TYPE_GENERAL",
        "asset": "bf5b9464d154ffeff57f05f90b223c1045f0754befd01a9a42c99382115e7833",
        "amount": "100000000000000000000",
        "oneOff": {

        }
    }
}
```

2. Fetch it: `curl 'https://be.testnet.vega.xyz/rest/transactions/1F6E1FFF705B57E2E6F3BC408017B22F65FA1E0E6CF0D2FC1C1D65468AB9F20B'`

# Expected
Some details

**Comment by zale144** [comment]
I tried reproducing locally and when calling this `http://localhost:1515/rest/transactions/32A346C8254B39463BDAA5883DF99AA9F13930EF87D5D3670B4C0E1A70EC48F3` endpoint  I got this response:

```
{
  "transaction": {
    "block": "109",
    "index": 0,
    "hash": "32A346C8254B39463BDAA5883DF99AA9F13930EF87D5D3670B4C0E1A70EC48F3",
    "submitter": "2ae3b5a4d3aa970fda611e73c79218f98e72742cf00141f08c4b7d80f671b9cb",
    "type": "Transfer Funds",
    "code": 0,
    "cursor": "109.0",
    "command": {
      "nonce": "0",
      "blockHeight": "0"
    },
    "signature": {
      "value": "eef964474db6cc63ad87fb83ef69d8a85732c1afd55cf34628559bf73b5d91df50cb2b0a791447f83d48a723f9256a73ea201679a16a470bdbd92de07ba0de04",
      "algo": "vega/ed25519",
      "version": 1
    }
  }
}
```

**Comment by zale144** [comment]
> @edd I tried reproducing locally and when calling this `http://localhost:1515/rest/transactions/32A346C8254B39463BDAA5883DF99AA9F13930EF87D5D3670B4C0E1A70EC48F3` endpoint I got this response:
> 
> ```
> {
>   "transaction": {
>     "block": "109",
>     "index": 0,
>     "hash": "32A346C8254B39463BDAA5883DF99AA9F13930EF87D5D3670B4C0E1A70EC48F3",
>     "submitter": "2ae3b5a4d3aa970fda611e73c79218f98e72742cf00141f08c4b7d80f671b9cb",
>     "type": "Transfer Funds",
>     "code": 0,
>     "cursor": "109.0",
>     "command": {
>       "nonce": "0",
>       "blockHeight": "0"
>     },
>     "signature": {
>       "value": "eef964474db6cc63ad87fb83ef69d8a85732c1afd55cf34628559bf73b5d91df50cb2b0a791447f83d48a723f9256a73ea201679a16a470bdbd92de07ba0de04",
>       "algo": "vega/ed25519",
>       "version": 1
>     }
>   }
> }
> ```
> 
> Not sure if it's the same thing

Ah, ok, you mean the "command" bit

**Comment by zale144** [comment]
@edd With this simple trick, your transaction response payloads can look like this one:
```
{
  "transaction": {
    "block": "109",
    "index": 0,
    "hash": "32A346C8254B39463BDAA5883DF99AA9F13930EF87D5D3670B4C0E1A70EC48F3",
    "submitter": "2ae3b5a4d3aa970fda611e73c79218f98e72742cf00141f08c4b7d80f671b9cb",
    "type": "Transfer Funds",
    "code": 0,
    "cursor": "109.0",
    "command": {
      "nonce": "4076347876826616415",
      "blockHeight": "124",
      "transfer": {
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "to": "dc3a3139316bfd81bc1218d7a8525d607617a2475ead47c338c20203ac5ac4ec",
        "toAccountType": "ACCOUNT_TYPE_GENERAL",
        "asset": "993ed98f4f770d91a796faab1738551193ba45c62341d20597df70fea6704ede",
        "amount": "1000000000000000000",
        "reference": "Bot 'w00' Top-Up",
        "oneOff": {
          "deliverOn": "0"
        }
      }
    },
    "signature": {
      "value": "eef964474db6cc63ad87fb83ef69d8a85732c1afd55cf34628559bf73b5d91df50cb2b0a791447f83d48a723f9256a73ea201679a16a470bdbd92de07ba0de04",
      "algo": "vega/ed25519",
      "version": 1
    }
  }
}
```
