### ISSUE TITLE
Error handling very inconsistent in the v2.tradingDataService

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#7477]
Some places we do this: 

t.formatE(err)

Other places we do this:

 errors.Wrap(err, "making edges")

And other places we do this:

fmt.Errorf("could not retrieve market data history for market id: %w", err)   (this latter should be a not found if message).

We should tidy it all up to do t.formatE(err) and correctly use not found errors -  user experience thing so @gordsport maybe do this asap?

**Comment by zale144** [comment]
dibs
