### ISSUE TITLE
Data Mismatch - vegatools diff tool reports data mismatch for epoch

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7482]
As part of all the system test pipelines we run the vegatools database diff tool to check if the data in the datanode matches with core.

**Command:**

**`vegatools difftool -s ./snapshot-tmp -d 127.0.0.1:3027`**

This command reports a mismatch for epoch, however looking at the data , looks like the data is correct BUT there is an additional field `first_block` returned from the datanode thats making the comparison to fail.

**Output:**

`key=epoch, matchResult=mismatching values, coreLength=1, datanodeLength=1, coreResult=seq:275 timestamps:{start_time:1675332957029983000 expiry_time:1675332962029983000}, datanodeResult=seq:275 timestamps:{start_time:1675332957029983000 expiry_time:1675332962029983000 first_block:4949}`

Jenkins Pipeline:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/46715/pipeline/

**Comment by MuthuVega** [comment]
A system test exists to exercise this functionality , which can be used when fixing this issue.

System Test Name - **test_datanode_compare_restored_datanode_data_against_core**
System Test Marker - **datanode_core_datadiff**

Unskip the test and run locally or on Jenkins to observe the issue.

Unskip the test when the defect has been fixed.

**Comment by wwestgarth** [comment]
This was fixed here: https://github.com/vegaprotocol/vegatools/pull/263

Running the tests the epoch comparison looks fine now https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/54649/tests:
```
E       AssertionError: Error running vegatools difftool for node /tmp/
E         completed diff for accounts with status 0
E         completed diff for orders with status 0
E         completed diff for markets with status 0
E         completed diff for parties with status 0
E         completed diff for limits with status 0
E         completed diff for assets with status 0
E         completed diff for delegations with status 0
E         completed diff for epoch with status 0 <- THIS ONE
E         completed diff for vegaTime with status 2
E         completed diff for nodes with status 0
E         completed diff for netparams with status 0
E         completed diff for proposals with status 0
E         completed diff for deposits with status 0
E         completed diff for withdrawals with status 0
E         completed diff for liquidityProvisions with status 0
E         completed diff for stake with status 0
E         completed diff for transfers with status 0
E         completed diff with success? false
```

The test still fails with a vegatime mismatch but I think thats likely because the system test is comparing the snapshot of a stopped node to a datanode that is still running, so I wouldn't expect them to match.
