### ISSUE TITLE
Memory Leak in event bus stream subscriber

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#7494]
FYI related to the main issue:
core/subscribers/stream_subscriber.go is a duplicate of datanode/subscribers/stream_subscriber.go
and
datanode/subscribers/service.go  and  core/core/subscribers/service.go
are duplicates of each, so suffer from the same bug, we may want to consolidate these as part of this fix,unless there is good reason to have the duplicates?  but can't see any.

the service.go has a memory leak that manifest itself if a client subscribes but is a slow consumer, see the printf in the code below, the datalength2 (and datalength1) has been observer to grow continuously is this scenario, we should set an allowed upper limit, beyond which the connection is closed.  Based on observeration, 10000 is probably a reasonable default.   Note, do consider if this limit makes sense for the cores version of the service as well (I think it does), if so consolidate the code.

`for {
			select {
			case <-ctx.Done():
				return
			case bs := <-in:
				// batch size changed: drain buffer and send data
				data = append(data, sub.UpdateBatchSize(ctx, bs)...)
				datalength1 := len(data)

				if datalength1 > lastLoggedDataLength+10000 {
					lastLoggedDataLength = datalength1
					fmt.Printf("SUBSCRIBER %s, DATALENGTH 1: %d\n", sub.StreamID, lastLoggedDataLength)
				}

				if datalength1 > 0 {
					trySend()
				}
			default:
				// wait for actual changes
				data = append(data, sub.GetData(ctx)...)

				datalength2 := len(data)
				if datalength2 > lastLoggedDataLength+10000 {
					lastLoggedDataLength = datalength2
					fmt.Printf("SUBSCRIBER %s, DATALENGTH 2: %d\n", sub.StreamID, lastLoggedDataLength)
				}

				// this is a very rare thing, but it can happen
				if len(data) > 0 {
					trySend()
				}
			}
		}`

**Comment by jeremyletang** [comment]
Yes 10000, is fine. Let’s merge both implementation if possible.
