### ISSUE TITLE
Implement check tx function on wallet

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7499]
Should support CLI, and Admin / Client namespaces on the API

```
vega wallet transaction check
```

```
admin.check_transaction
```

```
client.check_transaction
```

Should bundle and send transaction on the Check Tx, and return the transaction so it can be send by the dapp.

**Comment by MuthuVega** [comment]
@gordsport - please can you let us know if this has been prioritised ?
Else, please can this be prioritised ?

**Comment by ValentinTrinque** [comment]
@MuthuVega this is currently being implemented
