### ISSUE TITLE
Transfer events not always sent after margin recheck

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#7508]
A loop returning early may result in transfer events not being sent if the first few transfers succeed, but the `n`-th one fails:
https://github.com/vegaprotocol/vega/blob/8d76c5e6865fad12cdc497189285121e9eb2655b/core/execution/collateral.go#LL93C5-L93C5

**Comment by jeremyletang** [comment]
To be fair, that code should probably panic there.

**Comment by witgaw** [comment]
It shouldn't, you could get something like a `ErrMinAmountNotReached` which is nothing to fret about.

I've got a fix here: https://github.com/vegaprotocol/vega/pull/7507

**Comment by witgaw** [comment]
Hmm though maybe we actually want a compound error (so we try to go through transfers after the one with the error too)
