### ISSUE TITLE
Docs on how to run vega and data-node without vegavisor

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7531]
Please create docs on:
- [ ] Running `vega` core without `vegavisor`,
- [ ] Running `vega` core with `data-node` without `vegavisor`,
- [ ] How to handle `Protocol Upgrade` when running `vega` core without `vegavisor`,
  - [ ] Example of how to automate this without `vegavisor`,
- [ ] How to handle `Protocol Upgrade` when running `vega` core with `data-node` without `vegavisor`,
  - [ ] Example of how to automate this without `vegavisor`,
- [ ] How to handle `Protocol Upgrade` when running `block explorer`,
  - [ ] Example of how to automate this,

Context: https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1675769141979479?thread_ts=1675763847.511879&cid=C9E6XA8GK

**Comment by gordsport** [comment]
@fkondej 

Can you please review both the [propose and execute upgrades ](https://docs.vega.xyz/testnet/node-operators/how-to/upgrade-network)docs page and this PR:

- https://github.com/vegaprotocol/documentation/issues/577

And feel free to contribute to this PR as you see fit, or if you points are covered we can close this issue

**Comment by gordsport** [comment]
Closing for now as the process to upgrade when no using Visor is covered here: 
- https://github.com/vegaprotocol/documentation/issues/577
