### ISSUE TITLE
Very easy to destroy database when loading NetworkHistory

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7532]
It is easy to destroy DataNode's database when loading data from Network History.

The process of loading data from Network History cannot be interrupted. Otherwise, it will leave a database in an unrecoverable state. The only solution in that state is to drop the whole database and start with an empty state.

This is not an ideal situation for an Archival Node. And you can question if you should use Network History for that node or rely on node catching up.

How the problem is triggered:
- the loading process of Network History is time-consuming,
  - e.g. one of the tests on Stagnet 3 showed that it took 2h30min to load 28hours of data,
- three different timeouts need to be increased accordingly before you start the process,
  - once you start the process and realise the timeout is too short, then you have only two options: pray or drop the db,

The three timeouts:
- `vega` config.toml: `Broker.Socket.DialTimeout`
- `vegavisor` config.toml: `maxNumberOfFirstConnectionRetries`
- `data-node` config.toml: `NetworkHistory.Initialise.TimeOut` - I could argue that this timeout should be removed entirely.

## Solutions

1. Improve `data-node` so it doesn't break the db when interrupted
2. Disable all 3 timeouts when loading from NetworkHistory
3. Anything else?

**Comment by ettec** [comment]
Should probably do the load in a transaction, however, things get a little more interesting when you load across a schema update boundary due to the de/reapplication of constraints/indexes and possible issues around some DDL changes in a transaction.   Needs testing to confirm.
