### ISSUE TITLE
datanode logging fixes

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7539]
1/ Can we separate the logs for vega/visor/datanode please, we have had DN issues and cannot identify what component is logging something, also make diagnosis difficult even at capsule level

2/ vega-visor-datanode stderr is a copy of stdout - only system errors should be piped here

**Comment by gordsport** [comment]
Closing as duplicate of:

- https://github.com/vegaprotocol/vega/issues/7501
