### ISSUE TITLE
Protocol upgrade failed on stagnet3

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7541]
### Protocol Upgrade partially failed on Stagnet 3 

3 out of 4 data-nodes failed, however, it worked on all validators. 

The only data-node that survived was previously (a couple of days ago) restarted from the latest snapshot/segment.

The last log of data-node is Attempting to initialise database..., then nothing for 5min. On the healthy node, after 2min there is 0003_closeout.sql in the logs.

**Comment by pscott31** [comment]
So this was simply a case of visor not giving datanode enough time to start up.

Elias's added a database migration for positions with steps like:

```UPDATE positions SET
  loss_socialisation_amount = ABS(loss) - adjustment,
  distressed_status = 'POSITION_STATUS_UNSPECIFIED';
  ```

Which are liable to take a long time with many positions in the database. I can see from the logs that postgres was very busy during the schema migrations at startup, so am 99% sure n07 was just lucky and got done just in time. I think maybe we could increase (or remove altogether) the timeout that visor uses when waiting for datanode to become ready - as occasionally it is possible that we will have migrations which will take a long time.

But I don't think there's a datanode bug here so closing this issue for now.
