### ISSUE TITLE
PANIC: deadlock detected: historysnapshot/market_data

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7547]
# Problem encountered
`n00.stagnet1.vega.xyz` running `v0.67.3` stopped with a PANIC:

`2023-02-08T23:17:38.379Z        PANIC        networkHistory.snapshot        snapshot/service_create_snapshot.go:119        failed to snapshot data        {"error": "failed to copy table data:failed to execute copy copy (select * from market_data where synthetic_time >= (SELECT vega_time from blocks where height = 1847701) order by synthetic_time) to '/home/vega/vega_home/state/data-node/networkhistory/snapshotscopyto/vega-stagnet1-202301232253-1847701-1848000-historysnapshot/market_data': ERROR: deadlock detected (SQLSTATE 40P01)"}`

```
panic: failed to snapshot data
goroutine 529508793 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc057fb1880?})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc035dd21a0, {0xc058b22b80, 0x1, 0x1})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc001b6eb20?, {0x344c242?, 0x1c32c0?}, {0xc058b22b80, 0x1, 0x1})
        /home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:251 +0x59
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot.func4()
        /home/runner/work/vega/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:119 +0x2da
created by code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot
        /home/runner/work/vega/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:124 +0x9ca
```

## PostgreSQL log

There is more info in postgres log `/var/log/postgresql/postgresql-14-main.log`:

**Note: there are more deadlock logs prior to the blow ones**

```
2023-02-08 23:11:00.495 UTC [4170992] LOG:  job 1021 threw an error
2023-02-08 23:11:00.495 UTC [4170992] ERROR:  deadlock detected
2023-02-08 23:11:00.495 UTC [4170992] DETAIL:  Process 4170992 waits for AccessExclusiveLock on relation 6351225 of database 5876743; blocked by process 2926975.
        Process 2926975 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4170992.
        Process 4170992: CALL _timescaledb_internal.policy_retention()
        Process 2926975: SELECT
        table_name,
        table_bytes,
        index_bytes,
        toast_bytes,
        total_bytes
        FROM (
            SELECT
              pg_catalog.pg_namespace.nspname           AS schema_name,
              relname                                   AS table_name,
              (hypertable_detailed_size(pg_catalog.pg_class.oid)).*
        
            FROM pg_catalog.pg_class
              JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid
          ) t
        WHERE schema_name = 'public'
        
2023-02-08 23:11:00.495 UTC [4170992] HINT:  See server log for query details.
2023-02-08 23:11:00.506 UTC [2926440] LOG:  background worker "Retention Policy [1021]" (PID 4170992) exited with exit code 1
```
...
```
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db ERROR:  deadlock detected
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db DETAIL:  Process 4171079 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4171223.
        Process 4171223 waits for AccessExclusiveLock on relation 6351225 of database 5876743; blocked by process 4171079.
        Process 4171079: copy (select * from market_data where synthetic_time >= (SELECT vega_time from blocks where height = 1847701) order by synthetic_time) to '/home/vega/vega_home/state/data-node/networkhistory/snapshotscopyto/vega-stagnet1-202301232253-1847701-1848000-historysnapshot/market_data'
        Process 4171223: CALL _timescaledb_internal.policy_retention()
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db HINT:  See server log for query details.
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db STATEMENT:  copy (select * from market_data where synthetic_time >= (SELECT vega_time from blocks where height = 1847701) order by synthetic_time) to '/home/vega/vega_home/state/data-node/networkhistory/snapshotscopyto/vega-stagnet1-202301232253-1847701-1848000-historysnapshot/market_data'
```
...
```
2023-02-08 23:17:39.259 UTC [4171223] LOG:  job 1021 threw an error
2023-02-08 23:17:39.259 UTC [4171223] ERROR:  deadlock detected
2023-02-08 23:17:39.259 UTC [4171223] DETAIL:  Process 4171223 waits for AccessExclusiveLock on relation 6351225 of database 5876743; blocked by process 2926975.
        Process 2926975 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4171223.
        Process 4171223: CALL _timescaledb_internal.policy_retention()
        Process 2926975: SELECT
        table_name,
        table_bytes,
        index_bytes,
        toast_bytes,
        total_bytes
        FROM (
            SELECT
              pg_catalog.pg_namespace.nspname           AS schema_name,
              relname                                   AS table_name,
              (hypertable_detailed_size(pg_catalog.pg_class.oid)).*
        
            FROM pg_catalog.pg_class
              JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid
          ) t
        WHERE schema_name = 'public'
        
2023-02-08 23:17:39.259 UTC [4171223] HINT:  See server log for query details.
2023-02-08 23:17:39.265 UTC [2926440] LOG:  background worker "Retention Policy [1021]" (PID 4171223) exited with exit code 1
```
....
```
2023-02-08 23:18:25.248 UTC [4171360] ERROR:  deadlock detected
2023-02-08 23:18:25.248 UTC [4171360] DETAIL:  Process 4171360 waits for AccessExclusiveLock on relation 6351225 of database 5876743; blocked by process 4171035.
        Process 4171035 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4171360.
        Process 4171360: CALL _timescaledb_internal.policy_retention()
        Process 4171035: SELECT "public"."market_data"."liquidity_provider_fee_shares", "public"."market_data"."price_monitoring_bounds" FROM "public"."market_data" LIMIT 500
```

**Comment by pscott31** [comment]
OK so I had a good dig into this, and I believe it is most likely to be a timescaledb bug.

There are a handful of deadlocks over the last day or two between the grafana postgres agent and the retention policy background process. When the retention process wants to delete a chunk[ it takes](https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/troubleshooting/#dropping-chunks-times-out) an AccessExclusive lock on the entire chunk table. We can see that here: 
 
>   Process 4171223 waits for **_AccessExclusiveLock_** on relation 6351225 of database 5876743; blocked by process 2926975.
>   Process 2926975 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4171223.
>   **Process 4171223: CALL _timescaledb_internal.policy_retention()**
>   Process 2926975: SELECT
>   table_name, ...

4171223 is the retention policy applier and 2926975 is the Grafana agent which is doing a query like 
```
            SELECT          (hypertable_detailed_size(pg_catalog.pg_class.oid)).*     
            FROM pg_catalog.pg_class
```

The retention policy applier is trying to acquire an `AccessExclusive` lock which is the strongest sort of lock in postgres and will conflict with any other lock. If the two processes acquire their locks in a different order there is chance of a deadlock.

Those deadlocks weren't causing any bother as the retention policy applier would just try again later, and its no big deal if we miss a couple of grafana data points.

The thing that floored the datanode was when the retention policy applier deadlocked with query that was generating a snapshot for network history - which is again possible when that transaction is acquiring normal read locks on data in hypertable chunks that are being removed by the retention policy applier.

There is an[ issue open](https://github.com/timescale/timescaledb/issues/3423) on timescale's Github which while not exactly the same is similar enough that I believe it's the same underlying problem with how timescale locks chunks.

I've left a comment there explaining what we saw. There isn't a huge amount we can do on our side; we could perhaps rejig our code to retry a transaction when if it fails; but that's a bit fiddly.

I think we should just keep an eye on it for now and hope this is an isolated occurance.

**Comment by pscott31** [comment]
As an illustration, this causes a deadlock if you run these two transactions in the indicated order
![image](https://user-images.githubusercontent.com/94362991/217927248-3db66228-0400-45d3-8608-11ad5f9b86c1.png)

**Comment by pscott31** [comment]
Closing this for now as we don't have an immediate plan to do anything about it, we can revisit later if it reoccurs
