### ISSUE TITLE
The data-node is not able to handle protocol upgrade in latest develop version

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7627]
# Problem encountered

I am getting the following error when i am doing the protocol upgrade:

```log
023-02-18T00:30:27.814Z	DEBUG	bootstrap	bootstrap/bootstrap.go:174	failed to bootstrap with 12D3KooWPzFoHc8RwhKAbFz3z6Jj32qMGU6TrnX5aEP7FTMxMjDP: dial to self attempted
2023-02-18T00:30:27.814Z	DEBUG	bootstrap	bootstrap/bootstrap.go:90	12D3KooWPzFoHc8RwhKAbFz3z6Jj32qMGU6TrnX5aEP7FTMxMjDP bootstrap error: failed to bootstrap. dial to self attempted
failed to create and publish segment: failed to create snapshot: failed to get data dump metadata: failed to get database version: FATAL: terminating connection due to administrator command (SQLSTATE 57P01)
Error: maximum number of possible restarts has been reached: failed to prepare args for Vega binary: failed to get latest history segment from data node: failed to execute binary /home/ubuntu/www/networkdata/testnet/visor/visor13/current/vega [datanode network-history latest-history-segment --home /home/ubuntu/www/networkdata/testnet/data-node/node13 --output json] with error: , {"error":"no history segments found"}
: exit status 1
Usage:
  vegavisor run [flags]

Flags:
  -h, --help          help for run
      --home string   Path to visor home folder
```

# Observed behaviour
Data node panics

# Expected behaviour
Data-node should be able to run 

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

#### 1. Compile the following binaries:

- devopsscripts
- vegatools

#### 2. use the following branches

- system-tests: devops-infra/1522-2
- vega: develop

#### 3. Execute the follwing command in the `system-tests/scripts` folder to start nomad

```bash
make start-nomad
```

#### 4. In separated command execute the following commands:

```bash
export VEGACAPSULE_CONFIG_FILENAME=/home/ubuntu/www/system-tests/vegacapsule/capsule_config_mainnet.hcl
make vegacapsule-cleanup
make rebuild
make vegacapsule-generate-network 
```

#### 5. Load mainnet checkpoint into the network

```bash
mkdir -p ./lnl-workdir

devopsscripts lnl prepare-network \
    --checkpoint-server-checkpoint-dir  /home/vega/vega_home/state/node/checkpoints \
    --checkpoint-server-host api2.mainnet.vega.xyz \
    --checkpoint-server-key-file <SSH-KEY> \
    --checkpoint-server-user <USER> \
    --genesis-uri file://<WORKSPACE_FOLDER>/system-tests/vegacapsule/net_configs/mainnet/genesis.json \
    --vegacapsule-network-home <WORKSPACE_PATH>networkdata/testnet \
    --out-dir ./lnl-workdir \
    --vegacapsule-path vegacapsule \
    --vega-path vega \
    --no-secrets
```

But replace the following data:

SSH_KEY - the key which gives you access to mainnet observer server
USER - your user on mainnet observer box
WORKSPACE_PATH - absolute path to the parent folder where you have all your repos(system-tests, vega, etc...) i have `/home/ubuntu/www/`

#### 6. Prepare checkpoints for lnl tests:

```bash

make vegacapsule-start-network-only
echo "sleeping 30 secs"
sleep 30
CHECKPOINT_PATH=$(devopsscripts vegacapsule wait-for-checkpoint --checkpoints 1 --timeout 10m --print-last-checkpoint-path-only --search-from-beginning --vegacapsule-path vegacapsule --network-home-path <WORKSPACE_PATH>networkdata/testnet --no-secrets)
vegatools checkpoint --file "$CHECKPOINT_PATH" --out<WORKSPACE_PATH>/system-tests/tests/LNL/after_checkpoint_load.json
cp ./lnl-workdir/checkpoint.json <WORKSPACE_PATH>/system-tests/tests/LNL/checkpoint-resume.json
```

#### 7. Run the following command to run the tests which does the protocol upgrade:

```bash


# export TEST_FUNCTION=test_checkpoint_loaded
export TEST_FUNCTION=test_extended_lnl
export TEST_DIRECTORY=tests/LNL
export MAINNET_TEST_CASE=true
export PROTOCOL_UPGRADE_EXTERNAL_RELEASE_VERSION=v99.9.9-system-tests-226
unset PROTOCOL_UPGRADE_EXTERNAL_RELEASE_VERSION
make tests
```

## Automation
I have a static server where i can simulate it, if you pickup the issue, ask @daniel1302  to add your pub key there and show how to trigger the issue. 

# Evidence

## Logs
See above

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Closing as this issue has been resolved in the latest version
