### ISSUE TITLE
Vega wallet missing nonce

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7663]
the nonce field is sometimes missing from the wallet response, tests use that to determine pow difficulty

example here for wallet V2 and V1 responses
we have the tid, input_data but no nonce

{'receivedAt': '2023-02-22T18:37:40.761568Z', 'sentAt': '2023-02-22T18:37:40.800372Z', 'transactionHash': 'C3A0C117F3D443ACA99C5A51431736EAE06CB895CEF8FD92F4D020DEEEBC382B', 'transaction': {'input_data': 'CILTyL+Xib69LhDjFco+vgEKQDk1ZjE2ZmE4ZGQ0ZDdkNzJjMjhjYzFhODNlZmY5MTM2ZTFiNzIwMzhmMzJkMTQwYTM4ODVhYTRjN2VjMzE2OTgSCTEwMDAwMDAwMBigwh4gASgBOAFCZTJlZWJkMzFhYzE0ZjM2ZDk3NTNkMjg3MGFhYzI2Njc1Yzg0NjU2MTZjY2Q5NTEzNGRiNDMxZTVjZTRhZmM5NzgtZmY4MGNlNmQtN2QxMy00YTk1LWEwY2MtNjdkMzdmODk3Yjk0', 'signature': {'value': 'b01dd49b155cbd182ef3a1af9c4107e1ee82fb2770ad80e916410893a2154107c9fcee150d556e7a7246d0fe31f4a6afde6f0360ceb173de8e33461aa2d2450e', 'algo': 'vega/ed25519', 'version': 1}, 'From': {'PubKey': '2eebd31ac14f36d9753d2870aac26675c8465616ccd95134db431e5ce4afc978'}, 'version': 3, 'pow': {'tid': 'f8331f7ada2023ff1c286d9bc83965d72ccb0635a71086d792ad1ba6800e784a'}}

'txHash': 'C3A0C117F3D443ACA99C5A51431736EAE06CB895CEF8FD92F4D020DEEEBC382B', 'tx': {'input_data': 'CILTyL+Xib69LhDjFco+vgEKQDk1ZjE2ZmE4ZGQ0ZDdkNzJjMjhjYzFhODNlZmY5MTM2ZTFiNzIwMzhmMzJkMTQwYTM4ODVhYTRjN2VjMzE2OTgSCTEwMDAwMDAwMBigwh4gASgBOAFCZTJlZWJkMzFhYzE0ZjM2ZDk3NTNkMjg3MGFhYzI2Njc1Yzg0NjU2MTZjY2Q5NTEzNGRiNDMxZTVjZTRhZmM5NzgtZmY4MGNlNmQtN2QxMy00YTk1LWEwY2MtNjdkMzdmODk3Yjk0', 'signature': {'value': 'b01dd49b155cbd182ef3a1af9c4107e1ee82fb2770ad80e916410893a2154107c9fcee150d556e7a7246d0fe31f4a6afde6f0360ceb173de8e33461aa2d2450e', 'algo': 'vega/ed25519', 'version': 1}, 'From': {'PubKey': '2eebd31ac14f36d9753d2870aac26675c8465616ccd95134db431e5ce4afc978'}, 'version': 3, 'pow': {'tid': 'f8331f7ada2023ff1c286d9bc83965d72ccb0635a71086d792ad1ba6800e784a'}}}

**Comment by wwestgarth** [comment]
The nonce in this case is likely `0`. The problem is that we use the proto definition of the transaction which when autogenerated puts `omitemty` everywhere. When the wallet marshalls it to json it'll take the `0` value as "empty" and not add it.

I remember reading somewhere that the json tags are deprecated, and we should use the the proto-json marshaller that would keep these values. But we can't just replace that in the jsonrpc code, so we might have to do it in two-steps somehow.

**Comment by ValentinTrinque** [comment]
@vega-paul please can you verify what's the Proof of work difficulty set on the network at the moment of the sending ? If it's set to 0 then the nonce will be set to 0. And, as pointed by @wwestgarth , if set to 0 it won't be returned, but it should be interpreted as such.

**Comment by vega-paul** [comment]
This particular test sets pow.difficulty to 1

**Comment by ValentinTrinque** [comment]
So it means the proof-of work computation found 1 leading 0 without needing to increase the nonce, leaving it to `0`.

**Comment by ValentinTrinque** [comment]
THis is likely to happen

**Comment by ValentinTrinque** [comment]
Try to increase it to 5 and see if you get a nonce

**Comment by gordsport** [comment]
@vega-paul - based on the above can this be closed?
