### ISSUE TITLE
data-node timing out on "fetching history for segment" step

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7683]
# Problem encountered
We have a `Snapshot` pipeline that runs every 12min and starts a new `data-node` from remote `snapshot` and `network-history`.
From time to time, the pipeline fails because the `data-node` fails to startup.

# Observed behaviour
While `data-node` starts using `network-history` it timeouts on a `fetching history for segment`.
The timeout is `1min`, but usually, this step takes `~1sec`.

# Expected behaviour
The data-node should always startup without timing out.

# Evidence

## Failed pipelines
- https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FFairground/detail/Fairground/14948/pipeline/110
- https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FFairground/detail/Fairground/14947/pipeline/110
- https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FFairground/detail/Fairground/15035/pipeline/110/

Some context: https://vegaprotocol.slack.com/archives/C03KD0MR8M8/p1677171191168049

## Logs

Failed startup:
<img width="1407" alt="Screenshot 2023-02-24 at 11 13 37" src="https://user-images.githubusercontent.com/20031574/221158314-3815b7cf-1da9-48a6-938b-1bc9425130a6.png">

Successful startup:
<img width="1429" alt="Screenshot 2023-02-24 at 11 15 02" src="https://user-images.githubusercontent.com/20031574/221158374-44ad4092-aef3-4913-a557-0a323259efcb.png">

**Comment by gordsport** [comment]
@fkondej 
The above issue has been merged. Please can you see if this issue is still present?

**Comment by wwestgarth** [comment]
The fairgournd pipeline which is where we saw this happening now has the fixes in and is a sea of green: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FFairground/activity

So I think we're ok now.

Interestingly I haven't seen the retry-code kick in on any of the runs, so it must've been the IPFS updates that fixed it.
