### ISSUE TITLE
Make the `SessionBegan` interaction easy to identify

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7723]
When the frontend receives a SesionBegan interaction, it doesn't know what workflow is targeted. This prevents the wallet UIs to adapt their displays, which stifle the user experience opportunities.

**So we need to add a `workflow` field (string) to help the front end identify the session that began:**

- 'WALLET_CONNECTION' in the `client.connect_wallet` method
- 'TRANSACTION_REVIEW' in the `client.<send|sign|check>_transaction` methods
- 'PERMISSION_REQUEST' in the `client.list_keys` method

**Comment by notbot00** [comment]
just for the record, i've started coding this on the frontend. ideally i would need this workflow field on every interaction event emitted, so i can keep track of them easily. the traceID itself is not enough anymore for this.
