### ISSUE TITLE
Bug: LP closeout during auction

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#7740]
the only LP (lpprov) got closed out during auction, the auction ended with a trade, market goes to continuous trading mode

expected behaviour should be:

liquidity auction being triggered, and market stays in liquidity auction

**Comment by EVODelavega** [comment]
Closing this one, as this turned out not to be a bug (triggering ratio was set to 0, supplied stake of 0 >= target_Stake * 0)
