### ISSUE TITLE
List asset signatures go missing if an asset proposal is enacted on the same block as an upgrade

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#7758]
# Problem encountered
We have a test which (accidentally, as it happens) sometimes enacts an ERC20 asset on an upgrade block. When it does, the list asset bundle is never found after the upgrade has happened.

# Observed behaviour
`    def wait_for_signature_bundle(self, update=False):
        """
        Retrieves the signature bundle to list or update the asset on the smart contract.
        """
        if not update:
            # Create/list asset
            sig_call = networkMod.get_list_asset_bundle
        else:
            # Update asset
            sig_call = networkMod.get_set_asset_limit_bundle
        # Signature bundle may be empty until data node catches up with core
        timeout = 5
        now = time.time()
        result = None
        num_nodes = len(networkMod.get_node_details())
        expected_sig_length = 130 * num_nodes + 2
        while time.time() <= now + timeout:
            result = sig_call(self.current_proposal.id)
            assert "signatures" in result
            if len(result["signatures"]) == 0:
                sigs_returned = 0
            else:
                sigs_returned = (len(result["signatures"]) - 2) / 130
            assert int(sigs_returned) == sigs_returned, f"Weird data returned for signature: {result}"
            if len(result["signatures"]) <= 2:
                logging.info(f"Waiting for valid signature bundle in data node.")
                time.sleep(0.2)
            elif sigs_returned < num_nodes:
                logging.info(f"Waiting for signatures from all nodes. Currently have: {sigs_returned} / {num_nodes}")
                time.sleep(0.2)
            elif sigs_returned > num_nodes:
                raise Exception(f"Too many signatures returned: {result}")
            else:
                break
        bundle = result["signatures"]
        nonce = result["nonce"]
>       assert len(bundle) > 2, f"Bad list asset bundle: {result}"
E       AssertionError: Bad list asset bundle: {'assetSource': '0xad221c9cbAF618890fC12136865Aad9F8dc888E2', 'vegaAssetId': '17838bbfd518edc7c44e47857eb860ad0239d3edf43fe2a63f0a6bd757b90b54', 'nonce': '10635616997434885844920268286264680989497494871490412493598980090653440543572', 'signatures': ''}
E       assert 0 > 2
E        +  where 0 = len('')

modules/govMod/governMod.py:1569: AssertionError`

# Expected behaviour
List asset bundle is found.

# Steps to reproduce

## Automation
Current develop version of test_proposals_can_span_upgrade can reproduce this. This is because of this line:
`erc20_asset.propose(proposer, state="Open", closeTimeOffSec=30, enactTimeOffSec=31)`
I'm about to fix it to be 90 & 91, so if you want to repro, you may need to change it back, and then run the following:
`pytest tests/protocol_upgrade -l test_proposals_can_span_upgrade -x --count 20`
This will cause it to attempt the test 20 times each, and fail the first time it goes wrong.

# Evidence

## Logs
```
{"id":"314-7","block":"695663EC5ADE10B1224ACADA04AA43108EEC352C2B0CFC51E5AF77785B729881","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"75fb1b2b62b1b643635501b563e10aa3d4e022a3eefc33f909a93a73841a72f1","reference":"A70F84023D","partyId":"95433207e7d0ee71e26c5e1bfcd379c3803ea22105530641a28507398262e1fd","state":"STATE_ENACTED","timestamp":"1677810932680274010","terms":{"closingTimestamp":"1677810962","enactmentTimestamp":"1677810963","validationTimestamp":"1677810943","newAsset":{"changes":{"name":"Test Asset","symbol":"TEST","decimals":"18","quantum":"1000000000000000000","erc20":{"contractAddress":"0xad221c9cbAF618890fC12136865Aad9F8dc888E2","lifetimeLimit":"100000000000000000000000000","withdrawThreshold":"1000000000000000000000"}}}},"rationale":{"description":"New asset","title":"Asset Proposal: Test Asset"},"requiredParticipation":"0.00000015","requiredMajority":"0.66"},"version":1,"chainId":"testnet-001","txHash":"695663EC5ADE10B1224ACADA04AA43108EEC352C2B0CFC51E5AF77785B729881"}
```
^ Asset enacted
```
{"id":"314-8","block":"695663EC5ADE10B1224ACADA04AA43108EEC352C2B0CFC51E5AF77785B729881","type":"BUS_EVENT_TYPE_PROTOCOL_UPGRADE_PROPOSAL","protocolUpgradeEvent":{"upgradeBlockHeight":"314","vegaReleaseTag":"v99.99.0+dev.3601bb6b.modified","approvers":["343d1bedf0c7cfc65d87c6d9dd87f3d0199145a439e0e8d371336e0a548630b6","478d2917d60f60e2124a19bca62077d9c3d59f3a3fd87c58f2207a0efc404ce3","54edab78feef1d7facd487f5ab734484ab4df13d11718b8371af220805a38f58","83c9eb2cbafde0ee072dcd48bca45a4fc161a2ad06572913523b16f9cb59d94b","b2339ffbf32b72067e7c9cb984cf6cfb3a6123f913e34971df422788e562c7ff"],"status":"PROTOCOL_UPGRADE_PROPOSAL_STATUS_APPROVED"},"version":1,"chainId":"testnet-001","txHash":"695663EC5ADE10B1224ACADA04AA43108EEC352C2B0CFC51E5AF77785B729881"}
```
^ Protocol upgrade happens

## Additional context
Tried waiting quite a while after upgrade, bundle never appears.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jgsbennett** [comment]
[This PR](https://github.com/vegaprotocol/system-tests/pull/1914) stops the test from hitting this issue. This test was trying to ensure the proposal would span the whole upgrade, which obviously wasn't happening in this case.

**Comment by wwestgarth** [comment]
The problem is when the notary engine restores from a snapshot. If we haven't seen a signature from ourselves for a resesource, we add it to the retry list with a `nil` signature:
```
for resource, ok := range selfSigned {
		if !ok {
			// this is not signed, just add it to the retries list
			retries.Add(resource, nil)
		}
	}
```

for withdrawal the signature is then regenerated during OnTick of the banking engine:
```
e.notary.OfferSignatures(
		types.NodeSignatureKindAssetWithdrawal, e.offerERC20NotarySignatures)
```
but we do not handle any other NodeSignature kinds, like `NodeSignatureKindAssetNew`. So the _full_ fix is to go around an do similar for all the other node-signature types.

But I do think there might be something easier we can do that would fix it for the protocol-upgrade case. The only reason the signatures for all nodes are even in the retry list is because of this:
```
// now let's just add the transaction to the retry list
// no need to send the signature, it will be done on next onTick <- THIS COMMENT HERE
n.retries.Add(idkind, signature)
```

If we were to instead send the node-signature transaction in straight away, it would hit the mempool before the network goes down to upgrade, then when it comes up it'll get picked up and processed. Much more simple.
