### ISSUE TITLE
Reinstate proxies in the wallet

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7771]
With privacy and security focused browsers, users fail to connect the wallet because of the baked-in protections.

See:
- https://github.com/vegaprotocol/frontend-monorepo/issues/3089

We need to provide a fallback solution to ensure users can bypass those protections without telling them to reconfigure there browser (and some browser won't just accept anyway).

We already had a solution in the past: allow loading the webapps behind reverse proxy. And we removed it as we thought it was not necessary anymore. We were wrong. We will have to reinstate it.

## Technical implication

We need a CLI

```bash
vega wallet proxy run --from-url "https://...." --port 1234
```

We need a handler to be implemented to be used as a library so it can be used in the desktop wallet.

**Comment by barnabee** [comment]
I'm not sure we really need to do this.

I have just tested a few browsers on Mac:

- **Firefox** works fine even with uBlock Origin, Privacy Badger and Decentraleyes installed and active.
- **Brave** works as long as you select "Allow all trackers and ads" or turn off "Shields" entirely for the site. Regrettable, especially as this probably unblocks Sentry 😳 but I think it is fine to give users the option to either do one of these steps or download a different browser.
- **Chrome** works as far as I've heard from others but I'm not about to install it to find out.]
- **Safari** doesn't seem to work, doesn't seem to be able to me made to work. Seems to force upgrade connections to localhost or 127.0.0.1 to HTTPS and I can't see a way to turn it off.

So it seems like we could:

- Detect if user is using Brave and tell them about the workarounds and the list of browsers that work on the wallet connection screen
- Detect if user is using Safari and tell them which browsers work on the wallet connection screen
- If there's no wallet found remind users they need to have the wallet app and service running, and let them know which browsers are expected to work

Unless the story is very different on Windows or Linux, I'm, not sure this warrants code changes. I think we just ought to tell people to use a supported browser (or use the workaround in Brave).

We will be pushing all these people to web wallet eventually anyway.

**Comment by ValentinTrinque** [comment]
Alright. Closing then. Will reopen if needed.
