### ISSUE TITLE
CPU is spending 100% time on disk operations and data-node fails behind of the core

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7775]
# Problem encountered

The data-node is constantly getting a bigger gap to the vega-core. Currently, there is a 40k block difference.

After debugging we figured out that the CPU is spending 90-100% of computing time on disk operations:

```shell
daniel@n10:~$ iostat -xmt 1

03/06/23 10:14:05
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           9.38    0.00    4.62   18.38    1.50   66.12

Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz  aqu-sz  %util
...
sda           1632.00     16.20     0.00   0.00    1.09    10.16   63.00      1.73    39.00  38.24    1.19    28.13    0.00      0.00     0.00   0.00    0.00     0.00    0.08 100.00
...
```
What we know from the above line:

- `sda` is a disk for vega and data&node home
- `%util = 100` - it means the CPU spends 100% time of using the disk. In that time, it does nothing else
- `r/s = 1632.00` - our applications requested 1632.00 reads from kernel per seconds
- `rMB/s = 16.20` - it does not matter how many megabytes we want to read if we want to read 1600 times per second.
 What do We want to do with that? The system is very idle, but the disk is very busy. 
 
Possible solutions are:
- Improve the performance of the app
- Put better disk on nodes(there is a chance, that disks are too poor)

I have collected the following data from the node. I collected them for about 20 minutes when the node was still slow.

- [`iotop -a`](https://github.com/vegaprotocol/vega/files/10899336/iotop.txt) - Output of the `iotop -a` command running for about 20 minutes
- [postgresql-14-main.log](https://github.com/vegaprotocol/vega/files/10899346/postgresql-14-main.log) - PostgreSQL, contains all of the queries executed for the 20 minutes
- [`iostat -xmt 1`](https://github.com/vegaprotocol/vega/files/10899378/iostat.txt) - Output of the `iostat -xmt 1` command. It is one line per second.

Base of the `iotop -a` file you can see that most of that is used by postgresql, 

In PostgreSQL, you can see the same queries are repeated every minute. This is single minute period: [postgresq-1m-period.log](https://github.com/vegaprotocol/vega/files/10899425/postgresq-period.log)

You can also see the graph:

![image](https://user-images.githubusercontent.com/1239637/223145822-3c4811ad-0e32-4fa5-9ccd-243040c216ff.png)

N07 has better disk (nvme), but n10 has SSD disk.

This is a dashboard for the iostat in grafana: https://metrics.vega.xyz/d/83wHz3bVz/daniel-iostat?orgId=1&var-instance=n07.testnet.vega.xyz&var-instance=n10.testnet.vega.xyz&var-device=nvme0n1&var-device=sda

There should be no traffic on the `n10.testnet.vega.xyz` data node as caddy is dissabled
![image](https://user-images.githubusercontent.com/1239637/223147521-749bb996-4d19-4f79-8281-eb02c843eda7.png)

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Closing as this issue has been resolved.

The issues seen on stagnet1 today related to this issue have been found to be disk space and will be resolved in ops/infra tasks
