### ISSUE TITLE
Error returned when running erc20SetAssetLimitsBundle graphql query

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7789]
Getting an error when running the below graphql query.

Note: The query returns an error as well as some valid data.

Expected Result: Don't expect to see the error message in the first part of the response.

**Query:**

```
query ExplorerUpdateAssetSignatureBundle 
  { erc20SetAssetLimitsBundle(proposalId: "ef4700e2dd7053e7482a86314fad27d96063f00316ecd47a46c1c3ec85e34520") 
    { signatures nonce } asset(id: "ef4700e2dd7053e7482a86314fad27d96063f00316ecd47a46c1c3ec85e34520") { status }}

```
**Response:**

```
{
  "errors": [
    {
      "message": "no resource corresponding to this id",
      "path": [
        "asset"
      ],
      "extensions": {
        "code": 5,
        "type": "NotFound"
      }
    }
  ],
  "data": {
    "erc20SetAssetLimitsBundle": {
      "signatures": "0x1e4073e2755ce4f6d309097ef89273fc0f631fd7ab101228a11810c59ac6c34034f9a59c55b24c12ff6f74de2f861e854bdd5d1e3723b0e0c1f7c42cd11cb95201f0bc418184978f562461dd5c160d1587cec7ac671332c9d33809265a9c3a17a5447e7cbf2b9d5517a461779af3dc868f67c1cad869cb036790f575a9d3b4122100",
      "nonce": "108228223069268104298663296273982128960325785140320048019042473114348787287328"
    },
    "asset": null
  }
}
```

**Comment by guoguojin** [comment]
Can I get some more information regarding which environment you ran this on? The error is telling me that the asset ID that you have provided in your request doesn't exist which is why you are seeing the error message.

**Comment by MuthuVega** [comment]
Hello @guoguojin 

 - to replicate the issue , run the below test from the below branch and then run the graphql query to see the issue
Test Name - test_graphql_queries
Branch - fix_failing_graphql_tests

**Comment by MuthuVega** [comment]
Also look at this slack thread for more details

https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1678191272688669
