### ISSUE TITLE
LP closeout on stagnet; confirm it's quadratic slippage factor making maint. margin huge

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#7818]
LP party https://api.n06.stagnet1.vega.xyz/api/v2/accounts?filter.partyIds=6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605 got closed out on stagnet1

<img width="297" alt="image" src="https://user-images.githubusercontent.com/62546419/224669942-762fc18d-961e-4f93-bb06-2b45a998652f.png">

Confirm that the reason was that the maintenance margin requirement was huge and that this was primarily coming from the quadratic slippage factor.

**Comment by gordsport** [comment]
Closing as this cannot be recreated - to be reopened if we get more info or the issue presents again
