### ISSUE TITLE
Metabase query is utilizing 100% disk

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7819]
# Problem encountered

Metabase query is calling this query:

```
SELECT "public"."orders_current_desc_by_party"."version" AS "version" FROM "public"."orders_current_desc_by_party" GROUP BY "public"."orders_current_desc_by_party"."version" ORDER BY "public"."orders_current_desc_by_party"."version" ASC LIMIT 1000
```

It is using 90-100% `ioutil%` - It means CPU is spending 90-100% time to execute this query.

After stop metabase connection to stagnet1 and kill the query `%ioutil looks like below`: 
![image](https://user-images.githubusercontent.com/1239637/224681599-7f21e89f-f3f3-44f1-945a-9040e9412928.png)

Before stopping the query it was reading about 100MB/s

![image](https://user-images.githubusercontent.com/1239637/224681872-15b98a5d-2de6-4a4c-851f-031e3de52423.png)

# Evidence

[vega.sql.log](https://github.com/vegaprotocol/vega/files/10956535/vega.sql.log)

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by guoguojin** [comment]
This looks like someone wrote a bad query to test the new view and it's unclear who it was what they're trying to achieve. This doesn't appear to be an issue with data-node directly.

https://vegaprotocol.slack.com/archives/CCBC320RM/p1678705181004399
