### ISSUE TITLE
Update estimateMargin and it's equivalent for liquidation price to use the slippage factors as upper bounds

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#7845]
We now have a cap for the slippage component coming from the slippage factors. Let's update `estimateMargin` and whatever method the liquidation price comes from to take this into account. 

The liquidation price should be derived under the assumption that general + margin balance are there to support the position on the market and that the the party has no position on any other market (or other demands on general account balance).

**Comment by barnabee** [comment]
I believe the API should now return a margin range between theoretical minimum (no slippage component) and maximum (capped slippage component).

**Comment by barnabee** [comment]
Also I think liquidation price is still client side, involves calling the API with the details for the position in question then figuring out the range of MTM price differences the margin plus general balance can tolerate.

However this is not entirely trivial with the non-linearity of slippage so we at least need to provide front end with an algo, or build it into a/the API.

**Comment by davidsiska-vega** [comment]
Superseded by https://github.com/vegaprotocol/vega/issues/7847
