### ISSUE TITLE
Set compression on the tendermint levelDB

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7865]
As part of the investigations into compressing/managing data better we need to investigate if its possible to enable compression on levelDB.

**Comment by ettec** [comment]
Tendermint creates the database as follows using the default goleveldb compression option, there is no way to override this:

https://github.com/cometbft/cometbft-db/blob/a9928b2facbd3c55122287aad51b358382060a91/goleveldb.go#L13


Default GolevelDB compression is:

`	// Compression defines the 'sorted table' block compression to use.
	//
	// The default value (DefaultCompression) uses snappy compression.
	Compression Compression`
	
So compression is already being set.
