### ISSUE TITLE
Feature tests for 0019-MCAL-004, 0019-MCAL-005, 0019-MCAL-007

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7886]
To ensure test coverage for the MCAL spec we need feature tests for:

 - [ ] 0019-MCAL-004
 - [ ] 0019-MCAL-005
 - [ ] 0019-MCAL-007

https://github.com/vegaprotocol/specs/blob/master/protocol/0019-MCAL-margin_calculator.md

**Comment by AnExsomnis** [comment]
The cases 0019-MCAL-004
 0019-MCAL-005
 0019-MCAL-007 do not exist in the specs and the existing ones are all covered by the feature tests.
https://jenkins.ops.vega.xyz/blue/rest/organizations/jenkins/pipelines/common/pipelines/approbation/runs/2434/nodes/177/steps/178/log/?start=0
Closing now.
