### ISSUE TITLE
Target stake/supplied stake calcs using triggering ratio

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7887]
Have a few tests including this one
test_market_triggering_ratio_update_affects_auction_entry

Which were passing on CI using this vega commit 0e724cbbc9dbecb7235634404493e76a1ab19d8d

Any test run on subsequent commits - numerous tests fail.

Following CI full system test runs have many breaking tests whereby market states are not as expected or refused to move to Auction when applying the triggering ratio.

In the test above we need to understand why the market state after updating the markets TR does not move to auction when clearly the  total_stake < TR * Target Stake should cause it to suspend.

**Comment by vega-paul** [comment]
broken tests on d58648d

commit before a change : 9c592f16e88764589b94d71b95447bf4aff61cd4 tests pass





[2:26](https://vegaprotocol.slack.com/archives/D02595S3NS3/p1679322384535349)
This is the merge before Elias changes.

**Comment by EVODelavega** [comment]
Problem found, tests have been updated, and created an integration test to make life easier when dealing with similar issues (#7904 )
