### ISSUE TITLE
Test data node data compression options

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7902]
## Issue

In order to assess the options we have around compressing data on the data node we need to run the following tests on a benchmark node (no compression) then with the ZFS, Timescale and Postgres compressions (inc any feasible combinations).

Once we have run these tests we need to present this information so we can make a decision on which option we should proceed with:

- Data metrics for each of the options vs the bench mark
- Realised pros/cons for each of the options
- Any risks that we should be aware of or accept for each option
- A recommendation of which option we should proceed with  

### 1st-3rd Test:

assess the impact of querying archived data being list old data (that is data that is compressed) 
- by market
- by party
- by ref.   

### 4th test:

Get the current version of an old order e.g., an order that is definitely in the archived chunk set.   

To get realistic numbers the DB should hold a representative amount of data - as much as poss, I would guess minimum 50GB if that is possible, with a majority of that archived.

**Comment by guoguojin** [comment]
https://docs.google.com/document/d/1zavZrODfd7lfdAQdJb6Ee9pyL9diJ5T3wOXQ_1vup4Y/edit
