### ISSUE TITLE
ListLiquidityProvisions Live filter does not return all the current states for ALL LPs

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7903]
ListLiquidityProvisionsRequest/ListLiquidityProvisions

When we have multiple LPs for a market and we use the above request/response endpoints and filter for just the market I expect to get back all the live states.

When we have
LP1 Pending
LP1 Active
LP2 Rejected

Requesting using the market and the live=True we return

LP1 Active

We are missing the live state of LP2 (Rejected)

**Comment by TomMcL** [comment]
Sounds like a conflict between `live = provisions which are live on the market` and `live = latest version of provision for any given LP`. Both seem like useful filters, could even have `latest` for the latter case of "all LPs" and `live` for current behaviour but maybe that's confusing? (And I'm not sure how one would combine the two filters 😄)

**Comment by AnExsomnis** [comment]
Closing, more context here - https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1679397759602189
