### ISSUE TITLE
Enhance tradesConnection and trades subscription with TradeFilter

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#7916]
# Feature Overview

**In order to** Show all trades for multiple pubkeys/markets
**We will** lift the tradesConnection query to the top level
**And** add required filters to the tradesConnection query
**And** add required filters to the trades subscription
**So that** So that users can more easily see all their trades across multiple keys and markets

# Acceptance Criteria

- It is possible to filter trades by one or more marketIds
- It is possible to filter trades by one ore more partyIds
- any system tests that are broken due to this change are fixed (system test issue to be opened)

Note:
- Similar filters were added to the `positions` query
- The `positionsConnection` query was deprecated in favor of a top level `positions` query, perhaps we'd want to do the same here

# Example

```
// SCHEMA CHANGES
TradesFilter {
  partyIds: [ID!],
  marketIds: [ID!],
}

type Query {
  tradesConnection(
    filter: TradesFilter
    pagination: Pagination
    dateRange: DateRange
  ): TradesConnection
}

type Subscription {
  trades(
    filter: TradesFilter
  ): [TradeUpdate!]!
}
```

**Comment by guoguojin** [comment]
@mattrussell36 TradesConnection is a sub-query under orders as well. I'm assuming that the filter should also include a list of orderID's that you want to fetch trades for?

```
TradesFilter {
  partyIds: [ID!],
  marketIds: [ID!],
  orderIds: [ID!],
}
```

**Comment by guoguojin** [comment]
This is going to require a change to the ListTradesRequest protobuf message to allow multiple parties, markets and order ids. This will in turn affect the REST API for ListTrades. 

The GraphQL API should be unaffected as I am able to deprecate the existing TradeConnection subqueries under the Parties, Markets and Orders queries and update the resolvers to support the updated gRPC request message.
