### ISSUE TITLE
Vega nodes sometimes restart after PUP on wrong block height

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#7931]
# Problem encountered
We can sometimes see nodes restart after a protocol upgrade on the wrong block height. In practice, I _think_ this results in no problems _somehow_ (@wwestgarth ?), since any of the tests we currently have seem to maintain consensus if you restart all vega nodes, but if you stop individual nodes and start them again one at a time and check what block height they're on, sometimes a node will report being on the wrong block.

# Observed behaviour
Sometimes nodes still report being on the upgrade block after restart.
```
E           AssertionError: Nodes should not be producing new blocks
E           assert 78 == (78 + 1)
E            +  where 78 = block_height: 78\ngenesis_time: "2023-03-22T13:38:53.8286054Z"\ncurrent_time: "2023-03-22T13:41:52.330508Z"\nvega_time: "2023-03-22T13:40:51.7619297Z"\nstatus: CHAIN_STATUS_CONNECTED\napp_version_hash: "15df8ef44f7fe91845eaa8669be89493e0249b26-modified"\napp_version: "v99.99.0+dev.15df8ef4.modified"\nchain_version: "0.34.27"\nuptime: "2023-03-22T13:41:23.4078292Z"\nchain_id: "testnet-001"\nepoch_seq: 9\nepoch_start_time: "2023-03-22T13:40:46.549935Z"\nepoch_expiry_time: "2023-03-22T13:40:51.549935Z"\n.block_height
E            +    where block_height: 78\ngenesis_time: "2023-03-22T13:38:53.8286054Z"\ncurrent_time: "2023-03-22T13:41:52.330508Z"\nvega_time: "2023-03-22T13:40:51.7619297Z"\nstatus: CHAIN_STATUS_CONNECTED\napp_version_hash: "15df8ef44f7fe91845eaa8669be89493e0249b26-modified"\napp_version: "v99.99.0+dev.15df8ef4.modified"\nchain_version: "0.34.27"\nuptime: "2023-03-22T13:41:23.4078292Z"\nchain_id: "testnet-001"\nepoch_seq: 9\nepoch_start_time: "2023-03-22T13:40:46.549935Z"\nepoch_expiry_time: "2023-03-22T13:40:51.549935Z"\n = <bound method Node.statistics of <modules.vegacapsule.network.Node object at 0x7f499df45df0>>()
E            +      where <bound method Node.statistics of <modules.vegacapsule.network.Node object at 0x7f499df45df0>> = <modules.vegacapsule.network.Node object at 0x7f499df45df0>.statistics

tests/protocol_upgrade/protocol_upgrade_test.py:1809: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /workspace/system-tests/tests/protocol_upgrade/protocol_upgrade_test.py(1809)test_validators_upgrade_with_correct_block_heights()
-> assert node.statistics().block_height == upgrade_block_height + 1, "Nodes should not be producing new blocks"
(Pdb) upgrade_block_height
78
(Pdb) node.statistics().block_height
78
(Pdb)
```

# Expected behaviour
Nodes usually immediately report being on upgrade block height + 1 after restart.

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Automation
The following will run this test 10 times in a row, and bail the first time that it fails.
```
pytest -k test_validators_upgrade_with_correct_block_heights --count 10 -x
```
Note, that these tests will automatically clean up the network once it is done (you'll be able to access the logs, but the network will be blown away. If desired, you can add `--pdb` to the command, it will sit and wait in the broken state while you investigate anything.
Requires this branch: wrong_block_heights_bug

# Evidence

## Logs
[vega-validator-0.stdout-2023-03-22T134123Z.log](https://github.com/vegaprotocol/vega/files/11042674/vega-validator-0.stdout-2023-03-22T13.41.23Z.log)
[vega-validator-1.stdout-2023-03-22T134135Z.log](https://github.com/vegaprotocol/vega/files/11042680/vega-validator-1.stdout-2023-03-22T13.41.35Z.log)
[vega-validator-2.stdout-2023-03-22T133945Z.log](https://github.com/vegaprotocol/vega/files/11042685/vega-validator-2.stdout-2023-03-22T13.39.45Z.log)
In the logs above, I believe I had only restarted 2 of the nodes.
```{"id":"78-3","block":"2D09745E123304AE0312FAFF7D26D858DBD1ECB81264DE44904F285881840782","type":"BUS_EVENT_TYPE_PROTOCOL_UPGRADE_PROPOSAL","protocolUpgradeEvent":{"upgradeBlockHeight":"78","vegaReleaseTag":"v99.99.0+dev.15df8ef4.modified","approvers":["8508b51373d48ab9cfee62a492cd1fccdd4472adaea12b3472057b503a099af7","98c7fa19894a1cd98624206f2ae3ab5250a669177e9bb20a5d4ac4644fc94965","d493e5047605e0cbe48a33e55bee99c734c21b2132368d9f72f585fffb059bc3"],"status":"PROTOCOL_UPGRADE_PROPOSAL_STATUS_APPROVED"},"version":1,"chainId":"testnet-001","txHash":"2D09745E123304AE0312FAFF7D26D858DBD1ECB81264DE44904F285881840782"}```

## Additional context
We see this from time to time in the post-CI protocol upgrade, presumably because that is also checking the block heights of the nodes as part of the checks/comparisons that are going on there. Previously when @wwestgarth and I looked into it, I think we observed that it was harder to reproduce with a larger network. We suspected that vega might be closing down without properly saving some state. This is a little odd, since the test actually waits for 5 seconds before closing down to ensure that none of the nodes were attempting to process any more blocks before the upgrade, so in theory, they ought to have had loads of time to process everything:
```
    # Confirm no blocks are still being generated, i.e: That processing stops.
    # Super rare case where sleep isn't so bad, since we genuinely want to allow *time* to prove no further processing
    # is happening.
    time.sleep(5)
    for node in all_nodes:
        assert node.statistics().block_height == upgrade_block_height

    # Now manually stop to do the upgrade
    for node in all_nodes:
        node.stop()
```

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by karlem** [comment]
Not a protocol update bug. Just found and race condition issue in the actual test code
