### ISSUE TITLE
Mainnet Outage - panic and crash when new validator joined the network

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7936]
## Issue

At 17:43 (GMT) 22/03/22 mainnet alerted to a number of Validator nodes being down for longer than one minute; the network stopped at block 12140183.

### Alert:

https://api0.mainnet.vega.xyz/statistics lag between currentTime and vegaTime is higher than 10seconds for more than 1 minute

### Checkpoint:

20230322173929-12140156-d833359cb648eb315b4d3f9ccaa5092bd175b2f72a9d44783377ca5d7a2ec965

**Comment by JonRay15** [comment]
Removing from known issues board since this was closed a long time ago
