### ISSUE TITLE
Data node is blocking protocol upgrade when it has already block after protocol upgrade block

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7965]
# Problem encountered

We have the following state:

A protocol upgrade has been proposed on block **1008000**.
The data-node has already block: **1008001**
Tendermint has block: **1008000**
Vega has block **1008001**

Previous vega version: `v0.68.2`
We proposed upgrade to `v0.68.5`

Then We restarted vega with version `v0.68.2`(the version before protocol upgrade) from block:  `1007700` - we have added this param to vega command: `--snapshot.load-from-block-height 1007700`

Then vega is printing this log:

```log
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.686Z        INFO        core.protocol.staking.stake-verifier        staking/stake_verifier_snapshot.go:57        serialising pending SR        {"n": 0}
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.704Z        INFO        core.protocol.snapshot        snapshot/engine.go:938        #### saving snapshot took         {"time": 0.007699459}
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.721Z        INFO        core.protocol.snapshot        snapshot/engine.go:926        snapshot taken        {"height": 1008000, "hash": "8fb62a13f57b4d3c516d354bd73ca0ec10af90b369239b8b018b40853c75e036"}
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.721Z        INFO        core.protocol.protocolupgrade        protocolupgrade/engine.go:337        marking vega core as ready to shut down
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.721Z        INFO        core.protocol.processor        processor/abci.go:881        #### snapshot took         {"time": 0.037060419}
Mar 24 10:57:04 n03.validators-testnet.vega.xyz visor[928032]: 2023-03-24T10:57:04.722Z        INFO        core.protocol.processor        processor/abci.go:821        waiting for data node to get ready for upgrade
```

And the data node is never ready. The entire node is stuck in the following state.

More output from commands:

```shell
root@n03:/home/vega/vegavisor_home# sudo -u vega  ./current/vega datanode last-block  --home /home/vega/vega_home
2023-03-24T11:00:30.064Z	INFO	root	commands/last-block.go:82	Last block	{"height": 1008001}
```

```shell
root@n03:/home/vega/vegavisor_home# sudo -u vega  ./current/vega tools snapshot --home /home/vega/vega_home
Snapshots available: 10
	Height: 1008000, Version: 3360, Size 80, Hash: 8fb62a13f57b4d3c516d354bd73ca0ec10af90b369239b8b018b40853c75e036
	Height: 1007700, Version: 3359, Size 80, Hash: 67a1bd7da6281b65f61fe45d544462ae6f413b49068ba0543a5dcceb002f96e4
	Height: 1007400, Version: 3358, Size 80, Hash: c21027e43d963089b036cacd9a7c3f57d806dbc2b15083be7d8c37e964bb901c
	Height: 1007100, Version: 3357, Size 80, Hash: ef32fcee8cc03fe1df1b21d95cbd06f1f80c4ec5c007c20319ff9d11427a1158
	Height: 1006800, Version: 3356, Size 80, Hash: 48649d0380ccfd5022289e67704ae682738bc6f6734c26591ad9bea6cabd3616
	Height: 1006500, Version: 3355, Size 80, Hash: feaca0808f57f9e1e6796b598fc46824579d96dd80aa0b6d47dc51a6ebd6a8bd
	Height: 1006200, Version: 3354, Size 80, Hash: 200ec5468cd2c255f4fd377cd36de4baefc7381226e9d27946fda7bb8d307960
	Height: 1005900, Version: 3353, Size 80, Hash: f44f04129a90acf5fcefdbf516eccef571ed84a89acfa085925383ef713c1565
	Height: 1005600, Version: 3352, Size 80, Hash: 50a9a33497f4c01ea493250436d7cbf55b087a7fc049fe201768adef3815e1c8
	Height: 1005300, Version: 3351, Size 80, Hash: bc1b38714f4e8a92d3ef7e4d3d4fd06e71712a583e43a3188d9d6cd4618916f9
```

# Steps to reproduce

## Manual
See above description how the error happened

# Evidence

The entire log is here: 
[vegavisor.log](https://github.com/vegaprotocol/vega/files/11061388/vegavisor.log)

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilatio
[vegavisor.log](https://github.com/vegaprotocol/vega/files/11061382/vegavisor.log)
n error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by ettec** [comment]
This will be fixed by this issue: https://github.com/vegaprotocol/vega/issues/7759 - being worked on now
