### ISSUE TITLE
data-node: syntax error at or near "from"

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#8018]
# Problem encountered
On `Stagnet 3` with `v0.70.0-12033-6f380d6b` version running.
The Snapshot pipeline (that starts core+data-node from remote snapshot/segment) failed with the following error:
```wrap
failed to initialize datanode from network history: failed to load history into the datanode: failed to load snapshot data:failed to load history segments: failed to load history segment {History Snapshot for Chain ID:vega-stagnet3-202303221357 Height From:614762 Height To:615061}: failed to copy uncompressed data into the database vega-stagnet3-202303221357-614762-615061-historysnapshot : failed to copy data into table order_updates: failed to copy current state table data into database: failed to copy data into current state table: ERROR: syntax error at or near "from" (SQLSTATE 42601)
```
job: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FStagnet3/detail/Stagnet3/15368/pipeline/111

**Comment by pscott31** [comment]
This isn't a bug per-se, but a side effect of my testing out the split order table idea on n00.. We're shelving that for now so we can restart that node. It needs it's database wiping and building up from scratch

**Comment by gordsport** [comment]
@fkondej - based on the above comment can this be closed as 'wont fix'?
