### ISSUE TITLE
Add an API for fetching data from network history

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/vega#8030]
# Feature Overview

**In order to** retrieve archived data that has been removed from the database due to data retention policies
**We will** Provide an API point which retrieves network history segments from the local IPFS (tbc: should it fetch files not locally present?), extracts relevant data and returns it
**So that** We have a method for retrieving archived data

## Specs
- [Link](xyz) tbc; @ettec volunteered to write one

Decisions:
 - What should API look like, e.g. query by block height range | time range | segment id at a time
 - Should we get data for one table or multiple at once
 - Return format? CSV? Currently use postgres' text format so requires a bit of parsing to do  that, we could switch to CSV for segments.

**Comment by ettec** [comment]
I think, if testing shows there is no impact, we should move to csv format for the segments anyway, but do this asap.

**Comment by ettec** [comment]
(tbc: should it fetch files not locally present?)  I would say yes.  One question though, if a user wants to query data not held locally, there will no entry in the nodes network history index for the given block/time range,  what to do in that case?   Its possible given a segment to get the chain of previous segments, but how to get that initial handle in the index does not have the span?
