### ISSUE TITLE
Validator ranking score inconsistency

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8040]
One of our overnight validator promotions test has been failing with the reason being the ranking score expected does not match the actual from the test.

**Spec Ref:**
https://github.com/vegaprotocol/specs/blob/master/protocol/0069-VCBS-validators_chosen_by_stake.md

**AC:**
Swap due to better score ([0069-VCBS-042](https://github.com/vegaprotocol/specs/blob/master/protocol/0069-VCBS-validators_chosen_by_stake.md#0069-VCBS-042)):
Setup a network with 5 Tendermint validators and self-delegate 1000 tokens to each of them.
Announce a new node at the beginning of the epoch, self-delegate to them a total that is 10000 tokens.
At the beginning of the next epoch the new validator should have ranking score equal or lower to all of the Tendermint validators so it doesn’t get promoted. The parameter <incubent_factor> is set sufficiently high to assure this (e.g., 1.1).
In the middle of the epoch, shut node 1 down.
Verify that at the beginning of the next epoch the announced node replaced node 1 as a Tendermint validator.
Restart node 1 again from a snapshot
Verify that node 1 is in a pending state and it’s ranking score is ~ 0.006666666667.

Upon investigation , we found that the raking score expected does not seem to be correct.

Ran the test 15 times back to back and below are the results:

Got the below scores:

0.06000000000000003 - 10 times
0.0666666666666667 - 2 times
0.05333333333333336 - 3 times

But as we can see none of these numbers are anywhere close to `0.006666666667` which is the expected score from the spec.

Please can someone have a look and let us know if this is a core bug OR a spec bug OR a test code bug ?

System Tests Test Name - `test_stop_and_swap`
System Tests Branch - `fix_overnight_failures_1`

**Jenkins Runs:**

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/62785/testReport/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/62824/testReport/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/62869/testReport/

**Comment by gordsport** [comment]
@MuthuVega - closing this as the spec should have been changed now and the test can be reviewed - no core change required ATM
