### ISSUE TITLE
Spot market

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#8119]
# Feature Overview

To be able to create and run a spot market need to implement the following:
* an execution market that behaves similarly to a futures market with the following exceptions
1. no liquidity auctions
2. no oracles or trading termination
3. different liquidity provisioning behaviour
4. different target stake calculation
5. no mark to market or margin requirements
6. no risk model

Ideally this can lift the existing market code. 

## Specs
- [Spot spec](https://github.com/vegaprotocol/specs/blob/3ad0facad09ca18f225a2144b67d6b138ea46f7c/protocol/0080-SPOT-product_builtin_spot.md#sell-orders) 

# Acceptance Criteria
TBD

**Comment by gordsport** [comment]
Closing as implemented in other issues and PRs with the label 'spot'
