### ISSUE TITLE
Protocol Upgrade failed on validator behind Sentry Nodes

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#8136]
# Problem encountered
During today's `Protocol Upgrade` on `Validator's Testnet` our `validator` node failed to upgrade. The `core` did not stop for `Protocol Upgrade` but instead continued running.

Our setup:
- `core validator` running on one machine, with `visor`, it connects only to the three Sentry Nodes,
- 3x `Sentry Node`, each running on a separate machine. Each is run by `visor`, (note: `Sentry Node` is `vega full` node with special CometBFT config, only the connection part is special describing "secret" node).

`core` on every `Sentry Node` was stopped by `visor` as expected, but not on the `validator` node. The logs look very similar on both nodes.
You can view logs on the machine:
```
ssh n01.validators-testnet.vega.xyz
sudo journalctl -u vegavisor --since "2023-04-13 12:59:50"
```
<img width="1728" alt="Screenshot 2023-04-13 at 16 31 43" src="https://user-images.githubusercontent.com/20031574/231816460-893009ad-de68-48f1-acdb-57284caffb09.png">

**Comment by gordsport** [comment]
@fkondej 
Its believed that the linked PR should resolve this. Should the issue persist please let me know and we can re-open or make a new issue with up-to-date details.
