### ISSUE TITLE
datanode hangs on fetching history for segment

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#8137]
# Problem encountered
One of the validators run into the issue that its datanode wrote `fetching history for segment` into the logs, and nothing more. Visor and core kept waiting for datanode forever. They were using `v0.70.2`.

We also see this one on our Snapshot pipeline:
- Fairground running `v0.70.0`: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FFairground/detail/Fairground/20773/pipeline/111
- Validators Testnet running `v0.70.2`: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2FSnapshots%2FValidators-Testnet/detail/Validators-Testnet/4030/pipeline/112
-

**Comment by MuthuVega** [comment]
@ettec - This happens in system tests as well - hanging when fetching a segment

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/65824/testReport/
