### ISSUE TITLE
vegatools diff pipeline reporting mismatches

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8141]
The below step in the system tests pipeline is reporting a data mismatch between vega core and datanode.

**Error Pipeline:**

https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/65849/pipeline/

**To recreate:**

Run a new system tests Jenkins job with the below params:

SYSTEM_TESTS_TEST_MARK = orders

**Comment by pscott31** [comment]
I'm pretty sure this will be fixed by this PR i just merged in vegatools

https://github.com/vegaprotocol/vegatools/pull/280

it works locally so I'll close for now - please reopen if you see any other strangeness
