### ISSUE TITLE
Cannot `IssueSignatures` across a checkpoint restore

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#8188]
# Problem encountered

If the multisig contract is not up-to-date and a checkpoint restore occurs, the ability to ask the Vega network for signatures to update the contract is lost because we do not store the `PendingSignatures` data in the checkpoint file.

This came up when looking at the state of the multisig contract on the validator-testnet. Before the recent checkpoint restart the multisig was out of sync and Vega knew about it happily ready for someone to send in an `IssueSignature` command. Now the restore has occurred the multisig is still out of sync, but you can no longer use `IssueSignature` to get the signatures.

Note: This may be less of an issue with multisig V2 because we won't need a history off adds/removes to resolve the contract. We will just need someone to tweak their stake to get a new bundle.

# Observed behaviour
A clear and concise description of how the system is behaving.

# Expected behaviour

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
@wwestgarth - please can you check in with @karlem as this may have been fixed

**Comment by wwestgarth** [comment]
> @wwestgarth - please can you check in with @karlem as this may have been fixed

I think @karlem fix was about snapshots and protocol upgrades. This is checkpoints. In retrospect, I don't know how much we care because in real life we can make sure that the multisig is up to date before and we have all the signatures we need before we do checkpoint restore in mainnet.
