### ISSUE TITLE
Data source decimal places field is missing from oracle events

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8206]
When setting up an oracle we submit the trx and include decimal_places for the data source.

Both the oracle event spec and data include info on the trm and settlement conditions but do not specify the decimal places. I feel this should be added the the event.

**Comment by EVODelavega** [comment]
When it comes to oracle data (settlement of a market), I don't think the resulting events should specify decimal places. Any value we receive is scaled to match the asset decimals. If we were to send out an event with a scaled value, but include the decimal places field, that's most likely going to result in people seeing that data, and assuming that conversion hasn't been applied yet.

**Comment by EVODelavega** [comment]
OK, to clarify: The oracle spec does not contain any information about decimal places. Once oracle data is provided for a property type integer or decimal, the data can specify a number of decimal places, which will then be used to scale the received data to asset precision, before the data is passed on to the market(s), and the datanode. This essentially means that all pubkeys which can provide oracle data can do so using however many decimal places they want, and that vega, when receiving this data, will normalise all values to the asset decimals. This is why no event will contain decimal places as a field, just the value scaled to asset decimals.
