### ISSUE TITLE
Unable to terminate a market post update market trx using same spec key name

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8211]
Consider the following

Market setup with term spec key_name term1 and settlement spec key_name settle1, pubkey = user1

market specs are updated via update market trx , this terminates the current oracle specs
new oracle specs are created with term1 and settle1 key names

user attempts to terminate the market using term1 for wallet_id user1, core rejects with msg

```
"the network could not process the transaction: no one listens to the public keys that signed this oracle data 
```

**Comment by ze97286** [comment]
@vega-paul can you attach the tests please?
