### ISSUE TITLE
Automated docs PR generates nearly duplicate swagger files

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#8214]
# Problem encountered
https://github.com/vegaprotocol/documentation/pull/584/ and the other PRs like it are created automatically when core tags a release. It's mostly good, but generates more files than it need to. And some of them, weirdly, are different

# Observed behaviour
https://github.com/vegaprotocol/documentation/pull/584/files#diff-ea367e5c237c4769db9dfedcc5ab8ec06d7ea1e1030ee63553fb40bd7ff620f9 and https://github.com/vegaprotocol/documentation/pull/584/files#diff-86c61942d9a245960b55c044cee6f350285409b26cbf5a61494bae6143849c00 are both nearly the same file. Except one of them has an empty `paths` object.

# Expected behaviour
- Only one version of each swagger file exists
- Every swagger file contains a `paths` property and it contains valid endpoints

**Comment by jeremyletang** [comment]
we will not be addressing this.
