### ISSUE TITLE
Cannot query for built in assets

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#8229]
# Problem encountered
Cannot query for built in asset by id

# Observed behaviour
`invalid asset id` error

# Expected behaviour
asset data

# System response
Query
```
query {
  asset(id:"XYZgamma") {
    symbol
  }
  assetsConnection {
    edges {
      node {
        id
        symbol
      }
    }
  }
}
```

Result
```
{
  "errors": [
    {
      "message": "invalid asset ID",
      "path": [
        "asset"
      ],
      "extensions": {
        "code": 3,
        "type": "InvalidArgument"
      }
    }
  ],
  "data": {
    "asset": null,
    "assetsConnection": {
      "edges": [
        {
          "node": {
            "id": "fdf0ec118d98393a7702cf72e46fc87ad680b152f64b2aac59e093ac2d688fbb",
            "symbol": "USDT-T"
          }
        },
        ...
        {
          "node": {
            "id": "XYZgamma",
            "symbol": "XYZgamma"
          }
        }
      ]
    }
  }
}
```

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. Go to graphql playground
2. Run the query above
3. Note that the fragment for a specific query fails

**Comment by daniel1302** [comment]
We do not have any more of those assets in the devnet1. I have replaced broken name with a valid one. One of the PRs is here: https://github.com/vegaprotocol/networks-internal/pull/242/files

**Comment by gordsport** [comment]
@mattrussell36 - based on the comment above can this be closed?

**Comment by daniel1302** [comment]
There is a PR to replace them in the other networks. https://github.com/vegaprotocol/networks-internal/pull/243

**Comment by gordsport** [comment]
Closing as the above PR has been merged
