### ISSUE TITLE
Datanode - command help options incorrect

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8268]
The help option for the datanode rollback command is incorrect and needs amending.

```
Muthus-MBP:networkdata muthupandianvadivelu$ ./vega datanode network-history rollback -h
Usage:
  datanode [OPTIONS] network-history rollback [rollback-OPTIONS]

Help Options:
  -h, --help                                                                        Show this help message

[rollback command options]
          --home=                                                                   Path to the custom home for vega
          --gateway-enabled=[true|false]                                            
          --auto-initialise=[true|false]                                            if true the node will attempt to load the latest history segment(s) from network history if the node is empty
          --chainID=
          --max-memory-percent=                                                     The maximum amount of memory reserved for the data node (default: 33%)
      -f, --force                                                                   do not prompt for confirmation

    Admin:
          --admin.log-level=

    Server:
          --admin.server.socket-path=                                               Listen for connection on UNIX socket path <file-path>
          --admin.server.http-path=                                                 Http path of the socket HTTP RPC server

    API:
          --api.log-level=
          --api.timeout=
          --api.port=
          --api.web-ui-port=
          --api.web-ui-enabled=
          --api.reflection=
          --api.ip=
          --api.stream-retries=
          --api.core-node-ip=
          --api.core-node-grpc-port=
          --api.max-subscription-per-client=
```

**Comment by ettec** [comment]
As discussed with @MuthuVega this issue is across most (all?) commands not just network history,  so for example:

data-node network-history -h shows:

`Usage:
  data-node [OPTIONS] network-history <command>

commands for managing network history

Help Options:
  -h, --help      Show this help message

Available commands:
  copy                               copy a history segment from network history to a file
  fetch                              fetch <history segment id> <blocks to fetch>, fetches the given segment and all previous segments until <blocks to fetch> blocks have been retrieved
  latest-history-segment             latest-history-segment returns the id of the node's latest history segment
  latest-history-segment-from-peers  latest-history-segment-from-peers returns the id of the networks latest history segment
  list-active-peers                  list the active datanode peers
  load                               load [from height] [to height], loads the given span of network history into the datanode, if no span is specified the latest contiguous network history will be loaded
  rollback                           rollback [to height], rolls back the datanode to the given height, the rollback height must match the to height of a network history segment
  show                               shows network history segments currently stored by the node
`
However, `data-node network-history rollback -h` shows the following noise, without a succint description of the command and with loads of irrelevent noise (this is the same across all commands)

`Usage:
  data-node [OPTIONS] network-history rollback [rollback-OPTIONS]

Help Options:
  -h, --help                                                                        Show this help message

[rollback command options]
          --home=                                                                   Path to the custom home for vega
          --gateway-enabled=[true|false]                                            
          --auto-initialise=[true|false]                                            if true the node will attempt to load the latest history segment(s) from network history if
                                                                                    the node is empty
          --chainID=
          --max-memory-percent=                                                     The maximum amount of memory reserved for the data node (default: 33%)
      -f, --force                                                                   do not prompt for confirmation

    Admin:
          --admin.log-level=

    Server:
          --admin.server.socket-path=                                               Listen for connection on UNIX socket path <file-path>
          --admin.server.http-path=                                                 Http path of the socket HTTP RPC server

    API:
          --api.log-level=
          --api.timeout=
          --api.port=
          --api.web-ui-port=
          --api.web-ui-enabled=
          --api.reflection=
          --api.ip=
          --api.stream-retries=
          --api.core-node-ip=
          --api.core-node-grpc-port=
          --api.max-subscription-per-client=

    rate-limits:
          --api.enabled                                                             Enable rate limit of API requests per IP address. Based on a 'token bucket' algorithm
          --api.rate=                                                               Refill rate of token bucket; maximum average request rate
          --api.burst=                                                              Size of token bucket; maximum number of requests in short time window
          --api.ttl=                                                                Time after which inactive token buckets are reset
          --api.banfor=                                                             If IP continues to make requests after passing rate limit threshold, ban for this duration.
                                                                                    Setting to 0 seconds disables banning.

    CandlesV2:
          --candlesv2.log-level=

    CandleUpdates:
          --candlesv2.candleupdates.candle-updates-stream-buffer-size=              buffer size used by the candle events stream for the per client per candle channel
          --candlesv2.candleupdates.candle-updates-stream-interval=                 The time between sending updated candles
          --candlesv2.candleupdates.candles-fetch-timeout=                          Maximum time permissible to fetch candles
          --candlesv2.candleupdates.candle-updates-stream-subscription-buffer-size= size of the buffer used to hold pending subcribe/unsubscribe requests

    Logging:
          --logging.env=[dev|custom]

    Sqlstore:
          --sqlstore.wipe-on-startup=                                               deprecated, use data-node unsafe_reset_all command instead
          --sqlstore.log-level=
          --sqlstore.use-embedded=                                                  Use an embedded version of Postgresql for the SQL data store
          --sqlstore.fan-out-buffer-size=                                           buffer size used by the fan out event source
          --sqlstore.disable-min-retention-policy-use-in-sys-test-only=             Disables the minimum retention policy interval check - only for use in system tests
          --sqlstore.retention-period=                                              Set the retention level for the database. standard, archive, or lite
          --sqlstore.verbose-migration=                                             Enable verbose logging of SQL migrations

    ConnectionConfig:
          --sqlstore.ConnectionConfig.host=
          --sqlstore.ConnectionConfig.port=
          --sqlstore.ConnectionConfig.username=
          --sqlstore.ConnectionConfig.password=
          --sqlstore.ConnectionConfig.database=
          --sqlstore.ConnectionConfig.socket-dir=                                   location of postgres UNIX socket directory (used if host is empty string)
          --sqlstore.ConnectionConfig.max-conn-lifetime=
          --sqlstore.ConnectionConfig.max-conn-lifetime-jitter=
          --sqlstore.ConnectionConfig.max-conn-pool-size=
          --sqlstore.ConnectionConfig.min-conn-pool-size=

    ConnectionRetryConfig:
          --sqlstore.ConnectionRetryConfig.max-retries=                             the maximum number of times to retry connecting to the database
          --sqlstore.ConnectionRetryConfig.initial-interval=                        the initial interval to wait before retrying
          --sqlstore.ConnectionRetryConfig.max-interval=                            the maximum interval to wait before retrying
          --sqlstore.ConnectionRetryConfig.max-elapsed-time=                        the maximum elapsed time to wait before giving up

    LogRotationConfig:
          --sqlstore.LogRotationConfig.max-size=                                    the maximum size of the log file in bytes
          --sqlstore.LogRotationConfig.max-age=                                     the maximum number of days to keep the log file

    Gateway:
          --gateway.port=                                                           Listen for connection on port <port>
          --gateway.ip=                                                             Bind to address <ip>
          --gateway.log-level=[debug|info|warning]
          --gateway.timeout=
          --gateway.subscription-retries=                                           
          --gateway.graphql-playground=                                             Enables the GraphQL playground
          --gateway.max-subscription-per-client=                                    Maximum graphql subscriptions allowed per client
          --gateway.https-enabled=                                                  If true, GraphQL gateway will require an HTTPS connection
          --gateway.auto-cert-domain=                                               Automatically generate and sign https certificate via LetsEncrypt
          --gateway.certificate-file=                                               Path to SSL certificate, if using HTTPS but not autocert
          --gateway.key-file=                                                       Path to private key, if using HTTPS but not autocert

    Node:
          --gateway.node.port=                                                      Listen for connection on port <port>
          --gateway.node.ip=                                                        Bind to address <ip>

    GraphQL:
          --gateway.graphql.enabled=                                                Start the GraphQl gateway
          --gateway.graphql.complexity-limit=
          --gateway.graphql.endpoint=                                               Endpoint to expose the graphql API at

    REST:
          --gateway.rest.enabled=[true|false]                                       Start the REST gateway
          --gateway.rest.apm-enabled=[true|false]                                   

    CORS:
          --gateway.cors.allowed-origins=                                           Allowed origins for CORS
          --gateway.cors.max-age=                                                   Max age (in seconds) for preflight cache

    RateLimits:
          --gateway.rate-limits.enabled                                             Enable rate limit of API requests per IP address. Based on a 'token bucket' algorithm
          --gateway.rate-limits.rate=                                               Refill rate of token bucket; maximum average request rate
          --gateway.rate-limits.burst=                                              Size of token bucket; maximum number of requests in short time window
          --gateway.rate-limits.ttl=                                                Time after which inactive token buckets are reset
          --gateway.rate-limits.banfor=                                             If IP continues to make requests after passing rate limit threshold, ban for this duration.
                                                                                    Setting to 0 seconds disables banning.

    Metrics:
          --metrics.log-level=                                                      
          --metrics.timeout=                                                        
          --metrics.port=                                                           
          --metrics.path=                                                           
          --metrics.enabled=                                                        

    Broker:
          --broker.log-level=
          --broker.socket-server-inbound-buffer-size=
          --broker.socket-server-outbound-buffer-size=
          --broker.use-event-file=                                                  set to true to source events from a file
          --broker.panic-on-error=                                                  if an error occurs on event push the broker will panic, else log the error
          --broker.use-buffered-event-source=                                       if true datanode will buffer events
          --broker.event-bus-client-buffer-size=

    Socket:
          --broker.socket.ip=                                                       
          --broker.socket.port=                                                     
          --broker.socket.max-receive-timeouts=
          --broker.socket.transport-type=

    FileEventSourceConfig:
          --broker.fileeventsource.directory=                                       the directory container the event files
          --broker.fileeventsource.send-buffer-size=                                size of channel buffer used to send events to broker

    BufferedEventSource:
          --broker.bufferedeventsource.events-per-file=                             the number of events to store in a file buffer, set to 0 to disable the buffer
          --broker.bufferedeventsource.send-buffer-size=                            sink event channel buffer size
          --broker.bufferedeventsource.archive                                      archives event buffer files after they have been read, default false
          --broker.bufferedeventsource.archive-maximum-size=                        the maximum size of the archive directory

    Service:
          --service.log-level=

    Pprof:
          --pprof.level=
          --pprof.enabled
          --pprof.port=
          --pprof.profiles-dir=
          --pprof.block-profile-rate=
          --pprof.mutex-profile-fraction=
          --pprof.write-every=                                                      write pprof files at this interval; if 0 only write on shutdown

    NetworkHistory:
          --networkhistory.log-level=
          --networkhistory.enabled=                                                 set to false to disable network history
          --networkhistory.wipe-on-startup=                                         deprecated and ignored, use data-node unsafe_reset_all command instead
          --networkhistory.publish=                                                 if true this node will create and publish network history segments
          --networkhistory.fetch-retry-max=                                         maximum number of times to retry fetching segments - default 10
          --networkhistory.retry-timeout=                                           time to wait between retries, increases with each retry - default 5s

    Store:
          --networkhistory.store.peer-id=                                           the ipfs peer id of this node
          --networkhistory.store.priv-key=                                          the ipfs priv key of this node
          --networkhistory.store.bootstrap-peers=                                   a list of the multiaddress of bootstrap peers, will be used in addition to the ipfs default
                                                                                    peers if enabled
          --networkhistory.store.swarm-port=                                        ipfs swarm port
          --networkhistory.store.swarm-key-override=                                optional swarm key override, the default behaviour is to use the datanode's chain id'
          --networkhistory.store.history-retention-block-span=                      the block span of history, from the most recent history segment, that should be retained

    Snapshot:
          --networkhistory.snapshot.wait-for-creation-lock-timeout=                 the maximum a caller to create snapshot should have to wait to acquire the creation lock

    Initialise:
          --networkhistory.initialise.to-segment=                                   the segment to initialise up to, if omitted the datanode will attempt to fetch the latest
                                                                                    segment from the network
          --networkhistory.initialise.block-count=                                  the minimum number of blocks to fetch
          --networkhistory.initialise.timeout=                                      maximum time allowed to auto-initialise the node
          --networkhistory.initialise.grpc-api-ports=                               list of additional ports to check to for api connection when getting latest segment

`
