### ISSUE TITLE
Add some additional data for proposals queries

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/vega#8275]
# Feature Overview

Please add the asset name in the in the 'UpdateAsset' type proposal terms data, and the market name in the 'UpdateMarket' type. This allows us to display some extra requested proposals data on Governance without requiring further queries.

**Comment by jeremyletang** [comment]
This won’t be implemented, just call the endpoints to get these by ID please.

**Comment by sam-keen** [comment]
@jeremyletang Would it not be preferable to reduce calls to the API? I'll need to double the calls for these proposal list items
