### ISSUE TITLE
[Bug]: Console listing of market info does not show internal data source details

### ISSUE THREAD

**Issue by AnExsomnis** [vegaprotocol/vega#8299]
### Problem encountered

Listing of data for a market does not show internal data source properly

### Observed behaviour

Console listing of market info does not show internal data source details - behavior is fully described here - https://github.com/vegaprotocol/frontend-monorepo/issues/3765

### Expected behaviour

Expect to see internal data source details properly listed

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

0.71.4

**Comment by gordsport** [comment]
When this is deployed to mainnet we may need to revist the following issue in the FE team:

- https://github.com/vegaprotocol/frontend-monorepo/issues/3765
