### ISSUE TITLE
Data source settlement trx returns success when filter condition is not met

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8308]
This jenkins test

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/70477/testReport/junit/tests.data_sources/dsrm_test/test_reject_duplicated_or_filtered_out_messages/

A terminated market is then settled using a trx with a price of "70". the market has a settlement filter of >= "130" but the settlement trx is accepted and returns a transactionHash. This is not expected - we check for no hash in this case.

Cannot produce locally
Evidence on run above.

**Comment by gordsport** [comment]
@vega-paul - if this cant be reproduced locally it possible implies that there is something happing in the tests / test-infra that may be causing this.

I suggest transferring to the system-tests repo for further triage

**Comment by gordsport** [comment]
closing as no update from above comment
