### ISSUE TITLE
Margin level stream API ObserveMarginLevels returns no data

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8315]
This endpoint returns no data and evntually reaches timeout without returning existing margin levels returns on ListMarginLevels API.

Have a market with orders and positions
Raised two crossing orders with new parties
Filtering using request ObserveMarginLevelsRequest with market ID and one of the new PartyIDs
No margin level data is returned on the stream.

**Comment by gordsport** [comment]
this is not believed to be a bug - can it please have further details added or be closed
