### ISSUE TITLE
[Bug]: LP Price range validation seems off

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#8317]
### Problem encountered

validateLpPriceRange for market proposal requires lp price range to be in (0, 100]:

```
func validateLpPriceRange(lpPriceRange num.Decimal) (types.ProposalError, error) {
	if lpPriceRange.IsZero() || lpPriceRange.IsNegative() || lpPriceRange.GreaterThan(num.DecimalFromInt64(100)) {
		return types.ProposalErrorLpPriceRangeNonpositive, fmt.Errorf("proposal LP price range has incorrect value, expected value in (0,100], got %s", lpPriceRange.String())
	}
	return types.ProposalErrorUnspecified, nil
}
```

However from how lpPriceRange is used it doesn't make sense for it to be > 1 or it would give a negative bid price:

```
func (m *Market) computeValidLPVolumeRange(bestStaticBid, bestStaticAsk *num.Uint) (*num.Uint, *num.Uint) {
	mid := bestStaticBid.ToDecimal().Add(bestStaticAsk.ToDecimal()).Div(num.DecimalFromFloat(2))

	lbD := num.DecimalOne().Sub(m.lpPriceRange).Mul(mid)
	ubD := num.DecimalOne().Add(m.lpPriceRange).Mul(mid)
```

### Observed behaviour

validation of price range seems wrong. 

### Expected behaviour

validation of price range won't allow for entering lpPriceRange > 1.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

v0.71.4

**Comment by witgaw** [comment]
This was deliberate to allow specifying an upper bound higher than 2x current mid price. If you look further down in the code the lower bound gets floored at the minimum valid price (1 tick):

https://github.com/vegaprotocol/vega/blob/8ff5adaca4f9331754b9c0c67db56f6a37e411d7/core/execution/liquidity_provision.go#L550-L553
