### ISSUE TITLE
GRPC-Stream API market_data returns "Internal error"

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8322]
When ObserveMarketsDataRequest/ObserveMarketsData is used to return latest market data updates it returns "Internal error" below

Request made with marketId

<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:3027 {created_time:"2023-05-18T15:32:52.403122+01:00", grpc_status:13, grpc_message:"Internal error"}"
>

**Comment by gordsport** [comment]
this is not believed to be a bug - can it please have further details added or be closed
