### ISSUE TITLE
Investigate: flickering PnL issue seen in Fairground

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8362]
## Issue

During use of fairground it has been noticed that the PnL value is flickering. On investigation it was identified that the resulting cashflow when the market settled was correct. 

We need to check this during a load test to help investigate why this flickering is occurring.  

### Pubkey used

6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605

### Additional information

This issue was worked on and relates to this persisting issue:

- https://github.com/vegaprotocol/vega/pull/7714

### Screenshots. 

Real profit is 28. Fake profit is -80,880.

![Image](https://github.com/vegaprotocol/vega/assets/83510148/748c02e6-18d0-4f7e-b882-6edbcff7903d)

![Image](https://github.com/vegaprotocol/vega/assets/83510148/4116d6ef-0b79-4c5b-85b2-d5fb35007328)

**Comment by peterbarrow** [comment]
I tried to reproduce this locally without success.
After speaking with Lewis I was able to see the issue by subscribing to the positions stream for the pubkey mentioned above. An incorrect positions update is sent out and then it is followed by the correct version. The time between the correct and incorrect message can be almost instant or sometimes many seconds. The incorrect numbers are usually emitted after a change in openVolume. Sometime only one of the PnL values is incorrect, sometimes they both are.

```
2023/05/30 14:29:02 {"id":"f6eccbea-d6d7-4f62-9051-a792cfff44f4","type":"data","payload":{"data":{"positions":[{"realisedPNL":"-28042737441","openVolume":"2247","unrealisedPNL":"-6272947644","averageEntryPrice":"279173","marketId":"2dca7baa5f7269b08d053668bca03f97f72e9a162327eebd941c54f1f9fb8f80","partyId":"6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605"}]}}} server
2023/05/30 14:29:03 {"id":"f6eccbea-d6d7-4f62-9051-a792cfff44f4","type":"data","payload":{"data":{"positions":[{"realisedPNL":"-83876717450","openVolume":"2245","unrealisedPNL":"-6267364256","averageEntryPrice":"279173","marketId":"2dca7baa5f7269b08d053668bca03f97f72e9a162327eebd941c54f1f9fb8f80","partyId":"6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605"}]}}} server
2023/05/30 14:29:06 {"id":"f6eccbea-d6d7-4f62-9051-a792cfff44f4","type":"data","payload":{"data":{"positions":[{"realisedPNL":"-125736471","openVolume":"2245","unrealisedPNL":"7909241","averageEntryPrice":"279173","marketId":"2dca7baa5f7269b08d053668bca03f97f72e9a162327eebd941c54f1f9fb8f80","partyId":"6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605"}]}}} server
```
