### ISSUE TITLE
[Bug]: 'the public key is required' returned from 'admin.sign_message`

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/vega#8376]
### Problem encountered

'the public key is required' returned from 'admin.sign_message` even if publicKey is provided (it changed from pubkey to publicKey in one of the latest updates in openrpc). It blocks desktop-wallet to be up to date with latest changes.

![image](https://github.com/vegaprotocol/vega/assets/24473278/2ef51a9b-55a2-4c86-87fb-6db7127c541b)
![image](https://github.com/vegaprotocol/vega/assets/24473278/c9fe0045-8d2e-4878-87f1-524584e08c63)

May be caused by following piece of code in `vega`

```
if params.PubKey == "" {
		return AdminSignMessageParams{}, ErrPublicKeyIsRequired
	}
```

```
type AdminSignMessageParams struct {
	Wallet         string `json:"wallet"`
	PubKey         string `json:"publicKey"`
	EncodedMessage string `json:"encodedMessage"`
}
```

### Observed behaviour

see above

### Expected behaviour

see above

### Steps to reproduce

```bash
https://github.com/vegaprotocol/vegawallet-desktop/pull/705

1. Build & run vegawallet-desktop
2. Open wallet
3. Open key
4. Try to sign message
```

### Software version

v0.71.4

**Comment by ValentinTrinque** [comment]
The documentation is aligned with the code. The code in the desktop-wallet should use the `publicKey` name
