### ISSUE TITLE
[Bug]: Non-Deterministic behaviour in delegations engine

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#8412]
### Problem encountered

Delegation events are submitted in different orders.  Can see this by the sequence number difference from this network history segment diff below.   Looks like the events need to be ordered by node id.  This is the first difference, occurred at segment 12601-12900.  Looks like events where fired as a result of an epoch event, as they have the same vega time as this epoch event:

`544 | 2023-05-08 17:41:51.603409+00 | 2023-05-09 17:41:51.603409+00 | 2023-05-09 17:41:54.346672+00 | \x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1 | 2023-05-09 17:41:54.346672+00`

Which would suggest some non-determinism in the `onEpochEvent` of the delegation engine, however, the code looks like it is correctly sorting before sending the events.

The code in datanode assigns the sequence number to each delegation as below, the sequence number assigned to the delegation object is determined by the order in which the event is received, which suggests different order of events from the nodes.

```
func (ds *Delegation) consume(ctx context.Context, event DelegationBalanceEvent) error {
	protoDBE := event.Proto()
	delegation, err := entities.DelegationFromEventProto(&protoDBE, entities.TxHash(event.TxHash()))
	if err != nil {
		return errors.Wrap(err, "unable to parse delegation")
	}

	delegation.VegaTime = ds.vegaTime
	delegation.SeqNum = event.Sequence()

	if err := ds.store.Add(ctx, delegation); err != nil {
		return errors.Wrap(err, "error adding delegation")
	}

	return nil
}
```

Values shown in the diff below correspond to these columns:

`party_id,node_id,epoch_id,amount,tx_hash,vega_time,seq_num`

History segment diff output

```
< \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\xb861c11eb825d55f835aec898b3caae66a681a354bcb59651d5b3faf02b34844,545,8244847001117249533626,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,11
< \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\x55504e9bfd914a7bbefa342c82f59a2f4dee344e5b6863a14c02a812f4fbde32,545,11981219453102414262312,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,12
< \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\x6f4a5c540b31d7643cd0187fab82fa26edae53f8aeb6fdcf9b257fd61c74b245,545,1457663463332234004697,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,13
---
> \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\x55504e9bfd914a7bbefa342c82f59a2f4dee344e5b6863a14c02a812f4fbde32,545,11981219453102414262312,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,11
> \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\x6f4a5c540b31d7643cd0187fab82fa26edae53f8aeb6fdcf9b257fd61c74b245,545,1457663463332234004697,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,12
> \x8218d363beb1ad27bf0ab6565ab9d777865b0c952eb786621b257790e6eb762b,\xb861c11eb825d55f835aec898b3caae66a681a354bcb59651d5b3faf02b34844,545,8244847001117249533626,\x7a07c382d6677dd91fed9087f0ead863b777ff81939306eca93db1534b39c3c1,2023-05-09 17:41:54.346672+00,13
```

### Observed behaviour

"

### Expected behaviour

"

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

0.71.5

**Comment by ze97286** [comment]
this is caused by the processing of auto delegation at the end of the epoch. The emitting of events for auto delegation for multiple nodes of the party is not done on a sorted list of nodes but rather on the map of node to amount which leads to the non-determinism. 

In the end of the epoch on the 9th of May we processed auto delegation and the party above has increased their stake on the morning of that epoch. As they were eligible for auto delegation their new stake has been auto delegated to the 3 validators they already had stake on which led to the 3 events with random order across the different validators.
