### ISSUE TITLE
Ethereum Oracles: Normaliation

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/vega#8417]
An Ethereum contract call returns a list of arbitrarily typed objects

The data sourcing/filtering system needs a map of string, string key value pairs.

Extend the Ethereum call spec with a way of extracting named bits of data from the call result, probably using something like [jsonpath](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html).

**Comment by gordsport** [comment]
todo:

- support for structs
