### ISSUE TITLE
A market that should get cancelled for sitting in an opening auction too long 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#8421]
A bit of spec that got ommitted:
```
Enactment date is passed by more than the maximum opening auction extension duration Network Parameter → Cancelled (the market ceases to exist, auction orders are cancelled, and no uncrossing occurs)
```
https://github.com/vegaprotocol/specs/blob/master/protocol/0043-MKTL-market_lifecycle.md#pending 

See also https://github.com/vegaprotocol/specs/issues/1728 for an incoming spec AC.

**Comment by gordsport** [comment]
This will be scheduled once we get the feature market changes in and know where we are
