### ISSUE TITLE
Vote totalGovernanceTokenWeight updates take excessive time which causes proposal to decline

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8433]
See this run
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/73283/pipeline/

test submits proposal and three votes
voter1 submits a Y vote
voter2 submits a Y and N vote
transaction_result events shows 3 votes Y,N,Y

vote events shows 5 votes, the votes are duplicated YYY, NN, one Yes /No vote duplicates in same block

proposal declines 
PROPOSAL_ERROR_MAJORITY_THRESHOLD_NOT_REACHED

updated votes appear with a block/seq > declined trx block/seq
the vote update of totalGovernanceTokenWeight takes 21 blocks which causes the proposal to decline

**Comment by vega-paul** [comment]
duplicates have requiredParticipation updates at 0.5

**Comment by gordsport** [comment]
this is not believed to be a bug - can it please have further details added or be closed
