### ISSUE TITLE
[Bug]: v0.71.6 RC makes it impossible to have a market with 0-length opening auction.

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8477]
### Problem encountered

(Discovered by @TomMcL ) Previously, it was possible to set closing time and enactment time for a market proposal to have the same timestamp, and if so, the market would leave opening auction as soon as the requisite conditions were met. It seems that this is no longer the case.

### Observed behaviour

Market with enactment timestamp == closing timestamp does not leave opening auction.

### Expected behaviour

Can leave opening auction

### Steps to reproduce

```bash
1. Using the following system test branch: https://github.com/vegaprotocol/system-tests/tree/propose_faster (develop system tests have a 2s opening auction. This branch changes to 0-length)
2: Any test which trades: i.e: `pytest tests/matching_engine -k test_FilledIOCMarketOrder`
3: At a certain point, test will report that it was unable to find a trade, since the market never left opening auction
```

### Software version

d95ce8e2707c6aa6ee4b103c30c8aff66bd6820d

### Relevant log output

```shell
(Pdb) marketsTrading.get_market(marketId)
{'id': 'e6368f4f20aaf293a8449a624a50a99dedfc8c1a7cd0bfe60044856b5e3139ef', 'tradableInstrument': {'instrument': {'code': 'CRYPTO:VEGA CORE SYS TEST', 'name': 'Futures System-Tests Market', 'metadata': {'tags': ['asset_class:fx/crypto', 'product:futures']}, 'future': {'settlementAsset': '78b5d40c406751650d1ad7aa82300ccee720a714a5aa212b91d67de46e613fd4', 'quoteName': 'USD', 'dataSourceSpecForSettlementData': {'id': 'd4159ff897f0d44bd3ffab001b7d6138472be51196c1517e2e54061487478929', 'data': {'external': {'oracle': {'signers': [{'pubKey': {'key': 'd22a46d13daa0f2cbe3bfd24cd9cacee2acbd7706926c2ae8921147254c41991'}}], 'filters': [{'key': {'name': 'oracle.test.settlement69F5A', 'type': 'TYPE_INTEGER', 'numberDecimalPlaces': '5'}, 'conditions': [{'operator': 'OPERATOR_GREATER_THAN_OR_EQUAL', 'value': '0'}]}]}}}, 'createdAt': '0', 'updatedAt': '0', 'status': 'STATUS_UNSPECIFIED'}, 'dataSourceSpecForTradingTermination': {'id': 'f52ac0be020201ea2045a43da1a1be08fba8bb91fb15622a4974ed95f4dc6a82', 'data': {'external': {'oracle': {'signers': [{'pubKey': {'key': 'd22a46d13daa0f2cbe3bfd24cd9cacee2acbd7706926c2ae8921147254c41991'}}], 'filters': [{'key': {'name': 'oracle.test.terminationA4623', 'type': 'TYPE_BOOLEAN'}, 'conditions': [{'operator': 'OPERATOR_EQUALS', 'value': 'True'}]}]}}}, 'createdAt': '0', 'updatedAt': '0', 'status': 'STATUS_UNSPECIFIED'}, 'dataSourceSpecBinding': {'settlementDataProperty': 'oracle.test.settlement69F5A', 'tradingTerminationProperty': 'oracle.test.terminationA4623'}}, 'id': ''}, 'marginCalculator': {'scalingFactors': {'searchLevel': 1.1, 'initialMargin': 1.2, 'collateralRelease': 1.4}}, 'logNormalRiskModel': {'riskAversionParameter': 0.001, 'tau': 0.00011407711613050422, 'params': {'r': 0.016, 'sigma': 1.5, 'mu': 0.0}}}, 'decimalPlaces': '5', 'fees': {'factors': {'makerFee': '0.004', 'infrastructureFee': '0.001', 'liquidityFee': '0.3'}}, 'openingAuction': {'duration': '0', 'volume': '0'}, 'priceMonitoringSettings': {'parameters': {'triggers': []}}, 'liquidityMonitoringParameters': {'targetStakeParameters': {'timeWindow': '10', 'scalingFactor': 5.0}, 'triggeringRatio': '0', 'auctionExtension': '1'}, 'tradingMode': 'TRADING_MODE_OPENING_AUCTION', 'state': 'STATE_PENDING', 'marketTimestamps': {'proposed': '1686318369171118952', 'pending': '1686318373000000000', 'open': '1686318373000000000', 'close': '0'}, 'positionDecimalPlaces': '5', 'lpPriceRange': '1', 'linearSlippageFactor': '0.01', 'quadraticSlippageFactor': '0'}
(Pdb) marketsTrading.get_market(marketId)["marketTimestamps"]
{'proposed': '1686318369171118952', 'pending': '1686318373000000000', 'open': '1686318373000000000', 'close': '0'}
```

**Comment by EVODelavega** [comment]
Hang on: there's a minimum opening auction duration network parameter to consider. Previously, because we validated the enactment time -  proposed time ( enactment timestamp - vegatime.Now() on submit) as the opening auction duration to validate, this wasn't an issue, because of the voting period.

The problem with this was that the valid proposals (with a close time in 7 days + enactment time in another month or so) would get rejected that was interpreted as an opening auction duration of  1month + 1 week (exceeding the max opening auction duration). I think the solution for this would be to set the opening auction duration to be `enactment time - close time + proposal.market.OpeningAuctionDuration`

**Comment by TomMcL** [comment]
Thinking about it, should this not be picked up and rejected by the exact validation that was causing an issue to begin with (though the other edge of it)?

**Comment by davidsiska-vega** [comment]
Or we should allow the proposal to set `enactment time` and `close time` the same but run the auction for at least `market.auction.minimumDuration`.

**Comment by TomMcL** [comment]
Unless opening auctions already check whether the minimum time has passed when trying to leave, in which case setting both to the same value should be fine and be handled by that check.

**Comment by davidsiska-vega** [comment]
@EVODelavega what is this `proposal.market.OpeningAuctionDuration` you talk about? I can find it in neither core nor spec repos.

**Comment by jgsbennett** [comment]
On my branch, I think market.auction.minimumDuration is set to 1s actually, so there was probably a bug present before anyway. Now the bug is different. Agree with @davidsiska-vega and @TomMcL that we should reject invalid proposals. Are we agreed that "0s" is a potentially valid value for market.auction.minimumDuration , and that in that situation things should work as before again?

**Comment by davidsiska-vega** [comment]
> Are we agreed that "0s" is a potentially valid value for market.auction.minimumDuration

No, auction should have non-zero lengths. So this is good:
```
MarketAuctionMinimumDuration:                    NewDuration(gte1s, lte1d).Mutable(true).MustUpdate("30m0s"),
```

For proposals I would go with what I'm suggesting above i.e. 

> We should validate that the distance between closing time i.e. (end of voting) and enactment time is between market.auction.minimumDuration and market.auction.maximumDuration.

**Comment by davidsiska-vega** [comment]
Actually, @jgsbennett makes a good point that for the sake of speed of system tests we want to allow `MarketAuctionMinimumDuration` to be `0s`. Which is fine, real networks set this via a netparam which will be whatever it needs to be (more than `0s`).

**Comment by jgsbennett** [comment]
Naturally, I'll update my branch to set the net param, which it did not previously. Sounds like we need to:
- Check we can still use market.auction.minimumDuration = 0s
- Check that we get a rejected proposal when the specified auction duration is < market.auction.minimumDuration (Surely we have a test for this somewhere?)

**Comment by TomMcL** [comment]
I am of the opinion that the proposal shouldn't care about auction minimum duration when validating closing vs enactment time. The auction should not exit when the length of the auction is less than the minimum duration, but that doesn't mean that the gap between closing and enactment must be at least that, the auction can just continue after enactment until that minimum time is reached. Only attempts to extend beyond the maximum should be a validation failure

**Comment by davidsiska-vega** [comment]
> the auction can just continue after enactment until that minimum time is reached. Only attempts to extend beyond the maximum should be a validation failure
That would also be fine.

**Comment by jgsbennett** [comment]
Currently, attempting to start a network with minimum duration set in genesis to 0s results in:
```
2023-06-12T16:49:46.619Z	FATAL	core.protocol.processor	processor/abci.go:699	couldn't initialise vega with the genesis block	{"error": "market.auction.minimumDuration: unable to validate market.auction.minimumDuration: expect >= 1s got 0s"}

```

**Comment by gordsport** [comment]
Postponing for now as the timesaving in system tests needs thinking about in terms of added risk of bugs etc.. - to be discussed

**Comment by TomMcL** [comment]
@gordsport Which aspect of this is being postponed?

**Comment by EVODelavega** [comment]
A zero-length opening auction essentially means we should allow a market to go straight from proposed to continuous trading, bypassing the `OnTick` (time update) checks that are used to check if a successor market can leave opening auction, get the state from the parent market and update any/all other successors for that parent market. Allowing zero-length opening auctions the way we currently do is strictly speaking not impossible, but it would be rather hacky to implement

**Comment by TomMcL** [comment]
Isn't the point that the market is basically in opening auction during the vote anyway? 

In any case, if it's a technical difficulty to implement I wouldn't be entirely opposed to just having validation say the period can't be zero and reject it. So long as we can't end up with an un-openable market I'm happy

**Comment by EVODelavega** [comment]
The market is in opening auction (Sort of) during the vote, but it's in the proposed state (essentially an opening auction the market can't leave). Once the vote closes and the proposal is enacted, we set the state to pending, and start the opening auction as specified in the proposal (enactment time - vote close time). Then, on time updates, we check if we can leave the opening auction (the auction duration has ended), and all requirements are met (LP, volume on the book, etc...).

To allow for zero-length opening auctions, we allow markets to skip the PENDING state entirely, and move the market directly to continuous trading. Next time update, however, if we don't have enough volume on the book or no LP is provided, the market will enter monitoring auction. For successor markets, we rely on the checks done during time updates: check if the market is a successor market, get the state from the parent market, copy it over to the successor market, check if we can leave opening auction (if no: rollback the state copy from parent etc... - if we left opening auction, check other successors for the parent and so on).

If we skip the opening auction step entirely, we'd either have to duplicate all the logic (meaning we'd be testing the duplicated code, not the code in the `OnTick` function that actual proposals in mainnet will go through). If we add some hacky stuff to the markets that allow us to fake the opening auction without _actually_ going through the opening auction, then we'd most likely have to add a bunch of exceptions to a myriad of checks the market normally performs at the end of the opening auction duration, adding needless complexlity, making a tricky part of the code needlessly more complex for the sole purpose of making testing easier, while simultaneously reducing our coverage of the actual code that gets executed on mainnet.

Currently, we have some code that allows for 0-duration opening auctions, accompanied by comments saying things like `// @TODO get rid of this` or `// this is only for testing` Removing this code is trivial, I'll push a PR out now

**Comment by jgsbennett** [comment]
Why would a 0-length opening auction allow a market to skip "Pending"? The market should still _have_ an opening auction, it just isn't time bound, it's entirely bound by orders. I mean, I haven't looked at the code, but the whole "skipping and going straight to continuous" feels odd. As I understand it, normally, even with a 1s auction, we can still be in opening auction after 1s due to having no orders to satisfy that auction, and leave once we get them. Surely we can just do a similar thing for 0s? i.e: We go to "Pending", but the first time-check will immediately declare that the market _can_ leave if there are sufficient orders.

**Comment by EVODelavega** [comment]
A zero-length auction skips the pending step because that's how auction monitoring is implemented. When a market is in the proposed state, with the trading mode being opening auction. Once the proposal passes the vote, the _actual_ opening auction is started with a given duration. If that duration is 0, then the market skips the pending step. The auction monitoring component is effectively bypassed because it cannot be configured to ensure an opening duration of any duration, whereas normally, we would call `StartOpeningAuction` on the market, take the auction duration and the current vega time, and set everything up. The auction monitoring component is not able to provide an actual end time of the auction here:

```go
func (a AuctionState) ExpiresAt() *time.Time {
	if a.begin == nil { // no start time == no end time
		return nil
	}
	if a.end == nil || a.end.Duration == 0 { // not time limited
		return nil
	}
	// add duration to start time, return
	t := a.begin.Add(time.Duration(a.end.Duration) * time.Second)
	return &t
}
```

Essentially, if we don't skip the pending step, we'd need to account for a market that is in a pending state, while also being in an invalid state (no auction end time), so we'd have to: change the validation on the governance side (to allow for 0-length auctions), change the execution package (again, to account for a market being in pending state without an actual auction), and ensuring the auction monitoring component acts as expected/required despite being potentially in an invalid state.

On top of that, and I really do think this is the most important reason why I don't think this is something we should spend time on: Setting the minimum auction duration to 1s is valid, so we'd save 1 second doing things this way (provided we submit orders and LP during the voting/governance period). If we don't submit these orders before the vote is closed, we really aren't saving any time because the previous 0-length opening auction implementation would essentially trigger a liquidity auction anyway.
More important than all of this, though, is that in order to allow for 0-length auctions (rather than 1 second auctions - again, which would work exactly the same way because the next time update, if orders are in place, we'd leave the opening auction all the same) is that we'd have to implement a series of exceptions that we don't want to allow to be usable by the end user, so all system tests would bypass a phase in the market lifecycle. That means system tests would not accurately reflect the way the system should work, and we would be testing the functionality of a workaround/hack rather than the actual functioning of the system

**Comment by TomMcL** [comment]
@EVODelavega To be clear, my initial concerns raising this weren't system test related, I was always thinking about real world markets (which I think could justifiably say "We don't want an opening auction period if it's not needed after enactment"). But 1s auctions are as good as equivalent for that purpose 😄

**Comment by jgsbennett** [comment]
> Essentially, if we don't skip the pending step, we'd need to account for a market that is in a pending state, while also being in an invalid state (no auction end time), so we'd have to: change the validation on the governance side (to allow for 0-length auctions),
Is that true? Why can't we just set the opening auction end to current vega time and make that allowed? How much has to change then? I can totally believe that skipping a state would cause all kinds of trouble, and I don't think we a) need or b) want to do that anyway. For me, the question is how sanely can we achieve that.

Frankly, personally I'd _almost_ accept swapping a 0s auction to 0.000000001s auction hidden in the code if you really need a future expiry time, which would limit us to leaving next block at the earliest. Don't know who if anybody else would be sad at that. Would that then become a trivial change?

**Comment by EVODelavega** [comment]
@TomMcL No worries. My last comment is mostly about the system-test side of things, because that's the only reason why allowing zero-length opening auctions is something we'd even want to allow. As mentioned earlier in this thread: 0-length opening auctions shouldn't be allowed. The validation on the governance level was still allowing 0-length auctions, but as mentioned before, because of how successor markets work, the only right thing to do here in my view is to disallow 0-length auctions as per spec

**Comment by TomMcL** [comment]
@jgsbennett I would say it comes down to that, as I hadn't realised was the case but looks like it is in the code @EVODelavega posted above, `0s` auctions were always an edge case where even a `1s` auction would be checked vs minimumAuctionLength but 0 wouldn't. Expanding that coverage to 0 as well seems reasonable (even though it is effectively disallowing it if the minimumAuctionLength value can't be 0). The whole "opening auction is technically running during the vote/enactment too" does feel a bit non-intuitive so having an enforced *some period* of opening auction is probably easier mental-model wise for new people.

**Comment by EVODelavega** [comment]
@jgsbennett Yes. What I said is true, even checked the code as I was writing it to make sure that I wasn't inaccurate. The end time of any auction isn't determined by a random time value. It's the starting time, and the `Duration` field (which in this case would be zero). The crux of it here is that the spec does not allow for zero-length opening auctions, so relying on hidden trickery in the code (like interpreting a 0-length auction as a 1ns duration) means there's code at work that may interfere with liquidity and or price auctions. It's all just implementing an exception to make something work that, as per spec, shouldn't be allowed.

**Comment by EVODelavega** [comment]
@TomMcL Yeah, the opening auction during voting is a tad unfortunate, but it's there to allow for orders and LP submissions to be made for a market before it _"technically"_ should exist. The market will show up as being in proposed state. In somewhat functions as being in opening auction, but the actual opening auction starts once the voting ends. It's something we had to do to allow LP submissions, and it's also part of the reason why I'm quite reluctant to mess with the way opening auctions work.

**Comment by jgsbennett** [comment]
> What I said is true, even checked the code as I was writing it
I wasn't questioning how well you've read the code, I'm questioning whether we _have to_ either
- Skip pending.
- End up with a market with no auction end time.

Seems to me the third option is:
- Have a market with end time _now_ (my original suggestion, rather than 1ns), and immediately end up in "Pending" where we haven't met liquidity requirements to enter normal trading.

...which ought to put the market in the same place it would be if 1s had passed and the other requirements had not been met. I've yet to hear why that can't work, just why the current special-case can't work. Surely that just requires we allow end time to be now when we open the auction, which I'm guessing must be disallowed somewhere, currently?

>  that's the only reason why allowing zero-length opening auctions is something we'd even want to allow
Not so. I can imagine lots of people will naturally try to say "Enable ASAP", and we'll end up having to correct proposals where they attempt this with a 0s proposal. At any rate, I'd love the 1s per test anyway.
