### ISSUE TITLE
[feature tests] Successor Market AC test coverage 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8496]
In order to have test coverage for the addition of successor markets the following tests in feature tests:

- [x] 0042-LIQF-031
- [x] 0042-LIQF-048
- [x] 0042-LIQF-033
- [x] 0081-SUCM-005
- [x] 0081-SUCM-006
- [x] 0081-SUCM-020
- [x] 0081-SUCM-021
- [x] 0081-SUCM-022
- [x] 0081-SUCM-009
- [x] 0081-SUCM-010
- [x] 0081-SUCM-011

**Comment by Jiajia-Cui** [comment]
removed  0042-LIQF-034 as its within SLA work instead of successor market
