### ISSUE TITLE
[feature tests] Iceberg order AC test coverage

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8498]
In order to have test coverage for the addition of [iceberg orders](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0014-ORDT-order_types.md#iceberg--transparent-iceberg-orders) we need to cover the following tests in feature tests

- [x] 0014-ORDT-039
- [x] 0014-ORDT-007
- [x] 0014-ORDT-008
- [x] 0014-ORDT-009
- [x] 0014-ORDT-010
- [x] 0014-ORDT-011
- [x] 0014-ORDT-012
- [x] 0014-ORDT-013
- [ ] 0014-ORDT-014
- [ ] 0014-ORDT-015
- [x] 0014-ORDT-023
- [x] 0014-ORDT-024
- [x] 0014-ORDT-025
- [x] 0014-ORDT-026
- [x] 0014-ORDT-027
- [x] 0014-ORDT-028
- [x] 0014-ORDT-029
- [x] 0014-ORDT-030
- [x] 0014-ORDT-031
- [x] 0014-ORDT-032
- [x] 0014-ORDT-033
- [x] 0014-ORDT-034
- [x] 0014-ORDT-037
- [x] 0014-ORDT-038
- [x] 0014-ORDT-039

**Comment by MuthuVega** [comment]
https://github.com/vegaprotocol/vega/pull/8445

**Comment by Jiajia-Cui** [comment]
close it as 0014-ORDT-014, 0014-ORDT-015 are covered now
