### ISSUE TITLE
Rename initial and minimum peak for icebergs in API

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vega#8524]
For the iceberg order API fields, term 'initial peak' is a little misleading as it's the actual peak amount of the iceberg, where initial implies it's likely to be changed, and 'minimum peak' doesn't actually make much sense language-wise.

@wwestgarth and I propose we change those field names:
`initial_peak_size` would become `peak_size`
`minimum_peak_size` would become `minimum_visible_size`

**Comment by neildawson** [comment]
Ben, @macqbat and I were throwing around a few options for labels last week:

![image](https://github.com/vegaprotocol/vega/assets/1080322/44043ad7-d423-406b-9a98-64506b8876f5)

We stopped on "display size" (which is language used in the specs) and "minimum size"

**Comment by MuthuVega** [comment]
In graphql - only the IcebergOrder is spel with the wrong case - all other fields are camel case but IcebergOrder is sticking out like a sore thumb

```
query AllOrders {
    party (id: "72086f90c12526b5450018cecb8aeb5fe8e3732671388a633236a4958d00026a") {
      id
      ordersConnection {
        edges {
          node {
            id
            side
            size
            price
            timeInForce
            market {
              id
            }
            createdAt
            expiresAt
            reduceOnly
            postOnly
            rejectionReason
            IcebergOrder {
              initialPeakSize
              minimumPeakSize
              reservedRemaining
            }
          }
        }
      }
    }
  }
```
