### ISSUE TITLE
governance transfers -transfer not failing when finding an empty source account during recurring transfer 

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8525]
During a recurring transfer if the source account balance becomes zero we expect a transfer rejection to occur

what actually happens is the recurring transfer still runs until the last epoch and shows an event with a 0 transfer at a STATUS_DONE

eg 
```
{"id":"6598-9","block":"E54914335E213C4DB0E02F53D052591895A83DCB5316BC245443DF22FA8A4597","type":"BUS_EVENT_TYPE_TRANSFER","transfer":{"id":"b47eb0bbcbabc254553eb7804b5c6ea14a2fcd1fbfe29ce0d3a09f3ce39a5250","from":"0000000000000000000000000000000000000000000000000000000000000000","fromAccountType":"ACCOUNT_TYPE_GLOBAL_REWARD","to":"744405bab49fc20e7fc800b3e2571a8b391a2edf8cae3cf29020baf728829278","toAccountType":"ACCOUNT_TYPE_GENERAL","asset":"6e465432c03f4b40eca991709b144876e1417bd18f2a947e5ab72a8e93058f2d","amount":"0","reference":"149346D21A","status":"STATUS_DONE","timestamp":"1686844104250439000","recurringGovernance":{"startEpoch":"803","endEpoch":"806"}},"version":1,"chainId":"testnet-001","txHash":"E54914335E213C4DB0E02F53D052591895A83DCB5316BC245443DF22FA8A4597"}```

**Comment by ze97286** [comment]
I'm not sure it should fail and be stopped, if there's nothing in the account, that's fine, I don't think this is a failure in any way. but it's a question for protocol design really. 
cc @davidsiska-vega

**Comment by davidsiska-vega** [comment]
> if the source account balance becomes zero we expect a transfer rejection to occur

@vega-paul can you point me at a place in the specs where we say that? It may need updating / thinking.

**Comment by vega-paul** [comment]
@davidsiska-vega 
When insufficient tokens are found in the source account at time of transfer (enactment) a transaction result event will show the transfer failing with an appropriate message ([0028-GOVE-095](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#0028-GOVE-095))

**Comment by davidsiska-vega** [comment]
I've updated the spec PR.
