### ISSUE TITLE
Governance transfers - proposal at enactment not failing with source account balance is zero

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8526]
This AC
```
When insufficient tokens are found in the source account at time of transfer (enactment) a transaction result event will show the transfer failing with an appropriate message ([0028-GOVE-095](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#0028-GOVE-095))
```

We propose a governance transfer when the source account balance is zero

What I see is that when the source account is zero after a recurring transfer and then we start a new deliveryOn transfer, the transfer events is produced as follows:

```"id":"7234-8","block":"15AB0A5FD375B3E836F8630A3F135DEA8339A1CF93ECB8D0F99C6324BE41EDB8","type":"BUS_EVENT_TYPE_TRANSFER","transfer":{"id":"639ab8c6c8b63543c48b6d717fbc3db9283f3bc074cc0570a76d6fce32990e22","from":"0000000000000000000000000000000000000000000000000000000000000000","fromAccountType":"ACCOUNT_TYPE_GLOBAL_REWARD","to":"a3efbbc909de96efe6ee21e7f24c1aac5dc23f1088493813c5f17fd7419b6301","toAccountType":"ACCOUNT_TYPE_GENERAL","asset":"814f02d8b19d63961123cb38df3424b968e619d9e4f708a0bd3e7b65063f1db8","amount":"0","reference":"53D86F97F1","status":"STATUS_DONE","timestamp":"1686844756076454000","oneOffGovernance":{}},"version":1,"chainId":"testnet-001","txHash":"15AB0A5FD375B3E836F8630A3F135DEA8339A1CF93ECB8D0F99C6324BE41EDB8"}
```

Expecting the proposal to fail with a rejection

**Comment by ze97286** [comment]
a couple of comments:
1. the time of enactment is only relevant for transfers executed immediately, i.e. one off with deliver on in the past. So a recurring transfer should certainly not be cancelled if at the time of enactment the source account has no balance
2. I think this whole check makes no sense because the transfer amount is calculated as a fraction of the balance of the source amount so having insufficient fund is impossible. 
cc @davidsiska-vega

**Comment by davidsiska-vega** [comment]
@ze97286 Indeed, given that the spec says:

```
transfer_amount = min(
    proposal.fraction_of_balance * source.balance,
    proposal.amount,
    NETWORK_MAX_AMOUNT,
    NETWORK_MAX_FRACTION * source.balance )
```

I don't see how there can ever be insufficient funds in the source account. So I think the AC 095 makes no sense and should be removed or re-purposed.

**Comment by davidsiska-vega** [comment]
https://github.com/vegaprotocol/specs/pull/1770

**Comment by vega-paul** [comment]
It is possible to exhaust the balance by using a fraction of 1 and with an amount = 100% of the source balance. Recurring transfer starts to transfer zero tokens at epoch 2.

**Comment by gordsport** [comment]
@vega-paul 
Ive assigned the following issue to you for review, once happy can you close this issue if no core changes required

- https://github.com/vegaprotocol/specs/pull/1770

**Comment by ze97286** [comment]
@vega-paul there's no need to "prove" anything. By definition you can get zero balances, but it doesn't mean that there won't be a balance in the next epoch. The fact that the reward account is empty at the end of one epoch doesn't mean it won't be funded by the end of the next one.

**Comment by davidsiska-vega** [comment]
> Also Ive proved we generate zero transfer events and ledger entries in this case. 

That seems to be the right behaviour. As there is nothing in the source to transfer. And as @ze97286 says, there may be a balance later, at which point non-zero transfers in the future.
