### ISSUE TITLE
[Bug]: Data node API returns sometimes returns 0 for market timestamps

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8535]
### Problem encountered

GetLatestMarketData returns 0 for all timestamps during continuous trading. Prior to entering continuous mode, the timestamps have a non-zero (correct) timestamp, and another API (GetMarket) returns sane timestamps even afterwards, but this API does not.

### Observed behaviour

'0' reported for all timestamps.

### Expected behaviour

Sane, non-zero timestamps returned for market in continuous trading

### Steps to reproduce

Check out lnl_new_openining_auction_case
Uncomment this line, which will assert that the API has non-zero values and show the issue:
https://github.com/vegaprotocol/system-tests/pull/2179/files#diff-3e1aa0cefaef2e2e3dac2ac4e916338691b15ba9266735264d8bf7bd9423bdeeR399

```
assert int(pre_cp_market_data["auctionStart"]) != 0, f"This should be a real timestamp!"
```
Run the test:
```
pytest -k test_orders_and_positions_not_maintained_across_checkpoints tests/newLnl
```
```


### Software version

7b7ac8b212ca9cdb73f924d7ea12f91ee8c806b5

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

```shell
>       assert int(pre_cp_market_data["auctionStart"]) != 0, f"This should be a real timestamp!"
E       AssertionError: This should be a real timestamp!
E       assert 0 != 0
E        +  where 0 = int('0')

tests/newLnl/lnl_test.py:399: AssertionError
```
```
### Extra notes
I tried going back a couple of weeks on develop and running the same check for that API, and the issue still seemed to be there, so I don't _think_ this is a recent issue.

**Comment by gordsport** [comment]
@jgsbennett @EVODelavega - I think this was covered in:
- https://github.com/vegaprotocol/vega/pull/8487
Can you please check and if so close this issue?

**Comment by gordsport** [comment]
closing as no update from above comment
