### ISSUE TITLE
Add extra validation to the protocol_upgrade_proposal command

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8548]
When the validators submitted the `protocol_upgrade_proposal` command for the patch release to 0.71.6.

Command used:

`vega protocol_upgrade_proposal --home <YOUR_VEGA_HOME> --vega-release-tag v0.71.6 --height 3917600`

Error message presented:

`failed to get commander: couldn't initialise ABCI client: abci client addr is empty in config`

This is believed to be due to the fact the Tendermint/cometBFT config is not complete.

Van we validate this earlier so that the validators can fix sooner, also is there any way to default to a known config in order for this command to be successful yet still advise they update.

**Comment by jeremyletang** [comment]
2 things to be done here:
- [ ] add validation to proper semver format, earlier issue today was a validator proposing for the version 0.71.9 instead of v0.71.9
- [ ] also when that error occur, add a fallback to the default tendermint port address, and then an error if it doesn't work as well.
