### ISSUE TITLE
[Bug]: Possible to get duplicate eth oracle chain events at startup 

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#8631]
### Problem encountered

Possible to get duplicate eth oracle chain events at startup as the prev block height is set after the eth call poller is started, which means it can be set to block already processed. Not a blocker for the merge to dev branch but should be addressed shortly thereafter.

### Observed behaviour

"

### Expected behaviour

"

### Steps to reproduce

```bash
"
```

### Software version

eth-oracles-feature

**Comment by gordsport** [comment]
Waiting for the snapshot engine refactors, once this is done we should then start this
