### ISSUE TITLE
[Bug]: data node reports 0 for close timestamp

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8655]
### Problem encountered

The close timestamp of a market is reported as '0' even after the market is terminated settled. If I call the GetMarket API for a market which has settled, I see the following:
```
 'marketTimestamps': {'proposed': '1688127772767526600', 'pending': '1688127776000000000', 'open': '1688127792510351700', 'close': '0'},
```
I _think_ I would have expected the 'close' timestamp to match the block that the market was settled? Though I'm not certain this is the case.

### Observed behaviour

Timestamp says "0".

### Expected behaviour

Non-zero timestamps. I _think_ it should be updated to match the time the market actually closed.

### Steps to reproduce

```bash
1. Find tests/settlement/settlement_test.py case: test_settlement_with_simple_oracle
2. Apply the following patch:

diff --git a/tests/settlement/settlement_test.py b/tests/settlement/settlement_test.py
index 01dddc4f..b12dfcd6 100644
--- a/tests/settlement/settlement_test.py
+++ b/tests/settlement/settlement_test.py
@@ -104,6 +104,8 @@ def test_settlement_with_simple_oracle(context, proposer, asset, settlement_trad
     # Now send a message to cause the market to settle. (Market requires information about a fair settlement price)
     oracle.send_settlement_data(500)
     marketsTrading.wait_for_market_settled(_market.id)
+    timestamps = marketsTrading.get_market(_market.id)["marketTimestamps"]
+    assert timestamps["close"] != "0", timestamps
     # Original trade at 5 * 1000. Market settles outstanding positions.
     # Trader 1: Loses 500 * 5. = -2500. However, receives "makerFee" as passive party, so overall: -2480.
     # Trader 2: Gains 500 * 5, = 2500, but paid fees ({"makerFee":"20","infrastructureFee":"5","liquidityFee":"1500"})
```
3. pytest -k test_settlement_with_simple_oracle tests/settlement
```


### Software version

88f7ba577092e067f9212c43b433a13124d25a7e

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

**Comment by wwestgarth** [comment]
This was previously fixed:
https://github.com/vegaprotocol/vega/pull/8238

but the lines I added have now disappeared. I'll see what happened here (I claim in my PR that I event had a system-test for it)

**Comment by wwestgarth** [comment]
It got removed here for some reason:
https://github.com/vegaprotocol/vega/pull/8327/files#diff-1782f5982916957ff0e7e82b0c7130c6d4c8ab4eb2e06f5c7b5b4a5925e15bcf

I'll add the fix back in.
