### ISSUE TITLE
[Feature]: Squash `goose` migrations before the first deployment

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#8673]
# Feature Overview

**In order to** keep our migration files easier to maintain
**We will** squash the new migrations files into a single `0002` migration file
**So that** its easier to reason with going forward

Similar to this ticket we had for trading-enabled: https://github.com/vegaprotocol/vega/issues/7926

**Comment by jeremyletang** [comment]
wont'do in the end.
