### ISSUE TITLE
Add gas estimation to stop orders

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#8690]
From @witgaw:

So I suppose we want the cost factor * number of stop orders to feature in [gas calculation](https://github.com/vegaprotocol/specs/blob/master/protocol/0079-TGAP-transaction_gas_and_priority.md#any-type-of-limit-or-market-order) for any transaction and a limit across all markets (same as pegged)? If that’s the direction you want to take it I can draft a spec change.

**Comment by witgaw** [comment]
That's what I drafted: https://github.com/vegaprotocol/specs/pull/1806
