### ISSUE TITLE
[Bug]: Network history segments are diverging

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8696]
### Problem encountered

Network history segments generated by a datanode created by replaying the chain are different to the ones that are generated by the original datanode.

Looks like the network segments are starting to diverge at height 4577

```
Restored Node is comparing :

'4577 to 4598, id: QmTmg2dwfAi2MN8hUSDmL78VxMbZ9qcTQ9B8LaeKdMpMTd, previous segment id: QmWXcsVcK5gL6NZMCs738d8oF6RvCYUrXUTU5QSjm4UTen'

Against golden node segments :

4555 to 4576, id: QmWXcsVcK5gL6NZMCs738d8oF6RvCYUrXUTU5QSjm4UTen, previous segment id: Qma4zroqcUfYaaGEhjbgy63bhLi2CUD9Y8GqxH6YnmYEMG
4577 to 4598, id: QmS6TYpkAAXHJjRfELUDef1hBEDnvw48rji4C9ZcZsYwfE, previous segment id: QmWXcsVcK5gL6NZMCs738d8oF6RvCYUrXUTU5QSjm4UTen
```

### Observed behaviour

Diverging network history segments

### Expected behaviour

Network history segments should remain the same across datanodes.

### Steps to reproduce

```bash
Not too sure if we can reproduce this error.

This was spotted as part of one of the full runs for a system tests PR.

https://jenkins.ops.vega.xyz/job/common/job/system-tests/23666/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_restore_from_dehistory/
```

### Software version

vega - develop

### Failing test

https://jenkins.ops.vega.xyz/job/common/job/system-tests/23666/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_restore_from_dehistory/

test_datanode_restore_from_dehistory

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/80502/

### Relevant log output

```shell
Trying to compare the network history segments of a restored datanode against the golden node

Unable to copy the logs here.

In this link, please search for the below text

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/80502/consoleText

AssertionError: assert '4577 to 4598, id: QmTmg2dwfAi2MN8hUSDmL78VxMbZ9qcTQ9B8LaeKdMpMTd, previous segment id: QmWXcsVcK5gL6NZMCs738d8oF6RvCYUrXUTU5QSjm4UTen' in ['Available contiguous history spans:', 'Contiguous history from block height 1 to 6622, from segment id: Qmbnox49EDyCYbYWhhgFPqt97Ccb4hCce3RPjaAuYNE9kv to Qme5VEGPDiBV8odwiiB1eMTZEjbPb52iimCiiZD5PzWH5x', '1 to 22, id: Qmbnox49EDyCYbYWhhgFPqt97Ccb4hCce3RPjaAuYNE9kv, previous segment id: ',
```

**Comment by ettec** [comment]
Unfortunately unable to diagnose the issue as the test is not storing the state of the restored datanode so cannot get hold of the segments to compare against those of the golden node.  @MuthuVega is investigating how to fix this.

**Comment by MuthuVega** [comment]
This issue can not be reproduced , however , if this happens again then all relevant artefacts required for troubleshooting are now being saved as per the below PR.

https://github.com/vegaprotocol/jenkins-shared-library/issues/549
