### ISSUE TITLE
[Feature]: Datanode API: Perpetual markets can be seen through all existing API that return a market

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#8762]
# Feature Overview

**In order to** Ensure that perpetual markets are visible and return the correct data across all existing datanode APIs
**We will** perform an code-review/audit/add unittests
**So that** perpetuals are as available and usable through our API as fixed expiry futures.

Given that we store the market definition in postgres as a jsonb I think this will just work. This ticket is sanity check this, and to write some unit-tests to confirm this to be true. This include new additions to any data-sourcing. We might also want to consider what new fields we could add to the market-data, such as funding rates.

We should also have a conversation with FE about how they expect to be able to filter between market types. Console currently have a TAB that toggles between product types. We should understand what they expect from our API's to support this:
<img width="325" alt="image" src="https://github.com/vegaprotocol/vega/assets/1857660/c28756ce-7fd1-4c3b-b6b8-6466226d0322">

## Specs
- [Link](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0048-DSRI-data_source_internal.md) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by edd** [comment]
- What will be the property we can use to determine if a market is a perpetual? 
- Please could we have a filter on `marketsConnection` (graphql) / `listMarkets` ([rest](https://docs.vega.xyz/mainnet/api/rest/data-v2/trading-data-service-list-markets)) to filter on this property. Because I don't know what the property is, I can't suggest how that would look.
