### ISSUE TITLE
[Feature]: Perps - Datanode API: EstimatePosition

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#8764]
# Feature Overview

**In order to** Have the `EstimatePosition` end-point reflect the margin calculations for a perps market
**We will** extend it to use the `margin_funding_factor` where appropriate
**So that** FE can give better estimates for required margins in the UI

This may or may not be possible depending what data is available in the data node. If we want to add on `margin_funding_factor * G(t_k-1, t)` we could use the funding payment from the last complete funding period which would be easiest. Or if we want to use the funding factor of the in progress funding period we would have to calculate the twap-difference in the data node from the data points. So it depends how accurate we want to be.

There is also the `EstimateMargin` which I believe is deprecated in favour of `EstimatePosition` so we may or may not want to add something there.

## Specs
- [Link](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0048-DSRI-data_source_internal.md) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by barnabee** [comment]
I assume the API request and response wouldn’t change and this is just updating the calculation to be accurate for perps, is that correct?

**Comment by witgaw** [comment]
[API](https://github.com/vegaprotocol/specs/pull/1907/files) is meant to expose the funding payment estimate, so we should add `max(0,position_size*funding_payment_estimate)` to the margin estimate.
