### ISSUE TITLE
Through the API, I can list each liquidity provider's average entry valuation

### ISSUE THREAD

**Issue by guoguojin** [vegaprotocol/vega#8783]
The average entry valuation is explained under this section of the [0042-LIQF-setting-fees-and-rewarding-lps](https://github.com/vegaprotocol/specs/blob/master/protocol/0042-LIQF-setting_fees_and_rewarding_lps.md#calculating-liquidity-provider-equity-like-share)

**Comment by gordsport** [comment]
closing to tidy up as all now listed under the parent issue and single linked PR:
- https://github.com/vegaprotocol/vega/pull/8859#issue-1812326850
