### ISSUE TITLE
[Bug]: Consensus failure on stagnet1 related to successor markets

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8796]
### Problem encountered
No blocks being produced and trading looks to have stopped at the time where one for my successor markets was enacted

### Observed behaviour
consensus failure and network stops when trying to test successor markets, 

Felt that the status of the market to continuous mode, was not what triggered the cancellation of the other successor market proposals, but rather when the first successor market proposal was enacted.

In case it helps, all three markets were having the same parent, none had gone to continuous. Tried to send lp but by that time it was already down

![Image](https://github.com/vegaprotocol/vega/assets/83510148/b3cdc2ee-2e63-4425-bb81-de778cfca4b2)

### Expected behaviour
successor markets work without network failures 

### Steps to reproduce
Made 3 markets:
1: Voting ends first enacts last
2: Voting ends second enacts first 17:49:55
3: Voting ends third enacts second

### Software version
v0.72.3

### Relevant log output
Jul 13 16:49:56 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:56.416Z        INFO        tendermint        txindex/indexer_service.go:97        indexed block exents        {"height": 812284}
Jul 13 16:49:56 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:56.660Z        INFO        tendermint        consensus/state.go:1850        received proposal        {"proposal": "Proposal{812285/0 (0DDEFBD6F52BEAD7FFF64BA1B23287BFE47462CDEA8B37666E3704D8091BE867:1:398E4AC32A9F, -1) 642B9D9D6BA5 @ 2023-07-13T16:49:56.433552693Z}"}
Jul 13 16:49:56 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:56.660Z        INFO        tendermint        consensus/state.go:1917        received complete proposal block        {"height": 812285, "hash": "0DDEFBD6F52BEAD7FFF64BA1B23287BFE47462CDEA8B37666E3704D8091BE867"}
Jul 13 16:49:56 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:56.993Z        INFO        tendermint        consensus/state.go:1604        finalizing commit of block        {"hash": "0DDEFBD6F52BEAD7FFF64BA1B23287BFE47462CDEA8B37666E3704D8091BE867", "root": "503A0B2983293CF31270277A7712DDC2BADD0A15855FB69FD1B543F6880161FC", "num_txs": 2}
Jul 13 16:49:57 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:57.003Z        ERROR        tendermint        consensus/state.go:732        CONSENSUS FAILURE!!!        {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 561 [running]:
runtime/debug.Stack()
\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c
panic({0x2f91b20, 0x5a514f0})
\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212
code.vegaprotocol.io/vega/core/governance.(*proposal).SucceedsMarket(...)
\t/home/runner/work/vega/vega/core/governance/engine.go:1292
code.vegaprotocol.io/vega/core/governance.(*Engine).FinaliseEnactment(0xc001660fc0, {0x3e2c7c8, 0xc0023cbad0}, 0xc0041bf290)
\t/home/runner/work/vega/vega/core/governance/engine.go:559 +0x2fb
code.vegaprotocol.io/vega/core/processor.(*App).onTick(0xc000d95b00, {0x3e2c7c8, 0xc0023cbad0}, {0x1?, 0x3e4ade8?, 0x0?})
\t/home/runner/work/vega/vega/core/processor/abci.go:1801 +0x8c3
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
\t/home/runner/work/vega/vega/core/vegatime/service.go:104
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000de0600, {0x3e2c7c8, 0xc0023cbad0}, {0x40?, 0x2e333a0?, 0x0?})
\t/home/runner/work/vega/vega/core/vegatime/service.go:77 +0x24f
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc00ad5a560, 0x20, 0x20}, {{0xb, 0x1}, {0xc009f5a420, 0x1a}, 0xc64fd, {0x1085dc68, ...}, ...}, ...})
\t/home/runner/work/vega/vega/core/processor/abci.go:802 +0x747
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc00ad5a560, 0x20, 0x20}, {{0xb, 0x1}, {0xc009f5a420, 0x1a}, 0xc64fd, {0x1085dc68, ...}, ...}, ...})
\t/home/runner/work/vega/vega/core/blockchain/abci/abci.go:46 +0x75
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).BeginBlock(_, {{0xc00ad5a560, 0x20, 0x20}, {{0xb, 0x1}, {0xc009f5a420, 0x1a}, 0xc64fd, {0x1085dc68, ...}, ...}, ...})
\t/home/runner/work/vega/vega/cmd/vega/commands/node/app_wrapper.go:64 +0x55
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00ad5a560, 0x20, 0x20}, {{0xb, 0x1}, {0xc009f5a420, 0x1a}, 0xc64fd, {0x1085dc68, ...}, ...}, ...})
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00ad5a560, 0x20, 0x20}, {{0xb, 0x1}, {0xc009f5a420, 0x1a}, 0xc64fd, {0x1085dc68, ...}, ...}, ...})
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3e2ab90?, 0xc00038e750}, {0x3e41760, 0xc005258240}, 0xc000eea1e0, {0x3e54328, 0xc00183d818}, 0xc64fc?)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00662dc68, 0x7}}, {0xc00664f2e0, 0x1a}, 0x1, 0xc64fc, {{0xc00dc15100, ...}, ...}, ...}, ...)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc00b7f4380, 0xc64fd)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0xafd
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc00b7f4380, 0xc64fd)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x2ff
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xaa
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc00b7f4380, 0xc64fd, 0x0)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xccf
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc00b7f4380, 0xc005ee4e60, {0xc001c89740, 0x28})
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x18dc
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc00b7f4380, 0xc005ee4e60, {0xc001c89740?, 0xc00016f700?})
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc00b7f4380, {{0x3e079e0?, 0xc00f1e1078?}, {0xc001c89740?, 0x0?}})
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x170
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc00b7f4380, 0x0)
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f9
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
\t/home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d
"}
Jul 13 16:49:57 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:57.005Z        INFO        tendermint        service/service.go:176        service stop        {"msg": "Stopping baseWAL service", "impl": "baseWAL"}
Jul 13 16:49:57 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:57.007Z        INFO        tendermint        service/service.go:176        service stop        {"msg": "Stopping Group service", "impl": "Group"}
Jul 13 16:49:59 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:49:59.415Z        INFO        tendermint        consensus/ticker.go:124        Timed out        {"dur": "3s", "height": 812285, "round": 0, "step": "RoundStepPropose"}
Jul 13 16:50:25 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:50:25.507Z        INFO        tendermint        pex/pex_reactor.go:477        Ensure peers        {"numOutPeers": 4, "numInPeers": 3, "numDialing": 0, "numToDial": 6}
Jul 13 16:50:25 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:50:25.508Z        INFO        tendermint        pex/pex_reactor.go:542        We need more addresses. Sending pexRequest to random peer        {"peer": "Peer{MConn{188.166.148.89:40128} d1ef64698e422a27fc3454b67897a5b35e541300 in}"}
Jul 13 16:50:55 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:50:55.482Z        INFO        tendermint        pex/file.go:22        Saving AddrBook to file        {"size": 217}
Jul 13 16:50:55 n01.stagnet1.vega.xyz visor[1144428]: 2023-07-13T16:50:55.507Z        INFO        tendermint        pex/pex_reactor.go:

**Comment by jgsbennett** [comment]
Can we work out what new test to add as part of this please? I can't reproduce with a test that does what is described above, so I think there's more to it than that:
```
def test_dan_thing(context, proposer):
    close_times = [time.time()+i for i in [20,30,40]]
    enactment_times=[time.time()+i for i in [55, 50, 45]]
    def get_offset(list, i):
        return int(list[i] - time.time())

    parent = Market(context, proposer=proposer,closeTimeOffset=get_offset(close_times, 0),
        enactTimeOffset=get_offset(enactment_times, 0),
                    )
    parent.propose(proposer, state="Open")
    parent.vote()

    # Propose one market and see what happens once the expiry window has passed.
    child1 = Market(
        context,
        proposer=proposer,
        parent_market_id=parent.id,
        insurance_pool_fraction=0.5,
        closeTimeOffset=get_offset(close_times, 1),
        enactTimeOffset=get_offset(enactment_times, 1),
    )
    child1.propose(proposer, state="Open")
    child1.vote()
    child2 = Market(
        context,
        proposer=proposer,
        parent_market_id=child1.id,
        insurance_pool_fraction=0.5,
        closeTimeOffset=get_offset(close_times, 2),
        enactTimeOffset=get_offset(enactment_times, 2),
    )
    child2.propose(proposer, state="Open")
    child2.vote()
    marketsTrading.wait_for_market_state(market_id=child2.id, expected_state="STATE_PENDING", timeout=60)
    marketsTrading.wait_for_market_state(market_id=child1.id, expected_state="STATE_PENDING", timeout=60)
    marketsTrading.wait_for_market_state(market_id=parent.id, expected_state="STATE_PENDING", timeout=60)
    ordersMod.reset_market(context, child2.id)
    ordersMod.reset_market(context, child1.id)
    ordersMod.reset_market(context, parent.id)
```
