### ISSUE TITLE
Market sim fuzzing run - failed to copy market data to database

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8842]
### Problem encountered

During the research market simulation fuzzing run, the fuzz tests caused a critical with the the data node presenting the following error vega data node stopped with `error: failed to flush subscriber:failed to copy market data into database:ERROR: could not open relation with OID 18405 (SQLSTATE XX000)`. 

### Observed behaviour

`error: failed to flush subscriber:failed to copy market data into database:ERROR: could not open relation with OID 18405 (SQLSTATE XX000)`. 

### Expected behaviour

Fuzzing run to succeed 

### Steps to reproduce

```bash
1. TBC
```

### Software version

Develop 

### Jenkins run

https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fvega-market-sim-reinforcement/detail/vega-market-sim-reinforcement/269/artifacts it's run vega-sim-1vdlqpr4 here

### Relevant log output

```shell
`error: failed to flush subscriber:failed to copy market data into database:ERROR: could not open relation with OID 18405 (SQLSTATE XX000)`.
```

**Comment by gordsport** [comment]
Also repeated in both:

- d6jmbmt6 here https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fvega-market-sim/detail/vega-market-sim/2419/artifacts
- also a very similar error with a1pp  here https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fvega-market-sim/detail/vega-market-sim/2416/artifacts vega data node stopped with error: failed to flush subscriber:flushing balances: failed to copy balances entries into database:ERROR: could not open relation with OID 18357 (SQLSTATE XX000)


Annoyingly replaying from the replay doesn't trivially seem to hit the same error

**Comment by pscott31** [comment]
so we never got completely to the bottom of this after several days investigation, but it can be mitigated by pausing for 6 seconds after starting up datanode. It's not ideal; I believe there is some timescale bug or somehing; background processes moving stuff around after hypertables are set up or some such but we ran out of time to investigate and it's quite specific in affecting these tests as they do a lot of starting/stopping datanodes
