### ISSUE TITLE
[Bug]: Spot order amended above the available funds is not cancelled

### ISSUE THREAD

**Issue by VanithaVega** [vegaprotocol/vega#8852]
**Spot AC**
If the party does not have sufficient funds in their general account to cover this transfer, the order should be cancelled([0080-SPOT-017](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0080-SPOT-product_builtin_spot.md#0080-SPOT-017)).

system-tests - testname test_order_cancel_no_funds_in_amend

**Description:**
Order is submitted with in the given assets and funds. After submission, perform order amend above the available funds. Order Amend Operation should not be successful and it has to fail and order should get cancelled. However in this situation, order is not cancelled. 

Recreation Steps
1. Propose a Spot Market and take it to Continuous Trading state
2. create a trader with asset "quote_asset" and deposit amount 100 to quote asset
3. submit a spot trade  BUY@base_asset/quote_asset@Size 5 @ Price 10 @Limit GTC
4. above order is in Active state and shows below account balance 
    assert buy_trader_balance["quote_asset"]["General"] == 50.0
    assert buy_trader_balance["base_asset"]["General"] == 0.0
    assert buy_trader_balance["quote_asset"]["Holding"] == 50.0
    assert buy_trader_balance["base_asset"]["Holding"] == 0.0
6. amend the above order as BUY@base_asset/quote_asset@Size delta - 12  and actual size 17 @ Price 10 

**Expected Result:**
Order is cancelled 

**Actual Result:**
Order is not Cancelled and in active state 

```
{"id":"43154-155","block":"825EFF0EE094F2C907A4F6DC6792C329481C158C76F98B8F260F51BC6078D13D","type":"BUS_EVENT_TYPE_ORDER","order":{"id":"ce54c600c9aa5f93c0779aebc87e7db5c3da993fd34f81efd396c50ec328b55c","marketId":"5c72eb5040fb55bdb40a3cc6949999cdd30f34a6173b68591ce2f9fad2c4cd19","partyId":"9c1bc133f5d71ff75c134d80b780d6c92556862bdf08ed102db477b605f2deab","side":"SIDE_BUY","price":"1000000","size":"500000","remaining":"500000","timeInForce":"TIME_IN_FORCE_GTC","type":"TYPE_LIMIT","createdAt":"1689771296541985642","status":"STATUS_ACTIVE","reference":"test_order_cancel_no_funds_in_amend-0faab129","version":"1","batchId":"1"},"version":1,"chainId":"testnet-001","txHash":"9DD559F1769AB303FF9C82AC0D9953E41ACCDBF40F548940F4532AFCBFB71583"}
{"id":"43171-157","block":"63AA7BFA90E60D1CBE1B34957956D4EE15E34067FEE909F562FAA6182291752D","type":"BUS_EVENT_TYPE_ORDER","order":{"id":"ce54c600c9aa5f93c0779aebc87e7db5c3da993fd34f81efd396c50ec328b55c","marketId":"5c72eb5040fb55bdb40a3cc6949999cdd30f34a6173b68591ce2f9fad2c4cd19","partyId":"9c1bc133f5d71ff75c134d80b780d6c92556862bdf08ed102db477b605f2deab","side":"SIDE_BUY","price":"1000000","size":"1700000","remaining":"1700000","timeInForce":"TIME_IN_FORCE_GTC","type":"TYPE_LIMIT","createdAt":"1689771296541985642","status":"STATUS_ACTIVE","reference":"test_order_cancel_no_funds_in_amend-0faab129","updatedAt":"1689771307219076929","version":"2","batchId":"1"},"version":1,"chainId":"testnet-001","txHash":"26E111929F513671EFFC92E46A2ADC55028FFD3DFB81BADB408C51D49CBD8E33"}

```

**Comment by ze97286** [comment]
I don't think the order should get cancelled but stopped. I think cancelled is a user initiated state. From what I understand from the ticket this is not happening anyways?

**Comment by cdummett** [comment]
Hey @Vanitha I think this is expected behavior, the test you describe covers [0011-MARA-019](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0011-MARA-check_order_allocate_margin.md#0011-MARA-019) where the expected behaviour is for the amended order to stay on the book.

```
In Spot market, if an order is amended such that holding requirement is increased and user doesn't have sufficient balance in the general account to top up their holding account then their amend is not executed but the unamended order stays on the book. (0011-MARA-019)
```

[0080-SPOT-017](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0080-SPOT-product_builtin_spot.md#0080-SPOT-017) is to cover the case where a Spot market transitions from continuous trading to an auction and additional funds are needed to cover the possibility of fees being incurred on auction exit. In this scenario, the order should be removed from the book if the party doesn't have the required funds.

@ze97286  is right though, the order should be `STATUS_STOPPED` not `STATUS_CANCELLED`. I'll update the spec and AC to make that clearer.

**Comment by gordsport** [comment]
closing

**Comment by VanithaVega** [comment]
Hi @ze97286  @cdummett , 

I have ran the following steps and this is definitely wrong right

1. Propose a Spot Market and take it to Continuous Trading state  (throughout the steps , market is in STATE_ACTIVE status
2. create a trader with asset "quote_asset" and deposit amount 100 to quote asset
3. submit a spot trade BUY@base_asset/quote_asset@Size 5 @ Price 10 @limit GTC
4. above order is in Active state and shows below account balance
```
assert buy_trader_balance["quote_asset"]["General"] == 50.0
assert buy_trader_balance["base_asset"]["General"] == 0.0
assert buy_trader_balance["quote_asset"]["Holding"] == 50.0
assert buy_trader_balance["base_asset"]["Holding"] == 0.0

```
5. amend the above order as BUY@base_asset/quote_asset@Size delta - 12 and actual size 17 @ Price 10
6. balace after the amend operation is shown as 

```
    assert buy_trader_balance["quote_asset"]["General"] == 0.0
    assert buy_trader_balance["base_asset"]["General"] == 0.0
    assert buy_trader_balance["quote_asset"]["Holding"] == 100.0
    assert buy_trader_balance["base_asset"]["Holding"] == 0.0

```
7. create another trader with asset "quote_asset" and "base_asset" and deposit amount 300 each asset
8. place a sell order as SELL@base_asset/quote_asset @ size 17 @ price 10 @ limit GTC 
9. Orders are matched and traded for size of 17  and maker fee (maker fee - 0.04% and infra fee 0.001% )
`"buyerFee":{"makerFee":"0","infrastructureFee":"0","liquidityFee":"0"},"sellerFee":{"makerFee":"680000000000000000","infrastructureFee":"170000000000000000","liquidityFee":"0"}}`
10.  Buy trader has the final balance of 

```
    assert buy_trader_balance["quote_asset"]["General"] == 0.68
    assert buy_trader_balance["base_asset"]["General"] == 17.0 
    assert buy_trader_balance["quote_asset"]["Holding"] == 0.0
    assert buy_trader_balance["base_asset"]["Holding"] == 0.0

```
11. seller balance is as below

    sell_trader_balance = get_balance(context,spot_trader_sell)

```
    assert sell_trader_balance["quote_asset"]["General"] == 399.15
    assert sell_trader_balance["base_asset"]["General"]  == 283.0
    assert sell_trader_balance["quote_asset"]["Holding"] == 0.0
    assert sell_trader_balance["base_asset"]["Holding"] == 0.0

```

The above scenario does not adhere to AC [0011-MARA-019](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0011-MARA-check_order_allocate_margin.md#0011-MARA-019)

`In Spot market, if an order is amended such that holding requirement is increased and user doesn't have sufficient balance in the general account to top up their holding account then their amend is not executed but the unamended order stays on the book. (0011-MARA-019)
`
`If the party does not have sufficient funds in their general account to cover this transfer, the order should be stopped ([0080-SPOT-017](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0080-SPOT-product_builtin_spot.md#0080-SPOT-017)).

`
The above both the ACs are failing as we have a filled order for 170 and buyer credited with 17 units of base asset (equivalent to 170 quote asset units) but the buyer just got asset balance of 100 . This defect is a valid one and can I go ahead and re-open the defect.

**Comment by ze97286** [comment]
the following FT demonstrates your steps 1-6 working as expected, can you please investigate the system test?

```
Feature: Failing to amend an order if there are insufficient funds, order remains in the book as is
  Scenario: Simple Spot Order matches with counter party
  Background:
    Given the fees configuration named "fees-config-1":
      | maker fee | infrastructure fee |
      | 0.005     | 0.002              |
    And the simple risk model named "my-simple-risk-model":
      | long                   | short                  | max move up | min move down | probability of trading |
      | 0.08628781058136630000 | 0.09370922348428490000 | -1          | -1            | 0.2                    |
    And the fees configuration named "my-fees-config":
      | maker fee | infrastructure fee |
      | 0.004     | 0.001              |
    And the spot markets:
      | id      | name    | base asset | quote asset | risk model           | auction duration | fees          | price monitoring | sla params    |
      | BTC/ETH | BTC/ETH | BTC        | ETH         | my-simple-risk-model | 1                | fees-config-1 | default-none     | default-basic |
    # setup accounts
    Given the parties deposit on asset's general account the following amount:
      | party  | asset | amount |
      | party1 | ETH   | 1000   |
      | party2 | BTC   | 100    |
    # place orders and generate trades
    And the parties place the following orders:
      | party  | market id | side | volume | price | resulting trades | type       | tif     | reference |
      | party1 | BTC/ETH   | buy  | 1      | 100   | 0                | TYPE_LIMIT | TIF_GFA | t1-b-1    |
      | party2 | BTC/ETH   | sell | 1      | 100   | 0                | TYPE_LIMIT | TIF_GTC | t2-s-1    |
    Then "party2" should have holding account balance of "1" for asset "BTC"
    Then "party1" should have holding account balance of "100" for asset "ETH"

    Then the orders should have the following states:
      | party  | market id | side | volume | price | status        |
      | party1 | BTC/ETH   | buy  | 1      | 100   | STATUS_ACTIVE |
      | party2 | BTC/ETH   | sell | 1      | 100   | STATUS_ACTIVE |

    Then the opening auction period ends for market "BTC/ETH"
    And the trading mode should be "TRADING_MODE_CONTINUOUS" for the market "BTC/ETH"
    And the mark price should be "100" for the market "BTC/ETH"

    And the following trades should be executed:
      | buyer  | price | size | seller |
      | party1 | 100   | 1    | party2 |
    Then "party2" should have holding account balance of "0" for asset "BTC"
    Then "party1" should have holding account balance of "0" for asset "ETH"
    Then "party1" should have general account balance of "900" for asset "ETH"

    And the parties place the following orders:
      | party  | market id | side | volume | price | resulting trades | type       | tif     | reference |
      | party1 | BTC/ETH   | buy  | 5      | 100   | 0                | TYPE_LIMIT | TIF_GTC | t1-b-111  |

    Then "party1" should have holding account balance of "500" for asset "ETH"

    Then the parties amend the following orders:
      | party  | reference | price | size delta | tif     | error                                                              |
      | party1 | t1-b-111  | 100   | 12         | TIF_GTC | party does not have sufficient balance to cover the trade and fees |

    Then "party1" should have holding account balance of "500" for asset "ETH"
    Then the orders should have the following states:
      | party  | market id | side | volume | price | status        |
      | party1 | BTC/ETH   | buy  | 5      | 100   | STATUS_ACTIVE |
```
