### ISSUE TITLE
[Bug]: One successor market passing governance adversely affects another child market which is trying to succeed the same parent.

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8861]
### Problem encountered

@daunatv found a bug on stagnet where a market proposal seems to have been rejected when another one passed governance, which is not something which should happen according to the specs (markets should only be rejected upon one becoming "Enacted"). I've modified an existing test which shows a similar but different issue, where the _second_ market due to pass governance never leaves "Proposed" state.

### Observed behaviour

Two markets with overlapping proposals can both go into opening auction when attempting to succeed the same parent.

### Expected behaviour

Depending on exact scenario and build either one is rejected or one may never leave "Proposed" state.

### Steps to reproduce

```bash
1. Check out overlapping_successor_proposals branch
2. pytest -k test_first_child_is_only_successor_overlapping_proposals
```

### Software version

fef2b0d70bccde2bc695787f2fe27330472f1f2b

**Comment by daunatv** [comment]
Will add an example to the issue:
Give both proposals enough votes to pass

**Market A:**
Submission time: 8:00 am
End of vote: 8:10 am
Enactment (not going out of opening auction): 08:20 am

**Market B:**
Submission time: 8:01 am
End of vote: 8:21 am
Enactment (not going out of opening auction): 8:22 am

At the time of **enactment** of Market A, Market B is **rejected** if the voting has not ended at this time, even if Market A is still in opening auction.
