### ISSUE TITLE
Review specs to ensure historical perpetual data will be available in the API

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega#8903]
We eventually want to be able to show historical data on a perpetual market on the front end. Until that time, the data needs to be accessible via the API.

We _believe_ this function is already defined in the spec. This task is to double check that the spec does include this function, and that the API will deliver all the data we expect:
- funding rate over time
- all funding payments over time
- one key's funding payments over time
- oracle price over time
- oracle price vs. market price over time

**Comment by JonRay15** [comment]
This is covered now by other epics / tickets
