### ISSUE TITLE
[Bug]: Cannot propose a market with performanceHysteresisEpochs=0

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#8932]
### Problem encountered

propose a market with performanceHysteresisEpochs=0 is rejected
https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
ACs 0042-LIQF-035 and 0042-LIQF-049 expect this param to be 0 so it should be a valid value

### Observed behaviour

failed on setup with "AssertionError: Unexpected wallet/core response self.wallet_response="{'jsonrpc': '2.0', 'error': {'code': -32602, 'message': 'Invalid params', 'data': 'proposal_submission.terms.change.new_market.changes.**sla_params**.performance_hysteresis_epochs (must be positive)'}, 'id': 'request'}""

### Expected behaviour

market proposal is successful
and when market proposal is rejected that the response has the correct parameter `liquidity_sla_parameters` instead of `sla_params` for a futures market

### Software version

vega branch feature/integrate-sla-rebased

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/86831/testReport/junit/tests.orders/orderStatus_test/test_send_order_during_auction/

**Comment by gordsport** [comment]
closing as fixed
