### ISSUE TITLE
Insurance pool distribution - treasury is not receiving a portion of the insurance pool from a settled market

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8937]
This requirement

```
 When the market enters transitions from "trading terminated state" to "settled" state (see [market lifecyle](0043-MKTL-market_lifecycle.md)),
    the insurance pool account has its balance[redistributed](./0015-INSR-market_insurance_pool_collateral.md) to the on-chain treasury
    for the settlement asset of the market and other insurance pools using the same asset.
```

Test test_insurance_pool_behaviour_on_market_settlement
This fails as we expect the insurance pool from a closedout market to be distributed evenly between all markets and the treasury pool.

The four markets are 
1. Has a insurance balance and is then settled.
2. Active market
3. Terminated market
4. Pending market

The markets 2,3,4 are receiving the insurance pool slice but the treasury pool does not get a slice  and remains at zero. Treasury pool in this case is account type "Reward" assetID VEGA asset.

**Comment by ze97286** [comment]
@vega-paul no, it's expected to be distributed between other market and the global insurance account.

**Comment by ze97286** [comment]
this is not a bug.
