### ISSUE TITLE
Wallet: User password not being allows for low entropy

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8941]
### Issue

Although it is ultimately the user/node operators responsibility to keep their security in check there is a minor enhancement suggestion that has come from the recent penetration testing audit.

Currently a user can use any any string as a password e.g., `vegavega` or `123` - these low entropy passwords can be easily brute forced. 

It may not be within the ethos of Vega to force a given rule set for the password to have to adhere to, however, maybe measuring the entropy and warning the user the password could be stronger.

**Comment by dexturr** [comment]
This is completed on the release that went out yesterday, so we wholeheartedly agree!

Thanks for the feedback.

<img width="356" alt="Screenshot 2023-07-28 at 10 02 12" src="https://github.com/vegaprotocol/vega/assets/26136207/a8cfb92b-029c-4e34-b4f6-5f17352d267e">

**Comment by gordsport** [comment]
duplicate
