### ISSUE TITLE
Governance Terminating market uncrossing price

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8964]
Proposed a market and moved state to TRADING_MODE_MONITORING_AUCTION by submitting two orders outside price mon boundaries.

orders buy/sell 1 @ 1300

Then terminated the market via govervance proposal, settle price was 1000

Trade produced 1 @ 1250

Expected trade at 1300

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/88802/

**Comment by gordsport** [comment]
@vega-paul 

Please can you ad more details like the branches being used etc.. to help investigations into this

**Comment by gordsport** [comment]
@vega-paul - is this still happening?

**Comment by EVODelavega** [comment]
The logs from this test aren't accessible anymore, but given that the market was in auction when it was settled, the price at which the book uncrosses will be the same as when we're leaving any other auction: the price at which we achieve the max tradable amount. There may well be a buy and sell order on the book, both at 1,300, but all orders must be taken into consideration. If there's existing buy/sell orders at, for example 1,250, then the buy order for 1,300 will likely uncross with those orders instead, leaving an uncrossed book and a last traded/new mark price of 1,250.

**Comment by gordsport** [comment]
@vega-paul - is this still happening?
