### ISSUE TITLE
[Bug]: Successor has no reference to a settled parent after checkpoint

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8968]
### Problem encountered

If the parent of a successor market has been settled, then we do a checkpoint restart, the parent is forgotten, and no longer referred to on the child, even as a reference. Per https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0081-SUCM-successor_markets.md#0081-SUCM-031 , it should be. We should either do this or update the spec if it is not desired.

### Observed behaviour

No parent can be found after checkpoint, either via the market API searching for the parent, or as a reference on the child market.

### Expected behaviour

AC says parent should still be available post restart since it has children, and as a reference on the child.

### Steps to reproduce

```bash
1. Check out this branch: https://github.com/vegaprotocol/system-tests/pull/2382 
2. Ensure test is not skipped (probably will be shortly, while this issue is open)
3. pytest -k test_settled_succeeded_parent_remembered
```

### Software version

ee22fd47cd44a334c9dcb47353318628c8b30755

**Comment by EVODelavega** [comment]
The successor not having the reference to the parent market is indeed a bug. The second assert in the test, however (calling `get_market` to check if the parent market has a reference to the child market) is not. The data-node DB is wiped when running this test, and the parent market has been terminated, succeeded, and settled, and the successor window has expired. As a result, the checkpoint will not contain the parent market anymore, so the data-node won't receive any data to create a new record.
