### ISSUE TITLE
[Bug]: successor field not updated on parent market

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8972]
### Problem encountered

I've written an automated test that uses a terminated & settled market as the parent for a new market. Once the child has been enacted, it is updated to show the parent, but the parent is not updated to show the child. (Note that the test I discovered this with does snapshot things, but I disabled that and it's not relevant. I _think_ the important part is that the parent is settled. Best guess we've previously only checked this field while the parent was still active, and data node loses the reference when termination/settlement happens?

### Observed behaviour

Successor field missing from parent market

### Expected behaviour

Successor field is visible on parent market

### Steps to reproduce

```bash
1. Check out https://github.com/vegaprotocol/system-tests/pull/2382
2. Re-enable the line that asserts the successor field on the parent market:

assert marketsTrading.get_market(child.id)["parentMarketId"] == parent.id
# assert marketsTrading.get_market(parent.id)["successorMarketId"] == child.id
```
3. pytest -k test_successor_markets_snapshots
```


### Software version

ee22fd47cd44a334c9dcb47353318628c8b30755

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

```shell
# Propose a new market using that as parent. Check the new node is still running.
        child = Market(
            context,
            proposer=proposer,
            parent_market_id=parent.id,
            insurance_pool_fraction=0.5,
        )
        child.propose(proposer)
        ordersMod.reset_market(context, child.id)
        assert marketsTrading.get_market(child.id)["parentMarketId"] == parent.id
>       assert marketsTrading.get_market(parent.id)["successorMarketId"] == child.id
E       KeyError: 'successorMarketId'
```

**Comment by guoguojin** [comment]
Closing as this was fixed with https://github.com/vegaprotocol/system-tests/pull/2418
