### ISSUE TITLE
[Bug]: It's not possible to cancel or amend a liquidity commitment that's pending 

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#8988]
It's not possible to submit a liquidity amendment or cancellation transaction while the commitment is in a PENDING state. 

As an aside: PENDING state is not consistent with previous behaviour, before we'd have that state only if liquidity provision was submitted during an auction. Now it remains PENDING until start of the new epoch for new commitments, not sure how amendments are treated. It's an internal concept (though it's visible externally) not covered by specs so I don't really care, just flagging it in case it has some implications for other bits of core or the frontend. 

When fixing this please assure the bond amount eventually gets released after successfully cancelling the commitment. 

See https://github.com/vegaprotocol/vega/pull/8987 to reproduce.

**Comment by gordsport** [comment]
merged
