### ISSUE TITLE
Rework the team implementation to match the reworked spec

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#8991]
**ON HOLD**

- Team is now ReferralSet
- Team details are scoped inside an TeamDetails message.
- JoinTeam is now ApplyReferalCode

**Comment by gordsport** [comment]
@guoguojin - please subscribe to this issue and check that there is not change to your PR (no impact is expected but best to check)

**Comment by ValentinTrinque** [comment]
Done.
