### ISSUE TITLE
[Bug]: market should be able to set providers_fee_calculation_time_step=0 

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#8992]
### Problem encountered

creating a new futures market with `providers_fee_calculation_time_step=0` reports an error

### Observed behaviour

`AssertionError: Unexpected wallet/core response self.wallet_response="{'jsonrpc': '2.0', 'error': {'code': -32602, 'message': 'Invalid params', 'data': 'proposal_submission.terms.change.new_market.changes.sla_params.providers.fee.calculation_time_step (must be positive)'}, 'id': 'request'}"`

### Expected behaviour

creating a new futures market with `providers_fee_calculation_time_step=0` should not report an error

### Steps to reproduce

```bash
1. create a futures market with `providers_fee_calculation_time_step=0`
2. Observe the error
```

### Software version

vega branch feature/integrate-sla-rebased-2

### Failing test

test_liquidity_providers_accounts_during_protocol_upgrade[auction_market_object-traders]

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/89739/testReport/junit/tests.protocol_upgrade/protocol_upgrade_test/test_liquidity_providers_accounts_during_protocol_upgrade_auction_market_object_traders_/

**Comment by ze97286** [comment]
should it not? what's the meaning of a timestep = 0? 

separately, given the validation is common, it equally applies to spots.

**Comment by Sohill-Patel** [comment]
Thanks for clarifying when the transfer does take place

**Comment by Sohill-Patel** [comment]
fixed
