### ISSUE TITLE
Perpertuals integration tests fails

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#8999]
See attached logs.

The command lauching the tests has been disabled in the Jenkinsfile.

[logs.txt](https://github.com/vegaprotocol/vega/files/12274877/logs.txt)

**Comment by EVODelavega** [comment]
Based on the logs attached, I don't think there's a particular test that fails, it looks like the job is killed mid-run, could be a timeout issue

**Comment by daniel1302** [comment]
Do you have failing job for that by chance?

**Comment by EVODelavega** [comment]
@daniel1302 The run from which this log was taken seems to be gone. The PR linked to this issue has the step enabled again, so if the pipeline fails for that PR, that'll be where to find the failing job I guess

**Comment by gordsport** [comment]
blocked on @vegaprotocol/ops to investigate issues since the move of Jenkins to the office hardware

**Comment by EVODelavega** [comment]
The step has been re-enabled, adding a `-timeout 30m` to the step. Because of the large number of steps we were running in parallel, running all the integration tests against perpetual markets could take longer than the default 10min timeout
