### ISSUE TITLE
[Bug]: Following checkpoint restore ACCOUNT_TYPE_LP_LIQUIDITY_FEES not transferred to network treasury

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9026]
### Problem encountered

Following network restore, the ACCOUNT_TYPE_LP_LIQUIDITY_FEES should be transferred to the network treasury

### Observed behaviour

ACCOUNT_TYPE_LP_LIQUIDITY_FEES not transferred to network treasury

### Expected behaviour

ACCOUNT_TYPE_LP_LIQUIDITY_FEES should be transferred to the network treasury

### Steps to reproduce

```bash
1. Run the test test_lp_fees_actioned_after_checkpoint in ST
2. Observe the error
```

### Software version

vega branch feature/integrate-sla-rebased-2

### Failing test

test_lp_fees_actioned_after_checkpoint

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/90691/testReport/junit/tests.snapshots/snapshot_test/test_lp_fees_actioned_after_checkpoint_auction_market_object_traders_/

**Comment by ze97286** [comment]
@Sohill-Patel can you share the checkpoint that this is loaded from? more specifically, you say it's not going to the network treasury, what does happen with the funds in that account?

**Comment by Sohill-Patel** [comment]
@ze97286 This is the checkpoint used
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/90691/artifact/checkpoints/

The funds are transferred to the lp's general account instead of the network treasury

**Comment by ze97286** [comment]
@Sohill-Patel as per the discussion and spec PR this is now the expected behaviour.
