### ISSUE TITLE
[Bug]: Error querying oracle/data sources in Fairground

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#9075]
### Problem encountered

This happens with 0.72.8 on testnet. Stagnet acts fine, which suggests weird state. It happens on at least 4 different nodes (n00, n06, n07, n08)

### Observed behaviour

Using GraphQL or REST to query oracle data both error. REST shows the most useful output:

```
{"code":13,"message":"Internal error","details":[{"@type":"type.googleapis.com/vega.ErrorDetail","code":190002,"message":"failed retrieve data for oracle specs","inner":"querying oracle specs: scany: scan row into struct fields: can't scan into dest[3]: proto: syntax error (line 1:1): unexpected token null"}]}⏎
```

REST:
```
curl -L -X GET 'https://api.n00.testnet.vega.xyz/api/v2/oracle/specs' -H 'Accept: application/json'
```

GraphQL: 
```graphql
{
  oracleSpecsConnection {
    edges {
      node {
        dataSourceSpec {
          spec {
            createdAt
          }
        }
      }
    }
  }
}
```

### Expected behaviour

I get a list of oracles

### Steps to reproduce

```bash
1. Go to https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-oracle-specs
2. Hit 'request'
3. Try the provided GraphQL equivalent
```

### Software version

0.72.8

**Comment by guoguojin** [comment]
Re-opening this ticket until I have checked to make sure that the oracle spec data column can/should  be nullable or fix whatever is causing the data to be created as null as stated above.

**Comment by guoguojin** [comment]
The data field was a recent addition to the oracle_specs table post going live. As a result, any rows in the oracle_specs table that was created before the column was added, including when the database is restored from network history will have null values in the oracle_specs table so the fix that was implemented was the correct fix. Closing this ticket as done.
