### ISSUE TITLE
[BUG] position settlement via governance market termination

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9082]
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92847/

Test confirms post settlement balances for two traders in a market which has been terminated via governance proposal. Looks like the settlement calc is not correct.

Market in auction state
```
{"id":"34299-91","block":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4","type":"BUS_EVENT_TYPE_MARKET_DATA","marketData":{"markPrice":"100000000","bestBidPrice":"0","bestOfferPrice":"0","bestStaticBidPrice":"0","bestStaticOfferPrice":"0","midPrice":"0","staticMidPrice":"0","market":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","timestamp":"1692110776463540000","openInterest":"1000000","auctionEnd":"1692110777083389000","auctionStart":"1692110769083389000","indicativePrice":"0","marketTradingMode":"TRADING_MODE_MONITORING_AUCTION","trigger":"AUCTION_TRIGGER_UNABLE_TO_DEPLOY_LP_ORDERS","extensionTrigger":"AUCTION_TRIGGER_UNABLE_TO_DEPLOY_LP_ORDERS","targetStake":"2764500000000000000000","suppliedStake":"390500000000000000000000","marketValueProxy":"390500000000000000000000","liquidityProviderFeeShare":[{"party":"cc539637c50c61f70f296b13c41f974ac104ee2e65d3046d29b1ac51bce2d424","equityLikeShare":"1","averageEntryValuation":"390500000000000000000000","averageScore":"0","virtualStake":"390500000000000000000000"}],"marketState":"STATE_SUSPENDED","nextMarkToMarket":"1692110768776614000","lastTradedPrice":"100000000","marketGrowth":"0"},"version":1,"chainId":"testnet-001","txHash":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4"}

```
Termination with price
```
{"id":"34299-140","block":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"54257ec797819db7fe106cf9adb594b3dc9dbc30fdceb1334d88856236ddd1b9","reference":"E221F5DC91","partyId":"cc539637c50c61f70f296b13c41f974ac104ee2e65d3046d29b1ac51bce2d424","state":"STATE_ENACTED","timestamp":"1692110770870715000","terms":{"closingTimestamp":"1692110775","enactmentTimestamp":"1692110775","updateMarketState":{"changes":{"marketId":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","updateType":"MARKET_STATE_UPDATE_TYPE_TERMINATE","price":"50000000"}}},"rationale":{"description":"Market State Update","title":"Market State Update Proposal: Terminate"},"requiredParticipation":"0.00000015","requiredMajority":"0.66","requiredLiquidityProviderParticipation":"0.00001","requiredLiquidityProviderMajority":"0.66"},"version":1,"chainId":"testnet-001","txHash":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4"}

```

Trade produced from two filled orders
```
{"id":"34299-87","block":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4","type":"BUS_EVENT_TYPE_ORDER","order":{"id":"f7de84769bcdf1de350ddd8644ffe3ad694a897bd1fbe11de0459f9694f78a7e","marketId":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","partyId":"331f42d41e4171aa551b05b4ca9025fd7b83f0ac8c143244509bed7ff16d7457","side":"SIDE_SELL","price":"100000000","size":"500000","timeInForce":"TIME_IN_FORCE_GTC","type":"TYPE_LIMIT","createdAt":"1692110770259323000","status":"STATUS_FILLED","reference":"test_auction_uncrosses_at_termination_settle_price[market]-ef9c8f75","updatedAt":"1692110776463540000","version":"1","batchId":"1"},"version":1,"chainId":"testnet-001","txHash":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4"}
{"id":"34299-89","block":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4","type":"BUS_EVENT_TYPE_ORDER","order":{"id":"cf4a5f675251d8b0207df34142ccd7f1ddc4cbbb25d887407bd370af65139676","marketId":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","partyId":"1f3a93ed78e05b474f20a9707fe0124742df20f07d22a40b7e9a7033cbe18526","side":"SIDE_BUY","price":"100000000","size":"500000","timeInForce":"TIME_IN_FORCE_GTC","type":"TYPE_LIMIT","createdAt":"1692110769690063000","status":"STATUS_FILLED","reference":"test_auction_uncrosses_at_termination_settle_price[market]-5a3cd01b","updatedAt":"1692110776463540000","version":"1","batchId":"1"},"version":1,"chainId":"testnet-001","txHash":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4"}

```

Trade
```
{"id":"34299-88","block":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4","type":"BUS_EVENT_TYPE_TRADE","trade":{"id":"9e07c945c45bc5f8aa40ded1206ba923bffba4e453aa04fb97e9993c8262b309","marketId":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","price":"100000000","size":"500000","buyer":"1f3a93ed78e05b474f20a9707fe0124742df20f07d22a40b7e9a7033cbe18526","seller":"331f42d41e4171aa551b05b4ca9025fd7b83f0ac8c143244509bed7ff16d7457","buyOrder":"cf4a5f675251d8b0207df34142ccd7f1ddc4cbbb25d887407bd370af65139676","sellOrder":"f7de84769bcdf1de350ddd8644ffe3ad694a897bd1fbe11de0459f9694f78a7e","timestamp":"1692110776463540000","type":"TYPE_DEFAULT","buyerFee":{"makerFee":"0","infrastructureFee":"2500000000000000000","liquidityFee":"750000000000000000000"},"sellerFee":{"makerFee":"0","infrastructureFee":"2500000000000000000","liquidityFee":"750000000000000000000"}},"version":1,"chainId":"testnet-001","txHash":"F0E3A6955C108DD252876EC349E7897BC7D6A8DB2E30DC37A95F8693425DBAE4"}
```

Starting balances
Buyer 100000000000000000000000000
Seller 100000000000000000000000000

Ending balances post termination
Buyer 99996747500000000000000000
Seller 100001747500000000000000000

Expected balance diffs
Buyer 500000000000000000000 (trade_price-settlement_price) + seller_fees  (1000-250) + (0 maker)
Seller 755000000000000000000 abs(settlement_price - trade_price) - seller_pay_fees - seller_pay_maker (750) - (150+50) - 0

Whats strange here is the scaling on the governance terminated market traded fees - they are enormous 

exactly the same trade created with oracle termination at same settled price
```
oracle trade
{"id":"33450-88","block":"E82D64EF1D4A70EF58FC050FE1C915D4E34886776161DAA5ED157F559B2162E3","type":"BUS_EVENT_TYPE_TRADE","trade":{"id":"0a52501ec14652cd055197e04485bb2618f8a4edd21aa892bf3178073e833cdf","marketId":"7ada4154a57bbc9d4cc52f3dc148519200935f785d3bf8a0e1e62de3e23b483e","price":"100000000","size":"500000","buyer":"2850bdf6ff353d0f6ffb31c7ebd354f7c8d0982bf3131356f3f004d1900562f3","seller":"6034ab99833ded7b333715d25098b8a8854967a0d6d95c864edd827f5e42abf9","aggressor":"SIDE_SELL","buyOrder":"89d6946b7bcbb7fef345260f3f4f2a11cfe457b0d33680a6918538d3016361de","sellOrder":"01f7cde1f2298ec4ec8acb781ddec0b38475b891eea5f6c8fdfaee6eb1c8fabc","timestamp":"1692110237527257000","type":"TYPE_DEFAULT","buyerFee":{"makerFee":"0","infrastructureFee":"0","liquidityFee":"0"},"sellerFee":{"makerFee":"20000000","infrastructureFee":"5000000","liquidityFee":"1500000000"}},"version":1,"chainId":"testnet-001","txHash":"C6920E36E6F54B8C3026D0D31D9FADA5A53093545D41B8F4E765C1AB9310CF5B"}
```

**Comment by ze97286** [comment]
@paul what decimals are you sending the settlement price with?

**Comment by vega-paul** [comment]
@ze97286 
update proposal has "updateType":"MARKET_STATE_UPDATE_TYPE_TERMINATE","price":"50000000"}
original proposal has
"decimalPlaces":"5", "positionDecimalPlaces":"5"


```{"id":"34250-74","block":"09D8FF4A12FC62D32EC38CC9DB4CB27769C00A63E2A8F161D60685B59934AF6E","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"735f0ee548c50c8359cf7110d1aede6f0846e978d8e98a83ba9973e547d8fde8","reference":"BB3301DF65","partyId":"cc539637c50c61f70f296b13c41f974ac104ee2e65d3046d29b1ac51bce2d424","state":"STATE_ENACTED","timestamp":"1692110746094358000","terms":{"closingTimestamp":"1692110750","enactmentTimestamp":"1692110751","newMarket":{"changes":{"instrument":{"name":"Futures System-Tests Market","code":"CRYPTO:VEGA CORE SYS TEST","future":{"settlementAsset":"2eb8557ac7b59b470840948d059ea39b869d32eff03a9a721a696040ec8abfc6","quoteName":"USD","dataSourceSpecForSettlementData":{"external":{"oracle":{"signers":[{"pubKey":{"key":"cc539637c50c61f70f296b13c41f974ac104ee2e65d3046d29b1ac51bce2d424"}}],"filters":[{"key":{"name":"oracle.test.settlement74D30","type":"TYPE_INTEGER","numberDecimalPlaces":"5"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}},"dataSourceSpecForTradingTermination":{"external":{"oracle":{"signers":[{"pubKey":{"key":"cc539637c50c61f70f296b13c41f974ac104ee2e65d3046d29b1ac51bce2d424"}}],"filters":[{"key":{"name":"oracle.test.terminationA73F9","type":"TYPE_BOOLEAN"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"True"}]}]}}},"dataSourceSpecBinding":{"settlementDataProperty":"oracle.test.settlement74D30","tradingTerminationProperty":"oracle.test.terminationA73F9"}}},"decimalPlaces":"5","metadata":["asset_class:fx/crypto","product:futures"],"priceMonitoringParameters":{},"liquidityMonitoringParameters":{"targetStakeParameters":{"timeWindow":"10","scalingFactor":5},"triggeringRatio":"0","auctionExtension":"1"},"logNormal":{"riskAversionParameter":0.001,"tau":0.00011407711613050422,"params":{"r":0.016,"sigma":1.5}},"positionDecimalPlaces":"5","lpPriceRange":"1","linearSlippageFactor":"0.01","quadraticSlippageFactor":"0"}}},"rationale":{"description":"Proposal submitted to enact a new Market","title":"Market Proposal"},"requiredParticipation":"0.00000015","requiredMajority":"0.66"},"version":1,"chainId":"testnet-001","txHash":"09D8FF4A12FC62D32EC38CC9DB4CB27769C00A63E2A8F161D60685B59934AF6E"}'```

**Comment by EVODelavega** [comment]
Based on the event logs, there's only 2 points at which a trade happens: block 200 (when leaving opening auction, and once before settling the market (at bock 240). Based on the transfers, though, there's a bond slashing transfer, and the market is stuck in liquidity auction until the end. The market is being settled on block 240, so that last trade is the market being closed (we were in auction up to this point, so again, the only fees that apply are infrastructure fees).
Turning back to the transfer events, we can see the infrastructure fees being moved to the vesting rewards account, and eventually in to the vested rewards accounts (block 247). These fees would've been paid out to the LP, but based on the bond slashing transfer, and the fact that the market was in liquidity auction (target stake not met), it seems that there was no LP for the market at the time, and the fees simply ended up in the insurance pools (for the market and global insurance), which is something we can see in the transfers, too.

I honestly don't see any indication of a bug. It's a bit of an odd case (settling a market without an LP, while it's in auction), but other than that, nothing jumps out

**Comment by EVODelavega** [comment]
Having looked at the events from a more recent build again in detail, the observed balances mentioned in this ticket can't be found. The last transfer, clearing margin accounts and moving the balance back to the general account shows this:

```
{
        "entries": [
          {
            "fromAccount": {
              "assetId": "5a38d4346477c500fddff7469a136028b6ada6e3d7587f69e8cd19c9b9b8a6db",
              "type": "ACCOUNT_TYPE_MARGIN",
              "owner": "25f7455dc88cc27d99e320ffa7ade932e65e644ebc84f2520b547c4420b049ca",
              "marketId": "a1bf17082fe74fec405ba4fc33b045bb7980451f5946f0e196ac0f1ec56f9d34"
            },
            "toAccount": {
              "assetId": "5a38d4346477c500fddff7469a136028b6ada6e3d7587f69e8cd19c9b9b8a6db",
              "type": "ACCOUNT_TYPE_GENERAL",
              "owner": "25f7455dc88cc27d99e320ffa7ade932e65e644ebc84f2520b547c4420b049ca"
            },
            "amount": "0",
            "type": "TRANSFER_TYPE_CLEAR_ACCOUNT",
            "timestamp": "1695806915664705823",
            "fromAccountBalance": "0",
            "toAccountBalance": "99997497500000000000000000"
          }
        ],
        "balances": [
          {
            "account": {
              "assetId": "5a38d4346477c500fddff7469a136028b6ada6e3d7587f69e8cd19c9b9b8a6db",
              "type": "ACCOUNT_TYPE_GENERAL",
              "owner": "25f7455dc88cc27d99e320ffa7ade932e65e644ebc84f2520b547c4420b049ca"
            },
            "balance": "0"
          }
        ]
      }
```

This is the party that was holding 5 long at 1,000. The proposal to terminate the market specified a settlement price of 500, so the trader incurs a loss of `5 * (1000 - 500)`, or 2,500. That would mean we'd expect to see an end balance of `9999750000`. 
What we haven't accounted for are the infrastructure fees on this trade, which come to 250 (again, this can be found in the ledger movement events and the trade events). Because the market was in auction, and as per spec, we are uncrossing the book before the final settlement, the fee is paid by both the buyer and the seller so 125 each), meaning we would expect the general balance to be `9999750000 - 125 = 999974975`. This is exactly what we're seeing here. Based on the events we can also see that the market is in auction, right up to the moment where the market settles. At that point, we can see a trade is generated (again, as per spec), and the market performs a final mark to market settlement before settling the open positions.

Not a bug, the balances are correct, the events indicate core is behaving exactly as expected, and in accordance with the spec.
