### ISSUE TITLE
[Bug]: too big precision of virtualStake in BUS_EVENT_TYPE_MARKET_DATA

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#9105]
### Problem encountered

Core event `BUS_EVENT_TYPE_MARKET_DATA` has a new `virtualStake` field in v0.72.8 compared with v0.71.x.
That field is a decimal with unlimited (seemingly) precision going up and above 600k digits on Fairground.

### Observed behaviour

Core event `BUS_EVENT_TYPE_MARKET_DATA` has a new `virtualStake` field in v0.72.8 compared with v0.71.x.
That field is a decimal with unlimited (seemingly) precision going up and above 600k digits on Fairground.

### Expected behaviour

The `virutalStake` should have a limited precision.

### Steps to reproduce

```bash
1. Download the correct vega binary (v0.72.x)
2. Connect to the stream of events coming from network

./v0.72.8/vega tools stream --address n01.testnet.vega.rocks:3002 --type BUS_EVENT_TYPE_MARKET_DATA | jq -r ".marketData.liquidityProviderFeeShare[] | .virtualStake"

3. Observer the precision of values
```

### Software version

v0.72.8

### Configuration used

```shell
Fairground network
```

**Comment by davidsiska-vega** [comment]
We probably shouldn't be calculating it to this precision in core either so there is a scope for not just truncating at the end but basically revisiting the whole calculation. 

As a rule of thumb: the virtual stake is almost like stake which is (I think) in asset precision, so virtual stake shouldn't use more precision than the data type we use for asset values.
