### ISSUE TITLE
[Bug]: internal error querying for stop orders

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#9118]
### Problem encountered

In stagnet, using pagination to filter/sort stop orders leads to an internal error

### Observed behaviour

```graphql
{
  stopOrders(pagination: {last: 2}) {
    edges {
      node {
      	status
      }
    }
  }
}
```

```json
{
  "errors": [
    {
      "message": "failed to get orders",
      "path": [
        "stopOrders"
      ],
      "extensions": {
        "code": 13,
        "type": "Internal"
      }
    }
  ],
  "data": {
    "stopOrders": null
  }
}
```

### Expected behaviour

The query returns stop orders

### Steps to reproduce

```bash
1. https://api.stagnet1.vega.xyz/graphql/
2. Submit query
```

### Software version

0.72.9

**Comment by ettec** [comment]
The reason for the error is the code below, basically iterating backward (ie from last) is not supported - iterating forward (from first) is fine.  The error message is clear but it gets lost, and the user is presented with a not at all useful 'internal error' message - this error handling is not particular to this scenario.

```
// We don't have the necessary views and indexes for iterating backwards for now so we can't use 'last'
	// as it requires us to order in reverse
	if p.HasBackward() {
		return nil, pageInfo, fmt.Errorf("'last' pagination for stop orders is not currently supported")
	}
```
