### ISSUE TITLE
[Bug]: SLA slashed at wrong time 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#9141]
### Problem encountered

See the feature test

1. line 165, supplied stake change from 1 to 2 (LP has amended commitment to 1); basically when LP did a LP amendment, 1 leaves 2 committed, 3 leaves 4 committed, 5 leaves 6 committed
2. line 89, the LP did not reduce anything yet, and then LP is slashed after moving blocks

### Observed behaviour

SLA is slashed when it should not 

### Expected behaviour

LP should not be slashed 

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

v0.71.6

### Failing test

https://github.com/vegaprotocol/vega/blob/spot-sla/core/integration/features/spot/liquidity_provision/0044-LIME_spot.feature

**Comment by gordsport** [comment]
closed in:

- https://github.com/vegaprotocol/vega/pull/9150
