### ISSUE TITLE
[Bug]: Network history segments start diverging

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9181]
### Problem encountered

The network history segment produced by datanodes start diverging.

The network history segment start diverging at segment - `2795`

`AssertionError: assert '2795 to 2816, id: QmVWZ1m17wxWd8v1yxLukA5nKe2eeeaR4hXmnUjx7J92nW, previous segment id: QmbwimURMb5WdeB6bLuUxwsynyE9j1AJhTBd4sqoG29ZKt' in ['Available contiguous history spans:', 'Contiguous history from block height 1 to 6710, from segment id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX to QmZZJVn63cftku6Nu9bRBa9tuV7WJCgnFJ1JBZRXx9vFkn', '1 to 22, id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX, previous segment id: ', '23 to 44, id: QmbvDfy7GVnDtrS683zjSQnmchQBp6EfjG1mCCpamWKcD4, previous segment id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX', '45 to 66, id: QmTuyG2sJRSdtz58tHiVpBdPo35poL88wMHLNMz1Nq471r, previous segment id: QmbvDfy7GVnDtrS683zjSQnmchQBp6EfjG1mCCpamWKcD4', '67 to 88, id: QmTY2u17DrzDaXLUHYCXhNp7ywAgebWRvXPfSJ9C8wpmsH, previous segment id: QmTuyG2sJRSdtz58tHiVpBdPo35poL88wMHLNMz1Nq471r', ...]`

### Observed behaviour

The segment produced by the restored node is 

`2795 to 2816, id: QmVWZ1m17wxWd8v1yxLukA5nKe2eeeaR4hXmnUjx7J92nW, previous segment id: QmbwimURMb5WdeB6bLuUxwsynyE9j1AJhTBd4sqoG29ZKt`

Original node:

`2795 to 2816, id: QmNMPPBH2xYgegYMK3hUqnZuCWT8ewmvuT4Dnr1viSkwsL, previous segment id: QmbwimURMb5WdeB6bLuUxwsynyE9j1AJhTBd4sqoG29ZKt`

### Expected behaviour

Data node segments produced by all datanodes should be the same.

### Steps to reproduce

```bash
Not too sure if this can be reproduced.

This issue was noticed as part of an overnight system tests run.

System Test Name - test_datanode_restore_from_dehistory
```

### Software version

vega - develop

### Failing test

test_datanode_restore_from_dehistory

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/98034/

### Relevant log output

```shell
AssertionError: assert '2795 to 2816, id: QmVWZ1m17wxWd8v1yxLukA5nKe2eeeaR4hXmnUjx7J92nW, previous segment id: QmbwimURMb5WdeB6bLuUxwsynyE9j1AJhTBd4sqoG29ZKt' in ['Available contiguous history spans:', 'Contiguous history from block height 1 to 6710, from segment id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX to QmZZJVn63cftku6Nu9bRBa9tuV7WJCgnFJ1JBZRXx9vFkn', '1 to 22, id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX, previous segment id: ', '23 to 44, id: QmbvDfy7GVnDtrS683zjSQnmchQBp6EfjG1mCCpamWKcD4, previous segment id: QmeFwiKYbrow6zB3yW5ziFmdLPvk6mVJ6yHj29W7jcHzaX', '45 to 66, id: QmTuyG2sJRSdtz58tHiVpBdPo35poL88wMHLNMz1Nq471r, previous segment id: QmbvDfy7GVnDtrS683zjSQnmchQBp6EfjG1mCCpamWKcD4', '67 to 88, id: QmTY2u17DrzDaXLUHYCXhNp7ywAgebWRvXPfSJ9C8wpmsH, previous segment id: QmTuyG2sJRSdtz58tHiVpBdPo35poL88wMHLNMz1Nq471r', ...]
```

**Comment by MuthuVega** [comment]
Another instance of the same error, updating here just for reference:

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/98533/testReport/tests.datanode/datanode_test/test_datanode_history_segments_are_deterministic/

**Comment by MuthuVega** [comment]
And another instance of the same error , updating as the older jobs / logs will be deleted after 7 days

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1485/testReport/tests.datanode/datanode_test/test_datanode_history_segments_are_deterministic/

**Comment by MuthuVega** [comment]
@ettec - Latest network divergence issue from last night's overnight run

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/22/testReport/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_history_segments_are_deterministic/

**Comment by gordsport** [comment]
@MuthuVega - is this run have the fix from Matt in here: https://github.com/vegaprotocol/vega/pull/9338

If not please can you open a new issue

**Comment by gordsport** [comment]
closed with https://github.com/vegaprotocol/vega/pull/9338
