### ISSUE TITLE
[Bug]: Error when starting new datanode - failed to start state sync: failed to set up light client state provider

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9245]
### Problem encountered

This error / issue happens once in a while.
Unable to start a new datanode and on investigation found the below error in the logs.

Core Logs:

```
2023-08-30T17:19:44.326Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting MConnection service", "impl": "MConn{127.0.0.1:26626}"}
2023-08-30T17:20:11.520Z	ERROR	core	node/node.go:191	problem starting blockchain	{"error": "failed to start state sync: failed to set up light client state provider: post failed: Post \"http://127.0.0.1:26657\": context deadline exceeded"}


failed to start state sync: failed to set up light client state provider: post failed: Post "http://127.0.0.1:26657": context deadline exceeded
```

### Observed behaviour

As described above.

Log Files:

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1485/artifact/testnet/logs/testnet-nodeset-full-6-full/vega-full-6.stderr-2023-08-30T17%3A19%3A31Z.log

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1485/artifact/testnet/logs/testnet-nodeset-full-6-full/vega-full-6.stdout-2023-08-30T17%3A19%3A31Z.log

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1485/artifact/testnet/logs/testnet-nodeset-full-6-full/

### Expected behaviour

No error

### Steps to reproduce

```bash
Not consistently reproducible.
```

### Software version

vega - develop

### Failing test

datanode tests

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1485/

**Comment by gordsport** [comment]
@wwestgarth - as thins looks to be a CometBFT issue can we close this?
