### ISSUE TITLE
The market parameter `market.liquiditySLAParameters.providersFeeCalculationTimeStep` has units ...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#9282]
... of time e.g. `1h` or `25s` when it enters the market proposal but the data node returns this converted to nanoseconds. 

It would be better if the data node returned the number in the same units as it went into the market proposal.

**Comment by EVODelavega** [comment]
Not sure if we can guarantee this will always be the exact same format as how these parameters were set initially, but we can treat the value as a `time.Duration` and convert it to string, so if the parameter was set to something like `120s`, that would return the value in a more human readable format (like `2m0s`)

**Comment by karlem** [comment]
Not a priority as it was already solved by UI.
