### ISSUE TITLE
[BUG] - SLA LP cancellation does not release the bond tokens to general

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9292]
Cancelled an LP with a trx

```
{"id":"3762-13","block":"3F616591A23ACBDD6F5E2779CE9B41F791CCCF53AC918AA3D6AA915EFA4151C7","type":"BUS_EVENT_TYPE_LIQUIDITY_PROVISION","liquidityProvision":{"id":"1912c89658aea58d874115fafe2deffc4dd59fc48dbafe9f944cb9406334e86e","partyId":"83bb9bedfca5b3a9e5dd0511d92c0268df4c00dc89e557ce7039155b98964eb5","createdAt":"1693907233764031000","updatedAt":"1693907234642683000","marketId":"d2b78045dc6f4600c4f6100a73ba4c490cea181643957961388f4635d363d912","commitmentAmount":"0","fee":"0","version":"2","status":"STATUS_CANCELLED"},"version":1,"chainId":"testnet-001","txHash":"574F02E75CFA8A724161CF57BD5F79A6E16DD64731E6EC55F55F3856B986410D"}
```

Checked the bond account expecting the tokens to be released....it wasnt

          "id": "2117e09270868035464f870e7b355d59090252cc6343eaf6de49c2179c2eb780"
              },
              "party": {
                "id": "83bb9bedfca5b3a9e5dd0511d92c0268df4c00dc89e557ce7039155b98964eb5"
              },
              "type": "ACCOUNT_TYPE_BOND",
              "balance": "1000000000000000000",
              "market": {
                "id": "d2b78045dc6f4600c4f6100a73ba4c490cea181643957961388f4635d363d912"
              }
            }
          },

test test_party_cancels_commitments_in_open_auction
branch sla-future-test-refactor

**Comment by davidsiska-vega** [comment]
From the test name `test_party_cancels_commitments_in_open_auction` I am assuming this is during an opening auction, is that correct ;-)?
