### ISSUE TITLE
[BUG] - SLA market data liquidity fee zero when cancelling and creating a new market commitment provision

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9301]
When creating a commitment provision for a market we can see the market data reflect the fee amount under 'fees'

When cancelling an LP for a market the market data liquidity fee amount can be to be 0

When creating a new commitment provision after cancellation we see the fee remain at 0

**Comment by vega-paul** [comment]
@karlem still an issue
See test_check_market_data_lp branch reset_lp_for_sla

**Comment by karlem** [comment]
Not and issue. The submission need to wait for the start of a new epoch - as mentioned in spec.
