### ISSUE TITLE
[Bug]: feature test does not support change of SLA market parameter 

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#9328]
### Problem encountered

When I use: “Then the markets are updated:” in feature test, I got a panic, see the feature test linked.

### Observed behaviour

When I use: “Then the markets are updated:” in feature test, I got a panic, see the feature test linked.

### Expected behaviour

I would like to be able to update market parameters in feature test 

### Software version

v0.72.14

### Failing test

https://github.com/vegaprotocol/vega/pull/9325

**Comment by gordsport** [comment]
Closing as this has now been checked and the results are as expectede
