### ISSUE TITLE
Transaction result event produced for banned parties transactions

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9342]
When a party is banned due to spam they cannot submit transactions for a predefined time, i.e. spamming the network using delegation transactions.

During the banned period the party can submit undelegation transactions which are confirmed via a valid transaction result event.
The undelegations are actually rejected and are not processed.

Expected no transaction result event during the banned period.

**Comment by ze97286** [comment]
I'm going to say this is impossible. If the party is banned their undelegation transaction will be rejected in checktx and not be added to a block. Can you please add some evidence supporting a transaction being created during ban period?

**Comment by jeremyletang** [comment]
@vega-paul anything to add to @ze97286 message? Can we close this?
