### ISSUE TITLE
[Bug]: Network History uses non trusted peers

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#9401]
### Problem encountered

When starting a new Data Node using Network History, a node operator must provide a list of trusted peers for Network History called `BootstrapPeers`.
This list is not considered when selecting the latest/newest segment to start the Data Node. Instead, it first connects to IPFS, discovers all the nodes, and picks a random one from the full list. This is not secure and risky. And a vector of attack.

### Observed behaviour

Data Node uses list of all IPFS nodes when selecting latest Network History segment.

### Expected behaviour

The Data Node should use a trusted peers (`BootstrapPeers`) list to select the latest Network History segment.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

v0.72.14

### Failing test

Snapshot pipeline

### Jenkins run

https://jenkins.vega.rocks/blue/organizations/jenkins/private%2FSnapshots%2FValidators-Testnet/detail/Validators-Testnet/2132/pipeline/160

### Configuration used

```shell
[NetworkHistory.Store]
  BootstrapPeers = ["/dns/n02.validators-testnet.vega.xyz/tcp/4001/ipfs/12D3KooWHffX2tdw2phH7ai8GCo2K3ehJfnLRATve5otVr4D3ggK","/dns/metabase00.validators-testnet.vega.xyz/tcp/4001/ipfs/12D3KooWKPDZ1s5FM8YewZVeRb9XwaQ7PdaoyD84hFnKmVbn94gN"]
```

### Relevant log output

```shell
got most recent history segment	{"segment": "from_height:9286301 to_height:9286600 history_segment_id:\"QmW1d5c9X7wcBRL1a1TjzrrScVFjV7iP6s9x72Ehu2pUpY\" previous_history_segment_id:\"QmSmwCp7V99e3evaSGJJUqFzBkzobosS8R8ruGov92GBx5\" database_version:21 chain_id:\"vega-testnet-0002-v4\"", "peer": "121.78.209.30:3007"}
```

Two problems:
1. `121.78.209.30:3007` is not trusted peer
```
n02.validators-testnet.vega.xyz = 134.122.2.178
metabase00.validators-testnet.vega.xyz = 167.172.84.20
```
2. Segment `QmSmwCp7V99e3evaSGJJUqFzBkzobosS8R8ruGov92GBx5` is not available on either of the trusted peers
- https://api.n02.validators-testnet.vega.xyz/api/v2/networkhistory/segments
- https://api.metabase00.validators-testnet.vega.xyz/api/v2/networkhistory/segments
```

**Comment by jeremyletang** [comment]
Let's make this an extra config boolean to exclude peers which is not part of the bootstrap list.
