### ISSUE TITLE
[GLS-065] Input validation: It is possible to send requests hundreds of megabytes in size to the gRPC API of the core node

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#9404]
## Description:

It is possible to send requests hundreds of megabytes in size to the gRPC API of the core node.

## Technical description:

During our attack on the staging node, responses lagged 65% of the time. Some responses came back in less than 5000ms, but these were few and between. The efficiency of this mixed-mode attack is shown by the fact that we used only half of our available resources to induce considerable lag in the node.

![Image](https://github.com/vegaprotocol/vega/assets/83510148/42047bd2-19dd-4cb3-91b2-080ab5dc6790)

**Chart details:**
```Attack Type
Duration
TX calls
RX data
X-axis
Y-axis
stage 4
overload, mixed mode A
trigger 500 error, very large transactions over gRPC
39 minutes
49890 requests
15,54 GB
elapsed time in milliseconds
node response time in milliseconds
```

**This issue can be reproduced as follows:**

```
cat tx.json | ./grpcurl -plaintext -d @ -proto protos/sources/vega/api/v1/core.proto -import-path
 protos/sources n05.stagnet1.vega.xyz:3007 vega.api.v1.CoreService.SubmitRawTransaction
```

Note: This request in a simple bash while loop already makes it possible for an attacker to apply significant load.

## Impact:
Being able to send a large request without being cut off by the core gRPC API makes it possible to put a significant data load on the connection.

## Recommendation:
- Check the size of incoming data, allow the option to cut it off beyond a certain threshold in the core gRPC API implementation.

**Comment by EVODelavega** [comment]
We currently don't set an explicit max message size, but digging through the grpc package, the default max message size would be used, and is set to 4MB:

```
// MaxRecvMsgSize returns a ServerOption to set the max message size in bytes the server can receive.
// If this is not set, gRPC uses the default 4MB.
func MaxRecvMsgSize(m int) ServerOption {
	return newFuncServerOption(func(o *serverOptions) {
		o.maxReceiveMessageSize = m
	})
}

```

This is consistent across all languages (e.g. C-core defines a macro/constant for this: https://github.com/grpc/grpc/blob/977df7208a6e3f9a62a6369af5cd6e4b69b4fdec/include/grpc/impl/codegen/grpc_types.h#L416). I suspect the here is that, before the size of the request is checked, we allow the full payload to be sent. Fixing that would be a bit more involved than simply checking the message size

**Comment by EVODelavega** [comment]
I'm proposing we close this as a won't fix or keep it in the backlog with a low priority

**Comment by gordsport** [comment]
This will be addressed in the docs: https://github.com/vegaprotocol/documentation/issues/753

Giving recommendations on the use of TLS etc.. in the documentation will give node operators the information required to mitigate this issue should they not be doing so already.
