### ISSUE TITLE
[GLS-014] Integer overflow: A crafted payload containing a very large integer can trigger a descriptive internal server error with SQL reference.

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#9408]
## Description:

A crafted payload containing a very large integer can trigger a descriptive internal server error with SQL reference.

## Technical description:

Several endpoints produce error messages that reveal information about the internal server configuration when a numeric parameter is very large, in this example, the largest value that can be represented as a signed 32-bit integer.

**To reproduce:**

```
curl -X GET http://127.0.0.1:3008/api/v2/accounts?pagination.{first,last,after, before}=2147483647
```

**The following error is returned:**

```
{"code":13,"message":"Internal error","details":[{"@type":"type.googleapis.com/
vega.ErrorDetail","code":80006,"message":"failed to get accounts","inner":"parsing account balances:
 scany: rows final error: ERROR: LIMIT must not be negative (SQLSTATE 2201W)"}]}
```

**Several endpoints display similar errors of this type:**
- api/v2/accounts
- api/v2/balance/changes • api/v2/assets
- api/v2/deposits
- api/v2/withdrawals

## Impact:
Triggering multiple server errors over a range of paths and payloads may enable an attacker to map vulnerabilities of a node. The curl example allows large scale scanning to easily detect the database being used in the node back-end. This makes it easier for an attacker to search for specific vulnerabilities.

## Recommendation:
- Return no response, or a generic error message when in production mode, along with an appropriate HTTP error code such as 400 or 422.

**Comment by wwestgarth** [comment]
This hasn't been fixed, it still happens on devnet1:
```
curl -X GET https://api.n00.devnet1.vega.rocks/api/v2/accounts?pagination.last=2147483647
{"code":13,"message":"Internal error","details":[{"@type":"type.googleapis.com/vega.ErrorDetail","code":80006,"message":"failed to get accounts","inner":"parsing account balances: scany: rows final error: ERROR: LIMIT must not be negative (SQLSTATE 2201W)"}]}
```

Also new validation was added here:
```
if *cp.Last < 0 {
    return CursorPagination{}, ErrCursorOverflow
}
```

even though we already have the same validation in `validatePagination()`. But for whatever reason _both_ aren't working.
