### ISSUE TITLE
[Bug]: GQL Error is not propagated to the stdout of the data-node

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#9446]
### Problem encountered

We are running the vega & data node with the vegavisor. We have an error in the REST API and the GQL API:

![image](https://github.com/vegaprotocol/vega/assets/1239637/84d31b2c-80f7-473c-accf-0e476b608ecf)

From the GQL Error We do not know what is the error, the error is also not propagated to the STDOUT.

However when We call the REST query with curl We can see:

```
HTTP/2 500
alt-svc: h3=":443"; ma=2592000
content-type: application/json
content-type: application/grpc
date: Mon, 18 Sep 2023 10:40:00 GMT
ratelimit-limit: 300
ratelimit-remaining: 999
ratelimit-request-remote-addr: 164.92.203.165, ::1
ratelimit-reset: 1
server: Caddy
vary: Origin
x-block-height: 7172429
x-block-timestamp: 1695033355612656000
x-vega-node-id: n00.stagnet1.vega.rocks

{"code":13,"message":"Internal error","details":[{"@type":"type.googleapis.com/vega.ErrorDetail","code":170002,"message":"failed to get proposals","inner":"ProposerPartyId: : querying proposals: scany: scan row into struct fields: can't scan into dest[4]: proto: (line 1:1183): unknown field \"lpPriceRange\""}]}
```

However we are not able to see the error in the browser:

![image](https://github.com/vegaprotocol/vega/assets/1239637/603d960f-7fa7-41b7-b8a7-b5d9fb0e4230)

### Observed behaviour

1. When GQL fails, we do not see error in the logs and in the response
2. REST response is not properly supported in the browser

### Expected behaviour

1. Error is logged in data-node stdout/stderr...
2. REST response is properly supported in the browser

### Steps to reproduce

1. Execute the below query in the api.n00.stagnet1.vega.rocks/graphql/

```
query{
	proposalsConnection{
    edges{
      node{
        reference
      }
    }
  }
}
```

2. Open the https://api.n00.stagnet1.vega.xyz/api/v2/governances

### Software version

v0.73.0.preview.2

### Relevant log output

```shell
We spent 1hr with Matthew to do a debugging, and He found the following error:


querying proposals: scany: scan row into struct fields: can't scan into dest[4]: proto: (line 1:1183): unknown field "lpPriceRange"
```
```

**Comment by ettec** [comment]
The issue here is that we were not seeing the error details in the GQL GUI, the error details are truncated away leaving a not particularly useful error message
