### ISSUE TITLE
Remove network param market.liquidity.targetstake.triggering.ratio

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9484]
This is no longer referred to in specs and no longer provides a default for market proposal trigger ratio (which is now mandatory between 0 and 1)

See https://github.com/vegaprotocol/specs/pull/1964

**Comment by EVODelavega** [comment]
This value is still being used in liquidity monitoring (supplied stake >= target stake * triggering ratio). If this parameter can be removed, then liquidity monitoring as a whole should be removed (confirm @witgaw @davidsiska-vega). Doing this would definitely cause problems for the system tests, as they quite often rely on triggering an auction. Price auctions could be used instead, but that requires each test to know the price bounds, and price bounds change over time, so they may be different from run to run, depending on the test suite you run, the order in which the tests run, and how long the run takes.

**Comment by witgaw** [comment]
Yeah it should definitely stay, nobody's advocating for the removal of liquidity monitoring at this stage.

**Comment by witgaw** [comment]
Is it not meant to be controlled by a market parameter now though? 
https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/markets.proto#L242C14-L242C14

**Comment by davidsiska-vega** [comment]
@EVODelavega if it is then that's a pretty huge bug, as @witgaw says, it's a market parameter.

**Comment by karlem** [comment]
@davidsiska-vega but that would mean that the bug has been there for a really long time. This has not been changed with SLA

**Comment by davidsiska-vega** [comment]
@karlem indeed, and I don't think there is a bug, I think the comment by @EVODelavega is plain wrong.
