### ISSUE TITLE
[Feature]: add steps for creating and funding reward pools with recurring transfers

### ISSUE THREAD

**Issue by cdummett** [vegaprotocol/vega#9496]
# Feature Overview

**In order to** test rewards vesting and activity streak benefits
**We will** require the ability to build configurable recurring transfers in feature tests
**So that** we can fund reward pools and distribute rewards to vesting accounts

#### Step: "the parties create the following reward schemes"
A step for creating reward schemes.
- mandatory columns
  - party
  - asset
  - amount
  - factor
  - start epoch
  - end epoch
  - dispatch strategy (must be created using the below step)
- optional columns
  - reference 
  - err

#### Step: "the dispatch strategy 'name':"
A step for configuring reward dispatch strategies.
- mandatory columns
  - reward metric
  - reward metric asset
  - entity scope
  - distribution strategy
  - window length
  - lock period
- optional columns
  - market scope
  - individual scope
  - team scope
  - top performers (defaults to `1` if not provided)
  - staking requirement (defaults to `0` if not provided)
  - notional twap requirement (defaults to `0` if not provided)
  - rank table (must be created using the below step)

### Step: "the rank table 'name':"
A step for creating a rank table to pass in a dispatch strategy step.
- mandatory columns
  - start rank
  - share ratio

## Specs
- [transfers spec](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0057-TRAN-transfers.md)

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] implement steps

**Comment by ze97286** [comment]
I don't think this should be supported. Users don't define "reward schemes", they setup transfers to fund reward accounts and this is already supported. I think all of the components of dispatch metrics are supported and if not I can add them.
