### ISSUE TITLE
LP commitment order not cancelled when market is terminated

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9507]
propose a market and create LP order supply commitment

LP is active, market is trading

terminate market
LP is still active - expected to be cancelled

**Comment by vega-paul** [comment]
terminated via oracle

**Comment by EVODelavega** [comment]
The LP won't be cleared until the market is settled, there's still a final settlement (and quite possibly a MTM settlement) to be done, and potentially fees to distribute

**Comment by Jiajia-Cui** [comment]
After the disunion on Slack, its expected behaviour (not bug) https://vegaprotocol.slack.com/archives/C05NF5QKZEX/p1695220850884739
