### ISSUE TITLE
[Bug]: referee apply referral code for another referral set does provide rejection response

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9523]
### Problem encountered

If a party is currently a referee (and the referrer is meeting the staking requirement), if they submit a signed ApplyReferralCode transaction then: ([0083-RFPR-026](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#0083-RFPR-026))
the party will not be added to the associated referral set. <- i would think that this would result in a error response either by wallet or transaction result (whichever is appropriate) but there is none

```
>           assert len(failed_tx) > 0
E           AssertionError: assert 0 > 0
E            +  where 0 = len('')
```

### Observed behaviour

no wallet rejection / failed transaction result

### Expected behaviour

either wallet rejection or failed transaction result (whichever is appropriate)

### Steps to reproduce

```bash
1. run the test `test_referee_in_referral_set_apply_referral_code[setup_referral_set1-True]` from system-test branch `0083-RFPR-026` 
2. At point of failure, we have confirmed the referee has not moved to the new referral set but we also dont have a failed transaction/wallet rejection
```

### Software version

dev branch

### Failing test

test_referee_in_referral_set_apply_referral_code[setup_referral_set1-True] 

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/13418/

**Comment by gordsport** [comment]
This will be resolved when the folowing is implemented:

- https://github.com/vegaprotocol/vega/issues/9231

**Comment by Sohill-Patel** [comment]
This issue has been fixed in palazzo and the ac rebranded as [0083-RFPR-052](https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0083-RFPR-on_chain_referral_program.md#0083-RFPR-052), which is covered in test test_referrer_min_stake_referee_apply_referral_code [here](https://github.com/vegaprotocol/system-tests/blob/develop/tests/teams/test_team_administration.py#L889-L893)
