### ISSUE TITLE
[Feature]: Feature tests for validator ranking metric and reward

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#9560]
Cover ACs:
0056-REWA-091
0056-REWA-092

**Comment by gordsport** [comment]
Closing as the following are now to be done as system tests:

[[Referral]: Add AC coverage for 0056-REWA-091](https://github.com/vegaprotocol/OctoberACs/issues/356)
[[Referral]: Add AC coverage for 0056-REWA-092](https://github.com/vegaprotocol/OctoberACs/issues/357)
