### ISSUE TITLE
[Bug]: Update referral program - incorrect validation on total number of benefit tiers submitted

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9581]
### Problem encountered

Incorrect validation applied to update referral program proposals - proposals with the number of benefit tiers == network parameter referralProgram.maxReferralTiers are Rejected with the below error mesage.

`assert None == 'the number of benefit tiers in the proposal is higher than the maximum allowed by the network parameter "referralProgram.maxReferralTiers": maximum is 10, but got 10'`

AC:

If an UpdateReferralProgram proposal does not fulfil one or more of the following conditions, the proposal should be STATUS_REJECTED:
the end_of_program_timestamp must be less than or equal to the proposals enactment_time ([0083-RFPR-001](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#0083-RFPR-001)).
the number of tiers in benefit_tiers must be less than or equal to the network parameter referralProgram.maxReferralTiers ([0083-RFPR-002](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#0083-RFPR-002)).

### Observed behaviour

Update referral program proposals are rejected if number of benefit tiers is == referralProgram.maxReferralTiers

### Expected behaviour

Update referral program proposals should be successful if number of benefit tiers is == referralProgram.maxReferralTiers

### Steps to reproduce

```bash
Run the below system test:

System Test Name - test_ref_program_benefit_tiers_count_bug
System Test Branch - feat_referral_program_ac_1
```

### Software version

vega - develop

### Failing test

test_ref_program_benefit_tiers_count_bug

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/15480/testReport/junit/tests.teams/test_team_administration/test_ref_program_benefit_tiers_count_bug/

### Relevant log output

```shell
assert None == 'the number of benefit tiers in the proposal is higher than the maximum allowed by the network parameter "referralProgram.maxReferralTiers": maximum is 10, but got 10'
 +  where None = <modules.govMod.governMod.CreateReferralProgram object at 0x7f41ca18b050>.error_details
```

**Comment by EVODelavega** [comment]
The test submits a proposal with exactly 10 benefit tiers (as is confirmed by the error message, and the events we can find in the build artefacts: https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/15480/artifact/test_logs/tests.teams.test_team_administration/test_ref_program_benefit_tiers_count_bug/BUS_EVENT_TYPE_PROPOSAL.txt). The proposal is valid, and nothing happens until it gets declined because the participation threshold is not reached (the second event in the linked file).

This doesn't seem to be a bug.
