### ISSUE TITLE
[Bug]: mac vegawallet binaries missing from recent releases

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#9582]
### Problem encountered

<img width="959" alt="Screenshot 2023-09-27 at 12 51 14" src="https://github.com/vegaprotocol/vega/assets/6678/911eae33-0116-4796-8da7-b98012b003d1">

### Observed behaviour

I expected vegawallet-darwin-amd64.zip to exist on the `0.73.0-preview.x` builds. They don't on any of them. Perhaps due to the preview tag?

https://github.com/vegaprotocol/vega/releases

### Expected behaviour

A zip exists

### Steps to reproduce

```bash
1. Pick a recent release from https://github.com/vegaprotocol/vega/releases
2. Look for a wallet.zip for the mac
3. Give up
4. Compile it yourself
```

### Software version

0.73.0-preview

**Comment by gordsport** [comment]
The agreement was re-signed on the 25th Sept to resolve this and build the Darwin binaries. the last preview tag was done on the 22nd. 

Therefore this is expected to be resolved. I will close if so on the next tag.

**Comment by gordsport** [comment]
The failed pipelines have been re-run: https://github.com/vegaprotocol/vega/actions/runs/6275970068

and have now passed
