### ISSUE TITLE
[Bug]: Network history segment divergence in system tests

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9594]
### Problem encountered

Encountered another instance of network history divergence issue in the system tests full run.

Test failure links:

https://jenkins.vega.rocks/job/common/job/system-tests/3159/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_restore_from_dehistory/

https://jenkins.vega.rocks/job/common/job/system-tests/3159/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_history_segments_are_deterministic/

### Observed behaviour

Network history segment divergence in system tests

### Expected behaviour

No network history segment divergence.

### Steps to reproduce

```bash
Not too sure if this can be reproduced.
This issue happened in one of the full system runs.
```

### Software version

vega - develop

### Failing test

test_datanode_history_segments_are_deterministic

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/15851/

**Comment by ettec** [comment]
k, we should have all necessary state persisted, so reproducing not necessary, will look shortly
