### ISSUE TITLE
Manual review of the checks for enums

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#9648]
We've had a few cases now where enums have been added to, or renamed in core - but the changes haven't gone all the way through to datanode and the database and the results can be quite severe (data node crashing because it can't insert a record).

Before the October release we should do a first pass of this to make sure that the exist both in core and the data base

**Comment by jeremyletang** [comment]
Just done that, for info I used the followign query to look at the different enums we have today:

List of all enums:
```
select n.nspname as enum_schema, t.typname as enum_name, e.enumlabel as enum_value from pg_type t join pg_enum e on t.oid = e.enumtypid join pg_catalog.pg_namespace n ON n.oid = t.typnamespace;
```

List all variant for a single enum:
```
select n.nspname as enum_schema, t.typname as enum_name, e.enumlabel as enum_value from pg_type t join pg_enum e on t.oid = e.enumtypid join pg_catalog.pg_namespace n ON n.oid = t.typnamespace where t.typname = 'ENUM_TYPE';
```
