### ISSUE TITLE
Spam rejection where party has insufficient tokens to apply referral sets missing balance

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9666]
testing this AC
```
Given longer than spam.protection.balanceSnapshotFrequency has elapsed since a party deposited or transferred funds,
     a party who has less then spam.protection.applyReferral.min.funds in their accounts should have any
     ApplyReferralCode transactions pre-block rejected. All assets count towards this threshold and balances should be
      scaled appropriately by the assets quantum. (0062-SPAM-028)
```

Setup
spam.protection.applyReferral.min.funds = 1000000000000000000 (1 token)
set spam.protection.balanceSnapshotFrequency to 30s
deposit 1000000000000000000 - 1 to a party
party submitted  straight to core a applyreferral code trx to a referral set 

expected an error to show required and available balance
instead we always see 0 as available balance

'party "4e951df02d4ccc0224db77b302207a71964e0e2f87e4255faf9cb28c3412e1ab" does not have sufficient balance to apply referral code, required balance 1000000000000000000 available balance 0'

```
{
  "data": {
    "party": {
      "accountsConnection": {
        "edges": [
          {
            "node": {
              "asset": {
                "symbol": "TAS",
                "name": "AssetID",
                "id": "af106f014b6814f7a3be08cee8d345969a2c05f3318f72b58f23a144b7789c48"
              },
              "type": "ACCOUNT_TYPE_GENERAL",
              "balance": "999999999999999999",
              "market": null
            }
          }
        ]
      }
    }
  }
}
```

**Comment by vega-paul** [comment]
[https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/19941/testReport/junit/[…]/spam_referrals_test/test_reject_apply_referral_codes_30s_/](https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/19941/testReport/junit/tests.spam/spam_referrals_test/test_reject_apply_referral_codes_30s_/)

**Comment by ze97286** [comment]
The behaviour is correct. The party has 0 balance after normalising by quantum. 
The deposit is:
`{"id":"132-7","block":"B153CFF38542A455F28FB1DE764923488ACADC1A3B9C4E400A3A468C87959DC9","type":"BUS_EVENT_TYPE_DEPOSIT","deposit":{"id":"056f34539112cc4323c633669083286468639ac079b7e0543b1a2b0ebe4adf82","status":"STATUS_FINALIZED","partyId":"a7951e23808eec825abdcbbd3bee19b05f1dfb441e267a20e376832646a13179","asset":"e7db166b586bbd1ed2b891e1c104a5dc64771978ff8e4f904f055df4cb2d16e4","amount":"999999999999999999","creditedTimestamp":"1696518080060116398","createdTimestamp":"1696518077505317652"},"version":1,"chainId":"testnet-001","txHash":"B153CFF38542A455F28FB1DE764923488ACADC1A3B9C4E400A3A468C87959DC9"}
`
The asset is:
`
{"id":"109-6","block":"701FD37442D2B134F125218AE14A8776FA13425FED9A61CE9E90AAB7D7947AE2","type":"BUS_EVENT_TYPE_ASSET","asset":{"id":"e7db166b586bbd1ed2b891e1c104a5dc64771978ff8e4f904f055df4cb2d16e4","details":{"name":"AssetID","symbol":"TAS","decimals":"18","quantum":"1000000000000000000","builtinAsset":{"maxFaucetAmountMint":"100000000000000000000000000"}},"status":"STATUS_ENABLED"},"version":1,"chainId":"testnet-001","txHash":"701FD37442D2B134F125218AE14A8776FA13425FED9A61CE9E90AAB7D7947AE2"}
`

The deposited amount 999999999999999999/1000000000000000000 < 1 = 0

That said however there seems to be a snapshot issue in your jenkins so I'll leave the ticket open.
