### ISSUE TITLE
[Feature]: Add LP fees to epoch summaries

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9740]
# Feature Overview

**In order to** allow users to make sense of their earnings on Vega
**We will** add summaries of LP fees earned to the end of epoch summaries
**So that** it is clear to users what they have earned

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Add LP fees earned per epoch to all 3 APIs below

### Additional Details (optional)
The current rewards APIs:
- /api/v2/rewards
- /api/v2/rewards/epoch/summaries
- /api/v2/rewards/summaries (Less important ... I have no idea if anyone uses this)

Currently contain per epoch summaries of:
- Rewards
  - Based on Taker fees paid
  - Based on Maker fees received
  - Based on LP fees received
  - Based on staking (aka "global rewards")
- Fees
  - Infra fees

It is unclear why this API stops at just the infra fees, when it could provide a per-epoch summary of the LP fees earned and once this was done this API would provide a holistic picture of all the rewards & fees that a party has earned per epoch. 

We want to add these to it...

**Comment by gordsport** [comment]
Issue has been split leave LP fees in this one. Maker fees to be done under:

- https://github.com/vegaprotocol/vega/issues/9743
