### ISSUE TITLE
Cancelling LP order fails to generate STATUS_CANCELLED event

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9754]
LP order created and then cancelled
We see a status pending event and we wairt until epoch expiry + a few seconds to confirm the status cancelled event but this never arrives

have two examples

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/22691/artifact/test_logs/tests.orders.orderSubmissions_test/test_ParkActiveRefExpirePegged%5Border_param0%5D/BUS_EVENT_TYPE_LIQUIDITY_PROVISION.txt

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/22691/artifact/test_logs/tests.orders.orderStatus_test/test_wash_trade_during_auction_uncrossing/BUS_EVENT_TYPE_LIQUIDITY_PROVISION.txt

**Comment by karlem** [comment]
Hey @vega-paul I have checked the code for reseting the market. Have you seen [this line](https://github.com/vegaprotocol/system-tests/blob/956918b304cf4f3b178f158d32d931475c72223f/modules/lpMod/liqProvMod.py#L342C37-L342C37) with Wills comment?
