### ISSUE TITLE
SLA API endpoints must report both current and pending amounts and fees

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#9757]
If a party has an active liquidity provision and then it makes an update to that it will now appear as PENDING on the API until the end of the current epoch when that update will be applied.

This is misleading because you can't tell the difference between a new provision which is contributing ZERO liquidity until the end of the epoch and one that is currently providing liquidity but will have some sort of change applied at end of epoch.

Update the SLA API endpoint so that it has both "current" part (amount, committed, fee proposed) and "pending part" (new amount and fee which will be activated at epoch boundary). 

For a party that submitted LP provision for the 1st time the "current" part can return `0` and `0` or `null` and `null` - whatever is more in keeping with the API style.

**Comment by karlem** [comment]
This should be quite easy change just on the actual API. I don't think we need to change DB or anything like that

**Comment by guoguojin** [comment]
This will create a breaking change to the Liquidity Provisions API as the LiquidityProvision data that will be returned will now have a `live` and `pending` component, one of which could be empty depending on the situation, or both could be filled depending on the situation:

1. No previous live provisions: `live` is empty, `pending` is not
2. Liquidity is live, no updates: `pending` is empty, `live` is not
3. Existing liquidity provision is live, and update has been accepted, `live` and `pending` will have liquidity provision information.

**Comment by guoguojin** [comment]
Actually, I'm managed to do it in a way that just adds a `pending` element to the LiquidityProvision object. This means that the breaking change will only affect the gRPC API as we need to change the gRPC message for the API, but the REST and GQL APIs should only see an extra field for the pending changes if they exist.
