### ISSUE TITLE
[Bug]: Fee stats is not filtering correctly 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9762]
### Problem encountered

Fee stats is not filtering by referrer / referree ID properly. 

### Observed behaviour

See above

### Expected behaviour

I would if i ran this query filtering for a referrer:

`query feeStats{
  referralFeeStats(
    marketId:"0dd6f74d6a80f6e4fb849fa455bb1a2d617ee851bc6f10330fce8d08e220c994",
    referrer:"58edaa6704adcaece66af3b892af491721f4d949c11912bc6056f9965f037e6e")
  {
    assetId
    marketId
    epoch
    refereesDiscountApplied{
      partyId
      amount
    }
    volumeDiscountApplied{
      partyId
      amount
    }
    totalRewardsPaid{
      partyId
      amount
    }
    referrerRewardsGenerated{
      referrerId
      generatedReward{
        partyId
        amount
      }
    }
  }
}`

That the result would only give me back:
- Referrer Diiscounts received by referees in that referrer's set 
- Volume discounts would be unaffected (or should not live on this API ...) 
- Total rewards paid IF I UNDERSTAND IT CORRECTLY should give me the rewards paid to THAT referrer, one record
- referrerRewardsGenerated should show me only one referrer ID and then nested inside that all the rewards generated per referree that will be paid to that referrer (which would therefore match the value above)

### Steps to reproduce

```bash
Run that query on stagnet
```

### Software version

Preview 15

**Comment by guoguojin** [comment]
I believe this is a result of storing the stats as JSON in the database. The query filters for records where the referrer or referee is in the JSON object, but then returns the entire JSON object without filtering for either the referrer or the referee.

We can do this after retrieving the data from the database and then filtering the stats for the referrer/referee before returning the results.
