### ISSUE TITLE
Realised & Unrealised P&L show strange values briefly after trade

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9770]
## Description

When a trade goes through there seems to be a brief period where the realised and unrealised P&L figures display weird values before they correct themselves .... almost as if the decimals arent applied initially and then they wake up. Maybe a call to the assets API and initially we show the unformatted version?

## Steps to Reproduce

1. Go to Console
2. Open a position
3. Approve the TX in your wallet
4. You will see the unrealised show a weird value briefly
5. Now hit the close position button 
6. Approve the TX in your wallet
7. You will see the realised show a weird value briefly

## Expected behavior

We should show the correct value so ppl dont panic briefly! 

## Device details

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by EVODelavega** [comment]
The issue does not present itself when a position is opened, but the unrealised PnL does flicker when a position is updated.
