### ISSUE TITLE
Transaction result subscription

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#9802]
Front-end apps have accrued significant technical debt in managing the UI surrounding different transaction types.

Once a transaction is sent to a wallet different subscriptions and logic is needed to properly track the transaction and the resulting changes on the network.

As a result the TransactionResult bus event was added, but it only gets us part of the way there.

This work is to improve that or add a new subscription specifically for this purpose, so that you can easily track transactions _and_ the changes that result from them.

This should also be beneficial in making it easier for external people to build on Vega

**Comment by mattrussell36** [comment]
I've put together a proposal of how this could look here: https://www.notion.so/vegaprotocol/Transaction-subscriptions-for-front-ends-75d6c18b2c96440387d8dfe6855d28bb?pvs=4

Please have a look. Open to any suggestions
