### ISSUE TITLE
[Feature]: Add epoch to / from filtering to the feeStats API 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9828]
# Feature Overview

**In order to** support nicer querying of sums of fees over time periods
**We will** add the normal epoch to / from filtering to the API
**So that** front end doint have to loop for 30D worth of data painfully

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Currently the API supports filtering by epoch .... ideally it would support to / from instead.

**Comment by ValentinTrinque** [comment]
After a chat with @JonRay15 and @asiaznik, there is no need for this on this endpoint as the computation per party is implemented on a more suitable endpoint fees-stats-for-party.
