### ISSUE TITLE
[Bug]: Pagination possibly broken on stagnet1

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#9836]
### Problem encountered

Using this little bit of python trying to page over all accounts, it works when:
`BASE_URL = "https://api.n00.testnet.vega.rocks/api/v2/"`

```
def get_accounts():
    url = "accounts"
    r = requests.get(BASE_URL + url)
    rr = r.json()
    print("nrefs", len(rr["accounts"]["edges"]))

    cursor = rr["accounts"]["pageInfo"]["endCursor"]
    print(cursor)
    while rr["accounts"]["pageInfo"]["hasNextPage"]:
        print()
        print(BASE_URL + url+ "?pagination.after="+ cursor)
        r = requests.get(BASE_URL + url+ "?pagination.after="+ cursor)
        rr = r.json()
        print("nrefs", len(rr["accounts"]["edges"]))
        cursor = rr["accounts"]["pageInfo"]["endCursor"]
        print(cursor)
```

If I run the same with `BASE_URL = "https://api.n00.stagnet1.vega.rocks/api/v2/"`, it loops forever printing the same `endCursor` for each iteration.

### Observed behaviour

Pagniation on stagnet1 doesn't seem to work.

### Expected behaviour

Pagniation on stagnet1 should work.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

**Comment by daniel1302** [comment]
I was seeing the same issue yesterday at night. I was too tired to debug but I saw start cursor == end cursor @wwestgarth
