### ISSUE TITLE
[Bug]: ListTeams / ListTeamReferees api inconsistency between grpc, gql and rest

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9840]
### Problem encountered

inconsistency in returned response,

Rest:
`createdAtEpoch` is not set

GQL - ListTeams
`createdAtEpoch` is not set

`createdAt` Also the time is wrong, seems to be suffering from nano > second conversion, looks similar to this issue -> https://github.com/vegaprotocol/vega/issues/9530

ListTeamReferees
`joinedAt` -  seems to be suffering from nano > second conversion, looks similar to this issue -> https://github.com/vegaprotocol/vega/issues/9530

GRPC
missing `createdAtEpoch`

### Observed behaviour

`BUS_EVENT_TYPE_TEAM_CREATED` will show 
`{"id":"219585-48","block":"E8DE5C4DBF7BC368DAAE8581AF064A0FD358B2EEF2450BC6BA036D0A9AA2EEC2","type":"BUS_EVENT_TYPE_TEAM_CREATED","teamCreated":{"teamId":"62d93e46b3277d31c35ad227c020f2432dd7b53275afcaffde87ed2ade25b5cb","referrer":"b5d335c82db5fdbb1dbc6ea36ca4e59db29a3002f7bd4a7590bea107700f2758","name":"team_0BE7DD62DE","teamUrl":"http://team-0BE7DD62DE.io","avatarUrl":"http://team-avatar-0BE7DD62DE.io/avatar.png","createdAt":"1697703090565629000","atEpoch":"24541"},"version":1,"chainId":"testnet-001","txHash":"C589880B71068ACD173FEDCC8360821AEAC6105074B8CA59BA0D86B2E53B7CF4"}`

rest response
```
{
  'teams': {
    'edges': [
      {
        'node': {
          'teamId': '62d93e46b3277d31c35ad227c020f2432dd7b53275afcaffde87ed2ade25b5cb',
          'referrer': 'b5d335c82db5fdbb1dbc6ea36ca4e59db29a3002f7bd4a7590bea107700f2758',
          'name': 'team_0BE7DD62DE',
          'teamUrl': 'http://team-0BE7DD62DE.io',
          'avatarUrl': 'http://team-avatar-0BE7DD62DE.io/avatar.png',
          'createdAt': '1697703090',
          'closed': False,
          'createdAtEpoch': '0'
        },
        'cursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9'
      }
    ],
    'pageInfo': {
      'hasNextPage': False,
      'hasPreviousPage': False,
      'startCursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9',
      'endCursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9'
    }
  }
}
```

GQL response

```
"teams": {
  "edges": [
    {
      "node": {
        "teamId": "62d93e46b3277d31c35ad227c020f2432dd7b53275afcaffde87ed2ade25b5cb",
        "referrer": "b5d335c82db5fdbb1dbc6ea36ca4e59db29a3002f7bd4a7590bea107700f2758",
        "name": "team_0BE7DD62DE",
        "teamURL": "http://team-0BE7DD62DE.io",
        "avatarURL": "http://team-avatar-0BE7DD62DE.io/avatar.png",
        "createdAt": "1970-01-01T00:00:01.69770309Z",
        "createdAtEpoch": 0,
        "closed": false
      }
    }
  ]
}
```

GRPC response

```
{
  'edges': [
    {
      'node': {
        'teamId': '62d93e46b3277d31c35ad227c020f2432dd7b53275afcaffde87ed2ade25b5cb',
        'referrer': 'b5d335c82db5fdbb1dbc6ea36ca4e59db29a3002f7bd4a7590bea107700f2758',
        'name': 'team_0BE7DD62DE',
        'teamUrl': 'http://team-0BE7DD62DE.io',
        'avatarUrl': 'http://team-avatar-0BE7DD62DE.io/avatar.png',
        'createdAt': '1697703090'
      },
      'cursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9'
    }
  ],
  'pageInfo': {
    'startCursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9',
    'endCursor': 'eyJDcmVhdGVkQXQiOiIyMDIzLTEwLTE5VDA5OjExOjMwLjU2NTYyOSswMTowMCIsIklEIjoiNjJkOTNlNDZiMzI3N2QzMWMzNWFkMjI3YzAyMGYyNDMyZGQ3YjUzMjc1YWZjYWZmZGU4N2VkMmFkZTI1YjVjYiJ9'
  }
}
```

### Expected behaviour

consistency in response between rest, gql and grpc

### Steps to reproduce

```bash
1. system-test branch `feat-3032` test name `test_list_teams` only covers rest, still in progress to include gql and grpc
```

### Software version

dev branch

**Comment by Sohill-Patel** [comment]
for the Closed field in the teams API, the field is set, but the behaviour of gRPC is to omit fields that have default values in the protobuf to save space. So what you're seeing in the gRPC is correct when the team is not closed:
When generating JSON-encoded output from a protocol buffer, if a protobuf field has the default value and if the field doesn't support field presence, it will be omitted from the output by default. An implementation may provide options to include fields with default values in the output.
From https://protobuf.dev/programming-guides/proto3/#json

**Comment by gordsport** [comment]
Blocked as we need to enable teams again now 0.73 has been deployed

Also blocking:

- https://github.com/vegaprotocol/system-tests/issues/3032
