### ISSUE TITLE
Add scanner for num.Uint in datanode

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#9849]
So the database can consume num.Uint instead of going through the num.Decimal which is slower

Example: https://github.com/holiman/uint256/blob/master/conversion.go#L682

**Comment by EVODelavega** [comment]
Worth considering that a lot of the `num.Uint` values are stored as the custom `HUGEINT` type (which is essentially `NUMERIC(1000, 0)` - so it's not out of the queston that a migration might be required for this.

**Comment by ValentinTrinque** [comment]
Good point.

Ultimately, I think it's seems fine to store in HUGEINT. But, apparently, reading a HUGEINT requires converting to num.Decimal. 

At least, I think both types should be eligible to read from and write to the database. 

Also, despite most performance issues live within the database queries (and design), it's worth measuring performance to determine the impact of using Decimal as the unique conversion type for HUGEINT, as we know it can become a performance penalty.
