### ISSUE TITLE
[Bug]: The referralSetReferees API is giving funky commission numbers

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9927]
### Problem encountered

I have done one epoch worth of trading with the key starting 099 on market 

https://vegafairground.eth.limo/#/markets/e97144288e3a98f5275e093260861d1f848f2a032990339b0d290f6e8aa43b6e

If I run this query to get back the referral set details for this set which contains only two keys, one of which is the above.

Then it says that the key starting 099 has done 50,787 of volume.

```
query refereesBySet {
  referralSetReferees(
    id:"876be7c89c40d4a898b886a17f0039f86063cb35223833e4d585cef18dc452b3")
  {
    edges{
      node{
        referralSetId
        refereeId
        joinedAt
        atEpoch
        totalRefereeGeneratedRewards
        totalRefereeNotionalTakerVolume
      }
    }
  }
}
```

That number seems reasonable enough since you can see the fills on that key add up to around 50k, and this is the ONLY trades I have done on that key since the fairground restart. 

<img width="1223" alt="image" src="https://github.com/vegaprotocol/vega/assets/89918817/9fe9d983-1e49-4161-a823-c97130e57e1d">

So the `totalRefereeNotionalTakerVolume` seems fine ... but the `totalRefereeGeneratedRewards` does not.

### Observed behaviour

The API is telling me that someone I generated 406,136 quantums worth of rewards from that 50k of trading. 

```
{
  "data": {
    "referralSetReferees": {
      "edges": [
        {
          "node": {
            "referralSetId": "876be7c89c40d4a898b886a17f0039f86063cb35223833e4d585cef18dc452b3",
            "refereeId": "099c59484e4a0db12d06dc52cb57f4c0e0b861a90d70d7afdfe6cd8e88d94612",
            "joinedAt": "2023-10-27T14:35:03.03017Z",
            "atEpoch": 9793,
            "totalRefereeGeneratedRewards": "406136",
            "totalRefereeNotionalTakerVolume": "50787"
          }
        },
        {
          "node": {
            "referralSetId": "876be7c89c40d4a898b886a17f0039f86063cb35223833e4d585cef18dc452b3",
            "refereeId": "b62eafc46e6fadc6e45ae51de8bda199f0702131e5b23665f3411223c598acc2",
            "joinedAt": "2023-10-27T09:54:37.513487Z",
            "atEpoch": 9788,
            "totalRefereeGeneratedRewards": "156228",
            "totalRefereeNotionalTakerVolume": "4947972630"
          }
        }
      ]
    }
  }
}
```

This cannot be right.

### Expected behaviour

Commission should be 3% of my fees ... based on console my fees were

11.209286
1.922552
2.847788
10.689219
13.555709
 
Or a total of 40.224554

Not sure how $40 of fees can generate 406k Quantums of rewards! 

### Steps to reproduce

```bash
See above
```

### Software version

73 rc4

**Comment by gordsport** [comment]
Closing as this has been fixed
