### ISSUE TITLE
Existing mainnet markets missing SLA params on the data node

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#9950]
The existing mainnet markets are missing SLA parameters on the data node:
![image](https://github.com/vegaprotocol/vega/assets/62546419/b9b1e5ca-e5f3-4ea1-8f78-394f36ef5e0b)

@wwestgarth inspected core snapshot and the core has the right numbers. 

Data node will update if one of the following happens:
- market going in/out of auction
- lp fee changing
- suspending/unsuspending the market
- market update

**Comment by jeremyletang** [comment]
fixed in tag v0.73.2
