### ISSUE TITLE
Enhance teams API for game stats

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9980]
## Teams API

On the teams API

```
query teams {
  teams{
    edges{
      node{
        teamId
        referrer
        name
        teamURL
        avatarURL
        createdAt
        createdAtEpoch
        closed
      }
    }
  }
}  
```

We need the list of members of the team:
- [x] Add Party ID list to the teams API
- [x] Need to be able to filter by Party ID so that I can call this to find the team my party is in 

## Team Stats API 

These could sit on the teams API but preference seemed to be for a dedicated stats API.

We need the following stats over the last `aggregationEpochs` epochs.

- [ ] Average normalised rank (on hold)
  - [ ] Rank is taken directly from the game details #9257, ie. you came 3rd of 10 participants
  - [ ] Normalised rank is then that rank as a percentile, ie. 0.3, and is also on the game details
  - [ ] Average normalised rank is then the mean of those normalised ranks over the aggregation period
  - [x] If the entity does not have at least `aggregationEpochs` worth of data it should return "Insufficient records"
- [ ] Total volume
- [x] Total rewards (as quantum)
- [x] List of reward per epoch 
- [x] Total games played
- [x] List of played games 

Inputs
- [x] Add that `aggregationEpochs` to the inputs. 
- [x] Filter by Team ID

eg. 
```
teamStats(aggregationEpochs:10){
  edges{
    node{
      teamID
      averageNormalisedRank
      totalReward
      totalVolume
      totalGamesPlayed
    }
  }
}
```

## Team Member Stats API

For any Party ID that is **currently** part of a team (I dont think we care about historic team results), provide the following similar to above but for the individual PARTY, therefore showing their contribution to the team's overall performance.

You could equally nest this in the team stats, and this might have the advantage of being able to reuse a lot of the strcuture from #9257 .... but here I've shown it split out because that has been your preference so far and this would mirror the referrerStats vs refereeStats APIs.

- [x] Party ID 
- [x] Team ID
- [ ] Average normalised rank (on hold)
- [ ] Total volume 
- [x] Total rewards (as quantum)
- [x] List of reward per epoch 
- [x] Total games played
- [x] List of played games 

Inputs
- [x] Add that `aggregationEpochs` to the inputs. 
- [x] Filter by Team ID
- [x] Filter by Party ID

eg. Option1 
```
teamMemberStats(aggregationEpochs:10){
  edges{
    node{
      Party ID
      teamID
      averageNormalisedRank
      totalReward
      totalVolume
      totalGamesPlayed
    }
  }
}
```

or Option 2
```
teamStats(aggregationEpochs:10){
  edges{
    node{
      teamID
      averageNormalisedRank
      totalReward
      totalVolume
      totalGamesPlayed
      members{
               partyID
               averageNormalisedRank
               totalReward
               totalVolume
               totalGamesPlayed
              }
    }
  }
}
```

**Comment by gordsport** [comment]
Team Stats API, average rank to be put on hold for now. Lets do it in the [Games details](https://github.com/vegaprotocol/vega/issues/9257) first and then reassess this
